trex: TREX::transaction::EnumeratedDomain< Ty, Comp > Class Template Reference
TREX::transaction::EnumeratedDomain< Ty, Comp > Class Template Reference
Domains
Enumeration based domain.
#include <trex/domain/EnumeratedDomain.hh>
Public Types
typedef
container_type::const_iterator iterator
Possible values iterator.
typedef
TREX::utils::XmlFactory
< DomainBase,
boost::shared_ptr< DomainBase > > xml_factory
XML parsing factory for domains.
Public Member Functions
void add (Ty const &val)
Add an element to the domain.
template<class Iter >
void add (Iter from, Iter to)
Add an element to the domain.
iterator begin () const
First element.
bool contains (Ty const &val) const
test for membership
virtual DomainBase * copy () const =0
Duplicate method.
iterator end () const
End iterator.
EnumeratedDomain (TREX::utils::Symbol const &type)
Constructor.
template<class Iter >
EnumeratedDomain (TREX::utils::Symbol const &type, Iter from, Iter to)
Constructor.
EnumeratedDomain (TREX::utils::Symbol const &type, Ty const &val)
Constructor.
bool equals (DomainBase const &other) const
Equality test.
boost::any getElement (size_t i) const
generic element access
boost::any getSingleton () const
singleton value
size_t getSize () const
element count
std::string getStringSingleton () const
singleton value
virtual std::string getStringValue (size_t i) const
Get element textual value.
template<class Ty , bool Safe>
Ty getTypedElement (size_t n) const
Typed element access.
template<class Ty , bool Safe>
Ty getTypedSingleton () const
singleton value
TREX::utils::Symbol const & getTypeName () const
type of the domain
bool intersect (DomainBase const &other) const
check for common values
bool isEnumerated () const
Check for enumerated domain.
bool isFull () const
check for full domain
bool isInterval () const
Check for interval domain.
bool isSingleton () const
check for singleton value
DomainBase & operator*= (DomainBase const &other)
Restrict domain possible values.
boost::any operator[] (size_t i) const
DomainBase & restrictWith (DomainBase const &other)
Restrict domain possible values.
std::ostream & toXml (std::ostream &out, size_t tabs) const
XML conversion.
virtual ~EnumeratedDomain ()
Destructor.
Protected Member Functions
void addTextValue (std::string const &val)
void completeParsing (boost::property_tree::ptree::value_type &node)
EnumeratedDomain (EnumeratedDomain const &other)
Copy constructor.
EnumeratedDomain (boost::property_tree::ptree::value_type &node)
XML parsing constructor.
std::ostream & print_value (std::ostream &out, size_t i) const
Friends
std::ostream & std::operator<< (std::ostream &out, TREX::utils::ostreamable const &x)
Detailed Description
template<typename Ty, class Comp = std::less<Ty>>
class TREX::transaction::EnumeratedDomain< Ty, Comp >
Enumeration based domain.
Parameters:
Ty type of the elements
Comp Ordering function
This template class provides a basis for defining enumeration based domains.
An enumerated domain is a domain that can easily be represented as a set of possible values.
Precondition:
Comp is expected to be a complete order over Ty
Note:
As for now this domain relies on the set standard C++ compiler. This results on the need to have the elements being comparable though an ordering functor. We may in the future use the more general collection_set, provided by next C++ standard (and already available on the boost library), which will remove this requirement.
To ease implementation of this class the full domain is represented by the fact that the subjacent value collection is empty. This simplifies the implementation of the default dcontructor of this domain which is implicitely expected to generate a full domain. If one wnats to derive from this class to create domains with fully specified set of possible values, he will also preferrably have to redefine the isFull method to reflect this.
Author:
Frederic Py fpy@m.nosp@m.bari.nosp@m..org
Definition at line 93 of file EnumeratedDomain.hh.
Member Typedef Documentation
typedef TREX::utils::XmlFactory<DomainBase, boost::shared_ptr<DomainBase> > TREX::transaction::DomainBase::xml_factory [inherited]
XML parsing factory for domains.
This type defines the factory that should be manipulated for parsing domains from xml.
Definition at line 403 of file DomainBase.hh.
Constructor & Destructor Documentation
template<typename Ty, class Comp = std::less<Ty>> TREX::transaction::EnumeratedDomain< Ty, Comp >::EnumeratedDomain (TREX::utils::Symbol const & type) [inline, explicit]
Constructor.
Parameters:
type a symbolic type name
Create a new instance as a full domain of type type.
Definition at line 108 of file EnumeratedDomain.hh.
template<typename Ty, class Comp = std::less<Ty>> template<class Iter > TREX::transaction::EnumeratedDomain< Ty, Comp >::EnumeratedDomain (TREX::utils::Symbol const & type, Iter from, Iter to) [inline]
Constructor.
Template Parameters:
Iter an iterator type
Parameters:
type A symbolic type name
from An iterator
to An iterator
Create a new instance of type type containing all the elements between from and to
Precondition:
[from, to) should be a valid iterator sequence
[from to) is not empty (ie from!=to)
the type referred by Iter should be convertible into Ty
Exceptions:
EmptyDomain the created domain is empty
Definition at line 125 of file EnumeratedDomain.hh.
template<typename Ty, class Comp = std::less<Ty>> TREX::transaction::EnumeratedDomain< Ty, Comp >::EnumeratedDomain (TREX::utils::Symbol const & type, Ty const & val) [inline, explicit]
Constructor.
Parameters:
type A symbolic type name
val A value
Create a new instance of type type containing only the element val
Definition at line 139 of file EnumeratedDomain.hh.
template<typename Ty, class Comp = std::less<Ty>> TREX::transaction::EnumeratedDomain< Ty, Comp >::EnumeratedDomain (EnumeratedDomain< Ty, Comp > const & other) [inline, protected]
Copy constructor.
Parameters:
other Another instance
Create a new instance which is a copy of other
Definition at line 245 of file EnumeratedDomain.hh.
template<typename Ty, class Comp = std::less<Ty>> TREX::transaction::EnumeratedDomain< Ty, Comp >::EnumeratedDomain (boost::property_tree::ptree::value_type & node) [inline, protected]
XML parsing constructor.
Parameters:
node An XML node
Create a new instance by parsing the content of node. The expected structure of this node is expected to be of a from similar to the following :
 < <type> >
   <elem value="<val1>"/>
   <elem value="<val2>"/>
   [...]
 </ <type> >
where <type> is the type of the domain and <vali> are possible values for this domain
Exceptions:
TREX::utils::bad_string_cast Unable to parse one of the <vali> attributes
Note:
If no elem tag is defined into node, the domain will be considered as full.
Definition at line 268 of file EnumeratedDomain.hh.
Member Function Documentation
template<typename Ty, class Comp = std::less<Ty>> void TREX::transaction::EnumeratedDomain< Ty, Comp >::add (Ty const & val) [inline]
Add an element to the domain.
Parameters:
val A value
This method allows user to add val into the possible values of this domain.
Note:
this method is an helper to ease the construction of enumerated domains. It should be used only when the domain is constructed and still not public to other reactors. Overwise using it represent a domain relaxation which could be problematic for third party components such as planner based reactors.
See also:
template<class Iter> void add(Iter, Iter)
Definition at line 164 of file EnumeratedDomain.hh.
Referenced by TREX::transaction::EnumeratedDomain< TREX::utils::Symbol >::EnumeratedDomain().
template<typename Ty, class Comp = std::less<Ty>> template<class Iter > void TREX::transaction::EnumeratedDomain< Ty, Comp >::add (Iter from, Iter to) [inline]
Add an element to the domain.
Template Parameters:
Iter An iterator type
Parameters:
from an iterator
to an iterator
This method allows user to add all the elements referred by [from, to) into the possible values of this domain.
Precondition:
[from, to) should be a valid iterator sequence
the type referred by Iter should be convertible into Ty
Note:
this method is an helper to ease the construction of enumerated domains. It should be used only when the domain is constructed and still not public to other reactors. Overwise it using it represent a domain relaxation which could be problematic for third party components such as planner based reactors.
See also:
void add(Ty const &)
Definition at line 188 of file EnumeratedDomain.hh.
template<typename Ty, class Comp = std::less<Ty>> iterator TREX::transaction::EnumeratedDomain< Ty, Comp >::begin () const [inline]
First element.
This method allows user to iterate through the possible values of the domain using classic C++ iterator paradigm.
Returns:
An iterator to the beginnig of the possible values collection
Definition at line 224 of file EnumeratedDomain.hh.
Referenced by TREX::transaction::EnumeratedDomain< TREX::utils::Symbol >::getElement(), TREX::transaction::EnumeratedDomain< Ty, Comp >::intersect(), and TREX::transaction::EnumeratedDomain< Ty, Comp >::restrictWith().
template<typename Ty, class Comp = std::less<Ty>> bool TREX::transaction::EnumeratedDomain< Ty, Comp >::contains (Ty const & val) const [inline]
test for membership
Parameters:
val A value
Return values:
true if val is a possible value for this domain
false otherwise
Definition at line 197 of file EnumeratedDomain.hh.
virtual DomainBase* TREX::transaction::DomainBase::copy () const [pure virtual, inherited]
Duplicate method.
Create a new instance which is identical to current instance value. This instance is usually created using the new operator and it is up to the caller to de-allocate it when not needed.
Returns:
The newly created instance
Implemented in TREX::transaction::EnumDomain, TREX::transaction::StringDomain, TREX::transaction::FloatDomain, TREX::transaction::IntegerDomain, TREX::transaction::BooleanDomain, TREX::europa::EuropaEntity, and TREX::europa::details::EuropaDomain.
Referenced by TREX::transaction::Variable::restrict().
template<typename Ty, class Comp = std::less<Ty>> iterator TREX::transaction::EnumeratedDomain< Ty, Comp >::end () const [inline]
End iterator.
This method allows user to iterate through the possible values of the domain using classic C++ iterator paradigm.
Returns:
An iterator to the end of the possible values collection
Definition at line 234 of file EnumeratedDomain.hh.
Referenced by TREX::transaction::EnumeratedDomain< TREX::utils::Symbol >::contains(), TREX::transaction::EnumeratedDomain< TREX::utils::Symbol >::getElement(), TREX::transaction::EnumeratedDomain< Ty, Comp >::intersect(), and TREX::transaction::EnumeratedDomain< Ty, Comp >::restrictWith().
template<class Ty , class Cmp > bool TREX::transaction::EnumeratedDomain< Ty, Cmp >::equals (DomainBase const & other) const [virtual]
Equality test.
Parameters:
other Another instance
Checks if current instance is identical to other. This generally means that both have the same type and exactly the same possible values. In that sense it is more restrictive than the intersect method.
Return values:
true if current instance is identical to other
false otherwise
See also:
bool intersect(DomainBase const &other) const
Implements TREX::transaction::DomainBase.
Definition at line 329 of file EnumeratedDomain.hh.
References TREX::transaction::DomainBase::getTypeName().
template<typename Ty, class Comp = std::less<Ty>> boost::any TREX::transaction::EnumeratedDomain< Ty, Comp >::getElement (size_t i) const [inline, virtual]
generic element access
Parameters:
i index of the element
This method give access to the element i of the domain.
Precondition:
i is less than the size of the set
Returns:
the element at index i encapsulated on the boost::any class
See also:
size_t getSize() const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Implements TREX::transaction::BasicEnumerated.
Definition at line 208 of file EnumeratedDomain.hh.
boost::any DomainBase::getSingleton () const [inherited]
singleton value
This methods give acces to the value of a singleton instance.
Precondition:
the instance is a singleton
Exceptions:
DomainAccess the insatnce was not a singleton
Returns:
The value of the domain encapsulated in a boost::any
Note:
except for the control of the instance being a singleton the actual code of this method will be provided by the virtual method singleton()
See also:
boost::any singleton() const
getStringSingleton() const
getTypedSingleton() const
Definition at line 56 of file DomainBase.cc.
References TREX::transaction::DomainBase::isSingleton(), and TREX::transaction::DomainBase::singleton().
Referenced by TREX::transaction::DomainBase::getTypedSingleton().
template<typename Ty, class Comp = std::less<Ty>> size_t TREX::transaction::EnumeratedDomain< Ty, Comp >::getSize () const [inline, virtual]
element count
This method gives access to the number of elements in this instance.
Returns:
the number of values associated to this domain
Note:
by convention if the returned value is 0, TREX will consider this domain as full
Implements TREX::transaction::BasicEnumerated.
Definition at line 204 of file EnumeratedDomain.hh.
std::string DomainBase::getStringSingleton () const [inherited]
singleton value
This methods give acces to the value of a singleton instance represented as a string
Precondition:
the instance is a singleton
Exceptions:
DomainAccess the insatnce was not a singleton
Returns:
The text representation of the singleton value
Note:
except for the control of the instance being a singleton the actual code of this method will be provided by the virtual method stringSingleton()
See also:
std::string stringSingleton() const
getStringSingleton() const
getTypedSingleton() const
Definition at line 62 of file DomainBase.cc.
References TREX::transaction::DomainBase::isSingleton(), and TREX::transaction::DomainBase::stringSingleton().
Referenced by TREX::transaction::DomainBase::getTypedSingleton().
std::string BasicEnumerated::getStringValue (size_t i) const [virtual, inherited]
Get element textual value.
Parameters:
[in] i Index of the element
Get the value of the element i of the domain in its textual form
Precondition:
i is a valid index (between 0 and the size of the set-1)
Returns:
A string with a human readable for the value of the element i
See also:
getSize() const
getElement(size_t) const
getTypedElement(size_t) const
Definition at line 68 of file BasicEnumerated.cc.
Referenced by TREX::transaction::BasicEnumerated::getTypedElement(), TREX::transaction::BasicEnumerated::toXml(), and TREX::europa::details::europa_domain::visit().
template<class Ty , bool Safe> Ty TREX::transaction::BasicEnumerated::getTypedElement (size_t n) const [inline, inherited]
Typed element access.
Template Parameters:
Ty expected return type
Safe extraction method
Parameters:
i index of the element
This method give access to the element i of the domain converted in the type Ty. The Safe flag indicate whether the conversion to Ty should be done using boost::any_cast -- which will fail if the encapsulated type is not Ty -- or using the safer string_cast that should be more type robust
Precondition:
i is less than the size of the set
if Safe is false, the underlying type of the container has to be exactly Ty
if Safe is true the string value of this element should be parseable into Ty
Returns:
the element at index i converted to the type Ty
Note:
No matter what this method is heavy in term of computation overhead and should be used wisely (mostly for debugging/instrumentation purpose)
See also:
size_t getSize() const
boost::any getElement(size_t i) const
std::string getStringValue(size_t i) const
Definition at line 137 of file BasicEnumerated.hh.
References TREX::transaction::BasicEnumerated::getElement(), TREX::transaction::BasicEnumerated::getStringValue(), and TREX::utils::string_cast().
template<class Ty , bool Safe> Ty TREX::transaction::DomainBase::getTypedSingleton () const [inline, inherited]
singleton value
Template Parameters:
Ty output type
Safe robust conversion
This methods give acces to the value of a singleton instance The output will be of type Ty
The Safe parameter indicates which method should be used.
If the real type of the underneath domain type is guaranteed to be Ty the Safe can be false for performance
If the type is not guaranteed to be Ty but its text representation is compatible with Ty the Safe should be true
Precondition:
the instance is a singleton
the type of the value manip[ulated by this domain should be convertible to Ty or exactly Ty is Safe is false
Exceptions:
DomainAccess the insatnce was not a singleton
boost::bad_string_cast Safe is true and the value of the singleton cannot be parse into Ty
boost::bad_string_cast Safe is false and the type of the singleton is not Ty
Returns:
The singleton value of this domain
See also:
getStringSingleton() const
getSingleton() const
Definition at line 368 of file DomainBase.hh.
References TREX::transaction::DomainBase::getSingleton(), TREX::transaction::DomainBase::getStringSingleton(), and TREX::utils::string_cast().
Referenced by TREX::europa::details::europa_domain::visit().
TREX::utils::Symbol const& TREX::transaction::DomainBase::getTypeName () const [inline, inherited]
type of the domain
This method indicates the type of this domain. The type is a symbol that describes what is the type manipulated by this domain.
Returns:
the type associated to this domain
Definition at line 223 of file DomainBase.hh.
Referenced by TREX::transaction::BooleanDomain::equals(), TREX::transaction::EnumeratedDomain< Ty, Comp >::equals(), TREX::transaction::BooleanDomain::intersect(), TREX::transaction::EnumeratedDomain< Ty, Comp >::intersect(), TREX::transaction::BooleanDomain::restrictWith(), TREX::transaction::EnumeratedDomain< Ty, Comp >::restrictWith(), TREX::transaction::BasicEnumerated::toXml(), TREX::transaction::BasicInterval::toXml(), and TREX::europa::details::europa_domain::visit().
template<class Ty , class Cmp > bool TREX::transaction::EnumeratedDomain< Ty, Cmp >::intersect (DomainBase const & other) const [virtual]
check for common values
Parameters:
other another instance
This methods indicates if current instance share values with other. This generally means that both have the same type and that one can safely restrict the domain of the other.
Return values:
true if current instance shares values with other
false otherwise
See also:
bool equals(DomainBase const &other) const
DomainBase &restrictWith(DomainBase const &other)
Implements TREX::transaction::DomainBase.
Definition at line 300 of file EnumeratedDomain.hh.
References TREX::transaction::EnumeratedDomain< Ty, Comp >::begin(), TREX::transaction::EnumeratedDomain< Ty, Comp >::end(), TREX::transaction::DomainBase::getTypeName(), and TREX::transaction::BasicEnumerated::isFull().
bool TREX::transaction::BasicEnumerated::isEnumerated () const [inline, virtual, inherited]
Check for enumerated domain.
This method check if the domain is based on an enumerated representation. In which case its representation is based on the list of all the possible values.
Return values:
true if the domain is enumeration based
false otherwise
See also:
bool isInterval() const
Implements TREX::transaction::DomainBase.
Definition at line 70 of file BasicEnumerated.hh.
bool TREX::transaction::BasicEnumerated::isFull () const [inline, virtual, inherited]
check for full domain
This method identifies if current domain is full. A full domain is adomain that includes al the possibles values for its type.
Return values:
true if current instance is full
false otherwise
Implements TREX::transaction::DomainBase.
Definition at line 74 of file BasicEnumerated.hh.
References TREX::transaction::BasicEnumerated::getSize().
Referenced by TREX::transaction::EnumeratedDomain< TREX::utils::Symbol >::contains(), and TREX::transaction::EnumeratedDomain< Ty, Comp >::intersect().
bool TREX::transaction::BasicEnumerated::isInterval () const [inline, virtual, inherited]
Check for interval domain.
This method is used to identify if this domain is an interval based domain. In which case it is represented by a lower and upper bound.
Return values:
true if the domain is interval based
false otherwise
See also:
bool isEnumerated() const
Implements TREX::transaction::DomainBase.
Definition at line 67 of file BasicEnumerated.hh.
bool TREX::transaction::BasicEnumerated::isSingleton () const [inline, virtual, inherited]
check for singleton value
This method identifies if current domain is a singleton. A singleton domain is defined by one and only one value.
Return values:
true if current instance is a singleton
false otherwise
Implements TREX::transaction::DomainBase.
Definition at line 77 of file BasicEnumerated.hh.
References TREX::transaction::BasicEnumerated::getSize().
DomainBase& TREX::transaction::DomainBase::operator*= (DomainBase const & other) [inline, inherited]
Restrict domain possible values.
Parameters:
other Another domain
This method restrict the domain of current instance to the values that are shared by this domain and other.
Precondition:
this domain intersect other
Returns:
this domain after the operation
Exceptions:
EmptyDomain resulting domain is empty
See also:
bool intersect(DomainBase const &) const
Definition at line 280 of file DomainBase.hh.
References TREX::transaction::DomainBase::restrictWith().
template<class Ty , class Cmp > DomainBase & TREX::transaction::EnumeratedDomain< Ty, Cmp >::restrictWith (DomainBase const & other) [virtual]
Restrict domain possible values.
Parameters:
other Another domain
This method restrict the domain of current instance to the values that are shared by this domain and other.
Precondition:
this domain intersect other
Returns:
this domain after the operation
Exceptions:
EmptyDomain resulting domain is empty
See also:
bool intersect(DomainBase const &) const
Implements TREX::transaction::DomainBase.
Definition at line 340 of file EnumeratedDomain.hh.
References TREX::transaction::EnumeratedDomain< Ty, Comp >::begin(), TREX::transaction::EnumeratedDomain< Ty, Comp >::end(), and TREX::transaction::DomainBase::getTypeName().
std::ostream & BasicEnumerated::toXml (std::ostream & out, size_t tabs) const [virtual, inherited]
XML conversion.
Parameters:
out An output stream
tabs indentation level
This methods writes an XML representation of the domain into the output stream out. The tabs attribute indicates the indentation level expected for the tags.
Note:
To ensure compatibility this method should produce an xml output which is compatible with the XML parsing constructor of this domain.
Returns:
out after the operation
See also:
DomainBase(rapidxml::xml_node<> const &)
xml_factory
Implements TREX::transaction::DomainBase.
Definition at line 86 of file BasicEnumerated.cc.
References TREX::transaction::BasicEnumerated::getSize(), TREX::transaction::BasicEnumerated::getStringValue(), and TREX::transaction::DomainBase::getTypeName().
The documentation for this class was generated from the following file:
trex/domain/EnumeratedDomain.hh