trex: TREX::transaction::BasicInterval Class Reference
TREX::transaction::BasicInterval Class Reference
Domains
Interval Domain base class.
#include <trex/domain/BasicInterval.hh>
Public Types
typedef
TREX::utils::XmlFactory
< DomainBase,
boost::shared_ptr< DomainBase > > xml_factory
XML parsing factory for domains.
Public Member Functions
virtual DomainBase * copy () const =0
Duplicate method.
virtual bool equals (DomainBase const &other) const =0
Equality test.
virtual boost::any getLower () const =0
boost::any getSingleton () const
singleton value
virtual std::string getStringLower () const
std::string getStringSingleton () const
singleton value
virtual std::string getStringUpper () const
template<class Ty , bool Safe>
Ty getTypedLower () const
template<class Ty , bool Safe>
Ty getTypedSingleton () const
singleton value
template<class Ty , bool Safe>
Ty getTypedUpper () const
TREX::utils::Symbol const & getTypeName () const
type of the domain
virtual boost::any getUpper () const =0
virtual bool hasLower () const =0
virtual bool hasUpper () const =0
virtual bool intersect (DomainBase const &other) const =0
check for common values
bool isEnumerated () const
Check for enumerated domain.
bool isFull () const
check for full domain
bool isInterval () const
Check for interval domain.
virtual bool isSingleton () const =0
check for singleton value
DomainBase & operator*= (DomainBase const &other)
Restrict domain possible values.
virtual DomainBase & restrictWith (DomainBase const &other)=0
Restrict domain possible values.
std::ostream & toXml (std::ostream &out, size_t tabs) const
XML conversion.
virtual ~BasicInterval ()
Destructor.
Protected Member Functions
BasicInterval (TREX::utils::Symbol const &type)
BasicInterval (boost::property_tree::ptree::value_type &node)
void completeParsing (boost::property_tree::ptree::value_type &node)
virtual void parseLower (std::string const &val)=0
virtual void parseUpper (std::string const &val)=0
virtual std::ostream & print_lower (std::ostream &out) const =0
virtual std::ostream & print_upper (std::ostream &out) const =0
Friends
std::ostream & std::operator<< (std::ostream &out, TREX::utils::ostreamable const &x)
Detailed Description
Interval Domain base class.
This class provide a unified abstract interface for implementing interval domains. It especially provide a way to ease and unify the access methods and input/output for all the domain of this kind.
Author:
Frederic Py fpy@m.nosp@m.bari.nosp@m..org
Definition at line 62 of file BasicInterval.hh.
Member Typedef Documentation
typedef TREX::utils::XmlFactory<DomainBase, boost::shared_ptr<DomainBase> > TREX::transaction::DomainBase::xml_factory [inherited]
XML parsing factory for domains.
This type defines the factory that should be manipulated for parsing domains from xml.
Definition at line 403 of file DomainBase.hh.
Member Function Documentation
virtual DomainBase* TREX::transaction::DomainBase::copy () const [pure virtual, inherited]
Duplicate method.
Create a new instance which is identical to current instance value. This instance is usually created using the new operator and it is up to the caller to de-allocate it when not needed.
Returns:
The newly created instance
Implemented in TREX::transaction::EnumDomain, TREX::transaction::StringDomain, TREX::transaction::FloatDomain, TREX::transaction::IntegerDomain, TREX::transaction::BooleanDomain, TREX::europa::EuropaEntity, and TREX::europa::details::EuropaDomain.
Referenced by TREX::transaction::Variable::restrict().
virtual bool TREX::transaction::DomainBase::equals (DomainBase const & other) const [pure virtual, inherited]
Equality test.
Parameters:
other Another instance
Checks if current instance is identical to other. This generally means that both have the same type and exactly the same possible values. In that sense it is more restrictive than the intersect method.
Return values:
true if current instance is identical to other
false otherwise
See also:
bool intersect(DomainBase const &other) const
Implemented in TREX::transaction::IntervalDomain< Ty, Comp >, TREX::transaction::IntervalDomain< long >, TREX::transaction::IntervalDomain< double >, TREX::transaction::EnumeratedDomain< Ty, Comp >, TREX::transaction::EnumeratedDomain< std::string >, TREX::transaction::EnumeratedDomain< TREX::utils::Symbol >, TREX::transaction::BooleanDomain, and TREX::europa::details::EuropaDomain.
Referenced by TREX::transaction::Goal::listAttributes().
boost::any DomainBase::getSingleton () const [inherited]
singleton value
This methods give acces to the value of a singleton instance.
Precondition:
the instance is a singleton
Exceptions:
DomainAccess the insatnce was not a singleton
Returns:
The value of the domain encapsulated in a boost::any
Note:
except for the control of the instance being a singleton the actual code of this method will be provided by the virtual method singleton()
See also:
boost::any singleton() const
getStringSingleton() const
getTypedSingleton() const
Definition at line 56 of file DomainBase.cc.
References TREX::transaction::DomainBase::isSingleton(), and TREX::transaction::DomainBase::singleton().
Referenced by TREX::transaction::DomainBase::getTypedSingleton().
std::string DomainBase::getStringSingleton () const [inherited]
singleton value
This methods give acces to the value of a singleton instance represented as a string
Precondition:
the instance is a singleton
Exceptions:
DomainAccess the insatnce was not a singleton
Returns:
The text representation of the singleton value
Note:
except for the control of the instance being a singleton the actual code of this method will be provided by the virtual method stringSingleton()
See also:
std::string stringSingleton() const
getStringSingleton() const
getTypedSingleton() const
Definition at line 62 of file DomainBase.cc.
References TREX::transaction::DomainBase::isSingleton(), and TREX::transaction::DomainBase::stringSingleton().
Referenced by TREX::transaction::DomainBase::getTypedSingleton().
template<class Ty , bool Safe> Ty TREX::transaction::DomainBase::getTypedSingleton () const [inline, inherited]
singleton value
Template Parameters:
Ty output type
Safe robust conversion
This methods give acces to the value of a singleton instance The output will be of type Ty
The Safe parameter indicates which method should be used.
If the real type of the underneath domain type is guaranteed to be Ty the Safe can be false for performance
If the type is not guaranteed to be Ty but its text representation is compatible with Ty the Safe should be true
Precondition:
the instance is a singleton
the type of the value manip[ulated by this domain should be convertible to Ty or exactly Ty is Safe is false
Exceptions:
DomainAccess the insatnce was not a singleton
boost::bad_string_cast Safe is true and the value of the singleton cannot be parse into Ty
boost::bad_string_cast Safe is false and the type of the singleton is not Ty
Returns:
The singleton value of this domain
See also:
getStringSingleton() const
getSingleton() const
Definition at line 368 of file DomainBase.hh.
References TREX::transaction::DomainBase::getSingleton(), TREX::transaction::DomainBase::getStringSingleton(), and TREX::utils::string_cast().
Referenced by TREX::europa::details::europa_domain::visit().
TREX::utils::Symbol const& TREX::transaction::DomainBase::getTypeName () const [inline, inherited]
type of the domain
This method indicates the type of this domain. The type is a symbol that describes what is the type manipulated by this domain.
Returns:
the type associated to this domain
Definition at line 223 of file DomainBase.hh.
Referenced by TREX::transaction::BooleanDomain::equals(), TREX::transaction::EnumeratedDomain< Ty, Comp >::equals(), TREX::transaction::BooleanDomain::intersect(), TREX::transaction::EnumeratedDomain< Ty, Comp >::intersect(), TREX::transaction::BooleanDomain::restrictWith(), TREX::transaction::EnumeratedDomain< Ty, Comp >::restrictWith(), TREX::transaction::BasicEnumerated::toXml(), toXml(), and TREX::europa::details::europa_domain::visit().
virtual bool TREX::transaction::DomainBase::intersect (DomainBase const & other) const [pure virtual, inherited]
check for common values
Parameters:
other another instance
This methods indicates if current instance share values with other. This generally means that both have the same type and that one can safely restrict the domain of the other.
Return values:
true if current instance shares values with other
false otherwise
See also:
bool equals(DomainBase const &other) const
DomainBase &restrictWith(DomainBase const &other)
Implemented in TREX::transaction::IntervalDomain< Ty, Comp >, TREX::transaction::IntervalDomain< long >, TREX::transaction::IntervalDomain< double >, TREX::transaction::EnumeratedDomain< Ty, Comp >, TREX::transaction::EnumeratedDomain< std::string >, TREX::transaction::EnumeratedDomain< TREX::utils::Symbol >, TREX::transaction::BooleanDomain, and TREX::europa::details::EuropaDomain.
Referenced by TREX::transaction::Goal::restrictTime(), and TREX::europa::details::europa_domain::visit().
bool TREX::transaction::BasicInterval::isEnumerated () const [inline, virtual]
Check for enumerated domain.
This method check if the domain is based on an enumerated representation. In which case its representation is based on the list of all the possible values.
Return values:
true if the domain is enumeration based
false otherwise
See also:
bool isInterval() const
Implements TREX::transaction::DomainBase.
Definition at line 70 of file BasicInterval.hh.
bool TREX::transaction::BasicInterval::isFull () const [inline, virtual]
check for full domain
This method identifies if current domain is full. A full domain is adomain that includes al the possibles values for its type.
Return values:
true if current instance is full
false otherwise
Implements TREX::transaction::DomainBase.
Reimplemented in TREX::transaction::BooleanDomain.
Definition at line 77 of file BasicInterval.hh.
Referenced by TREX::europa::details::europa_domain::visit().
bool TREX::transaction::BasicInterval::isInterval () const [inline, virtual]
Check for interval domain.
This method is used to identify if this domain is an interval based domain. In which case it is represented by a lower and upper bound.
Return values:
true if the domain is interval based
false otherwise
See also:
bool isEnumerated() const
Implements TREX::transaction::DomainBase.
Definition at line 67 of file BasicInterval.hh.
virtual bool TREX::transaction::DomainBase::isSingleton () const [pure virtual, inherited]
check for singleton value
This method identifies if current domain is a singleton. A singleton domain is defined by one and only one value.
Return values:
true if current instance is a singleton
false otherwise
Implemented in TREX::transaction::IntervalDomain< Ty, Comp >, TREX::transaction::IntervalDomain< long >, TREX::transaction::IntervalDomain< double >, TREX::transaction::BooleanDomain, TREX::transaction::BasicEnumerated, and TREX::europa::details::EuropaDomain.
Referenced by TREX::transaction::DomainBase::getSingleton(), TREX::transaction::DomainBase::getStringSingleton(), and TREX::europa::details::europa_domain::visit().
DomainBase& TREX::transaction::DomainBase::operator*= (DomainBase const & other) [inline, inherited]
Restrict domain possible values.
Parameters:
other Another domain
This method restrict the domain of current instance to the values that are shared by this domain and other.
Precondition:
this domain intersect other
Returns:
this domain after the operation
Exceptions:
EmptyDomain resulting domain is empty
See also:
bool intersect(DomainBase const &) const
Definition at line 280 of file DomainBase.hh.
References TREX::transaction::DomainBase::restrictWith().
virtual DomainBase& TREX::transaction::DomainBase::restrictWith (DomainBase const & other) [pure virtual, inherited]
Restrict domain possible values.
Parameters:
other Another domain
This method restrict the domain of current instance to the values that are shared by this domain and other.
Precondition:
this domain intersect other
Returns:
this domain after the operation
Exceptions:
EmptyDomain resulting domain is empty
See also:
bool intersect(DomainBase const &) const
Implemented in TREX::transaction::IntervalDomain< Ty, Comp >, TREX::transaction::IntervalDomain< long >, TREX::transaction::IntervalDomain< double >, TREX::transaction::EnumeratedDomain< Ty, Comp >, TREX::transaction::EnumeratedDomain< std::string >, TREX::transaction::EnumeratedDomain< TREX::utils::Symbol >, TREX::transaction::BooleanDomain, and TREX::europa::details::EuropaDomain.
Referenced by TREX::transaction::DomainBase::operator*=().
std::ostream & BasicInterval::toXml (std::ostream & out, size_t tabs) const [virtual]
XML conversion.
Parameters:
out An output stream
tabs indentation level
This methods writes an XML representation of the domain into the output stream out. The tabs attribute indicates the indentation level expected for the tags.
Note:
To ensure compatibility this method should produce an xml output which is compatible with the XML parsing constructor of this domain.
Returns:
out after the operation
See also:
DomainBase(rapidxml::xml_node<> const &)
xml_factory
Implements TREX::transaction::DomainBase.
Reimplemented in TREX::transaction::BooleanDomain.
Definition at line 80 of file BasicInterval.cc.
References TREX::transaction::DomainBase::getTypeName().
The documentation for this class was generated from the following files:
trex/domain/BasicInterval.hh
trex/domain/BasicInterval.cc