trex: TREX::utils::RStat Class Reference
TREX::utils::RStat Class Reference
Basic utilities
Resource usage stats management class.
#include <trex/utils/RStat.hh>
Public Types
enum who_type { self = RUSAGE_SELF, children = RUSAGE_CHILDREN, zeroed = 1, unknown = 2 }
stats about who
Public Member Functions
std::ostream & compact_desc (std::ostream &out) const
Short stats description.
std::ostream & long_desc (std::ostream &out) const
Long stats description.
long const & max_resident () const
Maximum resident set size.
long const & n_page_faults () const
Number of page faults.
long const & n_page_reclaims () const
Number of page reclaims.
RStat operator* (long n) const
Multiplication.
RStat operator+ (RStat const &other) const
Addition of stats.
RStat operator- (RStat const &other) const
Difference between stats.
RStat operator/ (long n) const
Division.
void reset (who_type who=unknown)
Get new stats.
RStat (who_type who=self)
Constructor.
timeval const & system_time () const
System time.
timeval const & user_time () const
User time.
who_type who () const
Type of process stats.
~RStat ()
Destructor.
Static Public Member Functions
static std::string compact_header ()
Compact stats header descprition.
Related Functions
(Note that these are not member functions.)
RStat operator* (long n, RStat const &s)
Multiplication.
std::ostream & operator<< (std::ostream &out, RStat const &stats)
Output write operator.
Detailed Description
Resource usage stats management class.
This class offer a simple and basic access to resource usage statistics for processes.
Author:
Frederic Py fpy@m.nosp@m.bari.nosp@m..org
Note:
This class is based on POSIX C function getrusage. It does not yet offer all the interfaces to access data given by this function.
Deprecated:
The RStat class is now replaced by Boost.Chrono library.
Definition at line 68 of file RStat.hh.
Member Enumeration Documentation
enum TREX::utils::RStat::who_type
stats about who
This type is used by RStat to specify what processes are described on statisitics.
Enumerator:
self
self statisitics.
children
children statistics.
Bug:
As said in the man page of getrusage : "There is no way to obtain information about a child process that has not yet terminated."
zeroed
Unknown statisitics.
This occur when you make operation with RStat instances having different who_type.
Definition at line 75 of file RStat.hh.
Constructor & Destructor Documentation
RStat::RStat (RStat::who_type who = self)
Constructor.
Parameters:
who Stats about who information
Precondition:
who value must be one of RStat::self or RStat::children
Create a new insatnce and get the stats for the given who. This give a direct snapshot of the process(es).
Exceptions:
ErrnoExcept A problem occured when getting stats. The most probable cause is a bad value for who (errno==EINVAL).
Definition at line 72 of file RStat.cc.
References reset().
Member Function Documentation
std::ostream & RStat::compact_desc (std::ostream & out) const
Short stats description.
Parameters:
out an output stream
This method writes a short descrip[tion of the stats grabbed by this instance into out. The format of the string written is as follow :
 user_time, system_time, max_resident, n_page_reclaims, n_page_faults
Returns:
out after the operation
See also:
std::ostream &long_desc(std::ostream &) const
std::ostream &operation<<(std::ostream &, RStat const &)
Definition at line 247 of file RStat.cc.
Referenced by operator<<().
std::ostream & RStat::long_desc (std::ostream & out) const
Long stats description.
Parameters:
out an output stream
This method writes a full descrip[tion of the stats grabbed by this instance into out
Returns:
out after the operation
See also:
std::ostream &compact_desc(std::ostream &out) const
Definition at line 216 of file RStat.cc.
long const& TREX::utils::RStat::max_resident () const [inline]
Maximum resident set size.
Returns:
the maximum amount of resident memory used.
Note:
It is not clear to right now what is the unity of this value. Indeed, it looks like it is given in term of memory pages. In this case we would probably need to get the page size on current system to convert into bytes. Right now I consider that this size is given in bytes.
Todo:
This value is for resident memory size. It will be less or equal to the real amount of memory. I have to find out a way to have the total amount of memory used but didn't found doc about that.
Bug:
This information is not updated in real-time by the system. The update rate of your OS can be found using the command :
 sysctl kern.clockrate
The value of stathz indicates the frequency of the updates (100Hz under MacOS X.4). Keep this in mind when you read the results.
Definition at line 188 of file RStat.hh.
long const& TREX::utils::RStat::n_page_faults () const [inline]
Number of page faults.
Returns:
The number of page faults
Definition at line 203 of file RStat.hh.
long const& TREX::utils::RStat::n_page_reclaims () const [inline]
Number of page reclaims.
Returns:
The number of page reclaimed
Definition at line 196 of file RStat.hh.
RStat RStat::operator* (long n) const
Multiplication.
Parameters:
n a factor
Returns:
A new stats snapshot which is current instance multiplied by n
Definition at line 154 of file RStat.cc.
RStat RStat::operator+ (RStat const & other) const
Addition of stats.
Parameters:
other another stats snapshot.
Returns:
A new stats snapshot giving the sum of current instance and other.
Note:
If the who() value differs form current instance and other, then the who() value of the result will be RStat::unknown which prohibit the call to reset.
Todo:
It may be preferable to throw an exception if who() types differs.
Definition at line 125 of file RStat.cc.
RStat RStat::operator- (RStat const & other) const
Difference between stats.
Parameters:
other another stats snapshot.
Returns:
A new stats snapshot giving the difference between current instance and other.
Note:
If the who() value differs form current instance and other, then the who() value of the result will be RStat::unknown which prohibit the call to reset.
Todo:
It may be preferable to throw an exception if who() types differs.
Definition at line 96 of file RStat.cc.
RStat RStat::operator/ (long n) const
Division.
Parameters:
n a divider
Precondition:
n!=0
Returns:
A new stats snapshot which is current instance divided by n
Definition at line 183 of file RStat.cc.
void RStat::reset (RStat::who_type wt = unknown)
Get new stats.
This method is called to update the stats values of this instance.
Precondition:
The who() value must be one of RStat::self or RStat::children
Exceptions:
ErrnoExcept A problem occured when getting stats. The most probable cause is a bad value for who() (errno==EINVAL).
See also:
who() const
Definition at line 79 of file RStat.cc.
References zeroed.
Referenced by RStat().
timeval const& TREX::utils::RStat::system_time () const [inline]
System time.
Returns:
The amount of time spent on system execution space. The system time correspond to the time spent on system calls.
See also:
user_time() const
Definition at line 158 of file RStat.hh.
timeval const& TREX::utils::RStat::user_time () const [inline]
User time.
Returns:
The amount of time spent on user execution space. The user time correspond to the non system calls.
See also:
system_time() const
Definition at line 146 of file RStat.hh.
who_type TREX::utils::RStat::who () const [inline]
Type of process stats.
Returns:
the type of processes the stats are depicting.
Definition at line 134 of file RStat.hh.
Referenced by TREX::utils::RStatLap::~RStatLap().
The documentation for this class was generated from the following files:
trex/utils/RStat.hh
trex/utils/RStat.cc