trex: TREX::transaction::DomainBase Class Reference
TREX::transaction::DomainBase Class Reference
Domains
Abstract domain definition.
#include <trex/domain/DomainBase.hh>
Public Types
typedef
TREX::utils::XmlFactory
< DomainBase,
boost::shared_ptr< DomainBase > > xml_factory
XML parsing factory for domains.
Public Member Functions
virtual void accept (DomainVisitor &visitor) const
Visiting method.
virtual DomainBase * copy () const =0
Duplicate method.
virtual bool equals (DomainBase const &other) const =0
Equality test.
boost::any getSingleton () const
singleton value
std::string getStringSingleton () const
singleton value
template<class Ty , bool Safe>
Ty getTypedSingleton () const
singleton value
TREX::utils::Symbol const & getTypeName () const
type of the domain
virtual bool intersect (DomainBase const &other) const =0
check for common values
virtual bool isEnumerated () const =0
Check for enumerated domain.
virtual bool isFull () const =0
check for full domain
virtual bool isInterval () const =0
Check for interval domain.
virtual bool isSingleton () const =0
check for singleton value
DomainBase & operator*= (DomainBase const &other)
Restrict domain possible values.
virtual DomainBase & restrictWith (DomainBase const &other)=0
Restrict domain possible values.
virtual std::ostream & toXml (std::ostream &out, size_t tabs=0) const =0
XML conversion.
virtual ~DomainBase ()
Destructor.
Protected Member Functions
DomainBase (TREX::utils::Symbol const &type)
Constructor.
DomainBase (boost::property_tree::ptree::value_type &node)
XML parsing constructor.
DomainBase (DomainBase const &other)
Copy constructor.
virtual std::ostream & print_domain (std::ostream &out) const =0
Print domain.
virtual boost::any singleton () const =0
singleton value This method is called by getSingleton() to get the actual value of a singleton domain
virtual std::string stringSingleton () const =0
singleton text representation This method is called by getStringSingleton() to get the actual value of a singleton domain as text
Friends
std::ostream & std::operator<< (std::ostream &out, TREX::utils::ostreamable const &x)
Detailed Description
Abstract domain definition.
This class is an abstract representation of a domain as manipulated by TREX. A domain specifies a set of possible values generally for a Variable
Author:
Frederic Py fpy@m.nosp@m.bari.nosp@m..org
Definition at line 156 of file DomainBase.hh.
Member Typedef Documentation
typedef TREX::utils::XmlFactory<DomainBase, boost::shared_ptr<DomainBase> > TREX::transaction::DomainBase::xml_factory
XML parsing factory for domains.
This type defines the factory that should be manipulated for parsing domains from xml.
Definition at line 403 of file DomainBase.hh.
Constructor & Destructor Documentation
TREX::transaction::DomainBase::DomainBase (TREX::utils::Symbol const & type) [inline, explicit, protected]
Constructor.
Parameters:
type A domain type descriptor
Create a new instance with associated domain type type
Definition at line 412 of file DomainBase.hh.
TREX::transaction::DomainBase::DomainBase (boost::property_tree::ptree::value_type & node) [inline, explicit, protected]
XML parsing constructor.
Parameters:
node An XML node
Create a new instance from parsing node. This constructor is used by xml_factory to generate domains from XML. At this abstract level. The only operation donae is to extract the type of the domain from the node tag.
Note:
to ensure compatibility this constructor should parse a XML code which is consistent with what is produced by the toXml method of your class
See also:
std::ostream &toXml(std::ostream &out, size_t tabs) const
xml_factory
Definition at line 430 of file DomainBase.hh.
TREX::transaction::DomainBase::DomainBase (DomainBase const & other) [inline, protected]
Copy constructor.
Parameters:
other Another instance
Create a new instance similar to other
Definition at line 437 of file DomainBase.hh.
Member Function Documentation
void DomainBase::accept (DomainVisitor & visitor) const [virtual]
Visiting method.
Parameters:
visitor A domain visitor
This method implement the Visitor design pattern for TREX domains. It will call visitor methods depending on the actual type of this instance.
There's 3 possible cases supported :
this class is a BasicInterval instance
this class is a BasicEnumerated instance
this class is none of the above
in each case the corresponding method of visitor will be called
See also:
DomainVisitor
Definition at line 52 of file DomainBase.cc.
References TREX::transaction::DomainVisitor::visit().
Referenced by TREX::europa::details::EuropaDomain::equals(), TREX::europa::details::EuropaDomain::intersect(), and TREX::europa::details::EuropaDomain::restrictWith().
virtual DomainBase* TREX::transaction::DomainBase::copy () const [pure virtual]
Duplicate method.
Create a new instance which is identical to current instance value. This instance is usually created using the new operator and it is up to the caller to de-allocate it when not needed.
Returns:
The newly created instance
Implemented in TREX::transaction::EnumDomain, TREX::transaction::StringDomain, TREX::transaction::FloatDomain, TREX::transaction::IntegerDomain, TREX::transaction::BooleanDomain, TREX::europa::EuropaEntity, and TREX::europa::details::EuropaDomain.
Referenced by TREX::transaction::Variable::restrict().
virtual bool TREX::transaction::DomainBase::equals (DomainBase const & other) const [pure virtual]
Equality test.
Parameters:
other Another instance
Checks if current instance is identical to other. This generally means that both have the same type and exactly the same possible values. In that sense it is more restrictive than the intersect method.
Return values:
true if current instance is identical to other
false otherwise
See also:
bool intersect(DomainBase const &other) const
Implemented in TREX::transaction::IntervalDomain< Ty, Comp >, TREX::transaction::IntervalDomain< long >, TREX::transaction::IntervalDomain< double >, TREX::transaction::EnumeratedDomain< Ty, Comp >, TREX::transaction::EnumeratedDomain< std::string >, TREX::transaction::EnumeratedDomain< TREX::utils::Symbol >, TREX::transaction::BooleanDomain, and TREX::europa::details::EuropaDomain.
Referenced by TREX::transaction::Goal::listAttributes().
boost::any DomainBase::getSingleton () const
singleton value
This methods give acces to the value of a singleton instance.
Precondition:
the instance is a singleton
Exceptions:
DomainAccess the insatnce was not a singleton
Returns:
The value of the domain encapsulated in a boost::any
Note:
except for the control of the instance being a singleton the actual code of this method will be provided by the virtual method singleton()
See also:
boost::any singleton() const
getStringSingleton() const
getTypedSingleton() const
Definition at line 56 of file DomainBase.cc.
References isSingleton(), and singleton().
Referenced by getTypedSingleton().
std::string DomainBase::getStringSingleton () const
singleton value
This methods give acces to the value of a singleton instance represented as a string
Precondition:
the instance is a singleton
Exceptions:
DomainAccess the insatnce was not a singleton
Returns:
The text representation of the singleton value
Note:
except for the control of the instance being a singleton the actual code of this method will be provided by the virtual method stringSingleton()
See also:
std::string stringSingleton() const
getStringSingleton() const
getTypedSingleton() const
Definition at line 62 of file DomainBase.cc.
References isSingleton(), and stringSingleton().
Referenced by getTypedSingleton().
template<class Ty , bool Safe> Ty TREX::transaction::DomainBase::getTypedSingleton () const [inline]
singleton value
Template Parameters:
Ty output type
Safe robust conversion
This methods give acces to the value of a singleton instance The output will be of type Ty
The Safe parameter indicates which method should be used.
If the real type of the underneath domain type is guaranteed to be Ty the Safe can be false for performance
If the type is not guaranteed to be Ty but its text representation is compatible with Ty the Safe should be true
Precondition:
the instance is a singleton
the type of the value manip[ulated by this domain should be convertible to Ty or exactly Ty is Safe is false
Exceptions:
DomainAccess the insatnce was not a singleton
boost::bad_string_cast Safe is true and the value of the singleton cannot be parse into Ty
boost::bad_string_cast Safe is false and the type of the singleton is not Ty
Returns:
The singleton value of this domain
See also:
getStringSingleton() const
getSingleton() const
Definition at line 368 of file DomainBase.hh.
References getSingleton(), getStringSingleton(), and TREX::utils::string_cast().
Referenced by TREX::europa::details::europa_domain::visit().
TREX::utils::Symbol const& TREX::transaction::DomainBase::getTypeName () const [inline]
type of the domain
This method indicates the type of this domain. The type is a symbol that describes what is the type manipulated by this domain.
Returns:
the type associated to this domain
Definition at line 223 of file DomainBase.hh.
Referenced by TREX::transaction::BooleanDomain::equals(), TREX::transaction::EnumeratedDomain< Ty, Comp >::equals(), TREX::transaction::BooleanDomain::intersect(), TREX::transaction::EnumeratedDomain< Ty, Comp >::intersect(), TREX::transaction::BooleanDomain::restrictWith(), TREX::transaction::EnumeratedDomain< Ty, Comp >::restrictWith(), TREX::transaction::BasicEnumerated::toXml(), TREX::transaction::BasicInterval::toXml(), and TREX::europa::details::europa_domain::visit().
virtual bool TREX::transaction::DomainBase::intersect (DomainBase const & other) const [pure virtual]
check for common values
Parameters:
other another instance
This methods indicates if current instance share values with other. This generally means that both have the same type and that one can safely restrict the domain of the other.
Return values:
true if current instance shares values with other
false otherwise
See also:
bool equals(DomainBase const &other) const
DomainBase &restrictWith(DomainBase const &other)
Implemented in TREX::transaction::IntervalDomain< Ty, Comp >, TREX::transaction::IntervalDomain< long >, TREX::transaction::IntervalDomain< double >, TREX::transaction::EnumeratedDomain< Ty, Comp >, TREX::transaction::EnumeratedDomain< std::string >, TREX::transaction::EnumeratedDomain< TREX::utils::Symbol >, TREX::transaction::BooleanDomain, and TREX::europa::details::EuropaDomain.
Referenced by TREX::transaction::Goal::restrictTime(), and TREX::europa::details::europa_domain::visit().
virtual bool TREX::transaction::DomainBase::isEnumerated () const [pure virtual]
Check for enumerated domain.
This method check if the domain is based on an enumerated representation. In which case its representation is based on the list of all the possible values.
Return values:
true if the domain is enumeration based
false otherwise
See also:
bool isInterval() const
Implemented in TREX::transaction::BasicEnumerated, TREX::transaction::BasicInterval, and TREX::europa::details::EuropaDomain.
virtual bool TREX::transaction::DomainBase::isFull () const [pure virtual]
check for full domain
This method identifies if current domain is full. A full domain is adomain that includes al the possibles values for its type.
Return values:
true if current instance is full
false otherwise
Implemented in TREX::transaction::BooleanDomain, TREX::transaction::BasicInterval, TREX::transaction::BasicEnumerated, and TREX::europa::details::EuropaDomain.
Referenced by TREX::transaction::Goal::listAttributes().
virtual bool TREX::transaction::DomainBase::isInterval () const [pure virtual]
Check for interval domain.
This method is used to identify if this domain is an interval based domain. In which case it is represented by a lower and upper bound.
Return values:
true if the domain is interval based
false otherwise
See also:
bool isEnumerated() const
Implemented in TREX::transaction::BasicEnumerated, TREX::transaction::BasicInterval, and TREX::europa::details::EuropaDomain.
virtual bool TREX::transaction::DomainBase::isSingleton () const [pure virtual]
check for singleton value
This method identifies if current domain is a singleton. A singleton domain is defined by one and only one value.
Return values:
true if current instance is a singleton
false otherwise
Implemented in TREX::transaction::IntervalDomain< Ty, Comp >, TREX::transaction::IntervalDomain< long >, TREX::transaction::IntervalDomain< double >, TREX::transaction::BooleanDomain, TREX::transaction::BasicEnumerated, and TREX::europa::details::EuropaDomain.
Referenced by getSingleton(), getStringSingleton(), and TREX::europa::details::europa_domain::visit().
DomainBase& TREX::transaction::DomainBase::operator*= (DomainBase const & other) [inline]
Restrict domain possible values.
Parameters:
other Another domain
This method restrict the domain of current instance to the values that are shared by this domain and other.
Precondition:
this domain intersect other
Returns:
this domain after the operation
Exceptions:
EmptyDomain resulting domain is empty
See also:
bool intersect(DomainBase const &) const
Definition at line 280 of file DomainBase.hh.
References restrictWith().
virtual std::ostream& TREX::transaction::DomainBase::print_domain (std::ostream & out) const [protected, pure virtual]
Print domain.
Parameters:
out An output stream
Print a non full domain value to out
This method is called internally by the print_to method when the domain to print is not full. Indeed Abstract domain represents full domains as '*'
Returns:
The output stream after the operation
See also:
std::ostream &print_to(std::ostream &out) const
virtual DomainBase& TREX::transaction::DomainBase::restrictWith (DomainBase const & other) [pure virtual]
Restrict domain possible values.
Parameters:
other Another domain
This method restrict the domain of current instance to the values that are shared by this domain and other.
Precondition:
this domain intersect other
Returns:
this domain after the operation
Exceptions:
EmptyDomain resulting domain is empty
See also:
bool intersect(DomainBase const &) const
Implemented in TREX::transaction::IntervalDomain< Ty, Comp >, TREX::transaction::IntervalDomain< long >, TREX::transaction::IntervalDomain< double >, TREX::transaction::EnumeratedDomain< Ty, Comp >, TREX::transaction::EnumeratedDomain< std::string >, TREX::transaction::EnumeratedDomain< TREX::utils::Symbol >, TREX::transaction::BooleanDomain, and TREX::europa::details::EuropaDomain.
Referenced by operator*=().
virtual boost::any TREX::transaction::DomainBase::singleton () const [protected, pure virtual]
singleton value This method is called by getSingleton() to get the actual value of a singleton domain
Returns:
the value of the singleton
Note:
as this method is called by getSingleton we have the guarantee that it will be called only if the domain is a singleton
See also:
boost::any getSingleton() const
Referenced by getSingleton().
virtual std::string TREX::transaction::DomainBase::stringSingleton () const [protected, pure virtual]
singleton text representation This method is called by getStringSingleton() to get the actual value of a singleton domain as text
Returns:
the textual value of the singleton
Note:
as this method is called by getStringSingleton we have the guarantee that it will be called only if the domain is a singleton
See also:
std::string getStringSingleton() const
Referenced by getStringSingleton().
virtual std::ostream& TREX::transaction::DomainBase::toXml (std::ostream & out, size_t tabs = 0) const [pure virtual]
XML conversion.
Parameters:
out An output stream
tabs indentation level
This methods writes an XML representation of the domain into the output stream out. The tabs attribute indicates the indentation level expected for the tags.
Note:
To ensure compatibility this method should produce an xml output which is compatible with the XML parsing constructor of this domain.
Returns:
out after the operation
See also:
DomainBase(rapidxml::xml_node<> const &)
xml_factory
Implemented in TREX::transaction::BasicInterval, TREX::transaction::BasicEnumerated, TREX::transaction::BooleanDomain, and TREX::europa::details::EuropaDomain.
Referenced by TREX::europa::details::EuropaDomain::toXml().
The documentation for this class was generated from the following files:
trex/domain/DomainBase.hh
trex/domain/DomainBase.cc