trex: TREX::utils::PluginLoader Class Reference
TREX::utils::PluginLoader Class Reference
Basic utilities
plug-in management class
#include <trex/utils/PluginLoader.hh>
Public Member Functions
void load (Symbol const &name)
plug-in load method
bool unload (Symbol const &name)
plug-in unload method
Friends
class SingletonWrapper< PluginLoader >
Detailed Description
plug-in management class
This class implement a simple way to dynamically load TREX plug-ins.
A TREX plug-in is named lib<plugin>.<ext> with <plugin> is a plug-in symbolic identifier and <ext> is the platform specific extension for dynamic libraries. A TREX plug-in is also expected to provide the function:
 extern "C" void TREX::initPlugin()
as defined in the utils/base/Plugin.hh header and can ususally implements extensions of TREX such as new reactor or clock types
A plug-in can be located at any place wich is in the TREX search path as maintined by LogManager.
This class is a pure singleton using some kind of reference counting to ensure that a plug-in won't be unloaded before it is not used anymore. Indeed, to unload a plug-in one need to either :
destroy the LogPLayer singleton
or call unload for this plug-in as many times as he called load
Author:
Frederic Py fpy@m.nosp@m.bari.nosp@m..org
Definition at line 81 of file PluginLoader.hh.
Member Function Documentation
void PluginLoader::load (Symbol const & name)
plug-in load method
Parameters:
[in] name Name of the plug-in
This method attempts to load the plug-in name by searching for the file named lib<name>.<ext> in the search path provided by LogManager.
When this library is loaded it then attempts to call the initPlugin function of this plug-in
This operation is guaranteed to be called only if the plug-in name is not currently loaded
Exceptions:
PluginError Problem while trying to load the plug-in name
Exception Unable to locate the library for name
Postcondition:
The plug-in name is loaded
Definition at line 83 of file PluginLoader.cc.
References TREX::utils::internals::p_dlclose(), TREX::utils::internals::p_dlext(), TREX::utils::internals::p_dlopen(), TREX::utils::internals::p_dlsym(), and TREX::utils::BasicSymbol< CharT, Traits, Alloc >::str().
bool PluginLoader::unload (Symbol const & name)
plug-in unload method
Parameters:
[in] name Name of the plug-in
If this method is called as many time as load for name. It will then unload this plug-in
Exceptions:
PluginError unable to unload the plug-in name
Return values:
true The plug-in was unloaded
false the plug-in was not unloaded. It can be because either this plug-in was not loaded on the first place or is still in use
Definition at line 110 of file PluginLoader.cc.
References TREX::utils::internals::p_dlclose().
The documentation for this class was generated from the following files:
trex/utils/PluginLoader.hh
trex/utils/PluginLoader.cc