trex: TREX::transaction::graph Class Reference
TREX::transaction::graph Class Reference
Transactions graph.
#include <trex/transaction/reactor_graph.hh>
Classes
class reactor_iterator
reactors iterator
struct timeline_failure
Timeline relation creation failure.
class timelines_listener
struct traversal_category
Graph traversal category.
Public Types
typedef
details::reactor_set::difference_type difference_type
typedef boost::directed_tag directed_category
typedef details::relation_iter edge_iterator
typedef
boost::allow_parallel_edge_tag edge_parallel_category
typedef boost::edge_name_t edge_property_type
typedef details::reactor_id reactor_id
reactor ID type
typedef Relation relation_type
reactor relation type
typedef boost::reverse_graph
< graph, graph const & > reverse_graph
Reverse of a reactor graph.
typedef
details::reactor_set::size_type size_type
typedef boost::vertex_name_t vertex_property_type
typedef
TREX::utils::XmlFactory
< TeleoReactor,
boost::shared_ptr
< TeleoReactor >, graph * > xml_factory
Reactor factory.
Public Member Functions
reactor_id add_reactor (boost::property_tree::ptree::value_type &description)
Create new reactor for this graph.
size_t add_reactors (boost::property_tree::ptree &conf)
Create new reactors for this graph.
template<class Iter >
size_t add_reactors (Iter from, Iter to)
Create new reactors for this graph.
size_t cleanup ()
Kill all isolated reactors.
void clear ()
Clear the graph.
size_type count_reactors () const
Number of reactors.
size_type count_relations () const
bool empty () const
Check if empty.
reactor_iterator find_reactor (TREX::utils::Symbol const &name) const
find a reactor
TICK getCurrentTick () const
get current tick
TREX::utils::Symbol const & getName () const
Graph name.
graph (TREX::utils::Symbol const &name, boost::property_tree::ptree &conf, TICK init=0)
Constructor.
graph (TREX::utils::Symbol const &name, TICK init=0)
Constructor.
long index (reactor_id r) const
Reactor index.
bool is_isolated (reactor_id r) const
bool is_member (reactor_id r) const
Check if part of the graph.
reactor_id isolate (reactor_id r) const
Isolate a reactor.
bool kill_reactor (reactor_id r)
Kill a reactor.
graph const & me () const
graph & me ()
reactor_iterator reactor_begin () const
Beginning reactor iterator.
reactor_iterator reactor_end () const
End reactor iterator.
edge_iterator relation_begin () const
edge_iterator relation_end () const
virtual double tickDuration () const
get tick duration
virtual double tickToTime (TICK cur) const
convert a TICK into its real-time equivalent
virtual TICK timeToTick (time_t secs, suseconds_t usecs=0) const
convert real-time into a TICK
virtual ~graph ()
Destructor.
Static Public Member Functions
static reactor_id null_reactor ()
Protected Types
typedef
details::timeline_set::const_iterator timeline_iterator
Protected Member Functions
reactor_id add_reactor (reactor_id r)
virtual void external_check (reactor_id r, details::timeline const &tl)
Check for external timeline creation.
bool has_timeline (TREX::utils::Symbol const &tl) const
virtual void internal_check (reactor_id r, details::timeline const &tl)
Check for internal timeline creation.
TREX::utils::LogManager & manager () const
void set_name (TREX::utils::Symbol const &name)
TREX::utils::internals::LogEntry syslog (std::string const &context=std::string()) const
timeline_iterator timeline_begin () const
timeline_iterator timeline_end () const
void updateTick (TICK value)
Friends
class TeleoReactor
class timelines_listener
Related Functions
(Note that these are not member functions.)
std::pair< graph_traits
< TREX::transaction::graph >
::adjacency_iterator,
graph_traits
< TREX::transaction::graph >
::adjacency_iterator > adjacent_vertices (TREX::transaction::graph::reactor_id r, TREX::transaction::graph const &g)
Reactor adjacency vertices of a reactor.
TREX::transaction::details::graph_vertex_id_map get (vertex_index_t, TREX::transaction::graph const &g)
Get reactor ID map.
TREX::utils::Symbol const & get (TREX::transaction::details::graph_vertex_name_map const &m, TREX::transaction::graph::reactor_id r)
Get reactor name.
TREX::transaction::details::graph_vertex_name_map get (vertex_name_t, TREX::transaction::graph const &)
Get reactor name map.
TREX::utils::Symbol const & get (TREX::transaction::details::graph_edge_name_map const &m, TREX::transaction::graph::relation_type const &rel)
Get relation name.
TREX::transaction::details::graph_edge_name_map get (edge_name_t, TREX::transaction::graph const &)
Get relation name map.
TREX::transaction::graph::size_type num_vertices (TREX::transaction::graph const &g)
Number of reactors.
TREX::transaction::TeleoReactor::size_type out_degree (TREX::transaction::graph::reactor_id r, TREX::transaction::graph const &g)
Number of external relations for a reactor.
std::pair
< TREX::transaction::TeleoReactor::external_iterator,
TREX::transaction::TeleoReactor::external_iterator > out_edges (TREX::transaction::graph::reactor_id r, TREX::transaction::graph const &g)
Out edges of a reactor.
TREX::transaction::graph::reactor_id source (TREX::transaction::graph::relation_type const &rel, TREX::transaction::graph const &g)
source of a relation
TREX::transaction::graph::reactor_id target (TREX::transaction::graph::relation_type const &rel, TREX::transaction::graph const &g)
target of a relation
std::pair
< TREX::transaction::graph::reactor_iterator,
TREX::transaction::graph::reactor_iterator > vertices (TREX::transaction::graph const &g)
Graph reactors.
Detailed Description
Transactions graph.
This class provides and maintain the transactions between reactors and timelines it maintins the relations of the reactors based on the timelines they declare as external and allow to traverse reactors based on these dependencies.
It is heavily based on the boost graph library leveraging the ability to uses the diverse graph traversal algorithms using diverse alghorithms (depth first search, ...) that are provided by this framework
In the past reactors and their realtion were amintined directly byt the Agent class. The order in which these reactors were executed was determined at the beginnign by storing them in a list using an ad-hoc topological sort. This approach was simple end efficient but very limitating for future evolutions/tweaking fo the agent. By porting this to a graph we can now have more flexibility on the way the reactors can be schedulled. The first positive impact on TREX is to allow to add new reactors on the egent after its initialisation while maintaining the requirements of the synchronization phase. Other potential arguments are :
allow to apply heurisitics to the way this graph is traversed. which could allow the agent to identify cynamic choices in how to schedulle reactors based on their criticity at a given time
potetnially allow parallel synchronization of reactors that are not dependents. Provided of course thata such algorithm has been implemented under BGL.
take benefit of any new search algorithm that has been implemented under BGL. This library effort is to provide a generic framework for implementing graph traversal algorithms. Having it as a basis of TREX allow then to take advantage of advances made in the field. It also allow a TREX developper to test an algorithm inside BGL before transferring it completely inside TREX.
Author:
Frederic Py <fpy@mbari.org>
Definition at line 116 of file reactor_graph.hh.
Member Typedef Documentation
typedef details::reactor_id TREX::transaction::graph::reactor_id
reactor ID type
The type used to represent a reactor in the graph
Definition at line 122 of file reactor_graph.hh.
typedef Relation TREX::transaction::graph::relation_type
reactor relation type
The type used to represent the dependencies between reactors in the graph.
Definition at line 156 of file reactor_graph.hh.
typedef boost::reverse_graph<graph, graph const &> TREX::transaction::graph::reverse_graph
Reverse of a reactor graph.
This type is the one used in order to refer to this graph with reversed relations
Definition at line 170 of file reactor_graph.hh.
typedef TREX::utils::XmlFactory<TeleoReactor, boost::shared_ptr<TeleoReactor>, graph *> TREX::transaction::graph::xml_factory
Reactor factory.
A factory used ot produce new reactor in a graph using XML input.
Definition at line 163 of file reactor_graph.hh.
Constructor & Destructor Documentation
graph::graph (TREX::utils::Symbol const & name, TICK init = 0) [explicit]
Constructor.
Parameters:
[in] name A symbolic name
[in] init An initial tick value
Create a new graph named name with an initial tick init
Postcondition:
the graph is empty
Definition at line 64 of file reactor_graph.cc.
graph::graph (TREX::utils::Symbol const & name, boost::property_tree::ptree & conf, TICK init = 0)
Constructor.
Parameters:
[in] name A symbolic name
[in] conf A XML structure iterator
[in] init An initial tick value
Create a new graph named name with an initial tick init. It will also create all the reactors as defined in the XML iterator conf.
Exceptions:
ReactorException An error ocured while trying to create the reactors
See also:
add_reactors(ext_iterator)
Definition at line 68 of file reactor_graph.cc.
References add_reactors().
graph::~graph () [virtual]
Destructor.
Destroy the graph along with all the reactors attached to it.
See also:
clear()
Definition at line 74 of file reactor_graph.cc.
References clear().
Member Function Documentation
graph::reactor_id graph::add_reactor (boost::property_tree::ptree::value_type & description)
Create new reactor for this graph.
Parameters:
[in] definition A xml configuration tree node
Create the reactor defined by description and attch it to this graph
Definition at line 110 of file reactor_graph.cc.
References TREX::utils::list_set< IdTraits, Cmp >::insert().
Referenced by TREX::agent::Agent::Agent().
size_t TREX::transaction::graph::add_reactors (boost::property_tree::ptree & conf) [inline]
Create new reactors for this graph.
Parameters:
[in] conf A xml configuration tree
Create all the reactors defined in conf and attach them to this graph
Definition at line 381 of file reactor_graph.hh.
References add_reactors().
template<class Iter > size_t TREX::transaction::graph::add_reactors (Iter from, Iter to) [inline]
Create new reactors for this graph.
Template Parameters:
Iter An iterator type
Parameters:
[in] from Initial iterator
[in] to end iterator
Precondition:
The value_type of Iter is boost::property_tree::ptree::value_type
Add all the reactor that can be parsed from thre properties referred by [from, to) to this graph
Definition at line 40 of file reactor_graph.tcc.
References TREX::utils::list_set< IdTraits, Cmp >::insert().
Referenced by add_reactors(), and graph().
size_t graph::cleanup ()
Kill all isolated reactors.
Kill all the reactors which have been explicitedly isolated in this graph
Returns:
the numeof reactor that have been killed
See also:
isolate(reactor_id) const
kill_reactor(reactor_id)
Definition at line 171 of file reactor_graph.cc.
References TREX::utils::list_set< IdTraits, Cmp >::empty(), and kill_reactor().
Referenced by TREX::agent::Agent::initComplete().
void graph::clear ()
Clear the graph.
Disconnect all the reactors from this graph
Postcondition:
The graph is empty
Definition at line 92 of file reactor_graph.cc.
References TREX::utils::list_set< IdTraits, Cmp >::clear(), and TREX::utils::list_set< IdTraits, Cmp >::empty().
Referenced by TREX::agent::Agent::~Agent(), and ~graph().
size_type TREX::transaction::graph::count_reactors () const [inline]
Number of reactors.
Returns:
the number of reactors in this graph
Definition at line 526 of file reactor_graph.hh.
References TREX::utils::list_set< IdTraits, Cmp >::size().
Referenced by TREX::agent::Agent::missionCompleted(), and num_vertices().
bool TREX::transaction::graph::empty () const [inline]
Check if empty.
Checks if the graph is empty. Meanining that it has no reactor associated to it.
Return values:
true if the graph is empty
false otherwise
Definition at line 358 of file reactor_graph.hh.
References TREX::utils::list_set< IdTraits, Cmp >::empty().
Referenced by TREX::agent::Agent::doNext(), and TREX::agent::Agent::initComplete().
virtual void TREX::transaction::graph::external_check (reactor_id r, details::timeline const & tl) [inline, protected, virtual]
Check for external timeline creation.
Parameters:
[in] r A reactor
[in] tl A timeline
This method is used by the graph to check if the reactor r can declare the timeline tl as external.
It can be used by derived classes to add extra control on the creation of internal timelines. For example this is where the Agent could check if such external timeline creation won't generate a dependency cycle.
Exceptions:
timeline_failure indicates that tl cannot be declared as external by r
See also:
TeleoReactor::failed_external(Symbol const &, timeline_failure const &)
internal_check(reactor_id r, details::timeline const &)
Definition at line 664 of file reactor_graph.hh.
reactor_iterator TREX::transaction::graph::find_reactor (TREX::utils::Symbol const & name) const [inline]
find a reactor
Parameters:
[in] name A reactor symbolic name
Returns:
An iterator referring to the reactor with the name name or reactor_end() if no such reactor exists
Note:
As the graph does not allow to have multiple reactors with the same name the solution is always unique.
See also:
reactor_end() const
TeleoReactor::getName() const
Definition at line 576 of file reactor_graph.hh.
References TREX::utils::list_set< IdTraits, Cmp >::find().
TICK TREX::transaction::graph::getCurrentTick () const [inline]
get current tick
This method provides the current tick being executed in the graph.
Returns:
The tick value
Note:
This method is not usefull at the graph level and is more used by the Agent. It may be refactored in roder to keep the graph class as simple as possible.
Definition at line 464 of file reactor_graph.hh.
Referenced by TREX::agent::Agent::doNext(), TREX::transaction::TeleoReactor::getCurrentTick(), and TREX::agent::Agent::missionCompleted().
TREX::utils::Symbol const& TREX::transaction::graph::getName () const [inline]
Graph name.
Returns:
The name of the graph
Definition at line 306 of file reactor_graph.hh.
Referenced by TREX::transaction::TeleoReactor::getGraphName(), and TREX::agent::Agent::initComplete().
long graph::index (graph::reactor_id id) const
Reactor index.
Parameters:
[in] r A reactor
Returns:
An arbitrary index value for r or count_reactors() if this reactor doea not belong to this graph.
Note:
For reactor tat belong to the graph the returned value is between 0 and count_reactors()-1
Warning:
The index of a reactor can change whenver the graph is changed (by either adding new reactors or removing ones)
See also:
count_reactors() const
Definition at line 101 of file reactor_graph.cc.
References TREX::utils::list_set< IdTraits, Cmp >::begin(), and TREX::utils::list_set< IdTraits, Cmp >::end().
Referenced by TREX::transaction::details::graph_vertex_id_map::operator[]().
virtual void TREX::transaction::graph::internal_check (reactor_id r, details::timeline const & tl) [inline, protected, virtual]
Check for internal timeline creation.
Parameters:
[in] r A reactor
[in] tl A timeline
This method is used by the graph to check if the reactor r can declare the timeline tl as internal.
It can be used by derived classes to add extra control on the creation of internal timelines. For example this is where the Agent could check if such internal timeline creation won't generate a dependency cycle.
Exceptions:
timeline_failure indicates that tl cannot be declared as internal by r
See also:
TeleoReactor::failed_internal(Symbol const &, timeline_failure const &)
external_check(reactor_id r, details::timeline const &)
Definition at line 645 of file reactor_graph.hh.
bool graph::is_member (graph::reactor_id r) const
Check if part of the graph.
Parameters:
[in] r A reactor
Checks if r is currently part of this graph or not. A reactor is not part of the graph if it has been isolated or killed
Return values:
true if the reactor is still part of this graph false otherwise
See also:
kill_reactor(reactor_id)
isolate(reactor_id)
Definition at line 131 of file reactor_graph.cc.
References TREX::utils::list_set< IdTraits, Cmp >::begin(), and TREX::utils::list_set< IdTraits, Cmp >::end().
graph::reactor_id graph::isolate (graph::reactor_id r) const
Isolate a reactor.
Parameters:
[in] r A reactor
Disconnect the ractor r in this graph. Disconnecting a reactor correspond to disable all timeline declarations made by this reactor inside this graph.
Note:
After this operation the graph still belongs to the graph, it is just not connected to any other reactor anymore.
Return values:
@p r or null_reactor() if r did not belong to this graph
Postcondition:
if r did belong to this graph it is added to the set of reactor to be killed during the next cleanup operation
See also:
cleanup()
Definition at line 158 of file reactor_graph.cc.
References TREX::utils::list_set< IdTraits, Cmp >::find(), and TREX::utils::list_set< IdTraits, Cmp >::insert().
Referenced by TREX::agent::details::sync_scheduller::discover_vertex(), and TREX::agent::details::init_visitor::finish_vertex().
bool graph::kill_reactor (graph::reactor_id r)
Kill a reactor.
[in] r A reactor
Disconnect and remove r from this graph
Return values:
true the reactor was successfully removed
false r did not belong to this graph
Postcondition:
r does not belong to this graph
See also:
isolate()
Definition at line 139 of file reactor_graph.cc.
References TREX::utils::list_set< IdTraits, Cmp >::erase(), and TREX::utils::list_set< IdTraits, Cmp >::find().
Referenced by cleanup().
reactor_iterator TREX::transaction::graph::reactor_begin () const [inline]
Beginning reactor iterator.
Returns:
a reactor_iterator pointing to the beginning of the reactors set maintained by this graph
See also:
reactor_end() const
Definition at line 551 of file reactor_graph.hh.
References TREX::utils::list_set< IdTraits, Cmp >::begin().
Referenced by vertices().
reactor_iterator TREX::transaction::graph::reactor_end () const [inline]
End reactor iterator.
Returns:
a reactor_iterator pointing to the end of the reactors set maintained by this graph
See also:
reactor_begin() const
Definition at line 560 of file reactor_graph.hh.
References TREX::utils::list_set< IdTraits, Cmp >::end().
Referenced by vertices().
virtual double TREX::transaction::graph::tickDuration () const [inline, virtual]
get tick duration
This method provides the tick duration in real-time in order to allow to convert tick varelated values into a real-time value
Returns:
The tick duration
Note:
This method is not usefull at the graph level and is more used by the Agent. It may be refactored in roder to keep the graph class as simple as possible.
See also:
tickToTime(TICK) const
timeToTick(time_t, suseconds_t) const
Reimplemented in TREX::agent::Agent.
Definition at line 479 of file reactor_graph.hh.
Referenced by TREX::transaction::TeleoReactor::tickDuration(), and tickToTime().
virtual double TREX::transaction::graph::tickToTime (TICK cur) const [inline, virtual]
convert a TICK into its real-time equivalent
Parameters:
cur A TICK date
This method provides an utility to convert a TICK value into its real-time equivalent
Returns:
a float representing the date (usually in seconds) corresponding to the tTICK cur
Note:
This method is not usefull at the graph level and is more used by the Agent. It may be refactored in roder to keep the graph class as simple as possible.
See also:
tickDuration() const
timeToTick(time_t, suseconds_t) const
Reimplemented in TREX::agent::Agent.
Definition at line 518 of file reactor_graph.hh.
References tickDuration().
Referenced by TREX::transaction::TeleoReactor::tickToTime().
virtual TICK TREX::transaction::graph::timeToTick (time_t secs, suseconds_t usecs = 0) const [inline, virtual]
convert real-time into a TICK
Parameters:
secs Number of seconds
usecs Micro seconds
This method provides an utility to convert a real-time date into a TICK value
Returns:
the TICK equalent to the time sepresented by secs seconds and usecs microseconds
Note:
This method is not usefull at the graph level and is more used by the Agent. It may be refactored in roder to keep the graph class as simple as possible.
See also:
tickDuration() const
tickToTime(TICK) const
Reimplemented in TREX::agent::Agent.
Definition at line 499 of file reactor_graph.hh.
Referenced by TREX::transaction::TeleoReactor::timeToTick().
The documentation for this class was generated from the following files:
trex/transaction/reactor_graph.hh
trex/transaction/bits/bgl_support.hh
trex/transaction/bits/reactor_graph.tcc
trex/transaction/reactor_graph.cc