#!/bin/bash
# This file sets up the environment for TREX development

# Source Repository Setup
export AMES_ROOT=https://babelfish.arc.nasa.gov/svn/europa/PLASMA/
export AUV_ROOT=:pserver:moonjelly.shore.mbari.org:/home/cvs/auv-qnx
export CVS_RSH=ssh
export TREX_ROOT=`svn info | awk '/^Repository Root:/ { print $3"/TREX"}'`

# Path Settings
export TREX_HOME=`pwd`
export TREX_LOG_DIR=$TREX_HOME/log
export LD_LIBRARY_PATH=$TREX_HOME/lib:$LD_LIBRARY_PATH
export DYLD_LIBRARY_PATH=$LD_LIBRARY_PATH
export PATH=.:$TREX_HOME/offboard/scripts:$TREX_HOME/bin:$PATH

# where TREX looks for external dependencies and files
export TREX_PATH=$TREX_HOME/cfg:$TREX_HOME/plugin:$TREX_HOME/plugin/cfg

