trex: TREX::utils::ext_iterator Class Reference
TREX::utils::ext_iterator Class Reference
[Basic utilities]
XML nodes iterator through files.
#include <trex/utils/XmlUtils.hh>
Public Types
typedef rapidxml::xml_node * pointer
Pointer type to the referred object.
typedef rapidxml::xml_node & reference
Type of a reference to the referred object.
typedef rapidxml::xml_node value_type
Referred objects type.
Public Member Functions
ext_iterator (rapidxml::xml_node<> const &node, std::string const &conf)
Child and external config iterator.
ext_iterator (rapidxml::xml_node<> &node)
Simple child iterator.
ext_iterator (ext_iterator const &other)
Copy constructor.
ext_iterator ()
default constructor Creates an iterator pointing to nothing
bool external () const
Check for external node.
ext_iterator externalBegin (char *name=NULL) const
First external node.
ext_iterator find_tag (std::string const &name) const
Find element.
bool hasExternal () const
Check for external file.
ext_iterator & next (std::string const &name=std::string())
advance to next node
bool operator! () const
Check for validity.
reference operator* () const
access operator
ext_iterator & operator++ ()
advance to next node
pointer operator-> () const
access operator
bool valid () const
Check for validity.
~ext_iterator ()
Destructor.
Detailed Description
XML nodes iterator through files.
This class implements an iterator for the childs of a node that can optional load an extranl file provide by an attribute of this node to provide extra tags
This allow to easily provide configuration externalization in optional files.
Author:
Frederic Py <fpy@mbari.org>
Definition at line 131 of file XmlUtils.hh.
Constructor & Destructor Documentation
TREX::utils::ext_iterator::ext_iterator (ext_iterator const & other) [inline]
Copy constructor.
Parameters:
other Creates a copy of other
Definition at line 153 of file XmlUtils.hh.
TREX::utils::ext_iterator::ext_iterator (rapidxml::xml_node<> & node) [explicit]
Simple child iterator.
Parameters:
node An XML node
Creates an iterator for the child nodes of node
TREX::utils::ext_iterator::ext_iterator (rapidxml::xml_node<> const & node, std::string const & conf)
Child and external config iterator.
Parameters:
node An XML node
conf An optional attribute of node
Creates an iterator that allows to iterate on both the childs of node and on the content of the file referred by the attribute conf. If conf attribute does not exist the instance will only iterate through the childs. If conf exist it will also iterate thought the childs of the root node fo the referred file.
Precondition:
if conf attribute exist it must be an existing file
this file should be a valid and non empty XML file
Exceptions:
std::runtime_error Failed to open the file
rapidxml::parse_error Unable to parse the file
XmlError The file is empty
Exception file not found
Member Function Documentation
bool TREX::utils::ext_iterator::external () const [inline]
Check for external node.
This method helps user to identify whether the referred node is a direct child of the node used for initial construction or if it is coming from the file loaded with an optional tag
Return values:
true if the referred node is coming from the file loaded with external tag
false otherwise
Note:
As soon as this value becomes true all valid successor will be external too.
if hasExternal() is false then this method will never return true
See also:
bool hasExternal() const
Definition at line 223 of file XmlUtils.hh.
References valid().
ext_iterator ext_iterator::externalBegin (char * name = NULL) const
First external node.
Parameters:
name A tag name
This method creates a node pointing to the first node with tag name that is external
Returns:
the iterator pointing to firts external node or an invalid node if this iterator has no external node
Note:
if @ name is NULL or not given this method just look for the first external node
See also:
bool hasExternal() const
Definition at line 62 of file XmlUtils.cc.
ext_iterator ext_iterator::find_tag (std::string const & name) const
Find element.
Parameters:
name a tag name
This method locates the iterator pointing to element with the tag name. If current instance is match es the tag then it is returned imediately as oopp[opsed to the behavior of next
See also:
ext_iterator &next(char *name)
Definition at line 95 of file XmlUtils.cc.
References TREX::utils::is_tag(), and next().
Referenced by TREX::agent::Agent::sendRequests().
bool TREX::utils::ext_iterator::hasExternal () const [inline]
Check for external file.
This methods indicate whether an external file was loaded for this iterator or not
Return values:
true if an external file was loaded
false else
Definition at line 234 of file XmlUtils.hh.
ext_iterator & ext_iterator::next (std::string const & name = std::string())
advance to next node
Parameters:
name tag of the node
This method advance to the next node. If name is specified and not NULL, the search is restricted to the nodes with the tag name
Returns:
the instance after the operation
See also:
ext_iterator &operator++()
Definition at line 78 of file XmlUtils.cc.
Referenced by find_tag(), operator++(), and TREX::agent::Agent::sendRequests().
bool TREX::utils::ext_iterator::operator! () const [inline]
Check for validity.
Returns:
!valid()
See also:
bool valid() const
Definition at line 203 of file XmlUtils.hh.
References valid().
reference TREX::utils::ext_iterator::operator* () const [inline]
access operator
Give access to the referred node
Precondition:
current instance should be valid
Exceptions:
NullAccess this instance is not valid
See also:
bool valid() const
pointer operator->() const
Definition at line 274 of file XmlUtils.hh.
References operator->().
ext_iterator& TREX::utils::ext_iterator::operator++ () [inline]
advance to next node
This method advance to the next node.
Returns:
the instance after the operation
See also:
ext_iterator &next(char *name)
Definition at line 298 of file XmlUtils.hh.
References next().
ext_iterator::pointer ext_iterator::operator-> () const
access operator
Give access to the referred node attributes and methods
Precondition:
current instance should be valid
Exceptions:
NullAccess this instance is not valid
See also:
bool valid() const
reference operator *() const
Definition at line 72 of file XmlUtils.cc.
References valid().
Referenced by operator*().
bool TREX::utils::ext_iterator::valid () const [inline]
Check for validity.
Return values:
true if current instance refer to a node
false else
See also:
bool operator !() const
Definition at line 194 of file XmlUtils.hh.
Referenced by external(), operator!(), operator->(), and TREX::agent::Agent::sendRequests().
The documentation for this class was generated from the following files:
trex/utils/XmlUtils.hh
trex/utils/XmlUtils.cc