trex: TREX::utils::BasicSymbol< CharT, Traits, Alloc > Class Template Reference
TREX::utils::BasicSymbol< CharT, Traits, Alloc > Class Template Reference
Basic utilities
generic symbol class
#include <trex/utils/Symbol.hh>
Public Types
typedef std::basic_string
< CharT, Traits, Alloc > str_type
equivalent string type
Public Member Functions
BasicSymbol (str_type const &str=str_type())
Constructor.
BasicSymbol (CharT const *str, size_t len=str_type::npos)
Constructor.
BasicSymbol (BasicSymbol const &other)
Copy constructor.
bool empty () const
Check for emptyness.
size_t length () const
Symbol length.
bool operator!= (BasicSymbol const &other) const
Difference test.
bool operator< (BasicSymbol const &other) const
Less than test.
bool operator<= (BasicSymbol const &other) const
Less or equal to test.
BasicSymbol & operator= (BasicSymbol const &other)
Asignment operator.
bool operator== (BasicSymbol const &other) const
Equality test.
bool operator> (BasicSymbol const &other) const
Greater than test.
bool operator>= (BasicSymbol const &other) const
Greater or equal to test.
BasicSymbol & reset (CharT const *str=NULL, size_t len=str_type::npos)
Eeset value.
str_type const & str () const
String value.
~BasicSymbol ()
Destructor.
Friends
std::size_t hash_value (TREX::utils::Hashable const &x)
std::ostream & std::operator<< (std::ostream &out, TREX::utils::ostreamable const &x)
std::istream & std::operator>> (std::istream &in, istreamable &x)
Related Functions
(Note that these are not member functions.)
size_t hash_value (TREX::utils::Hashable const &x)
Hashing proxy for boost::hash.
Detailed Description
template<class CharT, class Traits = std::char_traits<CharT>, class Alloc = std::allocator<CharT>>
class TREX::utils::BasicSymbol< CharT, Traits, Alloc >
generic symbol class
Parameters:
CharT character type
Traits character manipulation traits for CharT
Alloc A memory allocator
This class offer a generic symbol class definition. A symbol is a a string access point ensuring that there's no more than one string value stored in memory. It relies on a unique reference memory managed by a reference counter to ensure both equality efficiency and better memory management.
Author:
Frederic Py fpy@m.nosp@m.bari.nosp@m..org
Definition at line 85 of file Symbol.hh.
Constructor & Destructor Documentation
template<class CharT, class Traits = std::char_traits<CharT>, class Alloc = std::allocator<CharT>> TREX::utils::BasicSymbol< CharT, Traits, Alloc >::BasicSymbol (str_type const & str = str_type()) [inline]
Constructor.
Parameters:
str a string
Create a new symbol with the same value as str
Definition at line 115 of file Symbol.hh.
template<class CharT, class Traits = std::char_traits<CharT>, class Alloc = std::allocator<CharT>> TREX::utils::BasicSymbol< CharT, Traits, Alloc >::BasicSymbol (CharT const * str, size_t len = str_type::npos) [inline]
Constructor.
Parameters:
str a string
len A length
Create a new symbol with the value of str up to its len character.
See also:
BasicSymbol &reset(CharT const *str, size_t len)
Definition at line 127 of file Symbol.hh.
template<class CharT, class Traits = std::char_traits<CharT>, class Alloc = std::allocator<CharT>> TREX::utils::BasicSymbol< CharT, Traits, Alloc >::BasicSymbol (BasicSymbol< CharT, Traits, Alloc > const & other) [inline]
Copy constructor.
Parameters:
other another instance
Create a new symbol with the same value as other
Definition at line 135 of file Symbol.hh.
Member Function Documentation
template<class CharT, class Traits = std::char_traits<CharT>, class Alloc = std::allocator<CharT>> bool TREX::utils::BasicSymbol< CharT, Traits, Alloc >::empty () const [inline]
Check for emptyness.
Return values:
true if length()==0
false otherwise
See also:
size_t length() const
Definition at line 176 of file Symbol.hh.
Referenced by TREX::transaction::Variable::isComplete(), TREX::utils::BasicSymbol< char >::length(), TREX::transaction::Predicate::Predicate(), TREX::transaction::Variable::restrict(), TREX::transaction::TeleoReactor::TeleoReactor(), and TREX::transaction::Variable::Variable().
template<class CharT, class Traits = std::char_traits<CharT>, class Alloc = std::allocator<CharT>> size_t TREX::utils::BasicSymbol< CharT, Traits, Alloc >::length () const [inline]
Symbol length.
Returns:
the length of the string representing this instance
Definition at line 183 of file Symbol.hh.
template<class CharT, class Traits = std::char_traits<CharT>, class Alloc = std::allocator<CharT>> bool TREX::utils::BasicSymbol< CharT, Traits, Alloc >::operator!= (BasicSymbol< CharT, Traits, Alloc > const & other) const [inline]
Difference test.
Parameters:
other Another instance
Test if current instance is different from other. This method relies on uniquer instance memory to ensure that this test is done in constant time independently of the string length
Return values:
true if current instance is not equal to other
false otherwise
See also:
bool operator==(BasicSymbol const &) const
Definition at line 216 of file Symbol.hh.
template<class CharT , class Traits , class Alloc > bool TREX::utils::BasicSymbol< CharT, Traits, Alloc >::operator< (BasicSymbol< CharT, Traits, Alloc > const & other) const
Less than test.
Parameters:
other instance
test if current instance is less than other. In the case these two are equals, the operation is accelerated by the unique instance memory
Return values:
true if current instance is before other
false otherwise
Definition at line 75 of file Symbol.hh.
Referenced by TREX::utils::BasicSymbol< char >::operator>=().
template<class CharT, class Traits = std::char_traits<CharT>, class Alloc = std::allocator<CharT>> bool TREX::utils::BasicSymbol< CharT, Traits, Alloc >::operator<= (BasicSymbol< CharT, Traits, Alloc > const & other) const [inline]
Less or equal to test.
Parameters:
other instance
test if current instance is less or equal other. In the case these two are equals, the operation is accelerated by the unique instance memory
Return values:
false if current instance is after other
true otherwise
Definition at line 256 of file Symbol.hh.
template<class CharT, class Traits = std::char_traits<CharT>, class Alloc = std::allocator<CharT>> BasicSymbol& TREX::utils::BasicSymbol< CharT, Traits, Alloc >::operator= (BasicSymbol< CharT, Traits, Alloc > const & other) [inline]
Asignment operator.
Parameters:
other another instance
Copy the value of other into current instance
Returns:
current instance after operation
Definition at line 149 of file Symbol.hh.
template<class CharT, class Traits = std::char_traits<CharT>, class Alloc = std::allocator<CharT>> bool TREX::utils::BasicSymbol< CharT, Traits, Alloc >::operator== (BasicSymbol< CharT, Traits, Alloc > const & other) const [inline]
Equality test.
Parameters:
other Another instance
Test if current instance is equal to other. This method relies on uniquer instance memory to ensure that this test is done in constant time independently of the string length
Return values:
true if current instance is equal to other
false otherwise
See also:
bool operator!=(BasicSymbol const &) const
Definition at line 200 of file Symbol.hh.
Referenced by TREX::utils::BasicSymbol< char >::operator!=().
template<class CharT, class Traits = std::char_traits<CharT>, class Alloc = std::allocator<CharT>> bool TREX::utils::BasicSymbol< CharT, Traits, Alloc >::operator> (BasicSymbol< CharT, Traits, Alloc > const & other) const [inline]
Greater than test.
Parameters:
other instance
test if current instance is greater than other. In the case these two are equals, the operation is accelerated by the unique instance memory
Return values:
true if current instance is after other
false otherwise
Definition at line 242 of file Symbol.hh.
Referenced by TREX::utils::BasicSymbol< char >::operator<=().
template<class CharT, class Traits = std::char_traits<CharT>, class Alloc = std::allocator<CharT>> bool TREX::utils::BasicSymbol< CharT, Traits, Alloc >::operator>= (BasicSymbol< CharT, Traits, Alloc > const & other) const [inline]
Greater or equal to test.
Parameters:
other instance
test if current instance is greater or equal other. In the case these two are equals, the operation is accelerated by the unique instance memory
Return values:
false if current instance is before other
true otherwise
Definition at line 270 of file Symbol.hh.
template<class CharT, class Traits = std::char_traits<CharT>, class Alloc = std::allocator<CharT>> BasicSymbol& TREX::utils::BasicSymbol< CharT, Traits, Alloc >::reset (CharT const * str = NULL, size_t len = str_type::npos) [inline]
Eeset value.
Parameters:
str a string
len A length
Change current instance value with the value of str up to its len character.
See also:
BasicSymbol(CharT const *str, size_t len)
Definition at line 164 of file Symbol.hh.
template<class CharT, class Traits = std::char_traits<CharT>, class Alloc = std::allocator<CharT>> str_type const& TREX::utils::BasicSymbol< CharT, Traits, Alloc >::str () const [inline]
String value.
Returns:
the equivalent string value to this instance
Definition at line 278 of file Symbol.hh.
Referenced by TREX::transaction::Predicate::getAttribute(), TREX::utils::PluginLoader::load(), main(), TREX::europa::EuropaReactor::notify(), TREX::transaction::Player::Player(), TREX::transaction::TeleoReactor::postObservation(), TREX::transaction::TeleoReactor::provide(), TREX::utils::BasicSymbol< char >::reset(), TREX::transaction::TeleoReactor::use(), and TREX::europa::details::europa_domain::visit().
The documentation for this class was generated from the following files:
trex/utils/Symbol.hh
trex/utils/bits/Symbol.tcc