trex: TREX::version Struct Reference
TREX::version Struct Reference
[Basic utilities]
Core libraies version information.
#include <trex/utils/TREXversion.hh>
Static Public Member Functions
static unsigned short major ()
Major version number.
static unsigned short minor ()
Minor version number.
static unsigned long number ()
version number
static unsigned short release ()
Patch version number.
static std::string str ()
Human readable version.
Detailed Description
Core libraies version information.
This simple class lows to access to information about the current TREX version of TREX core libararies
Author:
Frederic Py <fpy@mbari.org>
Definition at line 16 of file TREXversion.hh.
Member Function Documentation
unsigned short TREX::version::major () [static]
Major version number.
Returns:
the major version number
Definition at line 10 of file TREXversion.cc.
Referenced by number(), and str().
unsigned short TREX::version::minor () [static]
Minor version number.
Returns:
the minor version number
Definition at line 14 of file TREXversion.cc.
Referenced by number(), and str().
unsigned long TREX::version::number () [static]
version number
Indicates the version number of this library. This version number follows the same nomenclature as th boost versionning and is guaranteed to increase as we have new versions.
Returns:
100*(100*major()+minor())+release()
See also:
major()
minor()
release()
str()
Definition at line 22 of file TREXversion.cc.
References major(), minor(), and release().
unsigned short TREX::version::release () [static]
Patch version number.
Returns:
the patch version number
Definition at line 18 of file TREXversion.cc.
Referenced by number(), and str().
std::string TREX::version::str () [static]
Human readable version.
Indicates the version number as a human readable string the string is formatted the usual way : <major>.<minor>.<patch>
Returns:
The string value for this version
See also:
major()
minor()
release()
number()
Definition at line 29 of file TREXversion.cc.
References major(), minor(), and release().
Referenced by TREX::utils::LogManager::logPath().
The documentation for this struct was generated from the following files:
trex/utils/TREXversion.hh
trex/utils/TREXversion.cc