trex: TREX::transaction::TeleoReactor Class Reference
TREX::transaction::TeleoReactor Class Reference
[TREX transaction]
TeleoReactor abstract interface.
#include <trex/transaction/TeleoReactor.hh>
Classes
class Logger
Transaction logger.
Public Types
typedef details::external external_iterator
Iterator other external timelines.
typedef details::relation_iter internal_iterator
typedef graph::reactor_id ref_type
Reactor reference type.
typedef size_t size_type
size type
typedef xml_factory::argument_type xml_arg_type
XML construction info.
typedef graph::xml_factory xml_factory
XML based factory.
Public Member Functions
size_type count_externals () const
Number of External timelines.
size_type count_internal_relations () const
Count the number of internal relations.
size_type count_internals () const
Count the number of internal timelines.
bool doSynchronize ()
Synchronization callback.
external_iterator ext_begin ()
beginning of External timelines set
external_iterator ext_end ()
end of External timelines set
TREX::utils::Symbol const & getAgentName () const
get "agent" name
TICK getCurrentTick () const
Get current tick.
TICK getExecLatency () const
reactor execution latency
TICK getFinalTick () const
Get final tick.
graph const & getGraph () const
Get graph.
TREX::utils::Symbol const & getGraphName () const
Get graph name.
TICK getInitialTick () const
reactor initial tick
TICK getLatency () const
reactor latency
TICK getLookAhead () const
Get reactor look-ahead.
TREX::utils::Symbol const & getName () const
Reactor name.
bool initialize (TICK final)
Final initialization.
internal_iterator int_begin () const
First internal relation iterator.
internal_iterator int_end () const
Last internal relation iterator.
bool newTick ()
New tick notification callback.
virtual void notify (Observation const &obs)
void step ()
Deliberation step.
TeleoReactor (xml_arg_type &arg, bool loadTL=true, bool log_default=true)
XML based constructor.
double tickDuration () const
Tick duration.
double tickToTime (TICK cur) const
tick to unix time conversion
TICK timeToTick (time_t secs, suseconds_t usecs=0) const
unix time to tick conversion
double workRatio ()
reactor deliberation work load
virtual ~TeleoReactor ()
Destructor.
Protected Member Functions
virtual void cancelledPlanToken (goal_id const &t)
void cancelPlanToken (goal_id const &g)
bool completedGoal (goal_id g)
Goal completion.
virtual bool failed_external (TREX::utils::Symbol const &timeline, graph::timeline_failure const &err)
Request for external failed.
virtual bool failed_internal (TREX::utils::Symbol const &timeline, graph::timeline_failure const &err)
Request for internal failed.
external_iterator find_external (TREX::utils::Symbol const &name)
Find an external timeline.
virtual void handleInit ()
reactor initialiszation callback
virtual void handleRecall (goal_id const &g)
Goal recall callback.
virtual void handleRequest (goal_id const &g)
Goal reception callback.
virtual void handleTickStart ()
New tick callback.
virtual bool hasWork ()
Check if need to deliberate.
bool isExternal (TREX::utils::Symbol const &timeline) const
Check for exeternal timeline.
bool isInternal (TREX::utils::Symbol const &timeline) const
Check for internal timeline.
TREX::utils::LogManager & manager () const
LogManager acces point.
virtual void newPlanToken (goal_id const &t)
goal_id postGoal (Goal const &g)
Post a goal.
bool postGoal (goal_id const &g)
Post a goal.
void postObservation (Observation const &o)
Produce an observation.
goal_id postPlanToken (Goal const &g)
Post a planned token.
bool postPlanToken (goal_id const &g)
Post a planned token.
bool postRecall (goal_id const &g)
Recall a goal.
void provide (TREX::utils::Symbol const &timeline, bool controllable=true, bool publish=false)
Internal timeline declaration.
virtual void resume ()
Deliberation step callback.
virtual bool synchronize ()=0
Synchronization callback.
TREX::utils::internals::LogEntry syslog (std::string const &context=std::string())
new log entry
TeleoReactor (graph *owner, TREX::utils::Symbol const &name, TICK latency, TICK lookahead, bool log=false)
Constructor.
void use (TREX::utils::Symbol const &timeline, bool control=true, bool plan_listen=false)
External timeline declaration.
Friends
class details::external
class details::timeline
class graph
class ReactorException
class Relation
Detailed Description
TeleoReactor abstract interface.
This class provides the basic framework for a Teleo-Reactor as defined for the TREX architecture. A Teleo-reactor (or reactor) is the basic construct managed by a TREX agent.
It is the also the node of a transaction graph connected with other reactors through the timeline relations it have with them. These relations can be deduced from how a reactor declares the timelines it manipulate:
External timelines is a state variable provided by another reactor in the graph. The reactor can observe its evolution and -- even though it cannot directly control this timelien value -- it can potentially post goals on this timeline expressing desired future value(s).
Internal timelines is a state varaible managed by this reactor and made publicly available in the graph. It is the repsonsibility of this reactor to provide new Observation when the value of this timeline change. Similarly this reactor will receive goals posted by other reactors that declared this timline as External
A reactor provide also informations about its latency and look-ahead which indicates its planning horizon and the maximum time it is exx1pected to deliberate in order to produce a plan for the goals it received.
All these informations are used by the agent in order to schedule the communication between agents along with their deliberation.
Author:
Conor McGann & Frederic Py <fpy@mbari.org>
See also:
class graph
Definition at line 89 of file TeleoReactor.hh.
Member Typedef Documentation
typedef details::external TREX::transaction::TeleoReactor::external_iterator
Iterator other external timelines.
The type used to iterate other the external timlines of a reactor. This is mostly used by the boost graph library.
Definition at line 434 of file TeleoReactor.hh.
typedef graph::reactor_id TREX::transaction::TeleoReactor::ref_type
Reactor reference type.
The type used to refer to specific reactor
Definition at line 98 of file TeleoReactor.hh.
typedef size_t TREX::transaction::TeleoReactor::size_type
size type
The type used to return a size such the number of External timleines of a reactor
Definition at line 440 of file TeleoReactor.hh.
typedef xml_factory::argument_type TREX::transaction::TeleoReactor::xml_arg_type
XML construction info.
The argument passed by xml_factory while calling reactor classes constructor. This type is not a simple rapidxml::xml_node<> but also embeds a reference to the graph that the newly created instance will be attached to.
See also:
TREX::utils::XmlFactory
TREX::utils::XmlFactory::arg_traits;
TREX::transaction::graph
Definition at line 115 of file TeleoReactor.hh.
typedef graph::xml_factory TREX::transaction::TeleoReactor::xml_factory
XML based factory.
The type of the factory used to generate reactors from XML
Definition at line 103 of file TeleoReactor.hh.
Constructor & Destructor Documentation
TeleoReactor::TeleoReactor (TeleoReactor::xml_arg_type & arg, bool loadTL = true, bool log_default = true) [explicit]
XML based constructor.
Parameters:
[in] arg A structure embedding the xml structure and the graph that called this constructor
[in] loadTL A flag to allow/prohibit the parsing of Internal and External relations gfrom the xml structure
[in] log_default A flag to indicate what is the default logging behavior for this reactor
This constructor creates a new reactor by parsing the xml structure arg. Ig loadTL is true it will also extract Internal and External timelines definitions from this structure. log_default indicates what is the default logging behaivor of the reactor when the log attribute is not given in the XML structure.
A typical reactor definition is as follow
 < <RType> name="<name>" lookahead="<lookahead>" latency="<latency>"
           config="<config>" log="<logflag>" >
      <External name="<ename>" goals="<post goal flag>" />
      <Internal name="<iname>" />
 </ <RType> >
With :
<RType> being the type of the reactor as declared to the factory
<name> the name of the reactor
<lookahead> the reactor's look-ahead
<latency> the reactors's latency
<logflag> a flag use to indicate that observations and commands issued from this reactor should be logged or not (default is log_default)
<config> An optional extra file that extends the defintions of this tag
If loadTL is true then that class will also parse the External and Internal tags in order to declare internal and external timelines of this reactor.
Exceptions:
TREX::utils::XmlError An error occured while extracting reactors information from the XML structure
Definition at line 191 of file TeleoReactor.cc.
References TREX::utils::BasicSymbol< CharT, Traits, Alloc >::empty(), TREX::utils::LogManager::file_name(), getName(), TREX::utils::is_tag(), manager(), provide(), syslog(), and use().
TeleoReactor::TeleoReactor (graph * owner, TREX::utils::Symbol const & name, TICK latency, TICK lookahead, bool log = false) [protected]
Constructor.
Parameters:
[in] owner The graph that creates and will own this insatnce
[in] name Name of the reactor
[in] latency Deliberation latency for this reactor
[in] lookahead of his reactor
[in] log A log flag
Create a new reactoe named name with a latency of latency and a look-ahead of lookahead and associate it to the graph owner
Definition at line 234 of file TeleoReactor.cc.
References TREX::utils::LogManager::file_name(), getName(), manager(), and syslog().
Member Function Documentation
bool TREX::transaction::TeleoReactor::completedGoal (goal_id g) [protected]
Goal completion.
Parameters:
[in] g A goal
This method can be used from the reactor to inform the goal management system that the goal g on one of its external timeline has completed
Deprecated:
This method should become useless as the goal management system is much more able to identify that a goal did complete
size_type TREX::transaction::TeleoReactor::count_externals () const [inline]
Number of External timelines.
Returns:
the number of External timelines on this reactor
Definition at line 446 of file TeleoReactor.hh.
TeleoReactor::size_type TeleoReactor::count_internal_relations () const
Count the number of internal relations.
This method count the number of relations that this reactor have with other reactors issued from its internla timelines.
This number does not count the number of internal timelines but the sum of all the reactors that are connected to this reactor through its internal timelines
Definition at line 259 of file TeleoReactor.cc.
References TREX::utils::list_set< IdTraits, Cmp >::begin(), and TREX::utils::list_set< IdTraits, Cmp >::end().
size_type TREX::transaction::TeleoReactor::count_internals () const [inline]
Count the number of internal timelines.
This methods indicates the number of internal timelines this reactor currently owns
Returns:
the number of internla timleins of this reactor
See also:
count_internal_relations() const
Definition at line 475 of file TeleoReactor.hh.
References TREX::utils::list_set< IdTraits, Cmp >::size().
bool TeleoReactor::doSynchronize ()
Synchronization callback.
This method is called by the agent to make the reactor execute its synchronization. It will call synchronize callback and returns then status of the reactor according to the execution of this call.
Return values:
true synchronization successfull
false the call to synchronize returned false or thew an exception
Warning:
when this method returns false this reflect a critical reactor failure. Therefre the agent will kill this reactor and produce the observation Failed on each of its Internal timeline.
See also:
synchronize()
Definition at line 506 of file TeleoReactor.cc.
References TREX::utils::list_set< IdTraits, Cmp >::begin(), TREX::utils::list_set< IdTraits, Cmp >::clear(), TREX::utils::list_set< IdTraits, Cmp >::end(), synchronize(), and syslog().
details::external TeleoReactor::ext_begin ()
beginning of External timelines set
Returns:
An iterator pointing to the beginning of the External timelines set for this reactor
See also:
ext_end()
Definition at line 276 of file TeleoReactor.cc.
Referenced by newTick(), and workRatio().
details::external TeleoReactor::ext_end ()
end of External timelines set
Returns:
An iterator pointing to the end of the External timelines set for this reactor
See also:
ext_begin()
Definition at line 280 of file TeleoReactor.cc.
virtual bool TREX::transaction::TeleoReactor::failed_external (TREX::utils::Symbol const & timeline, graph::timeline_failure const & err) [inline, protected, virtual]
Request for external failed.
Parameters:
[in] timeline Symbolic name of the timeline
[in] err Descriptor of the error
This callback is executed when an attempt to use the External timeline timeline triggered an error. The reason of the failure is described by err. It can be derived in order to provide an alternate way to handle this failed request
See also:
failed_internal(TREX::utils::symbol const &, graph::timeline_failure const &)
Definition at line 834 of file TeleoReactor.hh.
virtual bool TREX::transaction::TeleoReactor::failed_internal (TREX::utils::Symbol const & timeline, graph::timeline_failure const & err) [inline, protected, virtual]
Request for internal failed.
Parameters:
[in] timeline Symbolic name of the timeline
[in] err Descriptor of the error
This callback is executed when an attempt to prtovide the Internal timeline timeline triggered an error. The reason of the failure is described by err. It can be derived in order to provide an alternate way to handle this failed request
See also:
failed_external(TREX::utils::symbol const &, graph::timeline_failure const &)
Definition at line 851 of file TeleoReactor.hh.
details::external TeleoReactor::find_external (TREX::utils::Symbol const & name) [protected]
Find an external timeline.
Parameters:
[in] name hte name of the timeline
Returns:
An iterator refering to the external timeline name or ext_end() if this reactor does not subscribe to name
Definition at line 284 of file TeleoReactor.cc.
Referenced by TREX::europa::EuropaReactor::hasWork().
TREX::utils::Symbol const& TREX::transaction::TeleoReactor::getAgentName () const [inline]
get "agent" name
Gets the name of the agent that controls this reactor.
Deprecated:
reactors are now manipulated by a graph. The agent uses this graph to trigger reactor's callbacks based on graph traversal algorithms. A graph is a more general concept thatn an agent (for example a graph could allow to have cyclic dependencies between reactors ...) to reflect this change this method has been replaced by getGraphName() and kept for backward compatibility.
Returns:
the name of the "agent"
See also:
getGraphName() const
Definition at line 187 of file TeleoReactor.hh.
References getGraphName().
TICK TREX::transaction::TeleoReactor::getCurrentTick () const [inline]
Get current tick.
Returns:
current tick date
See also:
getInitialTick() const
getFinalTick()
graph::getInitialTick() const
Definition at line 281 of file TeleoReactor.hh.
References TREX::transaction::graph::getCurrentTick().
Referenced by TREX::europa::EuropaReactor::hasWork(), initialize(), newTick(), postObservation(), postPlanToken(), and workRatio().
TICK TREX::transaction::TeleoReactor::getExecLatency () const [inline]
reactor execution latency
Indicates the reactor execution latency. This value correspond to the delay it take s for thsi reactor to start executing its plan. It is function of the execution latency of the reactors it depends on and is updated automatically by the reactors graph.
This value is used by TREX and represent this reactor's dispatch window lowe bound.
Returns:
the reactor's execution latency
See also:
getLatency() const
Definition at line 327 of file TeleoReactor.hh.
Referenced by initialize(), and TREX::transaction::details::timeline::latency().
TICK TREX::transaction::TeleoReactor::getFinalTick () const [inline]
Get final tick.
Identify the agent final tick. This value correspond to the maximum possible life-time of the agent.
@ pre the reactor is initialized
Returns:
mission final tick
See also:
initialize()
getInitialTick() const
getCurrentTick() const
Definition at line 297 of file TeleoReactor.hh.
graph const& TREX::transaction::TeleoReactor::getGraph () const [inline]
Get graph.
This methods gives a reference to the graph that manage this reactor
Returns:
the graph
See also:
getGraphName() const
Definition at line 206 of file TeleoReactor.hh.
TREX::utils::Symbol const& TREX::transaction::TeleoReactor::getGraphName () const [inline]
Get graph name.
Returns:
the name of the graph that maintins this reactor relations
See also:
class TREX::transaction::graph
Definition at line 196 of file TeleoReactor.hh.
References TREX::transaction::graph::getName().
Referenced by getAgentName().
TICK TREX::transaction::TeleoReactor::getInitialTick () const [inline]
reactor initial tick
This method indicates the tick during which the reactor has been initialized.
Precondition:
the reactor has bein initialized
Returns:
the tick during which the reactor got started
See also:
handleInit()
getCurrentTick() const
getFinalTick() const
Definition at line 223 of file TeleoReactor.hh.
Referenced by initialize().
TICK TREX::transaction::TeleoReactor::getLatency () const [inline]
reactor latency
Indicates the reactor deliberation latency. Thids vlaue reflects the exstimated maximum delay this reactor needs to produce a new plan and is usually provided by the user during agent definition
Returns:
the reactor's latency
See also:
getExecLatency() const
Definition at line 310 of file TeleoReactor.hh.
Referenced by workRatio().
TICK TREX::transaction::TeleoReactor::getLookAhead () const [inline]
Get reactor look-ahead.
Indicates how many ticks the reactors look ahead while planning. A value of 0 indicates that this reactor does not accept goal.
Returns:
the reactor look-ahead
Definition at line 337 of file TeleoReactor.hh.
Referenced by TREX::transaction::details::timeline::look_ahead().
TREX::utils::Symbol const& TREX::transaction::TeleoReactor::getName () const [inline]
Reactor name.
Returns:
the anme of the reactor
Definition at line 168 of file TeleoReactor.hh.
Referenced by TREX::transaction::Player::Player(), syslog(), and TeleoReactor().
virtual void TREX::transaction::TeleoReactor::handleInit () [inline, protected, virtual]
reactor initialiszation callback
This callback is called during initialize() is order to allow derived classes to complete their initialization before the reactor goat executed.
It is called once at the beginning of the reactor ewxecution.
Bug:
this function is blocking and while it is usuaally called before the clock of the agent got started if the reactor is created at the beginning of the mission. it won't be the case for a reactor created on the fly which may be problematic if the calls takes too long in comparison of the tick duration.
Reimplemented in TREX::europa::EuropaReactor.
Definition at line 705 of file TeleoReactor.hh.
Referenced by initialize().
virtual void TREX::transaction::TeleoReactor::handleRecall (goal_id const & g) [inline, protected, virtual]
Goal recall callback.
Parameters:
[in] g a goal
This method is called by the agent in roder to notify this reactor that the goal g is no logner desired.
Warning:
the duration of this call should be neglectable in comparison to the tick duration.
Reimplemented in TREX::europa::EuropaReactor.
Definition at line 769 of file TeleoReactor.hh.
Referenced by TREX::transaction::details::timeline::recall().
virtual void TREX::transaction::TeleoReactor::handleRequest (goal_id const & g) [inline, protected, virtual]
Goal reception callback.
Parameters:
[in] g a goal
This method is called by the agent in roder to notify this reactor that the goal g has been requested to him.
Warning:
the duration of this call should be neglectable in comparison to the tick duration.
Reimplemented in TREX::europa::EuropaReactor.
Definition at line 759 of file TeleoReactor.hh.
Referenced by TREX::transaction::details::timeline::request().
virtual void TREX::transaction::TeleoReactor::handleTickStart () [inline, protected, virtual]
New tick callback.
This call back is executed at the beginning of a new tick. and can be used for the reactor to prepare for synchronization. It is also often used by the reactor to post its new goals.
Note:
at this stage the reactor should have received all the new goals for this tick. but this is not guaranteed.
Warning:
the duration of this call should be neglectable in comparison to the tick duration.
Reimplemented in TREX::europa::EuropaReactor.
Definition at line 717 of file TeleoReactor.hh.
Referenced by newTick().
virtual bool TREX::transaction::TeleoReactor::hasWork () [inline, protected, virtual]
Check if need to deliberate.
This method is called during workRatio in order to idenitfy if the reactor needs to deliberate.
By default it always return 0 and need to be redefined by derived classes if they need to deliberate.
Return values:
true this instance needs to deliberate
false this instance does not require deliberation
If the methods returns true this will eventually result on the agent calling the step() method
See also:
workRatio()
step()
Reimplemented in TREX::europa::EuropaReactor.
Definition at line 546 of file TeleoReactor.hh.
Referenced by workRatio().
bool TeleoReactor::initialize (TICK final)
Final initialization.
Parameters:
[in] final The final tick date
Precondition:
getCurrentTick() < final
the reactor has not been inited yet
This method is called by the agent to allow the reactor to complete its initialization. At this stage the treactor knwos that it is part of the reactor graph and can complete its initialisation if needed. During this call, the callback handleInit will be executed allowing to execute reactors spacific initializations
Exceptions:
ReactorException Attempted to call this method twice
Postcondition:
The reactor is ready to be executed in the agent
See also:
handleInit()
getInitialTick() const
getCurrentTick() const
Definition at line 431 of file TeleoReactor.cc.
References getCurrentTick(), getExecLatency(), getInitialTick(), handleInit(), and syslog().
internal_iterator TREX::transaction::TeleoReactor::int_begin () const [inline]
First internal relation iterator.
See also:
count_internal_relations() const
int_end() const
Definition at line 494 of file TeleoReactor.hh.
References TREX::utils::list_set< IdTraits, Cmp >::begin(), and TREX::utils::list_set< IdTraits, Cmp >::end().
internal_iterator TREX::transaction::TeleoReactor::int_end () const [inline]
Last internal relation iterator.
See also:
count_internal_relations() const
int_begin() const
Definition at line 502 of file TeleoReactor.hh.
References TREX::utils::list_set< IdTraits, Cmp >::end().
bool TeleoReactor::isExternal (TREX::utils::Symbol const & timeline) const [protected]
Check for exeternal timeline.
Parameters:
[in] timeline A name
Return values:
true if timeline is External to this reactor
false otherwise
See also:
isInternal(TREX::utils::Symbol const &) const
use(TREX::utils::Symbol const &, bool)
Definition at line 272 of file TeleoReactor.cc.
bool TeleoReactor::isInternal (TREX::utils::Symbol const & timeline) const [protected]
Check for internal timeline.
Parameters:
[in] timeline A name
Return values:
true if timeline is Internal to this reactor
false otherwise
See also:
isExternal(TREX::utils::Symbol const &) const
provide(TREX::utils::Symbol const &)
Definition at line 268 of file TeleoReactor.cc.
References TREX::utils::list_set< IdTraits, Cmp >::end(), and TREX::utils::list_set< IdTraits, Cmp >::find().
Referenced by provide(), and use().
TREX::utils::LogManager& TREX::transaction::TeleoReactor::manager () const [inline, protected]
LogManager acces point.
Returns:
the LogManager instance for this run
Definition at line 525 of file TeleoReactor.hh.
Referenced by TREX::transaction::Player::Player(), and TeleoReactor().
bool TeleoReactor::newTick ()
New tick notification callback.
This method is called by the agent to notify the reactor that a new tick has started. It will call the handleTickStart() method
See also:
handleTickStart()
Definition at line 456 of file TeleoReactor.cc.
References TREX::transaction::details::external::dispatch(), ext_begin(), getCurrentTick(), handleTickStart(), syslog(), and TREX::transaction::details::external::valid().
virtual void TREX::transaction::TeleoReactor::notify (Observation const & obs) [inline, virtual]
New observation callback
Parameters:
[in] obs An observation
This method is called by the agent when one of the External timelines of this reactor changed state. The state is described by obs and satrts from the current tick.
It is guartanteed that all the notification of the current tick will be notified before the reactor synchronization
Warning:
the duration of this call should be neglectable in comparison to the tick duration.
See also:
synchronize()
Reimplemented in TREX::europa::EuropaReactor.
Definition at line 354 of file TeleoReactor.hh.
goal_id TeleoReactor::postGoal (Goal const & g) [protected]
Post a goal.
Parameters:
[in] g A goal
This method is just an overload of postGoal(goal_d const &) for user facility
Precondition:
g.object() is an External timeline
Exceptions:
DispatchError the goal wasn't on an External timeline
Returns:
the goal_id for this goal
See also:
postGoal(goal_id const &)
isExternal(TREX::utils::Symbol const &) const
Definition at line 368 of file TeleoReactor.cc.
References postGoal().
bool TeleoReactor::postGoal (goal_id const & g) [protected]
Post a goal.
Parameters:
[in] g A goal id
Post the goal g to an external timeline
Precondition:
g is a valid goal_id (i.e. not NULL)
g->object() is an External timeline of this reactor
Exceptions:
DispatchError The goal was not valid or was not on an external timeline of this reactor
Returns:
true the goal has been succesfully posted and is queued for dispatching
false this goal id is already in the dispatching queue
Note:
sucessfully posting a goal do not gauarantee that this goal will be duispatched and even less executed. It can be already too late to dispatch such a goal or the goal is simply impossible to be executed in current situation. As of today, the only way to check a goal has been executed is to wait for the corresponding observation unitl the maximum start time has been passed.
See also:
isExternal(TREX::utils::Symbol const &) const
postRecall(goal_id const &)
Definition at line 353 of file TeleoReactor.cc.
Referenced by postGoal().
void TeleoReactor::postObservation (Observation const & o) [protected]
Produce an observation.
Parameters:
[in] o An observation
This method is a falcility to produce internally an observation o on one of the reactors Internal timeline.
It can be called internally to the reactor when a new state has been identified for this timeline.
Precondition:
o.object() is internal to this reactor
Postcondition:
Unless postObservation is called in between with an observation on the same object, the observation o will be dispatched to all the clients of o.object() during the next doNotify()
Exceptions:
SynchronizationError attempt to post an observation in a timeline which is not Internal to this reactor.
See also:
class Observation
isInternal(TREX::utils::Symbol const &) const
doNotify()
Definition at line 342 of file TeleoReactor.cc.
References TREX::utils::list_set< IdTraits, Cmp >::end(), TREX::utils::list_set< IdTraits, Cmp >::find(), getCurrentTick(), TREX::utils::list_set< IdTraits, Cmp >::insert(), TREX::transaction::Predicate::object(), and TREX::utils::BasicSymbol< CharT, Traits, Alloc >::str().
goal_id TeleoReactor::postPlanToken (Goal const & g) [protected]
Post a planned token.
Parameters:
[in] g A goal
This method is just an overload of postPlanToken(goal_d const &) for user facility
Precondition:
g.object() is an Internal timeline of this reactor
Exceptions:
DispatchError The token was not on an internal timeline of this reactor
goal_id for the token posted. This id is invalid if the token was not posted
See also:
isInternal(TREX::utils::Symbol const &) const
postPlanToken(goal_id const &)
Definition at line 410 of file TeleoReactor.cc.
References postPlanToken().
bool TeleoReactor::postPlanToken (goal_id const & g) [protected]
Post a planned token.
Parameters:
[in] g A goal id
Inform that the token g is now part of the plan of the reactor
Precondition:
g is a valid goal_id (i.e. not NULL)
g->object() is an Internal timeline of this reactor
Exceptions:
DispatchError The token was not valid or was not on an internal timeline of this reactor
Returns:
true the token has been correctly integrated.
false this token id is already broadcasted or its end time is in the past
See also:
isInternal(TREX::utils::Symbol const &) const
cancelPlanToken(goal_id const &)
Definition at line 393 of file TeleoReactor.cc.
References TREX::utils::list_set< IdTraits, Cmp >::end(), TREX::utils::list_set< IdTraits, Cmp >::find(), and getCurrentTick().
Referenced by postPlanToken().
bool TeleoReactor::postRecall (goal_id const & g) [protected]
Recall a goal.
Parameters:
[in] g A goal
This method recall the goal with the goal_id of g
Return values:
true the goal was sucessfully recalled
false the goal was not valid or is not on an External timeline
Note:
The goal_id g should be execatly the one passed to postGoal (or returned by it).
As for postGoal sucessfully recalling a goal does not mean that it will be removed from the plan of the owner of this timeline. It is more a way to indicate that this goal is not required anymore.
See also:
postGoal(goal_id const &)
postGoal(Goal const &)
isExternal(TREX::utils::Symbol const &) const
Definition at line 379 of file TeleoReactor.cc.
void TeleoReactor::provide (TREX::utils::Symbol const & timeline, bool controllable = true, bool publish = false) [protected]
Internal timeline declaration.
Parameters:
[in] timeline a name
[in] controlable does this timeline accept goals
[in] publish does this timeline will publish its plan
This method is used to declare timeline as an Internal timeline.
Warning:
The type of a timeline can change during reactor execution and this is the reason why this methods give no feedback. It is always recommend to check the success/failure of this operation using isInternal
Note:
If the timlien was External and is not woned yet by any reactor, this call will promote it as Internal
See also:
isExternal(TREX::utils::Symbol const &) const
isInternal(TREX::utils::Symbol const &) const
graph::assign(graph::reactor_id, TREX::utils::Symbol const &)
use(TREX::utils::Symbol const &, bool)
Definition at line 559 of file TeleoReactor.cc.
References isInternal(), TREX::utils::BasicSymbol< CharT, Traits, Alloc >::str(), and syslog().
Referenced by TeleoReactor().
virtual void TREX::transaction::TeleoReactor::resume () [inline, protected, virtual]
Deliberation step callback.
This callback will be executed in response of hasWork returning true. It allows the reactor to execute an atomic deliberation step.
Warning:
the duration of this call should be neglectable in comparison to the tick duration.
Reimplemented in TREX::europa::EuropaReactor.
Definition at line 748 of file TeleoReactor.hh.
Referenced by step().
void TeleoReactor::step ()
Deliberation step.
This method is aclled by the agent when it allows the reactor to do one deliberation step. It calls resume() and update informations in order to compute the reactors next work ratio
See also:
workRatio()
resume()
Definition at line 538 of file TeleoReactor.cc.
References resume().
virtual bool TREX::transaction::TeleoReactor::synchronize () [protected, pure virtual]
Synchronization callback.
This method is called in order to ask for the reactor to
resolve its current state
produce new observation on its exeternal timelines if their state have changed The agent ensures that all new observation on this reactor timelines have been produced -- and received through notify -- to this reactor.
This is one of the more critical callback of the reactor and when it fails is considereed as a critical error resulting on the resactor being killed by the agent
Return values:
true synchronization succeeded
false synchronization failure. Will result on the reactor being killed soon after
Warning:
the duration of this call should be neglectable in comparison to the tick duration.
Implemented in TREX::europa::EuropaReactor.
Referenced by doSynchronize().
TREX::utils::internals::LogEntry TREX::transaction::TeleoReactor::syslog (std::string const & context = std::string()) [inline, protected]
new log entry
Parameters:
[in] context log entry prefix
create a new entry in TREX.log
Returns:
a stream that can be used to qwrite in the entry
See also:
TREX::utils::LogManager
TREX::utils::TextLog
Definition at line 890 of file TeleoReactor.hh.
References getName().
Referenced by doSynchronize(), TREX::europa::EuropaReactor::handleRequest(), TREX::europa::EuropaReactor::hasWork(), initialize(), newTick(), TREX::europa::EuropaReactor::notify(), TREX::transaction::Player::Player(), provide(), TREX::transaction::details::timeline::request(), TREX::europa::EuropaReactor::resume(), TREX::europa::EuropaReactor::synchronize(), TeleoReactor(), use(), and workRatio().
double TREX::transaction::TeleoReactor::tickDuration () const [inline]
Tick duration.
Indicates the duration of the tick. This duration is expected to be expressed in seconds even though nothing in the architecture constraint such aspect.
Returns:
the duration of a single tick
Definition at line 234 of file TeleoReactor.hh.
References TREX::transaction::graph::tickDuration().
double TREX::transaction::TeleoReactor::tickToTime (TICK cur) const [inline]
tick to unix time conversion
Parameters:
[in] cur A tick value
Returns:
equivalent unix time to cur as a float
This method is an utility to ease the conversion form a tick to unix time it calls the agent clock corresponding method to convert the specified tick value into unix time
Note:
the result of the method depends on the clock implementation. For example the RealTimeClock fully support it while the StepClock will simply assume that unixtime and tick are perfeclty aligned (as if the mission started on January 1st 1970)
Definition at line 270 of file TeleoReactor.hh.
References TREX::transaction::graph::tickToTime().
TICK TREX::transaction::TeleoReactor::timeToTick (time_t secs, suseconds_t usecs = 0) const [inline]
unix time to tick conversion
Parameters:
[in] secs Number of seconds
[in] usecs Number of microseconds
Returns:
equivalent tick to the time secs.usecs
This method is an utility to ease the conversion form unix time to tick it calls the agent clock corresponding method to convert the specified unix time into a tick value
Note:
the result of the method depends on the clock implementation. For example the RealTimeClock fully support it while the StepClock will simply assume that unixtime and tick are perfeclty aligned (as if the mission started on January 1st 1970)
Definition at line 253 of file TeleoReactor.hh.
References TREX::transaction::graph::timeToTick().
void TeleoReactor::use (TREX::utils::Symbol const & timeline, bool control = true, bool plan_listen = false) [protected]
External timeline declaration.
Parameters:
[in] timeline a name
[in] control goal dispatching flag
[in] plan_listen plan listening flag
This method is used to declare timeline as an External timeline. The optional control flag prohibits goal dispatching to this timeline when false. The plan_listen flag aloow the reactor to be notified whenever the owner of this timeline does give the current tokens it has in his future plan
Precondition:
The timleine is not already Internal
Warning:
The type of a timeline can change during reactor execution and this is the reason why this methods give no feedback. It is always recommend to check the success/failure of this operation using isExternal
See also:
isExternal(TREX::utils::Symbol const &) const
isInternal(TREX::utils::Symbol const &) const
graph::subscribe(graph::reactor_id, TREX::utils::Symbol const &, details::transaction_flag const &)
provide(TREX::utils::Symbol const &)
Definition at line 545 of file TeleoReactor.cc.
References isInternal(), TREX::utils::BasicSymbol< CharT, Traits, Alloc >::str(), and syslog().
Referenced by TeleoReactor().
double TeleoReactor::workRatio ()
reactor deliberation work load
This method calls hasWork method and, depending on the returned value and how close the reactor is to reach is latency, will give a value indicating heurisitically how urgent it is for him to delinerate.
Returns:
a value that becomes larger as the reactor is approaching its latency deadline or NAN if hasWork() returned false
See also:
hasWork()
step()
Definition at line 299 of file TeleoReactor.cc.
References TREX::transaction::details::external::dispatch(), ext_begin(), getCurrentTick(), getLatency(), hasWork(), syslog(), and TREX::transaction::details::external::valid().
The documentation for this class was generated from the following files:
trex/transaction/TeleoReactor.hh
trex/transaction/TeleoReactor.cc