trex: TREX::utils::LogManager Class Reference
TREX::utils::LogManager Class Reference
Basic utilities
Centralized logging and files management.
#include <trex/utils/LogManager.hh>
Public Types
enum LogLevel { LogMin = 0, LogNormal, LogExtensive }
Log verbosity level.
typedef std::list< path_type >
::const_iterator path_iterator
TREX_PATH iterator.
typedef boost::filesystem::path path_type
Public Member Functions
bool addSearchPath (std::string const &path)
add a directory to the search path
path_iterator begin () const
First path.
path_iterator end () const
End of searh path.
path_type file_name (std::string const &short_name)
log file complete name
path_type getCfgPath ()
Get directory where cfg files should be stored.
LogLevel getLogLevel () const
Current verbosity level.
path_type locate (std::string const &file, bool &found) const
Locate a file.
path_type const & logPath ()
Logging path This method indicates in which directory log files should be placed. It also manage the creation of this directory and other files to simplify its organization/access.
bool setLogLevel (LogLevel lvl)
Set verbosity level.
bool setLogPath (std::string const &path)
Set log path.
std::string use (std::string const &file_name, bool &found)
Configuration files management.
internals::LogEntry syslog (std::string const &who)
Named text entry.
TextLog & syslog ()
Named text entry.
Friends
class SingletonWrapper< LogManager >
Related Functions
(Note that these are not member functions.)
#define LATEST_DIR "latest"
Name of the symbolic link to "latest" logs.
#define LOG_DIR_ENV "TREX_LOG_DIR"
log directory environment variable
#define MAX_LOG_ATTEMPT 1024
Maximum log directory creation attempts.
#define SEARCH_ENV "TREX_PATH"
Search path environment variable.
#define TREX_ENV "TREX_HOME"
Home environment variable.
#define TREX_LOG_FILE "TREX.log"
TREX default log file name.
#define TREX_LOG_LEVEL LogNormal
Default verbosity level.
Detailed Description
Centralized logging and files management.
This class is a core component on TREX logging and file management. It provides a transparent one-stop shopping to :
Locate and load files
produce text log messages toward a singfle log directory This class manages in a cntral way all this while ensuring that files that are used by an agent are easily accessed and stored in a single log directory giving the ability to knbow exactly what files were used on a specific run.
It provides utilities that will create a log directory and the default TextLog file so other components can produce messages seamlessly.
It gives information of the user selected verbosity level which can then be used by other components to identify whether they should log this message or not.
It also provide a way to put all the configurations files used by the program in a specific directory.
This class is a pure singleton and consequently its access should be done using SingletonUse :
 #include "LogManager.hh"
 TREX::utils::SingletonUse<TREX::utils::LogManager> log;
 log->syslog("me")<<"A message to the log"<<std::endl;
Author:
Frederic Py fpy@m.nosp@m.bari.nosp@m..org
Definition at line 172 of file LogManager.hh.
Member Typedef Documentation
typedef std::list<path_type>::const_iterator TREX::utils::LogManager::path_iterator
TREX_PATH iterator.
An iterator used to go through all the path used by LogManager to locate a file
See also:
locate(std::string const &,bool &) const
Definition at line 313 of file LogManager.hh.
Member Enumeration Documentation
enum TREX::utils::LogManager::LogLevel
Log verbosity level.
Enumerator:
LogMin
Minimum verbosity.
LogNormal
Normal level.
LogExtensive
High verbosity (usually for debugging)
Definition at line 176 of file LogManager.hh.
Member Function Documentation
bool LogManager::addSearchPath (std::string const & path)
add a directory to the search path
Parameters:
path A directory
This method adds path to the end of the search path. It will do so only if path is a valid directory or is starting with '.'
Return values:
true if path was successfully added
false otherwise
Postcondition:
if the returned value is true path is now part of the serch path
See also:
std::string locate(std::string const &file, bool &found) const
Definition at line 98 of file LogManager.cc.
path_iterator TREX::utils::LogManager::begin () const [inline]
First path.
Returns:
An iterator refering to the first element of TREX_PATH
See also:
setLogPath(std::string const &)
end() const
Definition at line 320 of file LogManager.hh.
path_iterator TREX::utils::LogManager::end () const [inline]
End of searh path.
Returns:
An iterator refering to the ebnd of TREX_PATH
See also:
setLogPath(std::string const &)
begin() const
Definition at line 329 of file LogManager.hh.
LogManager::path_type LogManager::file_name (std::string const & short_name)
log file complete name
Parameters:
[in] short_name A short file name
This method indicates the full name of a file that has to be stored in the log directory
Exceptions:
ErrnoExcept A problem occured while trying to create log directory
Returns:
The complete file name for the file short_name into the log directory
See also:
logPath()
Definition at line 202 of file LogManager.cc.
References logPath().
Referenced by getCfgPath(), TREX::agent::Agent::initComplete(), and TREX::transaction::TeleoReactor::TeleoReactor().
LogManager::path_type LogManager::getCfgPath ()
Get directory where cfg files should be stored.
See also:
use(std::string const &)
Definition at line 209 of file LogManager.cc.
References file_name().
Referenced by use().
LogLevel TREX::utils::LogManager::getLogLevel () const [inline]
Current verbosity level.
Returns:
the current verbosity level
See also:
setLogLevel(LogLevel)
Definition at line 254 of file LogManager.hh.
LogManager::path_type LogManager::locate (std::string const & file, bool & found) const
Locate a file.
Parameters:
[in] file A file name
[out] found Indicator of success/failure
This methods tries to locate file in the search path. it first attempt to see if file exists by its own. If it is not the case and file do not starts with a '/', it iterates through the search path and tries to locate the file.
Return values:
@p file if found is false which indicates that it was unable to locate this file
A valid symbolic name for file if found is true
See also:
bool addSearchPath(std::string const &path)
std::string use(std::string const &, bool &)
Definition at line 70 of file LogManager.cc.
Referenced by use().
LogManager::path_type const & LogManager::logPath ()
Logging path This method indicates in which directory log files should be placed. It also manage the creation of this directory and other files to simplify its organization/access.
Exceptions:
ErrnoExcept a problem occured while trying to create log directories.
Returns:
a string with the full name of the log directory
Definition at line 133 of file LogManager.cc.
References TREX::utils::TextLog::open(), TREX::version::str(), and TREX_LOG_FILE.
Referenced by file_name().
bool LogManager::setLogLevel (LogLevel lvl)
Set verbosity level.
Parameters:
[in] lvl current verbosity level
Sets the verbosity level to lvl
Precondition:
The verbosity level cannot be changed after the LogManager has been fully initialized
Return values:
true level sucessfully set to lvl
false the verbosity level cannot be changed for this session
See also:
getLogLevel() const
setLogPath(std::string const &)
Definition at line 243 of file LogManager.cc.
References syslog().
bool LogManager::setLogPath (std::string const & path)
Set log path.
Parameters:
[in] path A path
Sets the log directory to path
Precondition:
The verbosity level cannot be changed after the LogManager has been fully initialized
Return values:
true log directory set to path
false the log directory has already been created and cannot be changed anymore
See also:
setLogLevel(LogLevel)
Definition at line 253 of file LogManager.cc.
References syslog().
internals::LogEntry LogManager::syslog (std::string const & who)
Named text entry.
Parameters:
[in] who The name of the source
This method create a new text entry on the TREX log. If who is provided the entry will start with the text [who].
Returns:
The text entry to be used with classical << output stream operator.
Definition at line 239 of file LogManager.cc.
Referenced by TREX::agent::RealTimeClock::getNextTick().
TextLog & LogManager::syslog ()
Named text entry.
Parameters:
[in] who The name of the source
This method create a new text entry on the TREX log. If who is provided the entry will start with the text [who].
Returns:
The text entry to be used with classical << output stream operator.
Definition at line 235 of file LogManager.cc.
Referenced by setLogLevel(), setLogPath(), and use().
std::string LogManager::use (std::string const & file_name, bool & found)
Configuration files management.
Parameters:
[in] file_name A configuration file name
[out] found Indicate if the file was found
This method is used to indicate that file_name has been used. It copies this file into the cfg subdirectory of the log directory.
If the file file_name cannot be found it also display a message in the log file.
Note:
This function uses locate method to look for the file in the current directory and the search path
Exceptions:
ErrnoExcept A problem occured while trying to copy file
ErrnoExcept A problem occured while trying to create log directory
Returns:
A complete name of file_name along with the path where it was located
See also:
logPath()
file_name(std::string const &)
std::string locate(std::string const &, bool &) const
Definition at line 213 of file LogManager.cc.
References getCfgPath(), locate(), and syslog().
Referenced by TREX::transaction::Player::Player().
Friends And Related Function Documentation
#define LATEST_DIR "latest" [related]
Name of the symbolic link to "latest" logs.
This macro gives the name to give to the symbolic link that will be created in the log directory to point to the logs of the latest/current session
Author:
Frederic Py fpy@m.nosp@m.bari.nosp@m..org
Definition at line 107 of file LogManager.hh.
#define LOG_DIR_ENV "TREX_LOG_DIR" [related]
log directory environment variable
This macro gives the name of the environment variable to read for knowing in what path the log files should be placed.
Author:
Frederic Py fpy@m.nosp@m.bari.nosp@m..org
Definition at line 97 of file LogManager.hh.
#define MAX_LOG_ATTEMPT 1024 [related]
Maximum log directory creation attempts.
This macro indicates how much attempt to create a new log directory should be done before giving up and generating an error.
Note:
This value do not mean that TREX can only execute up to MAX_LOG_ATTEMPT missions in a single day. Ifndeed if one look at the code of LogManager::createLatest he will see that it makes this number of attempt stariung from the directory referred by LATEST_DIR link. Such behavior should really happen if the symbolic link LATEST_DIR is not set properly.
Author:
Frederic Py fpy@m.nosp@m.bari.nosp@m..org
Definition at line 123 of file LogManager.hh.
#define SEARCH_ENV "TREX_PATH" [related]
Search path environment variable.
The name of the environment variable that indicates where TREX can search for files to locate them. The format fro this variable is a list of directories separated by a column (':')
Author:
Frederic Py fpy@m.nosp@m.bari.nosp@m..org
See also:
LogManager::m_searchPath
Definition at line 87 of file LogManager.hh.
#define TREX_ENV "TREX_HOME" [related]
Home environment variable.
The name of the environment variable that indicates where TREX is located. If valid, the value of this variable will be automatically added to the search path used by LogManager to locate new files
Author:
Frederic Py fpy@m.nosp@m.bari.nosp@m..org
See also:
LogManager::m_searchPath
Definition at line 75 of file LogManager.hh.
#define TREX_LOG_FILE "TREX.log" [related]
TREX default log file name.
This macro is used by LogManager. It gives the name of the log file to create for logging text messages.
Author:
Frederic Py fpy@m.nosp@m.bari.nosp@m..org
Definition at line 62 of file LogManager.hh.
Referenced by logPath().
#define TREX_LOG_LEVEL LogNormal [related]
Default verbosity level.
Specifies the level of verbosity to select if not given
Author:
Frederic Py fpy@m.nosp@m.bari.nosp@m..org
Definition at line 132 of file LogManager.hh.
The documentation for this class was generated from the following files:
trex/utils/LogManager.hh
trex/utils/LogManager.cc