trex: TREX::agent::RealTimeClock Class Reference
TREX::agent::RealTimeClock Class Reference
[TREX agent]
Real time default clock for TREX.
#include <trex/agent/RealTimeClock.hh>
Public Types
typedef
TREX::utils::XmlFactory< Clock > xml_factory
XML factory for clocks.
Public Member Functions
void doStart ()
Start the clock.
TREX::transaction::TICK getNextTick ()
Compute tick date.
virtual TREX::transaction::TICK initialTick () const
Initial tick.
RealTimeClock (boost::property_tree::ptree::value_type &node)
XML parsing constructor.
RealTimeClock (double secondsPerTick)
Constructor.
virtual void sleep () const
Sleep until next tick.
double tickDuration () const
tick duration
double tickToTime (TREX::transaction::TICK cur) const
TREX::transaction::TICK timeToTick (time_t secs, suseconds_t usecs=0) const
~RealTimeClock ()
Destructor.
Static Public Member Functions
static void sleep (double sleepDuration)
Process sleep.
Protected Member Functions
void advanceTick (TREX::transaction::TICK &tick)
increment tick value
Related Functions
(Note that these are not member functions.)
Clock::xml_factory::declare
< RealTimeClock > rt_decl ("RealTime")
Clock XML factor declaration for RealTimeClock.
Detailed Description
Real time default clock for TREX.
This class implements a real-time clock based on gettimeofday primitive to be used for TREX agent.
Author:
Conor McGann & Frederic Py <fpy@mbari.org>
Definition at line 65 of file RealTimeClock.hh.
Constructor & Destructor Documentation
RealTimeClock::RealTimeClock (double secondsPerTick) [explicit]
Constructor.
Parameters:
secondsPerTick tick duration in seconds
Create a new instance with the tick duration set to secondsPerTick
Precondition:
secondsPerTick should be greater than 0.0
Definition at line 75 of file RealTimeClock.cc.
RealTimeClock::RealTimeClock (boost::property_tree::ptree::value_type & node) [explicit]
XML parsing constructor.
Parameters:
node A XML clock definition
Create a new instance based on the constent of node. The expected structure of node is
 <RealTime tick="<duration>"/>
where <duration> is a float giving the number of seconds per tick.
Exceptions:
TREX::utils::Exception tick attribute missing
TREX::utils::bad_string_cast unable to parse tick attribute
TREX::utils::Exception tick attribute value is less than 0
Definition at line 80 of file RealTimeClock.cc.
References TREX::utils::to_timeval().
Member Function Documentation
void TREX::agent::Clock::advanceTick (TREX::transaction::TICK & tick) [protected, inherited]
increment tick value
Parameters:
tick A tick variable
increase the value of tick by 1
Deprecated:
This method was used for computing extra stats. We need to find a better approach. Specifically it would be relevant to have the tick variable located on this class.
Referenced by TREX::agent::StepClock::getNextTick().
void Clock::doStart () [inherited]
Start the clock.
This method is the public interface used to start the clock.
See also:
void start()
Definition at line 71 of file Clock.cc.
References TREX::agent::Clock::start().
Referenced by TREX::agent::Agent::initComplete().
TICK RealTimeClock::getNextTick () [virtual]
Compute tick date.
This method get the system time and identify what is the current tick
Returns:
current time in tick
Note:
If more than one tick duration happened between the last call and this one. This method will display it in the TREX log.
Implements TREX::agent::Clock.
Definition at line 100 of file RealTimeClock.cc.
virtual TREX::transaction::TICK TREX::agent::Clock::initialTick () const [inline, virtual, inherited]
Initial tick.
Returns:
the value of the initial tick
Definition at line 89 of file Clock.hh.
void Clock::sleep (double sleepDuration) [static, inherited]
Process sleep.
Parameters:
sleepDuration number of seconds to sleep
This methods make the calling process to sleep for sleepDuration seconds
Exceptions:
ErrnoExcept An error occurred while trying to sleep
Definition at line 51 of file Clock.cc.
void Clock::sleep () const [virtual, inherited]
Sleep until next tick.
This method check the time left before next tick and put the process asleep for this duration.
Exceptions:
ErrnoExcept An error occurred while trying to sleep
See also:
double getSleepDelay() const
void sleep(double)
Definition at line 83 of file Clock.cc.
References TREX::agent::Clock::getSleepDelay().
Referenced by TREX::agent::Agent::doNext().
double TREX::agent::RealTimeClock::tickDuration () const [inline, virtual]
tick duration
This methods return the TICK duration. It is expected to be in seconds
Returns:
tick duration
Reimplemented from TREX::agent::Clock.
Definition at line 107 of file RealTimeClock.hh.
The documentation for this class was generated from the following files:
trex/agent/RealTimeClock.hh
trex/agent/RealTimeClock.cc