trex: TREX::europa::EuropaReactor Class Reference
TREX::europa::EuropaReactor Class Reference
Public Types
typedef details::external external_iterator
Iterator other external timelines.
typedef details::relation_iter internal_iterator
typedef graph::reactor_id ref_type
Reactor reference type.
typedef size_t size_type
size type
typedef xml_factory::argument_type xml_arg_type
XML construction info.
typedef graph::xml_factory xml_factory
XML based factory.
Public Member Functions
size_type count_externals () const
Number of External timelines.
size_type count_internal_relations () const
Count the number of internal relations.
size_type count_internals () const
Count the number of internal timelines.
bool doSynchronize ()
Synchronization callback.
EuropaReactor (TREX::transaction::TeleoReactor::xml_arg_type arg)
external_iterator ext_begin ()
beginning of External timelines set
external_iterator ext_end ()
end of External timelines set
TREX::utils::Symbol const & getAgentName () const
get "agent" name
TICK getCurrentTick () const
Get current tick.
TICK getExecLatency () const
reactor execution latency
TICK getFinalTick () const
Get final tick.
graph const & getGraph () const
Get graph.
TREX::utils::Symbol const & getGraphName () const
Get graph name.
TICK getInitialTick () const
reactor initial tick
TICK getLatency () const
reactor latency
TICK getLookAhead () const
Get reactor look-ahead.
TREX::utils::Symbol const & getName () const
Reactor name.
bool initialize (TICK final)
Final initialization.
internal_iterator int_begin () const
First internal relation iterator.
internal_iterator int_end () const
Last internal relation iterator.
bool newTick ()
New tick notification callback.
void step ()
Deliberation step.
double tickDuration () const
Tick duration.
double tickToTime (TICK cur) const
tick to unix time conversion
TICK timeToTick (time_t secs, suseconds_t usecs=0) const
unix time to tick conversion
double workRatio ()
reactor deliberation work load
Protected Types
typedef boost::filter_iterator
< details::is_external,
state_iterator > external_iterator
Iterator through TREX external state variables.
typedef boost::filter_iterator
< details::is_internal,
state_iterator > internal_iterator
Iterator through TREX internal state variables.
typedef state_map::const_iterator state_iterator
Iterator through TREX state variables.
Protected Member Functions
void add_state_var (EUROPA::TimelineId const &obj)
Add TREX state variable.
void archive ()
state_iterator begin () const
external_iterator begin_external () const
internal_iterator begin_internal () const
void cancelledPlanToken (TREX::transaction::goal_id const &t)
void cancelPlanToken (goal_id const &g)
EUROPA::ConstrainedVariableId
const & clock () const
Clock variable.
bool completedGoal (goal_id g)
Goal completion.
void configure_solvers (std::string const &cfg)
Configure solvers.
EUROPA::ConstraintEngineId const & constraint_engine () const
EUROPA::TokenId create_token (EUROPA::ObjectId const &obj, std::string const &name, bool fact)
EUROPA::ConstrainedVariableId default_pred (EUROPA::ObjectId const &obj) const
bool do_synchronize ()
state_iterator end () const
external_iterator end_external () const
internal_iterator end_internal () const
bool external (EUROPA::TokenId const &tok) const
Check if external.
bool external (EUROPA::ObjectId const &obj) const
Check if external.
virtual bool failed_external (TREX::utils::Symbol const &timeline, graph::timeline_failure const &err)
Request for external failed.
virtual bool failed_internal (TREX::utils::Symbol const &timeline, graph::timeline_failure const &err)
Request for internal failed.
external_iterator find_external (TREX::utils::Symbol const &name)
Find an external timeline.
void getFuturePlan ()
Gets the Future plan.
void handleInit ()
reactor initialiszation callback
void handleRecall (TREX::transaction::goal_id const &request)
Goal recall callback.
void handleRequest (TREX::transaction::goal_id const &request)
Goal reception callback.
void handleTickStart ()
New tick callback.
bool hasWork ()
Check if need to deliberate.
bool have_predicate (EUROPA::ObjectId const &obj, std::string &name) const
void ignore (EUROPA::ObjectId const &obj)
Mark as ignored.
bool ignored (EUROPA::TokenId const &tok) const
Check if ignored.
bool ignored (EUROPA::ObjectId const &obj) const
Check if ignored.
void init_clock_vars ()
Initialize plan clock varaiables.
bool internal (EUROPA::TokenId const &tok) const
Check if internal.
bool internal (EUROPA::ObjectId const &obj) const
Check if internal.
bool is_action (EUROPA::TokenId const &tok) const
Check if action.
bool is_agent_timeline (EUROPA::ObjectId const &obj) const
bool is_agent_timeline (EUROPA::DataTypeId const &type) const
bool is_agent_timeline (EUROPA::TokenId const &token) const
bool is_condition (EUROPA::TokenId const &tok) const
Check for condition attribute.
bool is_effect (EUROPA::TokenId const &tok) const
Check for effect attribute.
bool is_goal (EUROPA::TokenId const &tok) const
Test if goal.
bool is_predicate (EUROPA::TokenId const &tok) const
Check if predicate.
bool isExternal (TREX::utils::Symbol const &timeline) const
Check for exeternal timeline.
bool isInternal (TREX::utils::Symbol const &timeline) const
Check for internal timeline.
TREX::utils::LogManager & manager () const
LogManager acces point.
EUROPA::ConstrainedVariableId mode (EUROPA::ObjectId const &obj) const
EUROPA::TokenId new_obs (EUROPA::ObjectId const &obj, std::string &pred, bool &undefined)
void new_tick ()
New tick notification.
void newPlanToken (TREX::transaction::goal_id const &t)
void notify (TREX::transaction::Observation const &obs)
EUROPA::PlanDatabaseId const & plan_db () const
EUROPA::SOLVERS::SolverId planner ()
Planner.
bool playTransaction (std::string const &nddl)
Load a model.
bool postGoal (goal_id const &g)
Post a goal.
goal_id postGoal (Goal const &g)
Post a goal.
void postObservation (Observation const &o)
Produce an observation.
bool postPlanToken (goal_id const &g)
Post a planned token.
goal_id postPlanToken (Goal const &g)
Post a planned token.
bool postRecall (goal_id const &g)
Recall a goal.
void print_plan (std::ostream &out, bool expanded=false) const
void provide (TREX::utils::Symbol const &timeline, bool controllable=true, bool publish=false)
Internal timeline declaration.
void recalled (EUROPA::TokenId const &tok)
bool relax (bool aggressive)
void resume ()
Deliberation step callback.
EUROPA::SchemaId const & schema () const
void setStream () const
Set debug output stream.
bool synchronize ()
Synchronization callback.
EUROPA::SOLVERS::SolverId synchronizer ()
Synchronizer.
TREX::utils::internals::LogEntry syslog (std::string const &context=std::string())
new log entry
void trex_timelines (std::list< EUROPA::ObjectId > &timelines) const
void use (TREX::utils::Symbol const &timeline, bool control=true, bool plan_listen=false)
External timeline declaration.
bool with_plan (EUROPA::ObjectId const &obj) const
Static Protected Member Functions
static bool actions_supported ()
Check for support of actions.
Static Protected Attributes
static EUROPA::LabelStr const CLOCK_VAR
static EUROPA::LabelStr const EXTERNAL_MODE
static std::string const FAILED_PRED
static EUROPA::LabelStr const IGNORE_MODE
static EUROPA::LabelStr const INTERNAL_MODE
static EUROPA::LabelStr const MISSION_END
static EUROPA::LabelStr const OBSERVE_MODE
static EUROPA::LabelStr const PRIVATE_MODE
static EUROPA::LabelStr const TICK_DURATION
static EUROPA::LabelStr const TREX_TIMELINE
static std::string const UNDEFINED_PRED
Friends
class details::external
class details::timeline
class TREX::europa::details::CurrentState
class TREX::europa::details::Schema
class TREX::europa::details::UpdateFlawIterator
Detailed Description
Definition at line 46 of file EuropaReactor.hh.
Member Typedef Documentation
typedef details::external TREX::transaction::TeleoReactor::external_iterator [inherited]
Iterator other external timelines.
The type used to iterate other the external timlines of a reactor. This is mostly used by the boost graph library.
Definition at line 434 of file TeleoReactor.hh.
typedef boost::filter_iterator<details::is_external, state_iterator> TREX::europa::Assembly::external_iterator [protected, inherited]
Iterator through TREX external state variables.
The type used to iterate through all the CurrentState instances maintaining the External state -- in TREX sense -- of this engine.
See also:
state_iterator
internal_iterator
TREX::europa::details::CurrentState
Definition at line 494 of file Assembly.hh.
typedef boost::filter_iterator<details::is_internal, state_iterator> TREX::europa::Assembly::internal_iterator [protected, inherited]
Iterator through TREX internal state variables.
The type used to iterate through all the CurrentState instances maintaining the Internal state -- in TREX sense -- of this engine.
See also:
internal_iterator
state_iterator
TREX::europa::details::CurrentState
Definition at line 504 of file Assembly.hh.
typedef graph::reactor_id TREX::transaction::TeleoReactor::ref_type [inherited]
Reactor reference type.
The type used to refer to specific reactor
Definition at line 98 of file TeleoReactor.hh.
typedef size_t TREX::transaction::TeleoReactor::size_type [inherited]
size type
The type used to return a size such the number of External timleines of a reactor
Definition at line 440 of file TeleoReactor.hh.
typedef state_map::const_iterator TREX::europa::Assembly::state_iterator [protected, inherited]
Iterator through TREX state variables.
The type used to iterate through all the CurrentState instances maintaining the Internal and External state -- in TREX sense -- of this engine.
See also:
external_iterator
internal_iterator
TREX::europa::details::CurrentState
Definition at line 483 of file Assembly.hh.
typedef xml_factory::argument_type TREX::transaction::TeleoReactor::xml_arg_type [inherited]
XML construction info.
The argument passed by xml_factory while calling reactor classes constructor. This type is not a simple rapidxml::xml_node<> but also embeds a reference to the graph that the newly created instance will be attached to.
See also:
TREX::utils::XmlFactory
TREX::utils::XmlFactory::arg_traits;
TREX::transaction::graph
Definition at line 115 of file TeleoReactor.hh.
typedef graph::xml_factory TREX::transaction::TeleoReactor::xml_factory [inherited]
XML based factory.
The type of the factory used to generate reactors from XML
Definition at line 103 of file TeleoReactor.hh.
Member Function Documentation
bool Assembly::actions_supported () [static, inherited]
Check for support of actions.
This method checks if this europa plugin have been compiled with support of actions. It is equivalent to check if the preprocessing macro EUROPA_HAVE_EFFECT exists
Note:
if you use europa 2.6 or above this method should return true
Return values:
true if support actions
false otherwise
Definition at line 151 of file Assembly.cc.
Referenced by TREX::initPlugin().
void Assembly::add_state_var (EUROPA::TimelineId const & obj) [protected, inherited]
Add TREX state variable.
Parameters:
[in] obj An europa timeline
Notifies this class that the timeline obj is a TREX timeline connected to the agent.
Postcondition:
obj is now marked as a state variable which can trigger new current state flaws in the synchronizer() if it eever becomes internal
See also:
synchronizer()
CurrentState
internal(EUROPA::ObjectId const &) const
external(EUROPA::ObjectId const &) const
Definition at line 228 of file Assembly.cc.
References TREX::utils::list_set< IdTraits, Cmp >::end(), TREX::europa::Assembly::external(), TREX::utils::list_set< IdTraits, Cmp >::find(), and TREX::utils::list_set< IdTraits, Cmp >::insert().
EUROPA::ConstrainedVariableId const& TREX::europa::Assembly::clock () const [inline, inherited]
Clock variable.
This method gives an easy access to the varaiable used in the model to represent the mission clock. This variable is updated as time advance and can be used to idenyify whether an instant is in the past or future
Precondition:
the clock has been initialized
Returns:
A reference to the clock variable
See also:
init_clock_vars()
Definition at line 356 of file Assembly.hh.
Referenced by handleTickStart().
bool TREX::transaction::TeleoReactor::completedGoal (goal_id g) [protected, inherited]
Goal completion.
Parameters:
[in] g A goal
This method can be used from the reactor to inform the goal management system that the goal g on one of its external timeline has completed
Deprecated:
This method should become useless as the goal management system is much more able to identify that a goal did complete
void Assembly::configure_solvers (std::string const & cfg) [protected, inherited]
Configure solvers.
Parameters:
[in] cfg A XML solver configuration file name
Configure both the planner and synchronizer solvers using the file cfg as a basis
Precondition:
cfg is a valid XML solver configuration file
Postcondition:
bothe the planner and synchronizer solvers are configured using cfg as a basis with the addition of their dedicated filters and flawmanagers
See also:
DeliberationFilter
SynchronizationFilter
SynchronizationManager
Definition at line 331 of file Assembly.cc.
size_type TREX::transaction::TeleoReactor::count_externals () const [inline, inherited]
Number of External timelines.
Returns:
the number of External timelines on this reactor
Definition at line 446 of file TeleoReactor.hh.
TeleoReactor::size_type TeleoReactor::count_internal_relations () const [inherited]
Count the number of internal relations.
This method count the number of relations that this reactor have with other reactors issued from its internla timelines.
This number does not count the number of internal timelines but the sum of all the reactors that are connected to this reactor through its internal timelines
Definition at line 259 of file TeleoReactor.cc.
References TREX::utils::list_set< IdTraits, Cmp >::begin(), and TREX::utils::list_set< IdTraits, Cmp >::end().
size_type TREX::transaction::TeleoReactor::count_internals () const [inline, inherited]
Count the number of internal timelines.
This methods indicates the number of internal timelines this reactor currently owns
Returns:
the number of internla timleins of this reactor
See also:
count_internal_relations() const
Definition at line 475 of file TeleoReactor.hh.
References TREX::utils::list_set< IdTraits, Cmp >::size().
bool TeleoReactor::doSynchronize () [inherited]
Synchronization callback.
This method is called by the agent to make the reactor execute its synchronization. It will call synchronize callback and returns then status of the reactor according to the execution of this call.
Return values:
true synchronization successfull
false the call to synchronize returned false or thew an exception
Warning:
when this method returns false this reflect a critical reactor failure. Therefre the agent will kill this reactor and produce the observation Failed on each of its Internal timeline.
See also:
synchronize()
Definition at line 506 of file TeleoReactor.cc.
References TREX::utils::list_set< IdTraits, Cmp >::begin(), TREX::utils::list_set< IdTraits, Cmp >::clear(), TREX::utils::list_set< IdTraits, Cmp >::end(), TREX::transaction::TeleoReactor::synchronize(), and TREX::transaction::TeleoReactor::syslog().
details::external TeleoReactor::ext_begin () [inherited]
beginning of External timelines set
Returns:
An iterator pointing to the beginning of the External timelines set for this reactor
See also:
ext_end()
Definition at line 276 of file TeleoReactor.cc.
Referenced by TREX::transaction::TeleoReactor::newTick(), and TREX::transaction::TeleoReactor::workRatio().
details::external TeleoReactor::ext_end () [inherited]
end of External timelines set
Returns:
An iterator pointing to the end of the External timelines set for this reactor
See also:
ext_begin()
Definition at line 280 of file TeleoReactor.cc.
bool Assembly::external (EUROPA::TokenId const & tok) const [inherited]
Check if external.
Parameters:
[in] tok A token
Checks if the token tok necessarily belong to an External timeline
Return values:
true if all the possible objects of tok ar External timelines
false otherwise
See also:
external(EUROPA::ObjectId const &) const
Definition at line 552 of file Assembly.cc.
Referenced by TREX::europa::Assembly::add_state_var().
bool Assembly::external (EUROPA::ObjectId const & obj) const [inherited]
Check if external.
Parameters:
[in] obj An object
Check if obj is a TREX external timeline.
Return values:
true if obj is an external timeline
false otherwise
See also:
is_external(EUROPA::LabelStr const &) const
is_agent_timeline(EUROPA::ObjectId const &) const
Definition at line 563 of file Assembly.cc.
virtual bool TREX::transaction::TeleoReactor::failed_external (TREX::utils::Symbol const & timeline, graph::timeline_failure const & err) [inline, protected, virtual, inherited]
Request for external failed.
Parameters:
[in] timeline Symbolic name of the timeline
[in] err Descriptor of the error
This callback is executed when an attempt to use the External timeline timeline triggered an error. The reason of the failure is described by err. It can be derived in order to provide an alternate way to handle this failed request
See also:
failed_internal(TREX::utils::symbol const &, graph::timeline_failure const &)
Definition at line 834 of file TeleoReactor.hh.
virtual bool TREX::transaction::TeleoReactor::failed_internal (TREX::utils::Symbol const & timeline, graph::timeline_failure const & err) [inline, protected, virtual, inherited]
Request for internal failed.
Parameters:
[in] timeline Symbolic name of the timeline
[in] err Descriptor of the error
This callback is executed when an attempt to prtovide the Internal timeline timeline triggered an error. The reason of the failure is described by err. It can be derived in order to provide an alternate way to handle this failed request
See also:
failed_external(TREX::utils::symbol const &, graph::timeline_failure const &)
Definition at line 851 of file TeleoReactor.hh.
details::external TeleoReactor::find_external (TREX::utils::Symbol const & name) [protected, inherited]
Find an external timeline.
Parameters:
[in] name hte name of the timeline
Returns:
An iterator refering to the external timeline name or ext_end() if this reactor does not subscribe to name
Definition at line 284 of file TeleoReactor.cc.
Referenced by hasWork().
TREX::utils::Symbol const& TREX::transaction::TeleoReactor::getAgentName () const [inline, inherited]
get "agent" name
Gets the name of the agent that controls this reactor.
Deprecated:
reactors are now manipulated by a graph. The agent uses this graph to trigger reactor's callbacks based on graph traversal algorithms. A graph is a more general concept thatn an agent (for example a graph could allow to have cyclic dependencies between reactors ...) to reflect this change this method has been replaced by getGraphName() and kept for backward compatibility.
Returns:
the name of the "agent"
See also:
getGraphName() const
Definition at line 187 of file TeleoReactor.hh.
References TREX::transaction::TeleoReactor::getGraphName().
TICK TREX::transaction::TeleoReactor::getCurrentTick () const [inline, inherited]
Get current tick.
Returns:
current tick date
See also:
getInitialTick() const
getFinalTick()
graph::getInitialTick() const
Definition at line 281 of file TeleoReactor.hh.
References TREX::transaction::graph::getCurrentTick().
Referenced by hasWork(), TREX::transaction::TeleoReactor::initialize(), TREX::transaction::TeleoReactor::newTick(), TREX::transaction::TeleoReactor::postObservation(), TREX::transaction::TeleoReactor::postPlanToken(), and TREX::transaction::TeleoReactor::workRatio().
TICK TREX::transaction::TeleoReactor::getExecLatency () const [inline, inherited]
reactor execution latency
Indicates the reactor execution latency. This value correspond to the delay it take s for thsi reactor to start executing its plan. It is function of the execution latency of the reactors it depends on and is updated automatically by the reactors graph.
This value is used by TREX and represent this reactor's dispatch window lowe bound.
Returns:
the reactor's execution latency
See also:
getLatency() const
Definition at line 327 of file TeleoReactor.hh.
Referenced by TREX::transaction::TeleoReactor::initialize(), and TREX::transaction::details::timeline::latency().
TICK TREX::transaction::TeleoReactor::getFinalTick () const [inline, inherited]
Get final tick.
Identify the agent final tick. This value correspond to the maximum possible life-time of the agent.
@ pre the reactor is initialized
Returns:
mission final tick
See also:
initialize()
getInitialTick() const
getCurrentTick() const
Definition at line 297 of file TeleoReactor.hh.
void Assembly::getFuturePlan () [protected, inherited]
Gets the Future plan.
Dispatches the plan to the plan_dispatch function
Definition at line 708 of file Assembly.cc.
References TREX::europa::Assembly::now().
Referenced by hasWork().
graph const& TREX::transaction::TeleoReactor::getGraph () const [inline, inherited]
Get graph.
This methods gives a reference to the graph that manage this reactor
Returns:
the graph
See also:
getGraphName() const
Definition at line 206 of file TeleoReactor.hh.
TREX::utils::Symbol const& TREX::transaction::TeleoReactor::getGraphName () const [inline, inherited]
Get graph name.
Returns:
the name of the graph that maintins this reactor relations
See also:
class TREX::transaction::graph
Definition at line 196 of file TeleoReactor.hh.
References TREX::transaction::graph::getName().
Referenced by TREX::transaction::TeleoReactor::getAgentName().
TICK TREX::transaction::TeleoReactor::getInitialTick () const [inline, inherited]
reactor initial tick
This method indicates the tick during which the reactor has been initialized.
Precondition:
the reactor has bein initialized
Returns:
the tick during which the reactor got started
See also:
handleInit()
getCurrentTick() const
getFinalTick() const
Definition at line 223 of file TeleoReactor.hh.
Referenced by TREX::transaction::TeleoReactor::initialize().
TICK TREX::transaction::TeleoReactor::getLatency () const [inline, inherited]
reactor latency
Indicates the reactor deliberation latency. Thids vlaue reflects the exstimated maximum delay this reactor needs to produce a new plan and is usually provided by the user during agent definition
Returns:
the reactor's latency
See also:
getExecLatency() const
Definition at line 310 of file TeleoReactor.hh.
Referenced by TREX::transaction::TeleoReactor::workRatio().
TICK TREX::transaction::TeleoReactor::getLookAhead () const [inline, inherited]
Get reactor look-ahead.
Indicates how many ticks the reactors look ahead while planning. A value of 0 indicates that this reactor does not accept goal.
Returns:
the reactor look-ahead
Definition at line 337 of file TeleoReactor.hh.
Referenced by TREX::transaction::details::timeline::look_ahead().
TREX::utils::Symbol const& TREX::transaction::TeleoReactor::getName () const [inline, inherited]
Reactor name.
Returns:
the anme of the reactor
Definition at line 168 of file TeleoReactor.hh.
Referenced by TREX::transaction::Player::Player(), TREX::transaction::TeleoReactor::syslog(), and TREX::transaction::TeleoReactor::TeleoReactor().
void EuropaReactor::handleInit () [protected, virtual]
reactor initialiszation callback
This callback is called during initialize() is order to allow derived classes to complete their initialization before the reactor goat executed.
It is called once at the beginning of the reactor ewxecution.
Bug:
this function is blocking and while it is usuaally called before the clock of the agent got started if the reactor is created at the beginning of the mission. it won't be the case for a reactor created on the fly which may be problematic if the calls takes too long in comparison of the tick duration.
Reimplemented from TREX::transaction::TeleoReactor.
Definition at line 230 of file EuropaReactor.cc.
References TREX::europa::Assembly::init_clock_vars(), and TREX::europa::Assembly::setStream().
void EuropaReactor::handleRecall (TREX::transaction::goal_id const & g) [protected, virtual]
Goal recall callback.
Parameters:
[in] g a goal
This method is called by the agent in roder to notify this reactor that the goal g is no logner desired.
Warning:
the duration of this call should be neglectable in comparison to the tick duration.
Reimplemented from TREX::transaction::TeleoReactor.
Definition at line 205 of file EuropaReactor.cc.
References TREX::europa::Assembly::setStream().
void EuropaReactor::handleRequest (TREX::transaction::goal_id const & g) [protected, virtual]
Goal reception callback.
Parameters:
[in] g a goal
This method is called by the agent in roder to notify this reactor that the goal g has been requested to him.
Warning:
the duration of this call should be neglectable in comparison to the tick duration.
Reimplemented from TREX::transaction::TeleoReactor.
Definition at line 168 of file EuropaReactor.cc.
References TREX::europa::Assembly::setStream(), and TREX::transaction::TeleoReactor::syslog().
void EuropaReactor::handleTickStart () [protected, virtual]
New tick callback.
This call back is executed at the beginning of a new tick. and can be used for the reactor to prepare for synchronization. It is also often used by the reactor to post its new goals.
Note:
at this stage the reactor should have received all the new goals for this tick. but this is not guaranteed.
Warning:
the duration of this call should be neglectable in comparison to the tick duration.
Reimplemented from TREX::transaction::TeleoReactor.
Definition at line 237 of file EuropaReactor.cc.
References TREX::europa::Assembly::clock(), TREX::europa::Assembly::new_tick(), and TREX::europa::Assembly::setStream().
bool EuropaReactor::hasWork () [protected, virtual]
Check if need to deliberate.
This method is called during workRatio in order to idenitfy if the reactor needs to deliberate.
By default it always return 0 and need to be redefined by derived classes if they need to deliberate.
Return values:
true this instance needs to deliberate
false this instance does not require deliberation
If the methods returns true this will eventually result on the agent calling the step() method
See also:
workRatio()
step()
Reimplemented from TREX::transaction::TeleoReactor.
Definition at line 445 of file EuropaReactor.cc.
References TREX::transaction::TeleoReactor::find_external(), TREX::transaction::TeleoReactor::getCurrentTick(), TREX::europa::Assembly::getFuturePlan(), TREX::transaction::IntervalDomain< Ty, Comp >::lowerBound(), TREX::europa::Assembly::planner(), TREX::europa::Assembly::setStream(), TREX::transaction::TeleoReactor::syslog(), TREX::transaction::IntervalDomain< Ty, Comp >::upperBound(), and TREX::transaction::details::external::valid().
void TREX::europa::Assembly::ignore (EUROPA::ObjectId const & obj) [inline, protected, inherited]
Mark as ignored.
Parameters:
[in] obj An object
Exclude obj from deliberation. Thids object and its attached tokens will be ignored from both the planner and synchronizer
See also:
ignored(EUROPA::ObjectId const &obj) const
Definition at line 436 of file Assembly.hh.
bool Assembly::ignored (EUROPA::TokenId const & tok) const [inherited]
Check if ignored.
Parameters:
[in] tok A token
Checks if the token tok does necessarily belong to an object ignored by the solvers.
Such token will be ignored during deliberation
Return values:
true if all the possible objects of tok are ignored timelines
false otherwise
See also:
ignored(EUROPA::ObjectId const &) const
Definition at line 567 of file Assembly.cc.
bool TREX::europa::Assembly::ignored (EUROPA::ObjectId const & obj) const [inline, inherited]
Check if ignored.
Parameters:
[in] obj An object
Check if the object obj is to be ignored by the solvers
Return values:
true if obj is ignored
false otherwise
Definition at line 279 of file Assembly.hh.
void Assembly::init_clock_vars () [protected, inherited]
Initialize plan clock varaiables.
Extract and initialize the variables in the model used to represent the agent mission time. These varaiables (mostly constants) allow the modeler to integrate mission timeling information into their model.
Definition at line 206 of file Assembly.cc.
References TREX::europa::Assembly::final_tick(), TREX::europa::Assembly::initial_tick(), and TREX::europa::Assembly::tick_duration().
Referenced by handleInit().
bool TeleoReactor::initialize (TICK final) [inherited]
Final initialization.
Parameters:
[in] final The final tick date
Precondition:
getCurrentTick() < final
the reactor has not been inited yet
This method is called by the agent to allow the reactor to complete its initialization. At this stage the treactor knwos that it is part of the reactor graph and can complete its initialisation if needed. During this call, the callback handleInit will be executed allowing to execute reactors spacific initializations
Exceptions:
ReactorException Attempted to call this method twice
Postcondition:
The reactor is ready to be executed in the agent
See also:
handleInit()
getInitialTick() const
getCurrentTick() const
Definition at line 431 of file TeleoReactor.cc.
References TREX::transaction::TeleoReactor::getCurrentTick(), TREX::transaction::TeleoReactor::getExecLatency(), TREX::transaction::TeleoReactor::getInitialTick(), TREX::transaction::TeleoReactor::handleInit(), and TREX::transaction::TeleoReactor::syslog().
internal_iterator TREX::transaction::TeleoReactor::int_begin () const [inline, inherited]
First internal relation iterator.
See also:
count_internal_relations() const
int_end() const
Definition at line 494 of file TeleoReactor.hh.
References TREX::utils::list_set< IdTraits, Cmp >::begin(), and TREX::utils::list_set< IdTraits, Cmp >::end().
internal_iterator TREX::transaction::TeleoReactor::int_end () const [inline, inherited]
Last internal relation iterator.
See also:
count_internal_relations() const
int_begin() const
Definition at line 502 of file TeleoReactor.hh.
References TREX::utils::list_set< IdTraits, Cmp >::end().
bool Assembly::internal (EUROPA::TokenId const & tok) const [inherited]
Check if internal.
Parameters:
[in] tok A token
Checks if the token tok necessarily belong to an Internal timeline
Return values:
true if all the possible objects of tok ar Internal timelines
false otherwise
See also:
internal(EUROPA::ObjectId const &) const
Definition at line 537 of file Assembly.cc.
bool Assembly::internal (EUROPA::ObjectId const & obj) const [inherited]
Check if internal.
Parameters:
[in] obj An object
Check if obj is a TREX internal timeline.
Return values:
true if obj is an internal timeline
false otherwise
See also:
is_internal(EUROPA::LabelStr const &) const
is_agent_timeline(EUROPA::ObjectId const &) const
Definition at line 548 of file Assembly.cc.
bool Assembly::is_action (EUROPA::TokenId const & tok) const [inherited]
Check if action.
Parameters:
[in] tok A token
Check if tok is an action token.
Note:
if actions are not supported then this method will always return false
Return values:
true if tok is an action
false otherwise
See also:
is_predicate(EUROPA::TokenId const &) const
actions_supported()
Definition at line 498 of file Assembly.cc.
bool Assembly::is_condition (EUROPA::TokenId const & tok) const [inherited]
Check for condition attribute.
Parameters:
[in] tok A token
Check if tok is a condition token. An effect token means that this token is semantically a condition necessary for "executing" its master (which usually will be an action)
Note:
if actions are not supported then this method will always return false
Return values:
true if tok is a condition
false otherwise
See also:
is_effect(EUROPA::TokenId const &) const
actions_supported()
Definition at line 515 of file Assembly.cc.
bool Assembly::is_effect (EUROPA::TokenId const & tok) const [inherited]
Check for effect attribute.
Parameters:
[in] tok A token
Check if tok is an effect token. An effect token means that this token is semantically yhe resulting effect of "executing" its master (which usually will be an action)
Note:
if actions are not supported then this method will always return false
Return values:
true if tok is an effect
false otherwise
See also:
is_condition(EUROPA::TokenId const &) const
actions_supported()
Definition at line 523 of file Assembly.cc.
bool Assembly::is_goal (EUROPA::TokenId const & tok) const [inherited]
Test if goal.
Parameters:
[in] tok A token
Test if tok is a goal token meaning that it is rejectable and associated to an internal timeline.
Return values:
true if tok is a goal
false otherwise
See also:
internal(EUROPA::TokenId const &) const
Definition at line 532 of file Assembly.cc.
bool Assembly::is_predicate (EUROPA::TokenId const & tok) const [inherited]
Check if predicate.
Parameters:
[in] tok A token
Check if tok is a predicate token
Note:
if actions are not supported then this method will always return true
Return values:
true if tok is an action
false otherwise
See also:
is_action(EUROPA::TokenId const &) const
actions_supported()
Definition at line 506 of file Assembly.cc.
bool TeleoReactor::isExternal (TREX::utils::Symbol const & timeline) const [protected, inherited]
Check for exeternal timeline.
Parameters:
[in] timeline A name
Return values:
true if timeline is External to this reactor
false otherwise
See also:
isInternal(TREX::utils::Symbol const &) const
use(TREX::utils::Symbol const &, bool)
Definition at line 272 of file TeleoReactor.cc.
bool TeleoReactor::isInternal (TREX::utils::Symbol const & timeline) const [protected, inherited]
Check for internal timeline.
Parameters:
[in] timeline A name
Return values:
true if timeline is Internal to this reactor
false otherwise
See also:
isExternal(TREX::utils::Symbol const &) const
provide(TREX::utils::Symbol const &)
Definition at line 268 of file TeleoReactor.cc.
References TREX::utils::list_set< IdTraits, Cmp >::end(), and TREX::utils::list_set< IdTraits, Cmp >::find().
Referenced by TREX::transaction::TeleoReactor::provide(), and TREX::transaction::TeleoReactor::use().
TREX::utils::LogManager& TREX::transaction::TeleoReactor::manager () const [inline, protected, inherited]
LogManager acces point.
Returns:
the LogManager instance for this run
Definition at line 525 of file TeleoReactor.hh.
Referenced by TREX::transaction::Player::Player(), and TREX::transaction::TeleoReactor::TeleoReactor().
void Assembly::new_tick () [protected, inherited]
New tick notification.
Notifies this solver that the tick date has been updated. It can then updates the clock variable to be greater or equal to now()
Precondition:
The clock has been initialized
Postcondition:
the clock varaiable is updated to the interval [now(), final_tick()]
See also:
clock()
now()
Definition at line 246 of file Assembly.cc.
References TREX::europa::Assembly::final_tick(), and TREX::europa::Assembly::now().
Referenced by handleTickStart().
bool TeleoReactor::newTick () [inherited]
New tick notification callback.
This method is called by the agent to notify the reactor that a new tick has started. It will call the handleTickStart() method
See also:
handleTickStart()
Definition at line 456 of file TeleoReactor.cc.
References TREX::transaction::details::external::dispatch(), TREX::transaction::TeleoReactor::ext_begin(), TREX::transaction::TeleoReactor::getCurrentTick(), TREX::transaction::TeleoReactor::handleTickStart(), TREX::transaction::TeleoReactor::syslog(), and TREX::transaction::details::external::valid().
void EuropaReactor::notify (TREX::transaction::Observation const & obs) [protected, virtual]
New observation callback
Parameters:
[in] obs An observation
This method is called by the agent when one of the External timelines of this reactor changed state. The state is described by obs and satrts from the current tick.
It is guartanteed that all the notification of the current tick will be notified before the reactor synchronization
Warning:
the duration of this call should be neglectable in comparison to the tick duration.
See also:
synchronize()
Reimplemented from TREX::transaction::TeleoReactor.
Definition at line 153 of file EuropaReactor.cc.
References TREX::transaction::Predicate::object(), TREX::transaction::Predicate::predicate(), TREX::europa::Assembly::setStream(), TREX::utils::BasicSymbol< CharT, Traits, Alloc >::str(), and TREX::transaction::TeleoReactor::syslog().
EUROPA::SOLVERS::SolverId TREX::europa::Assembly::planner () [inline, protected, inherited]
Planner.
Give access to the solver dedicated for planning. This solver is a regular Europa solver that filters out from its deliberation all tokens outside of the plan_scope
Returns:
the planner
See also:
plan_scope() const
synchronizer()
Definition at line 592 of file Assembly.hh.
Referenced by hasWork(), resume(), and synchronize().
bool Assembly::playTransaction (std::string const & nddl) [protected, inherited]
Load a model.
Parameters:
[in] nddl A nddl model file
Load the model described in the file nddl
Precondition:
nddl must be a valid nddl file
Exceptions:
EuropaException Failed to load the file nddl
Postcondition:
the model described in nddl is loaded in the engine
Return values:
true the plan database is consistent
false the plan database is now inconsistent
Definition at line 308 of file Assembly.cc.
bool TeleoReactor::postGoal (goal_id const & g) [protected, inherited]
Post a goal.
Parameters:
[in] g A goal id
Post the goal g to an external timeline
Precondition:
g is a valid goal_id (i.e. not NULL)
g->object() is an External timeline of this reactor
Exceptions:
DispatchError The goal was not valid or was not on an external timeline of this reactor
Returns:
true the goal has been succesfully posted and is queued for dispatching
false this goal id is already in the dispatching queue
Note:
sucessfully posting a goal do not gauarantee that this goal will be duispatched and even less executed. It can be already too late to dispatch such a goal or the goal is simply impossible to be executed in current situation. As of today, the only way to check a goal has been executed is to wait for the corresponding observation unitl the maximum start time has been passed.
See also:
isExternal(TREX::utils::Symbol const &) const
postRecall(goal_id const &)
Definition at line 353 of file TeleoReactor.cc.
References TREX::transaction::details::external::post_goal().
Referenced by TREX::transaction::TeleoReactor::postGoal().
goal_id TeleoReactor::postGoal (Goal const & g) [protected, inherited]
Post a goal.
Parameters:
[in] g A goal
This method is just an overload of postGoal(goal_d const &) for user facility
Precondition:
g.object() is an External timeline
Exceptions:
DispatchError the goal wasn't on an External timeline
Returns:
the goal_id for this goal
See also:
postGoal(goal_id const &)
isExternal(TREX::utils::Symbol const &) const
Definition at line 368 of file TeleoReactor.cc.
References TREX::transaction::TeleoReactor::postGoal().
void TeleoReactor::postObservation (Observation const & o) [protected, inherited]
Produce an observation.
Parameters:
[in] o An observation
This method is a falcility to produce internally an observation o on one of the reactors Internal timeline.
It can be called internally to the reactor when a new state has been identified for this timeline.
Precondition:
o.object() is internal to this reactor
Postcondition:
Unless postObservation is called in between with an observation on the same object, the observation o will be dispatched to all the clients of o.object() during the next doNotify()
Exceptions:
SynchronizationError attempt to post an observation in a timeline which is not Internal to this reactor.
See also:
class Observation
isInternal(TREX::utils::Symbol const &) const
doNotify()
Definition at line 342 of file TeleoReactor.cc.
References TREX::utils::list_set< IdTraits, Cmp >::end(), TREX::utils::list_set< IdTraits, Cmp >::find(), TREX::transaction::TeleoReactor::getCurrentTick(), TREX::utils::list_set< IdTraits, Cmp >::insert(), TREX::transaction::Predicate::object(), and TREX::utils::BasicSymbol< CharT, Traits, Alloc >::str().
bool TeleoReactor::postPlanToken (goal_id const & g) [protected, inherited]
Post a planned token.
Parameters:
[in] g A goal id
Inform that the token g is now part of the plan of the reactor
Precondition:
g is a valid goal_id (i.e. not NULL)
g->object() is an Internal timeline of this reactor
Exceptions:
DispatchError The token was not valid or was not on an internal timeline of this reactor
Returns:
true the token has been correctly integrated.
false this token id is already broadcasted or its end time is in the past
See also:
isInternal(TREX::utils::Symbol const &) const
cancelPlanToken(goal_id const &)
Definition at line 393 of file TeleoReactor.cc.
References TREX::utils::list_set< IdTraits, Cmp >::end(), TREX::utils::list_set< IdTraits, Cmp >::find(), and TREX::transaction::TeleoReactor::getCurrentTick().
Referenced by TREX::transaction::TeleoReactor::postPlanToken().
goal_id TeleoReactor::postPlanToken (Goal const & g) [protected, inherited]
Post a planned token.
Parameters:
[in] g A goal
This method is just an overload of postPlanToken(goal_d const &) for user facility
Precondition:
g.object() is an Internal timeline of this reactor
Exceptions:
DispatchError The token was not on an internal timeline of this reactor
goal_id for the token posted. This id is invalid if the token was not posted
See also:
isInternal(TREX::utils::Symbol const &) const
postPlanToken(goal_id const &)
Definition at line 410 of file TeleoReactor.cc.
References TREX::transaction::TeleoReactor::postPlanToken().
bool TeleoReactor::postRecall (goal_id const & g) [protected, inherited]
Recall a goal.
Parameters:
[in] g A goal
This method recall the goal with the goal_id of g
Return values:
true the goal was sucessfully recalled
false the goal was not valid or is not on an External timeline
Note:
The goal_id g should be execatly the one passed to postGoal (or returned by it).
As for postGoal sucessfully recalling a goal does not mean that it will be removed from the plan of the owner of this timeline. It is more a way to indicate that this goal is not required anymore.
See also:
postGoal(goal_id const &)
postGoal(Goal const &)
isExternal(TREX::utils::Symbol const &) const
Definition at line 379 of file TeleoReactor.cc.
References TREX::transaction::details::external::recall().
void TeleoReactor::provide (TREX::utils::Symbol const & timeline, bool controllable = true, bool publish = false) [protected, inherited]
Internal timeline declaration.
Parameters:
[in] timeline a name
[in] controlable does this timeline accept goals
[in] publish does this timeline will publish its plan
This method is used to declare timeline as an Internal timeline.
Warning:
The type of a timeline can change during reactor execution and this is the reason why this methods give no feedback. It is always recommend to check the success/failure of this operation using isInternal
Note:
If the timlien was External and is not woned yet by any reactor, this call will promote it as Internal
See also:
isExternal(TREX::utils::Symbol const &) const
isInternal(TREX::utils::Symbol const &) const
graph::assign(graph::reactor_id, TREX::utils::Symbol const &)
use(TREX::utils::Symbol const &, bool)
Definition at line 559 of file TeleoReactor.cc.
References TREX::transaction::TeleoReactor::isInternal(), TREX::utils::BasicSymbol< CharT, Traits, Alloc >::str(), and TREX::transaction::TeleoReactor::syslog().
Referenced by TREX::startrex::Auv::Auv(), TREX::lightswitch::Light::Light(), and TREX::transaction::TeleoReactor::TeleoReactor().
void EuropaReactor::resume () [protected, virtual]
Deliberation step callback.
This callback will be executed in response of hasWork returning true. It allows the reactor to execute an atomic deliberation step.
Warning:
the duration of this call should be neglectable in comparison to the tick duration.
Reimplemented from TREX::transaction::TeleoReactor.
Definition at line 487 of file EuropaReactor.cc.
References TREX::europa::Assembly::planner(), TREX::europa::Assembly::setStream(), and TREX::transaction::TeleoReactor::syslog().
void Assembly::setStream () const [protected, inherited]
Set debug output stream.
This emthod allow to reset the europa debug output stream to the file dedicated to this engine. As all the debugMsg of Europa are managed by a central singleton, his call allow to put all the messages for this sepcific engine into a special file.
Postcondition:
all the debugMsg are now redirected to the file m_debug
See also:
m_debug
Definition at line 304 of file Assembly.cc.
Referenced by handleInit(), handleRecall(), handleRequest(), handleTickStart(), hasWork(), notify(), resume(), synchronize(), and TREX::europa::Assembly::~Assembly().
void TeleoReactor::step () [inherited]
Deliberation step.
This method is aclled by the agent when it allows the reactor to do one deliberation step. It calls resume() and update informations in order to compute the reactors next work ratio
See also:
workRatio()
resume()
Definition at line 538 of file TeleoReactor.cc.
References TREX::transaction::TeleoReactor::resume().
bool EuropaReactor::synchronize () [protected, virtual]
Synchronization callback.
This method is called in order to ask for the reactor to
resolve its current state
produce new observation on its exeternal timelines if their state have changed The agent ensures that all new observation on this reactor timelines have been produced -- and received through notify -- to this reactor.
This is one of the more critical callback of the reactor and when it fails is considereed as a critical error resulting on the resactor being killed by the agent
Return values:
true synchronization succeeded
false synchronization failure. Will result on the reactor being killed soon after
Warning:
the duration of this call should be neglectable in comparison to the tick duration.
Implements TREX::transaction::TeleoReactor.
Definition at line 348 of file EuropaReactor.cc.
References TREX::europa::Assembly::planner(), TREX::europa::Assembly::setStream(), TREX::europa::Assembly::synchronizer(), and TREX::transaction::TeleoReactor::syslog().
EUROPA::SOLVERS::SolverId TREX::europa::Assembly::synchronizer () [inline, protected, inherited]
Synchronizer.
Give acces to the solver dedicated for synchronization. This solver is a regular Europa solver that filters out from its deliberation all tokens that do not overlap the current tick and also resolve current state flaws for all the internal timelines of this engine
See also:
now() const
SynchronizationManager
planner()
Definition at line 579 of file Assembly.hh.
Referenced by synchronize().
TREX::utils::internals::LogEntry TREX::transaction::TeleoReactor::syslog (std::string const & context = std::string()) [inline, protected, inherited]
new log entry
Parameters:
[in] context log entry prefix
create a new entry in TREX.log
Returns:
a stream that can be used to qwrite in the entry
See also:
TREX::utils::LogManager
TREX::utils::TextLog
Definition at line 890 of file TeleoReactor.hh.
References TREX::transaction::TeleoReactor::getName().
Referenced by TREX::startrex::Auv::Auv(), TREX::transaction::TeleoReactor::doSynchronize(), handleRequest(), hasWork(), TREX::transaction::TeleoReactor::initialize(), TREX::lightswitch::Light::Light(), TREX::transaction::TeleoReactor::newTick(), notify(), TREX::transaction::Player::Player(), TREX::transaction::TeleoReactor::provide(), TREX::transaction::details::timeline::request(), resume(), synchronize(), TREX::transaction::TeleoReactor::TeleoReactor(), TREX::transaction::TeleoReactor::use(), and TREX::transaction::TeleoReactor::workRatio().
double TREX::transaction::TeleoReactor::tickDuration () const [inline, inherited]
Tick duration.
Indicates the duration of the tick. This duration is expected to be expressed in seconds even though nothing in the architecture constraint such aspect.
Returns:
the duration of a single tick
Definition at line 234 of file TeleoReactor.hh.
References TREX::transaction::graph::tickDuration().
double TREX::transaction::TeleoReactor::tickToTime (TICK cur) const [inline, inherited]
tick to unix time conversion
Parameters:
[in] cur A tick value
Returns:
equivalent unix time to cur as a float
This method is an utility to ease the conversion form a tick to unix time it calls the agent clock corresponding method to convert the specified tick value into unix time
Note:
the result of the method depends on the clock implementation. For example the RealTimeClock fully support it while the StepClock will simply assume that unixtime and tick are perfeclty aligned (as if the mission started on January 1st 1970)
Definition at line 270 of file TeleoReactor.hh.
References TREX::transaction::graph::tickToTime().
TICK TREX::transaction::TeleoReactor::timeToTick (time_t secs, suseconds_t usecs = 0) const [inline, inherited]
unix time to tick conversion
Parameters:
[in] secs Number of seconds
[in] usecs Number of microseconds
Returns:
equivalent tick to the time secs.usecs
This method is an utility to ease the conversion form unix time to tick it calls the agent clock corresponding method to convert the specified unix time into a tick value
Note:
the result of the method depends on the clock implementation. For example the RealTimeClock fully support it while the StepClock will simply assume that unixtime and tick are perfeclty aligned (as if the mission started on January 1st 1970)
Definition at line 253 of file TeleoReactor.hh.
References TREX::transaction::graph::timeToTick().
void TeleoReactor::use (TREX::utils::Symbol const & timeline, bool control = true, bool plan_listen = false) [protected, inherited]
External timeline declaration.
Parameters:
[in] timeline a name
[in] control goal dispatching flag
[in] plan_listen plan listening flag
This method is used to declare timeline as an External timeline. The optional control flag prohibits goal dispatching to this timeline when false. The plan_listen flag aloow the reactor to be notified whenever the owner of this timeline does give the current tokens it has in his future plan
Precondition:
The timleine is not already Internal
Warning:
The type of a timeline can change during reactor execution and this is the reason why this methods give no feedback. It is always recommend to check the success/failure of this operation using isExternal
See also:
isExternal(TREX::utils::Symbol const &) const
isInternal(TREX::utils::Symbol const &) const
graph::subscribe(graph::reactor_id, TREX::utils::Symbol const &, details::transaction_flag const &)
provide(TREX::utils::Symbol const &)
Definition at line 545 of file TeleoReactor.cc.
References TREX::transaction::TeleoReactor::isInternal(), TREX::utils::BasicSymbol< CharT, Traits, Alloc >::str(), and TREX::transaction::TeleoReactor::syslog().
Referenced by TREX::transaction::TeleoReactor::TeleoReactor().
double TeleoReactor::workRatio () [inherited]
reactor deliberation work load
This method calls hasWork method and, depending on the returned value and how close the reactor is to reach is latency, will give a value indicating heurisitically how urgent it is for him to delinerate.
Returns:
a value that becomes larger as the reactor is approaching its latency deadline or NAN if hasWork() returned false
See also:
hasWork()
step()
Definition at line 299 of file TeleoReactor.cc.
References TREX::transaction::details::external::dispatch(), TREX::transaction::TeleoReactor::ext_begin(), TREX::transaction::TeleoReactor::getCurrentTick(), TREX::transaction::TeleoReactor::getLatency(), TREX::transaction::TeleoReactor::hasWork(), TREX::transaction::TeleoReactor::syslog(), and TREX::transaction::details::external::valid().
The documentation for this class was generated from the following files:
extra/europa/EuropaReactor.hh
extra/europa/EuropaReactor.cc