trex: TREX::transaction::IntervalDomain< Ty, Comp >::bound Class Reference
TREX::transaction::IntervalDomain< Ty, Comp >::bound Class Reference
interval bounds extension of Ty
#include <trex/domain/IntervalDomain.hh>
Public Member Functions
bound (Ty const &val=Ty())
constructor
bound (bound const &other)
Copy constructor.
bool isInfinity () const
Check for infinity.
bound const & max (bound const &other) const
Maximum value.
bound const & min (bound const &other) const
Minimum value.
bound minus (bound const &other, bound const &onInf) const
substraction
bool operator!= (bound const &other) const
bool operator< (bound const &other) const
less than operator
bool operator<= (bound const &other) const
bound & operator= (bound const &other)
Assignment.
bound & operator= (Ty const &val)
Assignment.
bool operator== (bound const &other) const
Equality test.
bool operator> (bound const &other) const
bool operator>= (bound const &other) const
bound plus (bound const &other, bound const &onInf) const
addition
Ty const & value () const
~bound ()
Destructor.
Friends
class IntervalDomain< Ty, Comp >
std::ostream & std::operator<< (std::ostream &out, TREX::utils::ostreamable const &x)
std::istream & std::operator>> (std::istream &in, istreamable &x)
Detailed Description
template<typename Ty, class Comp = std::less<Ty>>
class TREX::transaction::IntervalDomain< Ty, Comp >::bound
interval bounds extension of Ty
This class extend the type Ty with the tow specific values -inf and +inf. It is used to represent interval domains.
See also:
class IntervalDomain
Author:
Frederic Py fpy@m.nosp@m.bari.nosp@m..org
Definition at line 90 of file IntervalDomain.hh.
Constructor & Destructor Documentation
template<typename Ty, class Comp = std::less<Ty>> TREX::transaction::IntervalDomain< Ty, Comp >::bound::bound (Ty const & val = Ty()) [inline]
constructor
Parameters:
val A value
Convert val into an interval bound
Definition at line 99 of file IntervalDomain.hh.
template<typename Ty, class Comp = std::less<Ty>> TREX::transaction::IntervalDomain< Ty, Comp >::bound::bound (bound const & other) [inline]
Copy constructor.
Parameters:
other Instance to copy
Creates a copy of other
Definition at line 107 of file IntervalDomain.hh.
Member Function Documentation
template<typename Ty, class Comp = std::less<Ty>> bool TREX::transaction::IntervalDomain< Ty, Comp >::bound::isInfinity () const [inline]
Check for infinity.
Checks if current instance is an infinity bound
Return values:
true if the value is +inf or -inf
false if the value is of type Ty
Definition at line 148 of file IntervalDomain.hh.
Referenced by TREX::transaction::IntervalDomain< double >::IntervalDomain().
template<typename Ty, class Comp = std::less<Ty>> bound const& TREX::transaction::IntervalDomain< Ty, Comp >::bound::max (bound const & other) const [inline]
Maximum value.
Parameters:
other another instance
Returns:
the highest value between *this and other
See also:
bool operator<(bound const &other) const
bound const &min(bound const &other) const
Definition at line 266 of file IntervalDomain.hh.
template<typename Ty, class Comp = std::less<Ty>> bound const& TREX::transaction::IntervalDomain< Ty, Comp >::bound::min (bound const & other) const [inline]
Minimum value.
Parameters:
other another instance
Returns:
the lowest value between *this and other
See also:
bool operator<(bound const &other) const
bound const &max(bound const &other) const
Definition at line 252 of file IntervalDomain.hh.
template<typename Ty, class Comp = std::less<Ty>> IntervalDomain< Ty, Cmp >::bound TREX::transaction::IntervalDomain< Ty, Cmp >::bound::minus (bound const & other, bound const & onInf) const
substraction
Parameters:
other another instance
onInf value if infinity
Compute the differenc between current instance and other.
Parameters:
onInf value to return if one is infinite
Return values:
the sum of the value of these two instances otherwise
See also:
bound plus(bound const &other, bound const &) const
Definition at line 84 of file IntervalDomain.hh.
template<typename Ty, class Comp = std::less<Ty>> bool TREX::transaction::IntervalDomain< Ty, Comp >::bound::operator!= (bound const & other) const [inline]
brief Difference test
Parameters:
other Another instance
Return values:
true if *this!=other
false otherwise
See also:
bool operator==(bound const &other) const
Definition at line 213 of file IntervalDomain.hh.
References TREX::transaction::IntervalDomain< Ty, Comp >::bound::operator==().
template<typename Ty, class Comp = std::less<Ty>> bool TREX::transaction::IntervalDomain< Ty, Comp >::bound::operator< (bound const & other) const [inline]
less than operator
Parameters:
other value to compare
Test if current instance is less than other. In this test -inf is smaller than any other value and +inf greater than any other value.
Return values:
true if *this<other
false otherwise
Definition at line 171 of file IntervalDomain.hh.
Referenced by TREX::transaction::IntervalDomain< Ty, Comp >::bound::operator>=().
template<typename Ty, class Comp = std::less<Ty>> bool TREX::transaction::IntervalDomain< Ty, Comp >::bound::operator<= (bound const & other) const [inline]
brief Less or equal to test
Parameters:
other Another instance
Return values:
true if *this<=other
false otherwise
See also:
bool operator<(bound const &other) const
Definition at line 231 of file IntervalDomain.hh.
References TREX::transaction::IntervalDomain< Ty, Comp >::bound::operator>().
template<typename Ty, class Comp = std::less<Ty>> bound& TREX::transaction::IntervalDomain< Ty, Comp >::bound::operator= (bound const & other) [inline]
Assignment.
Parameters:
other another instance
Assign other to the current instance
Returns:
*this after the operation
Definition at line 121 of file IntervalDomain.hh.
template<typename Ty, class Comp = std::less<Ty>> bound& TREX::transaction::IntervalDomain< Ty, Comp >::bound::operator= (Ty const & val) [inline]
Assignment.
Parameters:
val A Ty value
Assign the value val to current instance
Returns:
*this after the operation
Definition at line 135 of file IntervalDomain.hh.
template<typename Ty, class Comp = std::less<Ty>> bool TREX::transaction::IntervalDomain< Ty, Comp >::bound::operator== (bound const & other) const [inline]
Equality test.
Parameters:
other value to compare
Test if current instance is equal to other.
Note:
To ensure genericity this test relies on Comp instead of basic subjacent equality test of Ty. This has two side effects :
The test may be inneficient as it relies on the fact that a==b is equivalent to !(a<b || b<a). Whivch may require more computation when used with a simple ordering between basic C types
For the reasonds mentionned above one need to make sure that Comp is a complete order
Return values:
true if *this==other
false otherwise
Definition at line 199 of file IntervalDomain.hh.
Referenced by TREX::transaction::IntervalDomain< Ty, Comp >::bound::operator!=().
template<typename Ty, class Comp = std::less<Ty>> bool TREX::transaction::IntervalDomain< Ty, Comp >::bound::operator> (bound const & other) const [inline]
brief Greater than test
Parameters:
other Another instance
Return values:
true if *this>other
false otherwise
See also:
bool operator<(bound const &other) const
Definition at line 222 of file IntervalDomain.hh.
Referenced by TREX::transaction::IntervalDomain< Ty, Comp >::bound::operator<=().
template<typename Ty, class Comp = std::less<Ty>> bool TREX::transaction::IntervalDomain< Ty, Comp >::bound::operator>= (bound const & other) const [inline]
brief Greater or equal to test
Parameters:
other Another instance
Return values:
true if *this>=other
false otherwise
See also:
bool operator<(bound const &other) const
Definition at line 240 of file IntervalDomain.hh.
References TREX::transaction::IntervalDomain< Ty, Comp >::bound::operator<().
template<typename Ty, class Comp = std::less<Ty>> IntervalDomain< Ty, Cmp >::bound TREX::transaction::IntervalDomain< Ty, Cmp >::bound::plus (bound const & other, bound const & onInf) const
addition
Parameters:
other another instance
onInf value to return if one is infinite
Compute the sum of current instance with other.
Return values:
onInf if this instance or other is an infinite bound
the sum of the value of these two instances otherwise
See also:
bound minus(bound const &other, bound const &) const
Definition at line 73 of file IntervalDomain.hh.
template<typename Ty, class Comp = std::less<Ty>> Ty const& TREX::transaction::IntervalDomain< Ty, Comp >::bound::value () const [inline]
Finite bound value
Precondition:
This bound is not infinite
Returns:
the value associated to this instance
See also:
bool isInfinity() const
Definition at line 157 of file IntervalDomain.hh.
Referenced by TREX::transaction::IntervalDomain< double >::closestTo().
The documentation for this class was generated from the following files:
trex/domain/IntervalDomain.hh
trex/domain/bits/IntervalDomain.tcc