trex: TREX::transaction::graph_names_writer Class Reference
TREX::transaction::graph_names_writer Class Reference
graphviz display helper
#include <trex/transaction/bits/bgl_support.hh>
Public Member Functions
graph_names_writer ()
Defualt constructor.
void operator() (std::ostream &out, graph::reactor_id r) const
label for a reactor
void operator() (std::ostream &out, graph::relation_type const &rel) const
label for a timeline relation
Detailed Description
graphviz display helper
This class is an helper for bgl graphviz export utility it allows to add labels to both the nodes and the edges of the graph reflecting the reactors and timelines names.
Author:
Frederic Py fpy@m.nosp@m.bari.nosp@m..org
Definition at line 531 of file bgl_support.hh.
Member Function Documentation
void TREX::transaction::graph_names_writer::operator() (std::ostream & out, graph::reactor_id r) const [inline]
label for a reactor
Parameters:
[in,out] out An output stream
[in] A reactor
This method will write intoo out the label graphviz attribute of the node with the name of the reactor r
Definition at line 544 of file bgl_support.hh.
void TREX::transaction::graph_names_writer::operator() (std::ostream & out, graph::relation_type const & rel) const [inline]
label for a timeline relation
Parameters:
[in,out] out An output stream
[in] A timeline relation
This method will write intoo out the label graphviz attribute of the node with the name of the timeline assicaited to the relation r
Definition at line 556 of file bgl_support.hh.
References TREX::transaction::Relation::accept_goals(), TREX::transaction::Relation::active(), TREX::transaction::Relation::latency(), TREX::transaction::Relation::look_ahead(), and TREX::transaction::Relation::name().
The documentation for this class was generated from the following file:
trex/transaction/bits/bgl_support.hh