trex: amc command
amc command
TREX commands
A simple agent batch running command.
Files
file AMC.cc
Autonomous Mission Controller.
Functions
int main (int argc, char **argv)
Batch execution (amc) main function.
Detailed Description
A simple agent batch running command.
This module embeds all the code related to the amc program
amc command usage
The amc command line is the basic way t execute an agent in batch mode. It can ba e called like this :
 amc <mission>[.cfg] [-sim [steps]
Where :
<mission> is the name of a mission configuration file. There should be a file named <mission>.cfg in the TREX_PATH that describes an agent in XML format
-sim indicates that we want to use StepClock instead of the default clock. Otherwise it loads the clock loaded by <mission>.cfg or RealTimeClock if none was required <steps> indicates the maximum number of deliberation steps per tick StepClock should allow.
The programs locate the file <mission> int TREX_PATH -- or <mission>.cfg if <mission> is not found -- parse its XML content in order to initialize the rset of reactors loaded and the potential clock defined and execute it until completion. If no clock is provided the command uses a default real-time clock with a tick duration of 1 second.
See also:
TREX::agent::Agent::Agent(std::string const &, Clock *)
Author:
Conor McGann & Frederic Py fpy@m.nosp@m.bari.nosp@m..org
Function Documentation
int main (int argc, char ** argv)
Batch execution (amc) main function.
Parameters:
argc Number of arguments
argv command line arguments
This is the main function for the amc program. This program accepts 1 to 3 arguments :
 amc <mission>[.cfg] [-sim [<steps>]]
Where :
<mission> is the name of a mission configuration file. There should be a file named <mission>.cfg in the TREX_PATH that describes an agent in XML format
-sim indicates that we want to use StepClock instead of the default clock. Otherwise it loads the clock loaded by <mission>.cfg or RealTimeClock if none was required <steps> indicates the maximum number of deliberation steps per tick StepClock should allow.
This program will then load and execute the agent in a batch mode until its mission is completed or an error occured
Definition at line 109 of file AMC.cc.
References TREX::agent::Agent::setClock(), TREX::utils::BasicSymbol< CharT, Traits, Alloc >::str(), and TREX::utils::string_cast().