trex: TREX transaction
TREX transaction
[TREX core]
TREX reactors and messaging types.
Classes
class TREX::transaction::DispatchError
Goal posting error.
class TREX::transaction::details::external
An external timeline.
class TREX::transaction::Goal
TREX goal.
struct TREX::transaction::details::graph_edge_name_map
relation name mapping
struct boost::graph_traits< TREX::transaction::graph >
Transaction graph traits.
struct TREX::transaction::details::graph_vertex_id_map
reactor ID mapping
struct TREX::transaction::details::graph_vertex_name_map
reactor name mapping
class TREX::transaction::GraphException
Graph Exception.
class TREX::transaction::MultipleReactors
Conflicting reactor names.
class TREX::transaction::Observation
Reactor observation.
class TREX::transaction::Predicate
TREX Predicate.
class TREX::transaction::PredicateException
Predicate manipulation error.
struct boost::property_map< TREX::transaction::graph, edge_name_t >
Graphs property map for edge name.
struct boost::property_map< TREX::transaction::graph, vertex_index_t >
Graphs property map for reactor ID.
struct boost::property_map< TREX::transaction::graph, vertex_name_t >
Graphs property map for reactor name.
struct boost::property_map< TREX::transaction::graph::reactor_id, TREX::transaction::details::graph_vertex_name_map >
Reactor name property map.
struct boost::property_map< TREX::transaction::graph::relation_type, TREX::transaction::details::graph_edge_name_map >
Edge name property map.
struct TREX::transaction::details::reactor_id_traits< PtrType >
ID traits for TeleoReactor.
class TREX::transaction::ReactorException
TeleoReactor related exception.
class TREX::transaction::Relation
Timeline relation.
class TREX::transaction::details::relation_iter
Iterator for reactors relations.
class TREX::transaction::SynchronizationError
Synchronization related exception.
class TREX::transaction::TeleoReactor
TeleoReactor abstract interface.
class TREX::transaction::TransactionLogger
Observation/Goal logger.
Namespaces
namespace TREX::transaction::details
Implementation details for transaction.
Files
file bgl_support.hh
Boost Graph Library support code.
file Clock.cc
Clock class implementation.
file Clock.hh
TREX Clock.
file external.hh
external timeline external utilities
file Goal.cc
Goal implementation.
file Goal.hh
TREX goal definition.
file Observation.cc
Observation implementation.
file Observation.hh
TREX observation definition.
file Predicate.cc
Precicate class implementation.
file Predicate.hh
abstract TREX predicate for transactions
file TeleoReactor.cc
Provides implementation for TeleoReactor.
file TeleoReactor.hh
Declares the main interface for a Teleo-Reactor.
file TeleoReactor_fwd.hh
Forward decalrions for TeleoReactor.
file Tick.hh
TREX time representation.
file TransactionLogger.hh
Definition of reactors transaction logging class.
Typedefs
typedef utils::list_set
< client_id_traits > client_set
Set of clients.
typedef utils::list_set
< pending_traits > external_set
external timelines
typedef boost::shared_ptr< Goal > goal_id
A goal identifier.
typedef std::list< goal_id > goal_queue
A goal queue.
typedef utils::map_id_traits
< Relation, goal_queue > pending_traits
A external timeline proxy.
typedef IntegerDomain::base_type TREX::transaction::TICK
TREX unit of time.
Functions
std::pair< graph_traits
< TREX::transaction::graph >
::adjacency_iterator,
graph_traits
< TREX::transaction::graph >
::adjacency_iterator > TREX::transaction::graph::adjacent_vertices (TREX::transaction::graph::reactor_id r, TREX::transaction::graph const &g)
Reactor adjacency vertices of a reactor.
TREX::transaction::details::graph_vertex_id_map TREX::transaction::graph::get (vertex_index_t, TREX::transaction::graph const &g)
Get reactor ID map.
TREX::utils::Symbol const & TREX::transaction::graph::get (TREX::transaction::details::graph_vertex_name_map const &m, TREX::transaction::graph::reactor_id r)
Get reactor name.
TREX::transaction::details::graph_vertex_name_map TREX::transaction::graph::get (vertex_name_t, TREX::transaction::graph const &)
Get reactor name map.
TREX::utils::Symbol const & TREX::transaction::graph::get (TREX::transaction::details::graph_edge_name_map const &m, TREX::transaction::graph::relation_type const &rel)
Get relation name.
TREX::transaction::details::graph_edge_name_map TREX::transaction::graph::get (edge_name_t, TREX::transaction::graph const &)
Get relation name map.
TREX::transaction::graph::size_type TREX::transaction::graph::num_vertices (TREX::transaction::graph const &g)
Number of reactors.
TREX::transaction::TeleoReactor::size_type TREX::transaction::graph::out_degree (TREX::transaction::graph::reactor_id r, TREX::transaction::graph const &g)
Number of external relations for a reactor.
std::pair
< TREX::transaction::TeleoReactor::external_iterator,
TREX::transaction::TeleoReactor::external_iterator > TREX::transaction::graph::out_edges (TREX::transaction::graph::reactor_id r, TREX::transaction::graph const &g)
Out edges of a reactor.
TREX::transaction::graph::reactor_id TREX::transaction::graph::source (TREX::transaction::graph::relation_type const &rel, TREX::transaction::graph const &g)
source of a relation
TREX::transaction::graph::reactor_id TREX::transaction::graph::target (TREX::transaction::graph::relation_type const &rel, TREX::transaction::graph const &g)
target of a relation
std::pair
< TREX::transaction::graph::reactor_iterator,
TREX::transaction::graph::reactor_iterator > TREX::transaction::graph::vertices (TREX::transaction::graph const &g)
Graph reactors.
Detailed Description
TREX reactors and messaging types.
This module offers all the utilities to help define and implements new reactors. It also defines goals and observations excahnged between reactor as the abstract definition of a clock. All of these are provided by the library lib/libTREXteransaction.
Usually plug-ins are based on this library and can then defines new reactors, observations, goals or clocks.
Author:
Conor McGann & Frederic Py <fpy@mbari.org>
Typedef Documentation
typedef utils::list_set<client_id_traits> client_set
Set of clients.
This type is usded to store and maintin the set of client to a timeline. The clients of a timline are the reactors that declared it as external
timeline
Definition at line 164 of file TeleoReactor_fwd.hh.
typedef utils::list_set<pending_traits> external_set
external timelines
The type used by a TeleoReactor to maintin and manage the set of all its External relation
Most of this management is done by the external class that acts as an iterator other this type with extra functionalities
See also:
class external
Definition at line 48 of file external.hh.
typedef boost::shared_ptr<Goal> goal_id
A goal identifier.
This is the type used by TREX to identify and manipulate goals
Goal
Definition at line 265 of file Goal.hh.
typedef std::list<goal_id> goal_queue
A goal queue.
The basic container used by external class to maintain and process the set of goals being posted by a reactor and yet to be dipatched to the owner of this timeline
external
Definition at line 26 of file external.hh.
typedef utils::map_id_traits< Relation, goal_queue > pending_traits
A external timeline proxy.
This type by a external class to represent an external timeline relation and its corresponding set of pending goals
external
Definition at line 35 of file external.hh.
Function Documentation
std::pair< graph_traits< TREX::transaction::graph >::adjacency_iterator, graph_traits< TREX::transaction::graph >::adjacency_iterator > adjacent_vertices (TREX::transaction::graph::reactor_id r, TREX::transaction::graph const & g) [related, inherited]
Reactor adjacency vertices of a reactor.
Parameters:
[in] r A reactor
[in] g A graph
Gives all the relations reflecting the external timelines of the reactor r. This method is very similar to out_edges except that the relation are represented differently.
See also:
out_degree(TREX::transaction::graph::reactor_id, TREX::transaction::graph const &)
out_edges(TREX::transaction::graph::reactor_id, TREX::transaction::graph const &)
Definition at line 260 of file bgl_support.hh.
TREX::transaction::details::graph_vertex_id_map get (vertex_index_t , TREX::transaction::graph const & g) [related, inherited]
Get reactor ID map.
Parameters:
[in] g A transaction graph
Gets the reactor ID map associated to the graph g
Definition at line 665 of file bgl_support.hh.
TREX::utils::Symbol const & get (TREX::transaction::details::graph_vertex_name_map const & m, TREX::transaction::graph::reactor_id r) [related, inherited]
Get reactor name.
Parameters:
[in] m A reactor name map
[in] r A reactor
Get the name of the relctor r as provided by the map m
See also:
get(vertex_name_t, TREX::transaction::graph const &)
TREX::transaction::details::graph_vertex_name_map
Definition at line 616 of file bgl_support.hh.
TREX::transaction::details::graph_vertex_name_map get (vertex_name_t , TREX::transaction::graph const &) [related, inherited]
Get reactor name map.
Gets the reactor name map associated to a graph
Definition at line 598 of file bgl_support.hh.
TREX::utils::Symbol const & get (TREX::transaction::details::graph_edge_name_map const & m, TREX::transaction::graph::relation_type const & rel) [related, inherited]
Get relation name.
Parameters:
[in] m A relation name map
[in] rel A relation
Get the name of the relation rel as provided by the map m
See also:
get(edge_name_t, TREX::transaction::graph const &)
TREX::transaction::details::graph_edge_name_map
Definition at line 551 of file bgl_support.hh.
TREX::transaction::details::graph_edge_name_map get (edge_name_t , TREX::transaction::graph const &) [related, inherited]
Get relation name map.
Gets the relation name map associated to a graph
Definition at line 533 of file bgl_support.hh.
TREX::transaction::graph::size_type num_vertices (TREX::transaction::graph const & g) [related, inherited]
Number of reactors.
Parameters:
[in] g A graph
Indicates the number of reactors mainteind by the graph g
Returns:
the number of reactors in g
See also:
TREX::transaction::graph::count_reactors() const
vertices(TREX::transaction::graph const &)
Definition at line 307 of file bgl_support.hh.
TREX::transaction::TeleoReactor::size_type out_degree (TREX::transaction::graph::reactor_id r, TREX::transaction::graph const & g) [related, inherited]
Number of external relations for a reactor.
Parameters:
[in] r A reactor
[in] g A graph
Indicates the number of External timelines the reactor r have declared
Returns:
The number of External timelines of r
See also:
TREX::transaction::TeleoReactor::count_externals() const
out_edges(TREX::transaction::graph::relation_id,TREX::transaction::graph const &)
Definition at line 235 of file bgl_support.hh.
std::pair< TREX::transaction::TeleoReactor::external_iterator, TREX::transaction::TeleoReactor::external_iterator > out_edges (TREX::transaction::graph::reactor_id r, TREX::transaction::graph const & g) [related, inherited]
Out edges of a reactor.
Parameters:
[in] r A reactor
[in] g A graph
Gives all the relations reflecting the external timelines of the reactor r
See also:
TREX::transaction::TeleoReactor::ext_begin()
TREX::transaction::TeleoReactor::ext_end()
out_degree(TREX::transaction::graph::reactor_id, TREX::transaction::graph const &)
adjacent_vertices(TREX::transaction::graph::reactor_id, TREX::transaction::graph const &)
Definition at line 164 of file bgl_support.hh.
TREX::transaction::graph::reactor_id source (TREX::transaction::graph::relation_type const & rel, TREX::transaction::graph const & g) [related, inherited]
source of a relation
Parameters:
[in] rel A relation
[in] g A graph
Gives the reactors that created this relation by declaring the corresponding timeline as External
Returns:
The reactor which is the client of this relation
See also:
TREX::transaction::Relation::client() const
target(TREX::transaction::graph::relation_type const &, TREX::transaction::graph cons &)
Definition at line 186 of file bgl_support.hh.
References TREX::transaction::Relation::client().
TREX::transaction::graph::reactor_id target (TREX::transaction::graph::relation_type const & rel, TREX::transaction::graph const & g) [related, inherited]
target of a relation
Parameters:
[in] rel A relation
[in] g A graph
Gives the reactors that this relation connect to. This reactor is the one that declared the corresponding timeline as Internal
Returns:
The reactor which is the client of this relation or TREX::transaction::graph::null_reactor() if the relation is not active
See also:
TREX::transaction::Relation::active() const
TREX::transaction::Relation::server() const
TREX::transaction::graph::null_reactor()
source(TREX::transaction::graph::relation_type const &, TREX::transaction::graph cons &)
Definition at line 211 of file bgl_support.hh.
References TREX::transaction::Relation::active(), and TREX::transaction::Relation::server().
std::pair< TREX::transaction::graph::reactor_iterator, TREX::transaction::graph::reactor_iterator > vertices (TREX::transaction::graph const & g) [related, inherited]
Graph reactors.
Parameters:
[in] g A graph
Gives access to all the reactors maintined by the graph g
See also:
TREX::transaction::graph::reactor_begin() const
TREX::transaction::graph::reactor_end() const
num_vertices(TREX::transaction::graph const &)
Definition at line 288 of file bgl_support.hh.