trex: TREX::transaction::details::timeline Class Reference
TREX::transaction::details::timeline Class Reference
TREX timeline representation.
#include <trex/transaction/bits/timeline.hh>
Public Types
typedef timeline base_type
typedef utils::Symbol id_type
typedef Relation iterator
typedef client_set::size_type size_type
Public Member Functions
bool active () const
Check if active.
Relation begin ()
Iterator to first client.
Relation end ()
Iterator to end of clients.
TICK lastObsDate () const
last observation date
Observation const & lastObservation () const
last observation
TICK latency () const
Timeline latency.
TICK look_ahead () const
Timeline look ahead.
utils::Symbol const & name () const
timeline name
bool no_client () const
check if no client
bool owned () const
Check if owned.
bool owned_by (TeleoReactor const &r) const
Check for ownership.
TeleoReactor & owner () const
Timeline owner.
void recall (goal_id const &g)
Recall a goal.
void request (goal_id const &g)
Request a new goal.
bool should_publish () const
size_type size () const
Number of clients.
timeline (TICK date, utils::Symbol const &name)
Constructor.
timeline (TICK date, utils::Symbol const &name, TeleoReactor &serv, transaction_flags const &flags)
Constructor.
~timeline ()
Destructor.
Static Public Member Functions
static id_type const & get_id (base_type const &tl)
Timline symbolic name.
Friends
class TREX::transaction::graph
class TREX::transaction::Relation
class TREX::transaction::TeleoReactor
Detailed Description
TREX timeline representation.
This class is used by TREX ot represent a timeline and its connection with reactors. It is used internally to miantin the relation graph betwen reactors as well as the observation and goal exchanges for this given timeline
Author:
Frederic Py fpy@m.nosp@m.bari.nosp@m..org
Definition at line 52 of file timeline.hh.
Constructor & Destructor Documentation
timeline::timeline (TICK date, utils::Symbol const & name)
Constructor.
Parameters:
[in] date The current tick
[in] name A symbolic name
Creates the timeline name with the initial default Failed observation starting from the tick date.
Postcondition:
the timeline is not owned
See also:
owned() const
Definition at line 58 of file Relation.cc.
timeline::timeline (TICK date, utils::Symbol const & name, TeleoReactor & serv, transaction_flags const & flags)
Constructor.
Parameters:
[in] date The current tick
[in] name A symbolic name
[in] serv A reactor
Creates the timeline name and makes serv its owner. It also creates the default observation Failed staring from date which should be replaced by an observation from serv
Postcondition:
the timeline is owned by serv
See also:
owned() const
owner() const
Definition at line 62 of file Relation.cc.
Member Function Documentation
bool TREX::transaction::details::timeline::active () const [inline]
Check if active.
Checks if this timeline is owned by a reactor and has at least one client. In such case the timeline should be explored during the traversal of the reactors relation graph
See also:
owned() const
no_client() const
size() const
Definition at line 169 of file timeline.hh.
References no_client(), and owned().
Relation TREX::transaction::details::timeline::begin () [inline]
Iterator to first client.
Returns:
An iterator that refers to the first client
See also:
end()
Definition at line 204 of file timeline.hh.
Relation TREX::transaction::details::timeline::end () [inline]
Iterator to end of clients.
Returns:
An iterator that refers to the end of the client list
See also:
begin()
Definition at line 213 of file timeline.hh.
static id_type const& TREX::transaction::details::timeline::get_id (base_type const & tl) [inline, static]
Timline symbolic name.
Parameters:
[in] tl A timeline
Returns:
the name of tl
See also:
timeline::name() const
Definition at line 65 of file timeline.hh.
References name().
TICK TREX::transaction::details::timeline::lastObsDate () const [inline]
last observation date
Returns:
the date of the ladst observation
See also:
lastObservation() const
postObservation(TICK, Observation const &)
Definition at line 223 of file timeline.hh.
Observation const& TREX::transaction::details::timeline::lastObservation () const [inline]
last observation
Returns:
the ladst observation
See also:
lastObsDate() const
postObservation(TICK, Observation const &)
Definition at line 233 of file timeline.hh.
TICK timeline::latency () const
Timeline latency.
Indicates the timeline latency. As opposed to a reactor latency This latency not only include the deliberation time to include a token in a plan but also includes the maximum time it will take for the requested goal to be observed. It is actually what is called the execution latency identified by getExecLatency method for a reactor
Note:
If the timeline has no reactor its latency is set to the default value 0. Thids may change in the future
See also:
TeleoReactor::getExecLatency() const
Definition at line 81 of file Relation.cc.
References TREX::transaction::TeleoReactor::getExecLatency(), owned(), and owner().
TICK timeline::look_ahead () const
Timeline look ahead.
Reflects the look ahaed of the reactor owning this timeline. This insdicates how far ahead a goal can be posted to the timeline. If the timlien does not accpet goals is look ahead is 0
Note:
the look_ahead of a timelien can change. This happens specifically when the owner of the timeline changes.
Returns:
the timeline look-ahead
See also:
TeleoReactor::getLookAhead() const TeleoReactor::latency()
Definition at line 77 of file Relation.cc.
References TREX::transaction::TeleoReactor::getLookAhead(), owned(), and owner().
utils::Symbol const& TREX::transaction::details::timeline::name () const [inline]
timeline name
This method gives acces to the timline unique name.
Returns:
The name of this timeline
Definition at line 109 of file timeline.hh.
Referenced by get_id(), and request().
bool TREX::transaction::details::timeline::no_client () const [inline]
check if no client
Indicates if this timeline has no reactor that declared it as external
Return values:
true if it has no client
false oterhwise
See also:
size() const
Definition at line 182 of file timeline.hh.
Referenced by active().
bool TREX::transaction::details::timeline::owned () const [inline]
Check if owned.
Indicates if this timlien is owned by any reactor
true if the timlien have an owner
Return values:
false otherwise
See also:
owner() const
owned_by(TeleoReactor const &) const
Definition at line 123 of file timeline.hh.
Referenced by active(), latency(), look_ahead(), recall(), and request().
bool TREX::transaction::details::timeline::owned_by (TeleoReactor const & r) const [inline]
Check for ownership.
Parameters:
[in] r A reactor
Checks if the reactor r is currently owning this timeline
Return values:
true if the timeline is owned by r
false otherwise
See also:
owned() const
owner() const
Definition at line 139 of file timeline.hh.
TeleoReactor& TREX::transaction::details::timeline::owner () const [inline]
Timeline owner.
Gets the reactor tahat owns this timline. It is usually the reactor thast first declared this timline as internal
Precondition:
the timline is owned
Returns:
the owner fo this timeline
See also:
owned() const
owned_by(TeleoReactor const &) const
assign(TeleoReactor &)
Definition at line 155 of file timeline.hh.
Referenced by latency(), look_ahead(), recall(), and request().
void timeline::recall (goal_id const & g)
Recall a goal.
Parameters:
[in] g A goal
This method inform the timeline (and potentially its owner) that the previously requested goal g is no longer requested
See also:
request(goal_id const &)
TeleoReactor::handleRecall(goal_id const &);
Definition at line 172 of file Relation.cc.
References TREX::transaction::TeleoReactor::handleRecall(), owned(), and owner().
void timeline::request (goal_id const & g)
Request a new goal.
Parameters:
[in] g A goal
This method inform the timeline (and potentially/eventually its owner) that the goal g is requested for this timeline.
See also:
recall(goal_id const &)
TeleoReactor::handleRequest(goal_id const &);
Definition at line 164 of file Relation.cc.
References TREX::transaction::TeleoReactor::handleRequest(), name(), owned(), owner(), and TREX::transaction::TeleoReactor::syslog().
size_type TREX::transaction::details::timeline::size () const [inline]
Number of clients.
Indicates the number of reactors that declared this timline as external
Returns:
the number of client for this timeline
See also:
no_client() const
Definition at line 195 of file timeline.hh.
The documentation for this class was generated from the following files:
trex/transaction/bits/timeline.hh
trex/transaction/Relation.cc