trex: TREX::agent::details::sync_scheduller Class Reference
TREX::agent::details::sync_scheduller Class Reference
TREX agent
reactor synchronization visitor
Public Types
typedef std::list
< graph::reactor_id > reactor_queue
scheduling queue type
Public Member Functions
void back_edge (TREX::transaction::graph::relation_type const &rel, TREX::transaction::graph const &g)
back edge callback
void discover_vertex (graph::reactor_id r, graph const &g)
First encounter of a reactor.
void finish_vertex (graph::reactor_id r, graph const &g)
Finish vertex callback.
sync_scheduller (reactor_queue &sync_order)
Constructor.
sync_scheduller (sync_scheduller const &other)
virtual ~sync_scheduller ()
Destructor.
Protected Member Functions
bool is_valid (TREX::transaction::graph::reactor_id r, TREX::transaction::graph const &g) const
Check for node validity.
Detailed Description
reactor synchronization visitor
This class is used during a depth first in order to:
call the method newTick() on each of these reactors
identify a scheduling order for calling the reactors synchronization from the least dependent to the most dependent.
The scheduling order is stored in the list this callback points to and can be used after the depth first search by the Agent to execue the synchronization of each reactors.
Note:
We may in the future embeds the synchronization call of the reactors directly into this search. Even though it may be more efficient -- as we would avoid to have to construct this list and then iterate though it. We have yet to check and verify that such approach would be valid as it would interleave the calls of newTick and synchronize of the reactors which may -- or may not -- be problematic.
Agent
Author:
Frederic Py fpy@m.nosp@m.bari.nosp@m..org
Definition at line 151 of file Agent.cc.
Member Typedef Documentation
typedef std::list<graph::reactor_id> TREX::agent::details::sync_scheduller::reactor_queue
scheduling queue type
The type of the queue which is used to store the reactors in the scheduling order for synchronization.
This is just a simple list which can then be iterated from the beginning in order to go in a valid order for reactors execution
Definition at line 162 of file Agent.cc.
Constructor & Destructor Documentation
TREX::agent::details::sync_scheduller::sync_scheduller (reactor_queue & sync_order) [inline, explicit]
Constructor.
Parameters:
[in,out] sync_order A reference to the list where the schduling order should be stored
Create A new instance that will put the reactor synchronization scheduling into the list referred by sync_order
Note:
As boost graph library passes visitors by copy it is necessary here to have this list maintained as a reference to the list. Otherwise we would loose the information of this scheduling as soon as the search complete.
Definition at line 177 of file Agent.cc.
TREX::agent::details::sync_scheduller::sync_scheduller (sync_scheduller const & other) [inline]
Copy constructor
Parameters:
[in] other Another instance
Create new instance referring to the same scheduling list as other
Definition at line 185 of file Agent.cc.
Member Function Documentation
void TREX::agent::CycleDetector::back_edge (TREX::transaction::graph::relation_type const & rel, TREX::transaction::graph const & g) [inline, inherited]
back edge callback
This dfs callback is called only when the dfs loops back to a vertex that is still being explored. This clearly idenitfy a loop in the graph wwhich is a proof of cyclic dependncy betwee two reactors
Exceptions:
CycleDetected always thrown as this call indicates a cyclic dependency in the egent graph
Definition at line 144 of file agent_graph.hh.
References TREX::agent::CycleDetector::is_valid().
void TREX::agent::details::sync_scheduller::discover_vertex (graph::reactor_id r, graph const & g) [inline]
First encounter of a reactor.
Parameters:
[in] r A reactor
[in] g The grah r belngs to
This method is called when the sarch encounter for the first time the reactor r. It calls the method newTick() to indicate to r that a new tick has started.
Definition at line 199 of file Agent.cc.
References TREX::transaction::graph::isolate().
void TREX::agent::details::sync_scheduller::finish_vertex (graph::reactor_id r, graph const & g) [inline]
Finish vertex callback.
Parameters:
[in] r A reactor
[in] g The graph r is attached to
This method is called when the sarch has explored all the reactor r depends on. It can the insert this reactor at the end of the scheduling list ensuring that this reactor synchronization won't be executed before all the reactors it depend on have been synchronized
Definition at line 218 of file Agent.cc.
bool TREX::agent::CycleDetector::is_valid (TREX::transaction::graph::reactor_id r, TREX::transaction::graph const & g) const [inline, protected, inherited]
Check for node validity.
Parameters:
[in] r A reactor reference
[in] g The graph supporting r
Check that r referes to an exisiting reactor. This method is used during graph traversal to check that the an edge is not pointing to nothing or to a node that has been isolated
Return values:
true if r refers to a reactor
false otherwise
See also:
TREX::transaction::garph::null_reactor()
Definition at line 166 of file agent_graph.hh.
Referenced by TREX::agent::CycleDetector::back_edge().
The documentation for this class was generated from the following file:
trex/agent/Agent.cc