trex: TREX::europa::Assembly Class Reference
TREX::europa::Assembly Class Reference
[Europa plug-in]
Interface toward europa.
#include <extra/europa/Assembly.hh>
Classes
class TokenManager
class TokenProcessor
Public Types
typedef TREX::utils::list_set
< details::InternalStateId_id_traits > obs_map
typedef std::list
< EUROPA::TokenId >
::const_iterator timeline_iterator
Public Member Functions
bool active () const
Check if active.
bool active () const
bool active () const
bool active () const
bool archive ()
Assembly (EuropaReactor &owner)
Constructor.
Assembly (EuropaReactor &owner)
Assembly (EuropaReactor &owner)
Constructor.
EUROPA::ConstrainedVariableId attribute (EUROPA::ObjectId const &obj, std::string const &attr) const
Extract an object attribute.
void check_default (EUROPA::ObjectId const &obj) const
void check_default (EUROPA::ObjectId const &obj) const
void check_default (EUROPA::ObjectId const &obj) const
Check for default predicate.
EUROPA::ConstrainedVariableId clock () const
void clock_advance (TREX::transaction::TICK value)
Update clock.
void completed (EUROPA::TokenId const &token)
void configure_solver (std::string const &cfg)
Load solver configuration.
void configure_solver (std::string const &cfg)
void configure_solver (std::string const &cfg)
That plan solver configuration.
EUROPA::ConstraintEngineId const & constraint_engine () const
Get europa constraint engine.
std::pair< EUROPA::ObjectId,
EUROPA::TokenId > convert (TREX::transaction::Predicate const &pred, bool isFact=false)
Convert TREX ptredicate into an europa token.
std::pair< EUROPA::ObjectId,
EUROPA::TokenId > convert (TREX::transaction::Predicate const &pred, bool isFact=false)
std::pair< EUROPA::ObjectId,
EUROPA::TokenId > convert (TREX::transaction::Predicate const &pred, bool isFact)
EUROPA::eint currentTick () const
EUROPA::ConstrainedVariableId default_pred (EUROPA::ObjectId const &obj) const
Access object default predicate.
EUROPA::LabelStr default_pred (EUROPA::ObjectId const &obj) const
EUROPA::ConstrainedVariableId default_pred (EUROPA::ObjectId const &obj) const
Get default predicate value.
bool external (EUROPA::TokenId const &tok) const
Check if external.
EUROPA::eint final () const
TREX::transaction::TICK final_tick () const
std::pair< timeline_iterator,
timeline_iterator > find_next (EUROPA::TimelineId const &tl) const
EUROPA::IntervalIntDomain const & horizon () const
void ignore (EUROPA::TokenId const &tok)
Ignore a token.
void ignore (EUROPA::ObjectId const &obj)
Ignore an object.
void ignore (EUROPA::ObjectId const &obj)
void ignore (EUROPA::ObjectId const &obj)
Set as ignored object.
bool ignored (EUROPA::TokenId const &tok) const
bool in_deliberation (EUROPA::TokenId const &tok) const
bool in_synch_scope (EUROPA::TokenId const &tok, EUROPA::TokenId &cand) const
bool in_synchronization () const
bool inactive () const
Check if inactive.
bool inactive () const
bool inactive () const
bool inactive () const
EUROPA::eint initial () const
bool insert_default (EUROPA::TimelineId const &obj, EUROPA::TokenId &tok, size_t &steps)
bool insert_default (EUROPA::ObjectId const &obj, EUROPA::TokenId &tok, size_t &steps)
bool insert_token (EUROPA::TokenId const &tok, size_t &steps)
bool insert_token (EUROPA::TokenId const &tok, size_t &steps)
void internal (EUROPA::ObjectId const &obj)
bool internal (EUROPA::TokenId const &tok) const
Check if internal.
obs_map::const_iterator internal_begin () const
obs_map::const_iterator internal_end () const
bool invalid () const
Check if invalid.
bool invalid () const
bool invalid () const
bool invalid () const
bool is_unit (EUROPA::TokenId const &tok, EUROPA::TokenId &merge_cand) const
bool is_unit (EUROPA::TokenId const &tok, EUROPA::TokenId &cand) const
bool isAgentTimeline (EUROPA::DataTypeId const &type) const
Check if TREX timeline.
bool isAgentTimeline (EUROPA::ObjectId const &obj) const
Check if TREX timeline.
bool isAgentTimeline (EUROPA::DataTypeId const &type) const
bool isAgentTimeline (EUROPA::ObjectId const &obj) const
bool isAgentTimeline (EUROPA::DataTypeId const &type) const
bool isAgentTimeline (EUROPA::ObjectId const &obj) const
bool isExternal (EUROPA::ObjectId const &obj) const
Check if External.
bool isExternal (EUROPA::ObjectId const &obj) const
bool isExternal (EUROPA::ObjectId const &obj) const
bool isExternal (EUROPA::ObjectId const &obj) const
Check if external.
bool isIgnored (EUROPA::TokenId const &tok) const
Check if ignored.
bool isIgnored (EUROPA::ObjectId const &obj) const
Check if ignored.
bool isIgnored (EUROPA::TokenId const &tok) const
bool isIgnored (EUROPA::ObjectId const &obj) const
bool isIgnored (EUROPA::TokenId const &tok) const
bool isIgnored (EUROPA::ObjectId const &object) const
bool isIgnored (EUROPA::ObjectId const &obj) const
Check if ignored.
bool isInternal (EUROPA::ObjectId const &obj) const
Check if Internal.
bool isInternal (EUROPA::TokenId const &tok) const
bool isInternal (EUROPA::ObjectId const &obj) const
bool isInternal (EUROPA::ObjectId const &obj) const
bool isInternal (EUROPA::ObjectId const &obj) const
Check if internal.
TREX::utils::internals::LogEntry log (std::string const &context) const
New log entry.
TREX::utils::internals::LogEntry log (std::string const &context) const
TREX::utils::internals::LogEntry log (std::string const &context) const
Log TREX message.
void log_plan (std::ostream &out) const
void logPlan (std::ostream &out) const
void mark_active ()
void mark_active ()
void mark_inactive ()
void mark_invalid ()
void mark_invalid ()
bool merge_token (EUROPA::TokenId const &tok, EUROPA::TokenId const &cand)
bool merge_token (EUROPA::TokenId const &tok, EUROPA::TokenId const &cand)
EUROPA::ConstrainedVariableId mode (EUROPA::ObjectId const &obj) const
Access object mode.
EUROPA::ConstrainedVariableId mode (EUROPA::ObjectId const &obj) const
EUROPA::ConstrainedVariableId mode (EUROPA::ObjectId const &obj) const
Get timeline mode.
TREX::utils::Symbol name () const
Assembly/reactor name.
TREX::utils::Symbol name () const
TREX::utils::Symbol name () const
void notify (EUROPA::TimelineId const &tl, EUROPA::TokenId const &obs)
EUROPA::eint now () const
bool overlaps_now (EUROPA::TokenId const &tok) const
EUROPA::PlanDatabaseId const & plan_db () const
Plan database access.
EUROPA::PlanDatabaseId const & plan_db () const
EUROPA::PlanDatabaseId const & plan_db () const
EUROPA::PlanDatabaseId const & plan_db () const
Get europa plan database.
bool playTransaction (std::string const &nddl)
Load nddl model.
bool playTransaction (std::string const &nddl)
bool playTransaction (std::string const &nddl)
Load a model.
void predicates (EUROPA::ObjectId const &obj, std::set< EUROPA::LabelStr > &result) const
bool process_agenda (TokenProcessor &sync)
bool propagate ()
bool propagate ()
bool propagate ()
void recall (EUROPA::TokenId const &goal)
bool relax (TREX::transaction::TICK exec_frontier, bool aggressive=false)
bool relax ()
bool resolve (EUROPA::TokenId const &tok, EUROPA::TokenId const &cand, size_t &steps)
bool resume ()
EUROPA::RulesEngineId const & rules_engine () const
Get europa rules engine.
EUROPA::SchemaId const & schema () const
Get europa schema This method gives a direct acces to the schema used by euroopa to manipulate the type of the different elements of the plan database.
EUROPA::SchemaId const & schema () const
EUROPA::SchemaId const & schema () const
Get europa schema.
void set_filter (DeliberationFilter *filt)
Set deliberation filter.
void setFinalTick (TREX::transaction::TICK value)
void setFinalTick (TREX::transaction::TICK value)
Set final tick.
void setStream ()
Switch europa debug stream.
void setStream ()
Reset Europa debug output stream.
void setStream ()
void setTickFactor (double delta)
void setTickFactor (double delta)
Set tick duration.
DbSolver & solver () const
Get solver.
DbSolver & solver () const
DbSolver & solver () const
Get the solver.
bool step ()
bool step ()
bool synchronize (TREX::transaction::TICK exec_frontier)
bool synchronize ()
bool synchronize ()
void trex_timelines (std::list< EUROPA::ObjectId > &timelines) const
TREX timelines.
void trex_timelines (std::list< EUROPA::ObjectId > &timelines) const
void trex_timelines (std::list< EUROPA::ObjectId > &objs) const
Get trex timelines.
~Assembly ()
Destructor.
Static Public Member Functions
static std::string predicate_name (EUROPA::ObjectId const &obj, std::string const &pred)
Static Public Attributes
static EUROPA::LabelStr const CLOCK_VAR
static EUROPA::LabelStr const EXTERNAL_MODE
Nddl external mode value.
static TREX::utils::Symbol const EXTERNAL_MODE
Europa external timelines descriptor.
static EUROPA::LabelStr const FAILED_PRED
static EUROPA::LabelStr const IGNORE_MODE
Nddl ignored mode value.
static TREX::utils::Symbol const IGNORE_MODE
Europa ignored timelines descriptor.
static EUROPA::LabelStr const INTERNAL_MODE
Nddl internal mode value.
static TREX::utils::Symbol const INTERNAL_MODE
Europa internal timelines descriptor.
static EUROPA::LabelStr const MISSION_END
Europa mission end variable.
static EUROPA::LabelStr const OBSERVE_MODE
Nddl observed mode value.
static TREX::utils::Symbol const OBSERVE_MODE
Europa observed timelines descriptor.
static EUROPA::LabelStr const PRIVATE_MODE
Nddl private mode value.
static TREX::utils::Symbol const PRIVATE_MODE
Europa private timelines descriptor.
static EUROPA::LabelStr const TICK_DURATION
tick duration variable
static EUROPA::LabelStr const TREX_TIMELINE
TREX agent timelines.
static EUROPA::LabelStr const UNDEFINED_PRED
static std::string const UNDEFINED_PRED
undefined predicate name
Friends
class DeliberationFilter
class EuropaReactor
class TokenManager
Detailed Description
Interface toward europa.
Interface with europa.
This class connects to europa components manipulated by TREX
Author:
Conor Mcgann & Frederic Py <fpy@mbari.org>
This class is used by a EuropaReactor and all its related classes as en entry point to the eeuropa plan data base and solvers. It gives access to europa constructs along with TREX specific entities inside the europa framework.
Author:
Conor McGann & Frederic Py <fpy@mbari.org>
Definition at line 120 of file Assembly.hh.
Constructor & Destructor Documentation
Assembly::Assembly (EuropaReactor & owner)
Constructor.
Parameters:
[in] owner the EuropaReactor that created this instance
Create a new instance associated to owner
Definition at line 172 of file Assembly.cc.
References TREX::transaction::TeleoReactor::getName(), and TREX::utils::BasicSymbol< CharT, Traits, Alloc >::str().
TREX::europa::Assembly::Assembly (EuropaReactor & owner)
Constructor.
Parameters:
[in] owner A reactor
Create a new instance associated to the reactor owner
Member Function Documentation
bool TREX::europa::Assembly::active () const [inline]
Check if active.
This method indicates if the Assembly deliberation state is active. Being active means that the current plan database of the assembly is not yet complete (meaning that there are still flaws to be resolved in the plan)
Return values:
true if this assembly deliberation state is active
false otherwise
See also:
bool inactive() const
bool invalid() const
Definition at line 288 of file Assembly.hh.
EUROPA::ConstrainedVariableId Assembly::attribute (EUROPA::ObjectId const & obj, std::string const & attr) const
Extract an object attribute.
Parameters:
[in] obj An object
[in] str An attribute name
Extract the attribute str from the object obj
Precondition:
obj has an attribute named str
Exceptions:
EuropaException The attribute str does not exist on obj
Returns:
The variable associated to the attribute str on obj
Definition at line 277 of file Assembly.cc.
Referenced by default_pred(), and mode().
void Assembly::check_default (EUROPA::ObjectId const & obj) const
Check for default predicate.
Parameters:
[in] obj An object
Precondition:
obj is a TREX timeline
the default predicate for obj is a fully specified value (ie a single value) and correspond ot a possible predicate for this object
Check that obj specifies a correct default predicate
Exceptions:
EuropaException obj is not a TREX timeline
EuropaException The default predicate of obj is not a singleton
EuropaException the default predicate of obj is not a valid predicate
See also:
default_pred(EUROPA::ObjectId const &) const
Definition at line 258 of file Assembly.cc.
References default_pred().
void Assembly::clock_advance (TREX::transaction::TICK value) [inline]
Update clock.
Parameters:
[in] value current tick value
Updates the lower bound of the clock variable (if available) to value
Precondition:
setFinalTick hase been called previously
Definition at line 200 of file Assembly.hh.
void TREX::europa::Assembly::configure_solver (std::string const & cfg)
Load solver configuration.
Parameters:
[in] cfg A europa solver confiuration file name
Load europa solver configuration from cfg
See also:
TREX::europa::DbSolver
void Assembly::configure_solver (std::string const & cfg)
That plan solver configuration.
Parameters:
[in] A solver configuration file
Precondition:
cfg is a file that can be found in TREX_PATH
cfg is a file in XML that can be used to create a DbSolver
This method has not been called before for this instance
Associate this class to a DbSolver configured using the xml content of cfg
Exceptions:
TREX::transaction::ReactorException Unable to locate cfg
TREX::transaction::ReactorException Unable to parse cfg as XML
See also:
DbSolver::DbSolver(Assembly const &, EUROPA::TiXmlElement const &)
Definition at line 483 of file Assembly.cc.
References TREX::transaction::TeleoReactor::manager(), TREX::transaction::TeleoReactor::syslog(), and TREX::utils::LogManager::use().
EUROPA::ConstraintEngineId const& TREX::europa::Assembly::constraint_engine () const [inline]
Get europa constraint engine.
Returns:
the constraint engine associated to this class
Definition at line 253 of file Assembly.hh.
std::pair<EUROPA::ObjectId, EUROPA::TokenId> TREX::europa::Assembly::convert (TREX::transaction::Predicate const & pred, bool isFact = false)
Convert TREX ptredicate into an europa token.
Parameters:
[in] pred A trex predicate
[in] isFact Fact flag
Convert pred as a europa token which is either a fact -- if isFact is true -- or a rejectable goal -- if isFact is false.
Precondition:
pred.object() is a valid AgentTimline in the loaded model
Returns:
A pair with second referring to the newly created token and first referrign to the timeline this token is attached to.
Note:
If the predicate name does not exist for the object of this predicate. The output will depend on isFact :
if isFact is true then this function will create the special UNDEFINED_PRED token.
if isFact is false it will not create a new token and will return a pair of noId() instead
Exceptions:
EuropaException Unable to create the UNDEFINED_PRED token
See also:
UNDEFINED_PRED
EUROPA::ConstrainedVariableId TREX::europa::Assembly::default_pred (EUROPA::ObjectId const & obj) const [inline]
Access object default predicate.
Parameters:
[in] obj A europa object
Precondition:
obj is an AgentTimeline
This method extract the default predicate attribute of obj.
The default predicate of an AgentTimeline is the default token type that would be produced in case the solver is not able to identify the current state of this variabale.
Exceptions:
EuropaException obj does not have a default predicate
Returns:
The europa variable representing the default for obj
See also:
isAgentTimeline(EUROPA::ObjectId const &) const
Definition at line 485 of file Assembly.hh.
References attribute().
EUROPA::LabelStr Assembly::default_pred (EUROPA::ObjectId const & obj) const [inline]
Get default predicate value.
Parameters:
[in] obj An object
Precondition:
obj is a trex timeline
Gets the timeline default predicate value. This value will be used to set the timeline state whwnever the model cannot idenitfy its value
Exceptions:
EuropaException obj is not a TREX timeline
Returns:
the variable that gives the default predicate of obj
Definition at line 317 of file Assembly.hh.
Referenced by check_default().
bool Assembly::external (EUROPA::TokenId const & tok) const
Check if external.
Parameters:
[in] tok A token
Return values:
true if all the possible objects for tok are trex External timelines
false otherwise
See also:
isExternal(EUROPA::ObjectId const &) const
internal(EUROPA::ObjectId const &) const
Definition at line 308 of file Assembly.cc.
References isExternal().
void TREX::europa::Assembly::ignore (EUROPA::TokenId const & tok)
Ignore a token.
Parameters:
[in] tok A europa token
Adds tok to the set of ignored tokens by this Assembly
Postcondition:
tok is ignored and all variables which are associated to it will be ignored during deliberation
See also:
ignore(EUROPA::ObjectId const &)
isIgnored(EUROPA::TokenId const &) const
void TREX::europa::Assembly::ignore (EUROPA::ObjectId const & obj)
Ignore an object.
Parameters:
[in] obj A europa object
Adds obj to the set of ignored objects by this Assembly
Postcondition:
obj is ignored and all variables and tokens which are associated to it will be ignored during deliberation
See also:
ignore(EUROPA::TokenId const &)
isIgnored(EUROPA::ObjectId const &) const
isIgnored(EUROPA::TokenId const &) const
void Assembly::ignore (EUROPA::ObjectId const & obj) [inline]
Set as ignored object.
Parameters:
[in] obj An object
Add obj to the object to be ignored in the plan database
Postcondition:
all the tokens associated to obj will be ignored during deliberation
Definition at line 380 of file Assembly.hh.
bool Assembly::ignored (EUROPA::TokenId const & tok) const
Precondition:
Ignored tokens filtering
Parameters:
[in] tok A token
Check if the token tok should be ignored. This mean that all the possible values of its associated object are in the ignore list
Return values:
true tok is ignored and can be discarded from deliberation
false there's still a possibility that tok is not to be ignored
See also:
ignore(EUROPA::ObjectId const &)
isIgnored(EUROPA::ObjectId const &) const
Definition at line 324 of file Assembly.cc.
References isIgnored().
Referenced by in_deliberation().
bool Assembly::in_deliberation (EUROPA::TokenId const & tok) const
Precondition:
Check if part of deliberation
Parameters:
[in] tok A token
Check if the token tok is part of current deliberation
This method is used during synchronization in order to avoid to badly impact any possible planning that happens meanwhile
Returns:
true if tok is part of pending deliberation
Return values:
false otherwise
Definition at line 335 of file Assembly.cc.
References TREX::transaction::TeleoReactor::getCurrentTick(), and ignored().
bool TREX::europa::Assembly::inactive () const [inline]
Check if inactive.
This method indicates if the Assembly deliberation state is inactive. Being inactive means that the current plan database of the assembluy is proven complete for the current tick.
Return values:
true if this assembly deliberation state is inactive
false otherwise
See also:
bool active() const
bool invalid() const
Definition at line 272 of file Assembly.hh.
bool Assembly::internal (EUROPA::TokenId const & tok) const
Check if internal.
Parameters:
[in] tok A token
Return values:
true if all the possible objects for tok are trex Internal timelines
false otherwise
See also:
isInternal(EUROPA::ObjectId const &) const
external(EUROPA::ObjectId const &) const
Definition at line 296 of file Assembly.cc.
References isInternal().
bool TREX::europa::Assembly::invalid () const [inline]
Check if invalid.
Indicate if the Assembly current state is invalid. The invalid state indicates that the plan data base is currently in a inconsitent state and needs to be repaired in order to allow this reactor to continue itsexecution.
Return values:
true if this assembly deliberation state is invalid
false otherwise
See also:
bool active() const
bool inactive() const
Definition at line 304 of file Assembly.hh.
bool TREX::europa::Assembly::isAgentTimeline (EUROPA::DataTypeId const & type) const
Check if TREX timeline.
Parameters:
[in] type An europa type
Return values:
true if type is a TREX timeline
false otherwise
bool TREX::europa::Assembly::isAgentTimeline (EUROPA::ObjectId const & obj) const
Check if TREX timeline.
Parameters:
[in] obj An europa object
Return values:
true if obj is a TREX timeline
false otherwise
bool TREX::europa::Assembly::isExternal (EUROPA::ObjectId const & obj) const
Check if External.
Parameters:
[in] obj A europa object
This method checks if obj is a TREX timeline that is External
Note:
This method is the only guaranteed way to know eactly whether a Europa object is an External timline or not
Return values:
true if obj is an External timeline
false else
See also:
isInternal(EUROPA::ObjectId const &) const
isIgnored(EUROPA::ObjectId const &) const
trex_timlines(std::list<EUROPA::ObjectId> &) const
TREX::transaction::TeleoReactor::isExternal
bool Assembly::isExternal (EUROPA::ObjectId const & obj) const
Check if external.
Parameters:
[in] obj An object
Check if obj is a trex External timeline.
Note:
This checking is at the reactor level -- and not simply ate the model level. Although for External timelines both the model and trex should be aligned
Return values:
true if obj is a trex External timeline
false otherwise
See also:
isInternal(EUROPA::ObjectId const &) const
isIgnored(EUROPA::ObjectId const &) const
Definition at line 291 of file Assembly.cc.
References TREX::transaction::TeleoReactor::isExternal(), and TREX_TIMELINE.
Referenced by external().
bool TREX::europa::Assembly::isIgnored (EUROPA::TokenId const & tok) const
Check if ignored.
Parameters:
[in] tok A europa token
This method checks if tok needs to be ignored during deliberation or not.
A token is ignored ifg all its possible associated objects are ignored or if it has been explicitely been set as ignored (for example because it is now in the past).
Return values:
true if the token should be ignored
false otherwise
See also:
isIgnored(EUROPA::ObjectId const &) const
ignore(EUROPA::TokenId const &)
bool TREX::europa::Assembly::isIgnored (EUROPA::ObjectId const & obj) const [inline]
Check if ignored.
Parameters:
[in] obj A europa object
This method checks if obj needs to be ignored during deliberation or not.
Note:
Ignored objects is some construct inherited from past versions of TREX where all the reactors where loading the same domain model differing only by the instaciation of this model. It is kept mostly for backward compatibility
Return values:
true if the object should be ignored
false otherwise
See also:
ignore(EUROPA::ObjectId const &)
Definition at line 420 of file Assembly.hh.
bool Assembly::isIgnored (EUROPA::ObjectId const & obj) const [inline]
Check if ignored.
Parameters:
[in] obj An object
Check if obj is a part of the objects to be ignored
Return values:
true if obj is part of the ignore list
false otherwise
See also:
isInternal(EUROPA::ObjectId const &) const
isIgnored(EUROPA::ObjectId const &) const
ignore(EUROPA::ObjectId const &)
Definition at line 487 of file Assembly.hh.
Referenced by ignored().
bool TREX::europa::Assembly::isInternal (EUROPA::ObjectId const & obj) const
Check if Internal.
Parameters:
[in] obj A europa object
This method checks if obj is a TREX timeline that is Internal
Note:
This method is the only guaranteed way to know exactly whether a Europa object is an External timline or not
Return values:
true if obj is an External timeline
false else
See also:
isInternal(EUROPA::ObjectId const &) const
isIgnored(EUROPA::ObjectId const &) const
trex_timlines(std::list<EUROPA::ObjectId> &) const
TREX::transaction::TeleoReactor::isExternal
bool Assembly::isInternal (EUROPA::ObjectId const & obj) const
Check if internal.
Parameters:
[in] obj An object
Check if obj is a trex Internal timeline.
Note:
This checking is at the reactor level -- and not simply at the model level. Indeed, it may happen that a timeline has been specified as Internal by the model but was already owned by another reactor. In that case a warning message would have been displayed in TREX.log and this timeline mode would have been set as Private and this method will return false
Bug:
I am not sure that this policy to migrate a timline from Internal o Private is the good one. It may be better to demote failed Internal timelines to External until we can take ownership of this timeline ...
Return values:
true if obj is a trex Internal timeline
false otherwise
See also:
isExternal(EUROPA::ObjectId const &) const
isIgnored(EUROPA::ObjectId const &) const
Definition at line 286 of file Assembly.cc.
References TREX::transaction::TeleoReactor::isInternal(), and TREX_TIMELINE.
Referenced by internal().
TREX::utils::internals::LogEntry TREX::europa::Assembly::log (std::string const & context) const
New log entry.
Parameters:
[in] context The context prefix
This method create a new log entry for the corresponding EuropaReactor with the context information context
Returns:
a new log entry tha can be used as a stream.
TREX::utils::internals::LogEntry Assembly::log (std::string const & context) const
Log TREX message.
Parameters:
[in] context message type/information
This method is a simple utility that allows to produces messages in TREX.log
Definition at line 545 of file Assembly.cc.
References TREX::transaction::TeleoReactor::syslog().
EUROPA::ConstrainedVariableId TREX::europa::Assembly::mode (EUROPA::ObjectId const & obj) const [inline]
Access object mode.
Parameters:
[in] obj A europa object
Precondition:
obj is an AgentTimeline
This mtehod extract the mode attribute of obj.
Exceptions:
EuropaException obj does not have a mode attribute
Returns:
The europa variable representing the mode of obj
Note:
This method indicates the mode of an object as specified in the model. In order to know the real mode of this object in the agent. It is strongly recommended to rely on isExternal or isInternal methods instead.
See also:
isAgentTimeline(EUROPA::ObjectId const &) const
isInternal(EUROPA::ObjectId const &) const
isExternal(EUROPA::ObjectId const &) const
isIgnored(EUROPA::ObjectId const &) const
Definition at line 464 of file Assembly.hh.
References attribute().
EUROPA::ConstrainedVariableId TREX::europa::Assembly::mode (EUROPA::ObjectId const & obj) const [inline]
Get timeline mode.
Parameters:
[in] obj An object
Precondition:
obj is a a trex timeline
Extract the mode of the timeline obj. This mode reflects whether the timeline is Internal, External or any other mode available.
Exceptions:
EuropaException obj is not a TREX timeline
Returns:
the variable that gives the mode of obj
See also:
INTERNAL_MODE
EXTERNAL_MODE
OBSERVE_MODE
PRIVATE_MODE
IGNORE_MODE
Definition at line 302 of file Assembly.hh.
TREX::utils::Symbol TREX::europa::Assembly::name () const
Assembly/reactor name.
Returns:
the name of the reactor that created this instance
EUROPA::PlanDatabaseId const& TREX::europa::Assembly::plan_db () const [inline]
Plan database access.
Returns:
An access to the plan database maintined by this Assembly
Definition at line 339 of file Assembly.hh.
EUROPA::PlanDatabaseId const& TREX::europa::Assembly::plan_db () const [inline]
Get europa plan database.
Returns:
the plan database associated to this class
Definition at line 260 of file Assembly.hh.
Referenced by setTickFactor().
bool TREX::europa::Assembly::playTransaction (std::string const & nddl)
Load nddl model.
Parameters:
nddl A filename
This method attempts to load the file nddl as a europa nddl model in the plan data base associated to this Assembly.
Precondition:
nddl is a valid nddl file
either NDDL.cfg or temp_nddl_gen.cfg files can be located using TREX_PATH and are valid europa XML configuration files.
Exceptions:
ReactorException Failed to locate NDDL.cfg or temp_nddl_gen.cfg
ReactorException NDDL.cfg or temp_nddl_gen.cfg is an empty xml file
ReactorException Failed to parse nddl
Postcondition:
the new model is loaded in the Assembly plan data base
Return values:
true if the constraint network is consistent
false if the constraint network is not constistent. Such situation should not occur and will probabaly be treated as an error from the caller.
bool Assembly::playTransaction (std::string const & nddl)
Load a model.
Parameters:
[in] nddl A nddl file symbolic name
Precondition:
A nddl configuration file named "NDDL.cfg" or "temp_nddl_gen.cfg" can be found in the TREX_PATH
The file nddl exist and is a valid nddl file
This method initialize the plan database using the model specified in the file nddl
Exceptions:
TREX::transaction::ReactorException An error occured while trying to load the model or either of the nddl configuartion files
TREX::utils::XmlError Erro while parsing the XML content of the nddl configuration file
Return values:
true The model was lsucessfully loaded and the plan data base is consistent
false The plan database is inconsitent after loading the model
Definition at line 504 of file Assembly.cc.
References TREX::utils::LogManager::begin(), TREX::utils::LogManager::end(), TREX::transaction::TeleoReactor::manager(), and TREX::utils::LogManager::use().
EUROPA::RulesEngineId const& TREX::europa::Assembly::rules_engine () const [inline]
Get europa rules engine.
Returns:
the rule engine associated to this class
Definition at line 267 of file Assembly.hh.
EUROPA::SchemaId const& TREX::europa::Assembly::schema () const [inline]
Get europa schema This method gives a direct acces to the schema used by euroopa to manipulate the type of the different elements of the plan database.
Returns:
The europa schema asociated to this instance
Definition at line 332 of file Assembly.hh.
EUROPA::SchemaId const& TREX::europa::Assembly::schema () const [inline]
Get europa schema.
Returns:
the schema associated to this class
Definition at line 246 of file Assembly.hh.
void TREX::europa::Assembly::set_filter (DeliberationFilter * filt) [inline]
Set deliberation filter.
Parameters:
[in] filt A deliberation filter
Associate this Assembly to the deliberation filter filt
Definition at line 496 of file Assembly.hh.
void TREX::europa::Assembly::setFinalTick (TREX::transaction::TICK value)
Set final tick.
Parameters:
[in] value The final tick value
This method is used to inject the final tick value of a TREX agent into the europa model. Is also manages to constraint the upper bound of the TREX_CLOCK (provided this variable exists) to this same value.
Exceptions:
ReactorException The current model does not have the FINAL_TICK variable
void TREX::europa::Assembly::setStream ()
Switch europa debug stream.
Set the europa debug stream toward the fille associated to this Assembly. Europa logging mechanism is tied to the global process but can be changed on the fly. We use this ability to be ebale to distribute logging messages in one fule per deliberative reactor. This method is called to ensure that future messages produced by europa logging (debugMsg) will all be redirected to the file associated to this assembly.
Postcondition:
all europa debug messages are now redirected toward the file associated to this assembly
See also:
TREX::europa::Schema::setStream(std::ostream &)
void TREX::europa::Assembly::setStream ()
Reset Europa debug output stream.
This method allows to redirect europa debug message to the output stream associated to this instance.
void Assembly::setTickFactor (double delta)
Set tick duration.
Parameters:
[in] A duration (often in seconds)
This method is used to inject in the model the duration of a tick as specified by the agent clock
Exceptions:
ReactorException The current model does not have the TICK_DURATION variable
Definition at line 776 of file Assembly.cc.
References plan_db(), and TICK_DURATION.
DbSolver& TREX::europa::Assembly::solver () const [inline]
Get solver.
Precondition:
configure_solver method has been successfully executed for this instance
Returns:
The solver used for this assembly deliberation
See also:
configure_solver(std::string const &)
Definition at line 323 of file Assembly.hh.
DbSolver& TREX::europa::Assembly::solver () const [inline]
Get the solver.
Returns:
the solver used by this class
See also:
configure_solver((std::string const &)
Definition at line 343 of file Assembly.hh.
void TREX::europa::Assembly::trex_timelines (std::list< EUROPA::ObjectId > & timelines) const
TREX timelines.
Parameters:
[out] timelines the list of TREX timelines in the plan database
This helper allow to access in the plan database alll the timelines that has been declared as AgentTimeline.
See also:
isAgentTimeline(ObjectId const &) const
void Assembly::trex_timelines (std::list< EUROPA::ObjectId > & objs) const [inline]
Get trex timelines.
Parameters:
[out] objs A list
Extract all the timleines of the model that are specified as trex timelines and store them in objs
Trex timelines are derived from the base class AgentTimeline in nddl; this method allows to selct of the objects that derive from this class in the plan database
See also:
TREX_TIMELINE
Definition at line 369 of file Assembly.hh.
Member Data Documentation
EUROPA::LabelStr const TREX::europa::Assembly::EXTERNAL_MODE [static]
Nddl external mode value.
The symbolic name used in europa model to specify a trex timeline as External.
An External timeline is not owned by this reactor but fully accessible (ie receive observation and post goals) by it.
See also:
OBSERVE_MODE
INTERNAL_MODE
PRIVATE_MODE
IGNORE_MODE
mode(EUROPA::ObjectId const &) const
Definition at line 85 of file Assembly.hh.
static EUROPA::LabelStr const TREX::europa::Assembly::EXTERNAL_MODE [static]
Europa external timelines descriptor.
Nddl external mode value.
The value used to specify a timeline as External in an nddl model
The symbolic name used in europa model to specify a trex timeline as External.
An External timeline is not owned by this reactor but fully accessible (ie receive observation and post goals) by it.
See also:
OBSERVE_MODE
INTERNAL_MODE
PRIVATE_MODE
IGNORE_MODE
mode(EUROPA::ObjectId const &) const
Definition at line 132 of file Assembly.hh.
EUROPA::LabelStr const TREX::europa::Assembly::IGNORE_MODE [static]
Nddl ignored mode value.
The symbolic name used in europa model to specify a trex timeline as Ignored.
An Ignored timeline is fully ignored during deliberation or synchronization.
Deprecated:
While such feature was necessary in past versions of TREX (as all reactors were loading the same domain with only a differenc in its instanciation) the utility of such feature on this version is still not clear. Still we keep such construct for backward compatibility.
See also:
EXTERNAL_MODE
OBSERVE_MODE
INTERNAL_MODE
PRIVATE_MODE
mode(EUROPA::ObjectId const &) const
Definition at line 89 of file Assembly.hh.
static EUROPA::LabelStr const TREX::europa::Assembly::IGNORE_MODE [static]
Europa ignored timelines descriptor.
Nddl ignored mode value.
The value used to specify that a specific timeline is ignored by the model
Deprecated:
This kind of timleine was used in the past when all europa reactors were loading the same model. As we now have each reactor loading their own model such feature is not really useful and may disappear in future versions
The symbolic name used in europa model to specify a trex timeline as Ignored.
An Ignored timeline is fully ignored during deliberation or synchronization.
Deprecated:
While such feature was necessary in past versions of TREX (as all reactors were loading the same domain with only a differenc in its instanciation) the utility of such feature on this version is still not clear. Still we keep such construct for backward compatibility.
See also:
EXTERNAL_MODE
OBSERVE_MODE
INTERNAL_MODE
PRIVATE_MODE
mode(EUROPA::ObjectId const &) const
Definition at line 161 of file Assembly.hh.
EUROPA::LabelStr const TREX::europa::Assembly::INTERNAL_MODE [static]
Nddl internal mode value.
The symbolic name used in europa model to specify a trex timeline as Internal.
An Internal timeline is owned by this reactor which means that this reactor will identify its current value and future plan.
Note:
The fact that a timeline has been specified as Internal does not guarantee that it will be during execution. Indeed such timeline can be already owned by another reactor.
See also:
EXTERNAL_MODE
OBSERVE_MODE
PRIVATE_MODE
IGNORE_MODE
mode(EUROPA::ObjectId const &) const
Definition at line 87 of file Assembly.hh.
static EUROPA::LabelStr const TREX::europa::Assembly::INTERNAL_MODE [static]
Europa internal timelines descriptor.
Nddl internal mode value.
The value used to specify a timeline as Internal in an nddl model
The symbolic name used in europa model to specify a trex timeline as Internal.
An Internal timeline is owned by this reactor which means that this reactor will identify its current value and future plan.
Note:
The fact that a timeline has been specified as Internal does not guarantee that it will be during execution. Indeed such timeline can be already owned by another reactor.
See also:
EXTERNAL_MODE
OBSERVE_MODE
PRIVATE_MODE
IGNORE_MODE
mode(EUROPA::ObjectId const &) const
Definition at line 143 of file Assembly.hh.
static EUROPA::LabelStr const TREX::europa::Assembly::MISSION_END [static]
Europa mission end variable.
The name of the variable in the model that is used to specify the the life time of the TREX agent
See also:
EuropaReactor::getFinalTick() const
Definition at line 170 of file Assembly.hh.
EUROPA::LabelStr const TREX::europa::Assembly::OBSERVE_MODE [static]
Nddl observed mode value.
The symbolic name used in europa model to specify a trex timeline as Observed.
An Observed timeline is not owned by a reactor and this reactor won't be allowed to post goals on it (as opposed to External ones).
See also:
EXTERNAL_MODE
INTERNAL_MODE
PRIVATE_MODE
IGNORE_MODE
mode(EUROPA::ObjectId const &) const
Definition at line 86 of file Assembly.hh.
static EUROPA::LabelStr const TREX::europa::Assembly::OBSERVE_MODE [static]
Europa observed timelines descriptor.
Nddl observed mode value.
The value used to specify a timeline as External which will not accept goals in an nddl model
The symbolic name used in europa model to specify a trex timeline as Observed.
An Observed timeline is not owned by a reactor and this reactor won't be allowed to post goals on it (as opposed to External ones).
See also:
EXTERNAL_MODE
INTERNAL_MODE
PRIVATE_MODE
IGNORE_MODE
mode(EUROPA::ObjectId const &) const
Definition at line 138 of file Assembly.hh.
EUROPA::LabelStr const TREX::europa::Assembly::PRIVATE_MODE [static]
Nddl private mode value.
The symbolic name used in europa model to specify a trex timeline as Private.
A Private timeline is owned by this reactor but not made publicly available for other reactors -- therefore acting as any europa timeline which is not an AgentTimeline. Such construct is usefull when someone wants to use an AgentTimeline but does not want to have this timeline constrainted by TREX requirements on shared timelines.
Note:
While his construct is not really necessary anymore in this version of TREX (as it supports basic europa timelines). It can proves convenient when a timeline specified as a TREX timeline needs to be used by a reactor without the need to publish it to other reactors.
See also:
EXTERNAL_MODE
OBSERVE_MODE
INTERNAL_MODE
IGNORE_MODE
mode(EUROPA::ObjectId const &) const
Definition at line 88 of file Assembly.hh.
static EUROPA::LabelStr const TREX::europa::Assembly::PRIVATE_MODE [static]
Europa private timelines descriptor.
Nddl private mode value.
The value used to specify a timeline as private in an nddl model. Private timelines are TREX timelines that are not shared with other reactors. They behave like regular europa timelines
The symbolic name used in europa model to specify a trex timeline as Private.
A Private timeline is owned by this reactor but not made publicly available for other reactors -- therefore acting as any europa timeline which is not an AgentTimeline. Such construct is usefull when someone wants to use an AgentTimeline but does not want to have this timeline constrainted by TREX requirements on shared timelines.
Note:
While his construct is not really necessary anymore in this version of TREX (as it supports basic europa timelines). It can proves convenient when a timeline specified as a TREX timeline needs to be used by a reactor without the need to publish it to other reactors.
See also:
EXTERNAL_MODE
OBSERVE_MODE
INTERNAL_MODE
IGNORE_MODE
mode(EUROPA::ObjectId const &) const
Definition at line 150 of file Assembly.hh.
static EUROPA::LabelStr const TREX::europa::Assembly::TICK_DURATION [static]
tick duration variable
The name of the variable in the model that is used to specify the duration of a tick.
See also:
EuropaReactor::tickDuration() const
Definition at line 178 of file Assembly.hh.
Referenced by setTickFactor().
static EUROPA::LabelStr const TREX::europa::Assembly::TREX_TIMELINE [static]
TREX agent timelines.
The name of the type used to specify a timeline shared in TREX
Definition at line 126 of file Assembly.hh.
Referenced by isExternal(), and isInternal().
static std::string const TREX::europa::Assembly::UNDEFINED_PRED [static]
undefined predicate name
The name of the undefined predicate for a TREX agent timeline. This predicate is often used whenever a new observation comes with a predicate name that is unknown by the europa model
Definition at line 189 of file Assembly.hh.
The documentation for this class was generated from the following files:
extra/europa/Assembly.hh
extra/europa.old/Assembly.hh
extra/europa2.old/Assembly.hh
extra/europa2.old/old/Assembly.hh
extra/europa/Assembly.cc
extra/europa.old/Assembly.cc
extra/europa2.old/Assembly.cc
extra/europa2.old/old/Assembly.cc