trex: TREX::agent::StepClock Class Reference
TREX::agent::StepClock Class Reference
TREX agent
Step based pseudo clock.
#include <trex/agent/StepClock.hh>
Public Types
typedef
TREX::utils::XmlFactory< Clock > xml_factory
XML factory for clocks.
Public Member Functions
void doStart ()
Start the clock.
TREX::transaction::TICK getNextTick ()
get current tick date This method advances the number of steps used in current tick by 1. If this number is greater or equal to the maximum number of steps allowed for this tick, then the tick date is incremented
virtual TREX::transaction::TICK initialTick () const
Initial tick.
void setMaxSteps (unsigned int nSteps) const
Change maximum number of steps for this tick.
virtual void sleep () const
Sleep until next tick.
StepClock (double sleepSeconds, unsigned int stepsPerTick)
Constructor.
StepClock (boost::property_tree::ptree::value_type &node)
XML parsing constructor.
virtual double tickDuration () const
tick duration
virtual double tickToTime (TREX::transaction::TICK cur) const
virtual TREX::transaction::TICK timeToTick (time_t secs, suseconds_t usecs=0) const
~StepClock ()
Destructor.
Static Public Member Functions
static void sleep (double sleepDuration)
Process sleep.
Protected Member Functions
void advanceTick (TREX::transaction::TICK &tick)
increment tick value
virtual double getSleepDelay () const
Time left before next tick.
virtual void start ()
Internal start method.
Related Functions
(Note that these are not member functions.)
Clock::xml_factory::declare
< StepClock > decl ("StepClock")
Clock XML factor declaration for StepClock.
Detailed Description
Step based pseudo clock.
This class implements a TREX clock that advances based on the number of steps used. This number of step can be modified for each tick allowing to reproduce a mission with similar CPU resource as it was during the previous run.
Note:
As this clock is just based on counting steps it is not real-time dependent and can go as fast as the host CPU allows or be paused if needed.
Author:
Conor McGann & Frederic Py fpy@m.nosp@m.bari.nosp@m..org
Definition at line 68 of file StepClock.hh.
Constructor & Destructor Documentation
StepClock::StepClock (double sleepSeconds, unsigned int stepsPerTick)
Constructor.
Parameters:
sleepSeconds how long should the process sleep
stepsPerTick default maximum number of steps per tick
Definition at line 90 of file StepClock.cc.
StepClock::StepClock (boost::property_tree::ptree::value_type & node)
XML parsing constructor.
Parameters:
node A XML clock definition
Create a new instance based on the constent of node. The expected structure of node is
 <StepClock steps="<number>"/>
where <number> is the default number of steps per tick.
Note:
If the steps attribute is not given its value is set to a default of 50
Exceptions:
TREX::utils::bad_string_cast unable to parse steps attribute
Definition at line 96 of file StepClock.cc.
Member Function Documentation
void Clock::advanceTick (TREX::transaction::TICK & tick) [protected, inherited]
increment tick value
Parameters:
tick A tick variable
increase the value of tick by 1
Deprecated:
This method was used for computing extra stats. We need to find a better approach. Specifically it would be relevant to have the tick variable located on this class.
Definition at line 76 of file Clock.cc.
Referenced by getNextTick().
void Clock::doStart () [inherited]
Start the clock.
This method is the public interface used to start the clock.
See also:
void start()
Definition at line 71 of file Clock.cc.
Referenced by TREX::agent::Agent::initComplete().
TICK StepClock::getNextTick () [virtual]
get current tick date This method advances the number of steps used in current tick by 1. If this number is greater or equal to the maximum number of steps allowed for this tick, then the tick date is incremented
Returns:
current tick date
See also:
setMaxSteps(unsigned int) const
Implements TREX::agent::Clock.
Definition at line 102 of file StepClock.cc.
References TREX::agent::Clock::advanceTick().
virtual double TREX::agent::Clock::getSleepDelay () const [inline, protected, virtual, inherited]
Time left before next tick.
This method indicates how much time is left before the next tick
Returns:
time left before next tick
Definition at line 141 of file Clock.hh.
virtual TREX::transaction::TICK TREX::agent::Clock::initialTick () const [inline, virtual, inherited]
Initial tick.
Returns:
the value of the initial tick
Definition at line 89 of file Clock.hh.
void StepClock::setMaxSteps (unsigned int nSteps) const
Change maximum number of steps for this tick.
Parameters:
nSteps New maximum number of steps
Precondition:
nSteps is greater than 0
Change the maximum number of steps for current tick to nSteps and reset the number of steps used to 0.
Definition at line 114 of file StepClock.cc.
void Clock::sleep () const [virtual, inherited]
Sleep until next tick.
This method check the time left before next tick and put the process asleep for this duration.
Exceptions:
ErrnoExcept An error occurred while trying to sleep
See also:
double getSleepDelay() const
void sleep(double)
Definition at line 83 of file Clock.cc.
Referenced by TREX::agent::Agent::doNext().
void Clock::sleep (double sleepDuration) [static, inherited]
Process sleep.
Parameters:
sleepDuration number of seconds to sleep
This methods make the calling process to sleep for sleepDuration seconds
Exceptions:
ErrnoExcept An error occurred while trying to sleep
Definition at line 51 of file Clock.cc.
virtual void TREX::agent::Clock::start () [inline, protected, virtual, inherited]
Internal start method.
This method is called internally by doStart to allow specialized initialization before starting the clock.
See also:
void doStart()
Definition at line 159 of file Clock.hh.
virtual double TREX::agent::Clock::tickDuration () const [inline, virtual, inherited]
tick duration
This methods return the TICK duration. It is expected to be in seconds
Returns:
tick duration
Reimplemented in TREX::agent::RealTimeClock.
Definition at line 98 of file Clock.hh.
Referenced by TREX::agent::Agent::tickDuration().
The documentation for this class was generated from the following files:
trex/agent/StepClock.hh
trex/agent/StepClock.cc