trex: TREX::startrex::Auv Class Reference
TREX::startrex::Auv Class Reference
The lightswitch plug-in
Auv reactor definition.
#include <extra/starfish/StarTrex.hh>
Public Types
typedef details::external external_iterator
Iterator other external timelines.
typedef details::relation_iter internal_iterator
typedef graph::reactor_id ref_type
Reactor reference type.
typedef size_t size_type
size type
typedef xml_factory::argument_type xml_arg_type
XML construction info.
typedef graph::xml_factory xml_factory
XML based factory.
Public Member Functions
Auv (TREX::transaction::TeleoReactor::xml_arg_type arg)
XML constructor.
size_type count_externals () const
Number of External timelines.
size_type count_internal_relations () const
Count the number of internal relations.
size_type count_internals () const
Count the number of internal timelines.
bool doSynchronize ()
Synchronization callback.
external_iterator ext_begin ()
beginning of External timelines set
external_iterator ext_end ()
end of External timelines set
TREX::utils::Symbol const & getAgentName () const
get "agent" name
TICK getCurrentTick () const
Get current tick.
TICK getExecLatency () const
reactor execution latency
TICK getFinalTick () const
Get final tick.
graph const & getGraph () const
Get graph.
TREX::utils::Symbol const & getGraphName () const
Get graph name.
TICK getInitialTick () const
reactor initial tick
TICK getLatency () const
reactor latency
TICK getLookAhead () const
Get reactor look-ahead.
TREX::utils::Symbol const & getName () const
Reactor name.
bool initialize (TICK final)
Final initialization.
internal_iterator int_begin () const
First internal relation iterator.
internal_iterator int_end () const
Last internal relation iterator.
bool newTick ()
New tick notification callback.
virtual void notify (Observation const &obs)
void step ()
Deliberation step.
double tickDuration () const
Tick duration.
double tickToTime (TICK cur) const
tick to unix time conversion
TICK timeToTick (time_t secs, suseconds_t usecs=0) const
unix time to tick conversion
double workRatio ()
reactor deliberation work load
~Auv ()
Destructor.
Protected Member Functions
virtual void cancelledPlanToken (goal_id const &t)
void cancelPlanToken (goal_id const &g)
bool completedGoal (goal_id g)
Goal completion.
virtual bool failed_external (TREX::utils::Symbol const &timeline, graph::timeline_failure const &err)
Request for external failed.
virtual bool failed_internal (TREX::utils::Symbol const &timeline, graph::timeline_failure const &err)
Request for internal failed.
external_iterator find_external (TREX::utils::Symbol const &name)
Find an external timeline.
virtual void handleTickStart ()
New tick callback.
virtual bool hasWork ()
Check if need to deliberate.
bool isExternal (TREX::utils::Symbol const &timeline) const
Check for exeternal timeline.
bool isInternal (TREX::utils::Symbol const &timeline) const
Check for internal timeline.
TREX::utils::LogManager & manager () const
LogManager acces point.
virtual void newPlanToken (goal_id const &t)
bool postGoal (goal_id const &g)
Post a goal.
goal_id postGoal (Goal const &g)
Post a goal.
void postObservation (Observation const &o)
Produce an observation.
bool postPlanToken (goal_id const &g)
Post a planned token.
goal_id postPlanToken (Goal const &g)
Post a planned token.
bool postRecall (goal_id const &g)
Recall a goal.
void provide (TREX::utils::Symbol const &timeline, bool controllable=true, bool publish=false)
Internal timeline declaration.
virtual void resume ()
Deliberation step callback.
TREX::utils::internals::LogEntry syslog (std::string const &context=std::string())
new log entry
void use (TREX::utils::Symbol const &timeline, bool control=true, bool plan_listen=false)
External timeline declaration.
Friends
class details::external
class details::timeline
Detailed Description
Auv reactor definition.
This class implements a very simple reactor that emulates a light switch. It provides a light timeline that can be either on (Auv.On) or off (Auv.Off)
Author:
Frederic Py fpy@m.nosp@m.bari.nosp@m..org
Definition at line 70 of file StarTrex.hh.
Member Typedef Documentation
typedef details::external TREX::transaction::TeleoReactor::external_iterator [inherited]
Iterator other external timelines.
The type used to iterate other the external timlines of a reactor. This is mostly used by the boost graph library.
Definition at line 434 of file TeleoReactor.hh.
typedef graph::reactor_id TREX::transaction::TeleoReactor::ref_type [inherited]
Reactor reference type.
The type used to refer to specific reactor
Definition at line 98 of file TeleoReactor.hh.
typedef size_t TREX::transaction::TeleoReactor::size_type [inherited]
size type
The type used to return a size such the number of External timleines of a reactor
Definition at line 440 of file TeleoReactor.hh.
typedef xml_factory::argument_type TREX::transaction::TeleoReactor::xml_arg_type [inherited]
XML construction info.
The argument passed by xml_factory while calling reactor classes constructor. This type is not a simple rapidxml::xml_node<> but also embeds a reference to the graph that the newly created instance will be attached to.
See also:
TREX::utils::XmlFactory
TREX::utils::XmlFactory::arg_traits;
TREX::transaction::graph
Definition at line 115 of file TeleoReactor.hh.
typedef graph::xml_factory TREX::transaction::TeleoReactor::xml_factory [inherited]
XML based factory.
The type of the factory used to generate reactors from XML
Definition at line 103 of file TeleoReactor.hh.
Constructor & Destructor Documentation
Auv::Auv (TREX::transaction::TeleoReactor::xml_arg_type arg)
XML constructor.
Parameters:
arg An XML node definition
This constructor is called to generate a Auv reactor based on an XML node. The expected XML format is the following:
 <Auv name="<name>" latency="<int>" lookahead="<int>" state="<bool>"
        verbose="<bool>" />
Where :
state is a boolean value indicating which is the initial state of the light timeline (default is true)
verbose is a boolean used to indicate whther we should repeat the light state at every tick or not (default is false)
Definition at line 82 of file StarTrex.cc.
References TREX::transaction::TeleoReactor::provide(), and TREX::transaction::TeleoReactor::syslog().
Member Function Documentation
bool TREX::transaction::TeleoReactor::completedGoal (goal_id g) [protected, inherited]
Goal completion.
Parameters:
[in] g A goal
This method can be used from the reactor to inform the goal management system that the goal g on one of its external timeline has completed
Deprecated:
This method should become useless as the goal management system is much more able to identify that a goal did complete
size_type TREX::transaction::TeleoReactor::count_externals () const [inline, inherited]
Number of External timelines.
Returns:
the number of External timelines on this reactor
Definition at line 446 of file TeleoReactor.hh.
TeleoReactor::size_type TeleoReactor::count_internal_relations () const [inherited]
Count the number of internal relations.
This method count the number of relations that this reactor have with other reactors issued from its internla timelines.
This number does not count the number of internal timelines but the sum of all the reactors that are connected to this reactor through its internal timelines
Definition at line 259 of file TeleoReactor.cc.
References TREX::utils::list_set< IdTraits, Cmp >::begin(), and TREX::utils::list_set< IdTraits, Cmp >::end().
size_type TREX::transaction::TeleoReactor::count_internals () const [inline, inherited]
Count the number of internal timelines.
This methods indicates the number of internal timelines this reactor currently owns
Returns:
the number of internla timleins of this reactor
See also:
count_internal_relations() const
Definition at line 475 of file TeleoReactor.hh.
References TREX::utils::list_set< IdTraits, Cmp >::size().
bool TeleoReactor::doSynchronize () [inherited]
Synchronization callback.
This method is called by the agent to make the reactor execute its synchronization. It will call synchronize callback and returns then status of the reactor according to the execution of this call.
Return values:
true synchronization successfull
false the call to synchronize returned false or thew an exception
Warning:
when this method returns false this reflect a critical reactor failure. Therefre the agent will kill this reactor and produce the observation Failed on each of its Internal timeline.
See also:
synchronize()
Definition at line 506 of file TeleoReactor.cc.
References TREX::utils::list_set< IdTraits, Cmp >::begin(), TREX::utils::list_set< IdTraits, Cmp >::clear(), TREX::utils::list_set< IdTraits, Cmp >::end(), TREX::transaction::TeleoReactor::synchronize(), and TREX::transaction::TeleoReactor::syslog().
details::external TeleoReactor::ext_begin () [inherited]
beginning of External timelines set
Returns:
An iterator pointing to the beginning of the External timelines set for this reactor
See also:
ext_end()
Definition at line 276 of file TeleoReactor.cc.
Referenced by TREX::transaction::TeleoReactor::newTick(), and TREX::transaction::TeleoReactor::workRatio().
details::external TeleoReactor::ext_end () [inherited]
end of External timelines set
Returns:
An iterator pointing to the end of the External timelines set for this reactor
See also:
ext_begin()
Definition at line 280 of file TeleoReactor.cc.
virtual bool TREX::transaction::TeleoReactor::failed_external (TREX::utils::Symbol const & timeline, graph::timeline_failure const & err) [inline, protected, virtual, inherited]
Request for external failed.
Parameters:
[in] timeline Symbolic name of the timeline
[in] err Descriptor of the error
This callback is executed when an attempt to use the External timeline timeline triggered an error. The reason of the failure is described by err. It can be derived in order to provide an alternate way to handle this failed request
See also:
failed_internal(TREX::utils::symbol const &, graph::timeline_failure const &)
Definition at line 834 of file TeleoReactor.hh.
virtual bool TREX::transaction::TeleoReactor::failed_internal (TREX::utils::Symbol const & timeline, graph::timeline_failure const & err) [inline, protected, virtual, inherited]
Request for internal failed.
Parameters:
[in] timeline Symbolic name of the timeline
[in] err Descriptor of the error
This callback is executed when an attempt to prtovide the Internal timeline timeline triggered an error. The reason of the failure is described by err. It can be derived in order to provide an alternate way to handle this failed request
See also:
failed_external(TREX::utils::symbol const &, graph::timeline_failure const &)
Definition at line 851 of file TeleoReactor.hh.
details::external TeleoReactor::find_external (TREX::utils::Symbol const & name) [protected, inherited]
Find an external timeline.
Parameters:
[in] name hte name of the timeline
Returns:
An iterator refering to the external timeline name or ext_end() if this reactor does not subscribe to name
Definition at line 284 of file TeleoReactor.cc.
Referenced by TREX::europa::EuropaReactor::hasWork().
TREX::utils::Symbol const& TREX::transaction::TeleoReactor::getAgentName () const [inline, inherited]
get "agent" name
Gets the name of the agent that controls this reactor.
Deprecated:
reactors are now manipulated by a graph. The agent uses this graph to trigger reactor's callbacks based on graph traversal algorithms. A graph is a more general concept thatn an agent (for example a graph could allow to have cyclic dependencies between reactors ...) to reflect this change this method has been replaced by getGraphName() and kept for backward compatibility.
Returns:
the name of the "agent"
See also:
getGraphName() const
Definition at line 187 of file TeleoReactor.hh.
References TREX::transaction::TeleoReactor::getGraphName().
TICK TREX::transaction::TeleoReactor::getCurrentTick () const [inline, inherited]
Get current tick.
Returns:
current tick date
See also:
getInitialTick() const
getFinalTick()
graph::getInitialTick() const
Definition at line 281 of file TeleoReactor.hh.
References TREX::transaction::graph::getCurrentTick().
Referenced by TREX::europa::EuropaReactor::hasWork(), TREX::transaction::TeleoReactor::initialize(), TREX::transaction::TeleoReactor::newTick(), TREX::transaction::TeleoReactor::postObservation(), TREX::transaction::TeleoReactor::postPlanToken(), and TREX::transaction::TeleoReactor::workRatio().
TICK TREX::transaction::TeleoReactor::getExecLatency () const [inline, inherited]
reactor execution latency
Indicates the reactor execution latency. This value correspond to the delay it take s for thsi reactor to start executing its plan. It is function of the execution latency of the reactors it depends on and is updated automatically by the reactors graph.
This value is used by TREX and represent this reactor's dispatch window lowe bound.
Returns:
the reactor's execution latency
See also:
getLatency() const
Definition at line 327 of file TeleoReactor.hh.
Referenced by TREX::transaction::TeleoReactor::initialize(), and TREX::transaction::details::timeline::latency().
TICK TREX::transaction::TeleoReactor::getFinalTick () const [inline, inherited]
Get final tick.
Identify the agent final tick. This value correspond to the maximum possible life-time of the agent.
@ pre the reactor is initialized
Returns:
mission final tick
See also:
initialize()
getInitialTick() const
getCurrentTick() const
Definition at line 297 of file TeleoReactor.hh.
graph const& TREX::transaction::TeleoReactor::getGraph () const [inline, inherited]
Get graph.
This methods gives a reference to the graph that manage this reactor
Returns:
the graph
See also:
getGraphName() const
Definition at line 206 of file TeleoReactor.hh.
TREX::utils::Symbol const& TREX::transaction::TeleoReactor::getGraphName () const [inline, inherited]
Get graph name.
Returns:
the name of the graph that maintins this reactor relations
See also:
class TREX::transaction::graph
Definition at line 196 of file TeleoReactor.hh.
References TREX::transaction::graph::getName().
Referenced by TREX::transaction::TeleoReactor::getAgentName().
TICK TREX::transaction::TeleoReactor::getInitialTick () const [inline, inherited]
reactor initial tick
This method indicates the tick during which the reactor has been initialized.
Precondition:
the reactor has bein initialized
Returns:
the tick during which the reactor got started
See also:
handleInit()
getCurrentTick() const
getFinalTick() const
Definition at line 223 of file TeleoReactor.hh.
Referenced by TREX::transaction::TeleoReactor::initialize().
TICK TREX::transaction::TeleoReactor::getLatency () const [inline, inherited]
reactor latency
Indicates the reactor deliberation latency. Thids vlaue reflects the exstimated maximum delay this reactor needs to produce a new plan and is usually provided by the user during agent definition
Returns:
the reactor's latency
See also:
getExecLatency() const
Definition at line 310 of file TeleoReactor.hh.
Referenced by TREX::transaction::TeleoReactor::workRatio().
TICK TREX::transaction::TeleoReactor::getLookAhead () const [inline, inherited]
Get reactor look-ahead.
Indicates how many ticks the reactors look ahead while planning. A value of 0 indicates that this reactor does not accept goal.
Returns:
the reactor look-ahead
Definition at line 337 of file TeleoReactor.hh.
Referenced by TREX::transaction::details::timeline::look_ahead().
TREX::utils::Symbol const& TREX::transaction::TeleoReactor::getName () const [inline, inherited]
Reactor name.
Returns:
the anme of the reactor
Definition at line 168 of file TeleoReactor.hh.
Referenced by TREX::transaction::Player::Player(), TREX::transaction::TeleoReactor::syslog(), and TREX::transaction::TeleoReactor::TeleoReactor().
virtual void TREX::transaction::TeleoReactor::handleTickStart () [inline, protected, virtual, inherited]
New tick callback.
This call back is executed at the beginning of a new tick. and can be used for the reactor to prepare for synchronization. It is also often used by the reactor to post its new goals.
Note:
at this stage the reactor should have received all the new goals for this tick. but this is not guaranteed.
Warning:
the duration of this call should be neglectable in comparison to the tick duration.
Reimplemented in TREX::europa::EuropaReactor.
Definition at line 717 of file TeleoReactor.hh.
Referenced by TREX::transaction::TeleoReactor::newTick().
virtual bool TREX::transaction::TeleoReactor::hasWork () [inline, protected, virtual, inherited]
Check if need to deliberate.
This method is called during workRatio in order to idenitfy if the reactor needs to deliberate.
By default it always return 0 and need to be redefined by derived classes if they need to deliberate.
Return values:
true this instance needs to deliberate
false this instance does not require deliberation
If the methods returns true this will eventually result on the agent calling the step() method
See also:
workRatio()
step()
Reimplemented in TREX::europa::EuropaReactor.
Definition at line 546 of file TeleoReactor.hh.
Referenced by TREX::transaction::TeleoReactor::workRatio().
bool TeleoReactor::initialize (TICK final) [inherited]
Final initialization.
Parameters:
[in] final The final tick date
Precondition:
getCurrentTick() < final
the reactor has not been inited yet
This method is called by the agent to allow the reactor to complete its initialization. At this stage the treactor knwos that it is part of the reactor graph and can complete its initialisation if needed. During this call, the callback handleInit will be executed allowing to execute reactors spacific initializations
Exceptions:
ReactorException Attempted to call this method twice
Postcondition:
The reactor is ready to be executed in the agent
See also:
handleInit()
getInitialTick() const
getCurrentTick() const
Definition at line 431 of file TeleoReactor.cc.
References TREX::transaction::TeleoReactor::getCurrentTick(), TREX::transaction::TeleoReactor::getExecLatency(), TREX::transaction::TeleoReactor::getInitialTick(), TREX::transaction::TeleoReactor::handleInit(), and TREX::transaction::TeleoReactor::syslog().
internal_iterator TREX::transaction::TeleoReactor::int_begin () const [inline, inherited]
First internal relation iterator.
See also:
count_internal_relations() const
int_end() const
Definition at line 494 of file TeleoReactor.hh.
References TREX::utils::list_set< IdTraits, Cmp >::begin(), and TREX::utils::list_set< IdTraits, Cmp >::end().
internal_iterator TREX::transaction::TeleoReactor::int_end () const [inline, inherited]
Last internal relation iterator.
See also:
count_internal_relations() const
int_begin() const
Definition at line 502 of file TeleoReactor.hh.
References TREX::utils::list_set< IdTraits, Cmp >::end().
bool TeleoReactor::isExternal (TREX::utils::Symbol const & timeline) const [protected, inherited]
Check for exeternal timeline.
Parameters:
[in] timeline A name
Return values:
true if timeline is External to this reactor
false otherwise
See also:
isInternal(TREX::utils::Symbol const &) const
use(TREX::utils::Symbol const &, bool)
Definition at line 272 of file TeleoReactor.cc.
bool TeleoReactor::isInternal (TREX::utils::Symbol const & timeline) const [protected, inherited]
Check for internal timeline.
Parameters:
[in] timeline A name
Return values:
true if timeline is Internal to this reactor
false otherwise
See also:
isExternal(TREX::utils::Symbol const &) const
provide(TREX::utils::Symbol const &)
Definition at line 268 of file TeleoReactor.cc.
References TREX::utils::list_set< IdTraits, Cmp >::end(), and TREX::utils::list_set< IdTraits, Cmp >::find().
Referenced by TREX::transaction::TeleoReactor::provide(), and TREX::transaction::TeleoReactor::use().
TREX::utils::LogManager& TREX::transaction::TeleoReactor::manager () const [inline, protected, inherited]
LogManager acces point.
Returns:
the LogManager instance for this run
Definition at line 525 of file TeleoReactor.hh.
Referenced by TREX::transaction::Player::Player(), and TREX::transaction::TeleoReactor::TeleoReactor().
bool TeleoReactor::newTick () [inherited]
New tick notification callback.
This method is called by the agent to notify the reactor that a new tick has started. It will call the handleTickStart() method
See also:
handleTickStart()
Definition at line 456 of file TeleoReactor.cc.
References TREX::transaction::details::external::dispatch(), TREX::transaction::TeleoReactor::ext_begin(), TREX::transaction::TeleoReactor::getCurrentTick(), TREX::transaction::TeleoReactor::handleTickStart(), TREX::transaction::TeleoReactor::syslog(), and TREX::transaction::details::external::valid().
virtual void TREX::transaction::TeleoReactor::notify (Observation const & obs) [inline, virtual, inherited]
New observation callback
Parameters:
[in] obs An observation
This method is called by the agent when one of the External timelines of this reactor changed state. The state is described by obs and satrts from the current tick.
It is guartanteed that all the notification of the current tick will be notified before the reactor synchronization
Warning:
the duration of this call should be neglectable in comparison to the tick duration.
See also:
synchronize()
Reimplemented in TREX::europa::EuropaReactor.
Definition at line 354 of file TeleoReactor.hh.
bool TeleoReactor::postGoal (goal_id const & g) [protected, inherited]
Post a goal.
Parameters:
[in] g A goal id
Post the goal g to an external timeline
Precondition:
g is a valid goal_id (i.e. not NULL)
g->object() is an External timeline of this reactor
Exceptions:
DispatchError The goal was not valid or was not on an external timeline of this reactor
Returns:
true the goal has been succesfully posted and is queued for dispatching
false this goal id is already in the dispatching queue
Note:
sucessfully posting a goal do not gauarantee that this goal will be duispatched and even less executed. It can be already too late to dispatch such a goal or the goal is simply impossible to be executed in current situation. As of today, the only way to check a goal has been executed is to wait for the corresponding observation unitl the maximum start time has been passed.
See also:
isExternal(TREX::utils::Symbol const &) const
postRecall(goal_id const &)
Definition at line 353 of file TeleoReactor.cc.
References TREX::transaction::details::external::post_goal().
Referenced by TREX::transaction::TeleoReactor::postGoal().
goal_id TeleoReactor::postGoal (Goal const & g) [protected, inherited]
Post a goal.
Parameters:
[in] g A goal
This method is just an overload of postGoal(goal_d const &) for user facility
Precondition:
g.object() is an External timeline
Exceptions:
DispatchError the goal wasn't on an External timeline
Returns:
the goal_id for this goal
See also:
postGoal(goal_id const &)
isExternal(TREX::utils::Symbol const &) const
Definition at line 368 of file TeleoReactor.cc.
References TREX::transaction::TeleoReactor::postGoal().
void TeleoReactor::postObservation (Observation const & o) [protected, inherited]
Produce an observation.
Parameters:
[in] o An observation
This method is a falcility to produce internally an observation o on one of the reactors Internal timeline.
It can be called internally to the reactor when a new state has been identified for this timeline.
Precondition:
o.object() is internal to this reactor
Postcondition:
Unless postObservation is called in between with an observation on the same object, the observation o will be dispatched to all the clients of o.object() during the next doNotify()
Exceptions:
SynchronizationError attempt to post an observation in a timeline which is not Internal to this reactor.
See also:
class Observation
isInternal(TREX::utils::Symbol const &) const
doNotify()
Definition at line 342 of file TeleoReactor.cc.
References TREX::utils::list_set< IdTraits, Cmp >::end(), TREX::utils::list_set< IdTraits, Cmp >::find(), TREX::transaction::TeleoReactor::getCurrentTick(), TREX::utils::list_set< IdTraits, Cmp >::insert(), TREX::transaction::Predicate::object(), and TREX::utils::BasicSymbol< CharT, Traits, Alloc >::str().
bool TeleoReactor::postPlanToken (goal_id const & g) [protected, inherited]
Post a planned token.
Parameters:
[in] g A goal id
Inform that the token g is now part of the plan of the reactor
Precondition:
g is a valid goal_id (i.e. not NULL)
g->object() is an Internal timeline of this reactor
Exceptions:
DispatchError The token was not valid or was not on an internal timeline of this reactor
Returns:
true the token has been correctly integrated.
false this token id is already broadcasted or its end time is in the past
See also:
isInternal(TREX::utils::Symbol const &) const
cancelPlanToken(goal_id const &)
Definition at line 393 of file TeleoReactor.cc.
References TREX::utils::list_set< IdTraits, Cmp >::end(), TREX::utils::list_set< IdTraits, Cmp >::find(), and TREX::transaction::TeleoReactor::getCurrentTick().
Referenced by TREX::transaction::TeleoReactor::postPlanToken().
goal_id TeleoReactor::postPlanToken (Goal const & g) [protected, inherited]
Post a planned token.
Parameters:
[in] g A goal
This method is just an overload of postPlanToken(goal_d const &) for user facility
Precondition:
g.object() is an Internal timeline of this reactor
Exceptions:
DispatchError The token was not on an internal timeline of this reactor
goal_id for the token posted. This id is invalid if the token was not posted
See also:
isInternal(TREX::utils::Symbol const &) const
postPlanToken(goal_id const &)
Definition at line 410 of file TeleoReactor.cc.
References TREX::transaction::TeleoReactor::postPlanToken().
bool TeleoReactor::postRecall (goal_id const & g) [protected, inherited]
Recall a goal.
Parameters:
[in] g A goal
This method recall the goal with the goal_id of g
Return values:
true the goal was sucessfully recalled
false the goal was not valid or is not on an External timeline
Note:
The goal_id g should be execatly the one passed to postGoal (or returned by it).
As for postGoal sucessfully recalling a goal does not mean that it will be removed from the plan of the owner of this timeline. It is more a way to indicate that this goal is not required anymore.
See also:
postGoal(goal_id const &)
postGoal(Goal const &)
isExternal(TREX::utils::Symbol const &) const
Definition at line 379 of file TeleoReactor.cc.
References TREX::transaction::details::external::recall().
void TeleoReactor::provide (TREX::utils::Symbol const & timeline, bool controllable = true, bool publish = false) [protected, inherited]
Internal timeline declaration.
Parameters:
[in] timeline a name
[in] controlable does this timeline accept goals
[in] publish does this timeline will publish its plan
This method is used to declare timeline as an Internal timeline.
Warning:
The type of a timeline can change during reactor execution and this is the reason why this methods give no feedback. It is always recommend to check the success/failure of this operation using isInternal
Note:
If the timlien was External and is not woned yet by any reactor, this call will promote it as Internal
See also:
isExternal(TREX::utils::Symbol const &) const
isInternal(TREX::utils::Symbol const &) const
graph::assign(graph::reactor_id, TREX::utils::Symbol const &)
use(TREX::utils::Symbol const &, bool)
Definition at line 559 of file TeleoReactor.cc.
References TREX::transaction::TeleoReactor::isInternal(), TREX::utils::BasicSymbol< CharT, Traits, Alloc >::str(), and TREX::transaction::TeleoReactor::syslog().
Referenced by Auv(), TREX::lightswitch::Light::Light(), and TREX::transaction::TeleoReactor::TeleoReactor().
virtual void TREX::transaction::TeleoReactor::resume () [inline, protected, virtual, inherited]
Deliberation step callback.
This callback will be executed in response of hasWork returning true. It allows the reactor to execute an atomic deliberation step.
Warning:
the duration of this call should be neglectable in comparison to the tick duration.
Reimplemented in TREX::europa::EuropaReactor.
Definition at line 748 of file TeleoReactor.hh.
Referenced by TREX::transaction::TeleoReactor::step().
void TeleoReactor::step () [inherited]
Deliberation step.
This method is aclled by the agent when it allows the reactor to do one deliberation step. It calls resume() and update informations in order to compute the reactors next work ratio
See also:
workRatio()
resume()
Definition at line 538 of file TeleoReactor.cc.
References TREX::transaction::TeleoReactor::resume().
TREX::utils::internals::LogEntry TREX::transaction::TeleoReactor::syslog (std::string const & context = std::string()) [inline, protected, inherited]
new log entry
Parameters:
[in] context log entry prefix
create a new entry in TREX.log
Returns:
a stream that can be used to qwrite in the entry
See also:
TREX::utils::LogManager
TREX::utils::TextLog
Definition at line 890 of file TeleoReactor.hh.
References TREX::transaction::TeleoReactor::getName().
Referenced by Auv(), TREX::transaction::TeleoReactor::doSynchronize(), TREX::europa::EuropaReactor::handleRequest(), TREX::europa::EuropaReactor::hasWork(), TREX::transaction::TeleoReactor::initialize(), TREX::lightswitch::Light::Light(), TREX::transaction::TeleoReactor::newTick(), TREX::europa::EuropaReactor::notify(), TREX::transaction::Player::Player(), TREX::transaction::TeleoReactor::provide(), TREX::transaction::details::timeline::request(), TREX::europa::EuropaReactor::resume(), TREX::europa::EuropaReactor::synchronize(), TREX::transaction::TeleoReactor::TeleoReactor(), TREX::transaction::TeleoReactor::use(), and TREX::transaction::TeleoReactor::workRatio().
double TREX::transaction::TeleoReactor::tickDuration () const [inline, inherited]
Tick duration.
Indicates the duration of the tick. This duration is expected to be expressed in seconds even though nothing in the architecture constraint such aspect.
Returns:
the duration of a single tick
Definition at line 234 of file TeleoReactor.hh.
References TREX::transaction::graph::tickDuration().
double TREX::transaction::TeleoReactor::tickToTime (TICK cur) const [inline, inherited]
tick to unix time conversion
Parameters:
[in] cur A tick value
Returns:
equivalent unix time to cur as a float
This method is an utility to ease the conversion form a tick to unix time it calls the agent clock corresponding method to convert the specified tick value into unix time
Note:
the result of the method depends on the clock implementation. For example the RealTimeClock fully support it while the StepClock will simply assume that unixtime and tick are perfeclty aligned (as if the mission started on January 1st 1970)
Definition at line 270 of file TeleoReactor.hh.
References TREX::transaction::graph::tickToTime().
TICK TREX::transaction::TeleoReactor::timeToTick (time_t secs, suseconds_t usecs = 0) const [inline, inherited]
unix time to tick conversion
Parameters:
[in] secs Number of seconds
[in] usecs Number of microseconds
Returns:
equivalent tick to the time secs.usecs
This method is an utility to ease the conversion form unix time to tick it calls the agent clock corresponding method to convert the specified unix time into a tick value
Note:
the result of the method depends on the clock implementation. For example the RealTimeClock fully support it while the StepClock will simply assume that unixtime and tick are perfeclty aligned (as if the mission started on January 1st 1970)
Definition at line 253 of file TeleoReactor.hh.
References TREX::transaction::graph::timeToTick().
void TeleoReactor::use (TREX::utils::Symbol const & timeline, bool control = true, bool plan_listen = false) [protected, inherited]
External timeline declaration.
Parameters:
[in] timeline a name
[in] control goal dispatching flag
[in] plan_listen plan listening flag
This method is used to declare timeline as an External timeline. The optional control flag prohibits goal dispatching to this timeline when false. The plan_listen flag aloow the reactor to be notified whenever the owner of this timeline does give the current tokens it has in his future plan
Precondition:
The timleine is not already Internal
Warning:
The type of a timeline can change during reactor execution and this is the reason why this methods give no feedback. It is always recommend to check the success/failure of this operation using isExternal
See also:
isExternal(TREX::utils::Symbol const &) const
isInternal(TREX::utils::Symbol const &) const
graph::subscribe(graph::reactor_id, TREX::utils::Symbol const &, details::transaction_flag const &)
provide(TREX::utils::Symbol const &)
Definition at line 545 of file TeleoReactor.cc.
References TREX::transaction::TeleoReactor::isInternal(), TREX::utils::BasicSymbol< CharT, Traits, Alloc >::str(), and TREX::transaction::TeleoReactor::syslog().
Referenced by TREX::transaction::TeleoReactor::TeleoReactor().
double TeleoReactor::workRatio () [inherited]
reactor deliberation work load
This method calls hasWork method and, depending on the returned value and how close the reactor is to reach is latency, will give a value indicating heurisitically how urgent it is for him to delinerate.
Returns:
a value that becomes larger as the reactor is approaching its latency deadline or NAN if hasWork() returned false
See also:
hasWork()
step()
Definition at line 299 of file TeleoReactor.cc.
References TREX::transaction::details::external::dispatch(), TREX::transaction::TeleoReactor::ext_begin(), TREX::transaction::TeleoReactor::getCurrentTick(), TREX::transaction::TeleoReactor::getLatency(), TREX::transaction::TeleoReactor::hasWork(), TREX::transaction::TeleoReactor::syslog(), and TREX::transaction::details::external::valid().
The documentation for this class was generated from the following files:
extra/starfish/StarTrex.hh
extra/starfish/StarTrex.cc