trex: TREX::transaction::Variable Class Reference
TREX::transaction::Variable Class Reference
Domains
TREX variable representation.
#include <trex/domain/Variable.hh>
Public Member Functions
void accept (DomainVisitor &visitor) const
DomainBase const & domain () const
Variable domain.
bool isComplete () const
Check for complete varaible definition.
TREX::utils::Symbol const & name () const
Variable name.
Variable & operator*= (DomainBase const &dom)
Restrict Variable domain.
Variable & operator*= (Variable const &var)
Merge variable.
Variable & operator= (Variable const &other)
Assignment operator.
Variable & restrict (DomainBase const &dom)
Restrict Variable domain.
Variable & restrict (Variable const &var)
Merge variable.
std::ostream & toXml (std::ostream &out, size_t pad=0) const
XML output.
template<class Ty >
Ty const & typedDomain () const
Variable domain.
Variable ()
Constructor.
Variable (TREX::utils::Symbol const &name, DomainBase const &domain)
Constructor.
Variable (Variable const &var)
Constructor.
Variable (boost::property_tree::ptree::value_type &node)
Constructor.
~Variable ()
Destructor.
Friends
class Predicate
std::ostream & std::operator<< (std::ostream &out, TREX::utils::ostreamable const &x)
Detailed Description
TREX variable representation.
This class implements a TREX variable. variables are used for representing any attribute of an Observation or Goal excahnged between reactors. They are represented by a symbolic name and its associated domain.
Author:
Frederic Py fpy@m.nosp@m.bari.nosp@m..org
Definition at line 90 of file Variable.hh.
Constructor & Destructor Documentation
Variable::Variable ()
Constructor.
Create an unnamed varaible with no domain.
Note:
This constructor is implemented only for allowing the support of the Varibale class for standard C++ containers. It should not be used by other components as it create an undefined variable
Definition at line 66 of file Variable.cc.
Variable::Variable (TREX::utils::Symbol const & name, DomainBase const & domain)
Constructor.
Parameters:
name A symbolic name
domain A domain
Create a new varaible named name with the domain domain
Precondition:
name should not be empty
Exceptions:
VariableException Tried to create a variable with an empty name
Definition at line 71 of file Variable.cc.
References TREX::utils::BasicSymbol< CharT, Traits, Alloc >::empty().
Variable::Variable (Variable const & var)
Constructor.
var Another instance
Create a copy of var
Definition at line 77 of file Variable.cc.
Variable::Variable (boost::property_tree::ptree::value_type & node)
Constructor.
Parameters:
node A XML node
Create a new instance by parsing the content of node. This content should be similar to the following
 <Variable name="<name>">
   domain
 </Variable>
Where <name> is a non empty string and domain is an XML domain description supported by DomainBase::xml_factory.
Exceptions:
Xmlerror name attribute was empty
XmlError domain was missing
XmlError An error occurred while parsing the domain
Definition at line 80 of file Variable.cc.
References TREX::utils::BasicSymbol< CharT, Traits, Alloc >::empty().
Member Function Documentation
DomainBase const & Variable::domain () const
Variable domain.
Precondition:
The variable is complete
Returns:
the domain of this variable
Exceptions:
VariableException the domain of this varaible is undefined
See also:
bool isComplete() const
template<class Ty> Ty const &typedDomain() const
Definition at line 128 of file Variable.cc.
Referenced by TREX::transaction::Goal::listAttributes(), TREX::transaction::Goal::restrictTime(), and typedDomain().
bool TREX::transaction::Variable::isComplete () const [inline]
Check for complete varaible definition.
This method checks if current instance is fully defined with a correct name and domain.
Return values:
true if fully defined
false else
Definition at line 149 of file Variable.hh.
References TREX::utils::BasicSymbol< CharT, Traits, Alloc >::empty().
Referenced by TREX::transaction::Predicate::restrictAttribute().
TREX::utils::Symbol const& TREX::transaction::Variable::name () const [inline]
Variable name.
Returns:
the name of this variable
See also:
bool isComplete() const
Definition at line 168 of file Variable.hh.
Referenced by TREX::transaction::Predicate::restrictAttribute(), and TREX::transaction::Goal::restrictAttribute().
Variable& TREX::transaction::Variable::operator*= (DomainBase const & dom) [inline]
Restrict Variable domain.
Parameters:
dom a domain
This method attempts to restrict current variable domain with dom. The resulting domain should be the intersection of dom with the current variable domain or simpluy a copy of dom if this varaible had no associated domain yet
Exceptions:
EmptyDomain the resulting domain is empty
Returns:
current instance after the operation
See also:
DomainBase &DomainBase::restrictWith(DomainBase const &)
Definition at line 236 of file Variable.hh.
References restrict().
Variable& TREX::transaction::Variable::operator*= (Variable const & var) [inline]
Merge variable.
Parameters:
var another variable
This method tries to merge current insatnce with var
Precondition:
var should have the same name and domain type as current instance or one of them should not be complete
Exceptions:
VariableException the 2 variables does not have the same name
EmptyDomain the intersection of current instance domain with var domain is empty
Returns:
current insatnce after being merged with var
See also:
DomainBase &DomainBase::restrictWith(DomainBase const &)
Definition at line 266 of file Variable.hh.
References restrict().
Variable & Variable::operator= (Variable const & other)
Assignment operator.
Parameters:
other Another instance
This method copy the value of other in current instance.
Returns:
current instance after operation
Definition at line 94 of file Variable.cc.
Variable & Variable::restrict (DomainBase const & dom)
Restrict Variable domain.
Parameters:
dom a domain
This method attempts to restrict current variable domain with dom. The resulting domain should be the intersection of dom with the current variable domain or simpluy a copy of dom if this varaible had no associated domain yet
Exceptions:
EmptyDomain the resulting domain is empty
Returns:
current instance after the operation
See also:
DomainBase &DomainBase::restrictWith(DomainBase const &)
Definition at line 100 of file Variable.cc.
References TREX::transaction::DomainBase::copy().
Referenced by operator*=(), restrict(), and TREX::transaction::Goal::restrictTime().
Variable & Variable::restrict (Variable const & var)
Merge variable.
Parameters:
var another variable
This method tries to merge current insatnce with var
Precondition:
var should have the same name and domain type as current instance or one of them should not be complete
Exceptions:
VariableException the 2 variables does not have the same name
EmptyDomain the intersection of current instance domain with var domain is empty
Returns:
current insatnce after being merged with var
See also:
DomainBase &DomainBase::restrictWith(DomainBase const &)
Definition at line 108 of file Variable.cc.
References TREX::utils::BasicSymbol< CharT, Traits, Alloc >::empty(), and restrict().
std::ostream & Variable::toXml (std::ostream & out, size_t pad = 0) const
XML output.
Parameters:
out An output stream
pad desired tag indentation
This method writes in out an XML representation of current instance with an indentation of pad
Returns:
out after the operation
Definition at line 141 of file Variable.cc.
template<class Ty > Ty const& TREX::transaction::Variable::typedDomain () const [inline]
Variable domain.
Template Parameters:
Ty Expected type of the domain
This method tries to return the domain of the Variable as a const reference to Ty
Precondition:
Ty should inherit from DomainBase
Ty should be a base class of the domain associted to this Variable
The variable is complete
Exceptions:
VariableException the domain of this variable is undefined
std::bad_cast Ty is not the correct domain
Note:
We use boost utilities to check that Ty inherits from DomainBase. This allows to detect a mistke on compilation time.
See also:
bool isComplete() const
DomainBase &domain() const
Definition at line 199 of file Variable.hh.
References domain().
Referenced by TREX::transaction::Predicate::getDomain(), TREX::transaction::Goal::getDuration(), TREX::transaction::Goal::getEnd(), TREX::transaction::Goal::getStart(), TREX::transaction::Goal::restrictAttribute(), TREX::transaction::Goal::restrictTime(), and TREX::transaction::Goal::startsAfter().
The documentation for this class was generated from the following files:
trex/domain/Variable.hh
trex/domain/Variable.cc