trex: TREX::transaction::BasicEnumerated Class Reference
TREX::transaction::BasicEnumerated Class Reference
[Domains]
Enumerated Domain base class.
#include <trex/domain/BasicEnumerated.hh>
Public Types
typedef
TREX::utils::XmlFactory
< DomainBase,
boost::shared_ptr< DomainBase > > xml_factory
XML parsing factory for domains.
Public Member Functions
virtual DomainBase * copy () const =0
Duplicate method.
virtual bool equals (DomainBase const &other) const =0
Equality test.
virtual boost::any getElement (size_t i) const =0
generic element access
boost::any getSingleton () const
singleton value
virtual size_t getSize () const =0
element count
std::string getStringSingleton () const
singleton value
virtual std::string getStringValue (size_t i) const
Get element textual value.
template<class Ty , bool Safe>
Ty getTypedElement (size_t n) const
Typed element access.
template<class Ty , bool Safe>
Ty getTypedSingleton () const
singleton value
TREX::utils::Symbol const & getTypeName () const
type of the domain
virtual bool intersect (DomainBase const &other) const =0
check for common values
bool isEnumerated () const
Check for enumerated domain.
bool isFull () const
check for full domain
bool isInterval () const
Check for interval domain.
bool isSingleton () const
check for singleton value
DomainBase & operator*= (DomainBase const &other)
Restrict domain possible values.
boost::any operator[] (size_t i) const
virtual DomainBase & restrictWith (DomainBase const &other)=0
Restrict domain possible values.
std::ostream & toXml (std::ostream &out, size_t tabs) const
XML conversion.
virtual ~BasicEnumerated ()
Destructor.
Protected Member Functions
virtual void addTextValue (std::string const &val)=0
BasicEnumerated (boost::property_tree::ptree::value_type &node)
BasicEnumerated (TREX::utils::Symbol const &type)
void completeParsing (boost::property_tree::ptree::value_type &node)
virtual std::ostream & print_value (std::ostream &out, size_t i) const =0
Friends
std::ostream & std::operator<< (std::ostream &out, TREX::utils::ostreamable const &x)
Detailed Description
Enumerated Domain base class.
This class provide a unified abstract interface for implementing enumerated domains. It especially provide a way to ease and unify the access methods and input/output for all the domain of this kind.
Author:
Frederic Py <fpy@mbari.org>
Definition at line 62 of file BasicEnumerated.hh.
Member Typedef Documentation
typedef TREX::utils::XmlFactory<DomainBase, boost::shared_ptr<DomainBase> > TREX::transaction::DomainBase::xml_factory [inherited]
XML parsing factory for domains.
This type defines the factory that should be manipulated for parsing domains from xml.
Definition at line 403 of file DomainBase.hh.
Member Function Documentation
virtual DomainBase* TREX::transaction::DomainBase::copy () const [pure virtual, inherited]
Duplicate method.
Create a new instance which is identical to current instance value. This instance is usually created using the new operator and it is up to the caller to de-allocate it when not needed.
Returns:
The newly created instance
Implemented in TREX::europa::EuropaDomain, TREX::europa::EuropaEntity, TREX::europa::EuropaEntity, TREX::europa::EuropaProxy, TREX::europa::EuropaEntity, TREX::europa::ProxyDomain, TREX::europa::EuropaEntity, TREX::europa::EuropaProxy, TREX::transaction::BooleanDomain, TREX::transaction::EnumDomain, TREX::transaction::FloatDomain, TREX::transaction::IntegerDomain, and TREX::transaction::StringDomain.
Referenced by TREX::transaction::Variable::restrict().
virtual bool TREX::transaction::DomainBase::equals (DomainBase const & other) const [pure virtual, inherited]
Equality test.
Parameters:
other Another instance
Checks if current instance is identical to other. This generally means that both have the same type and exactly the same possible values. In that sense it is more restrictive than the intersect method.
Return values:
true if current instance is identical to other
false otherwise
See also:
bool intersect(DomainBase const &other) const
Implemented in TREX::europa::EuropaDomain, TREX::europa::EuropaProxy, TREX::europa::ProxyDomain, TREX::europa::EuropaProxy, TREX::transaction::BooleanDomain, TREX::transaction::EnumeratedDomain< Ty, Comp >, TREX::transaction::IntervalDomain< Ty, Comp >, TREX::transaction::EnumeratedDomain< std::string >, TREX::transaction::EnumeratedDomain< TREX::utils::Symbol >, TREX::transaction::IntervalDomain< long >, and TREX::transaction::IntervalDomain< double >.
Referenced by TREX::transaction::Goal::listAttributes().
boost::any TREX::transaction::BasicEnumerated::getElement (size_t i) const [pure virtual]
generic element access
Parameters:
i index of the element
This method give access to the element i of the domain.
Precondition:
i is less than the size of the set
Returns:
the element at index i encapsulated on the boost::any class
See also:
size_t getSize() const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Implemented in TREX::transaction::EnumeratedDomain< Ty, Comp >, TREX::transaction::EnumeratedDomain< std::string >, and TREX::transaction::EnumeratedDomain< TREX::utils::Symbol >.
Referenced by getTypedElement().
boost::any DomainBase::getSingleton () const [inherited]
singleton value
This methods give acces to the value of a singleton instance.
Precondition:
the instance is a singleton
Exceptions:
DomainAccess the insatnce was not a singleton
Returns:
The value of the domain encapsulated in a boost::any
Note:
except for the control of the instance being a singleton the actual code of this method will be provided by the virtual method singleton()
See also:
boost::any singleton() const
getStringSingleton() const
getTypedSingleton() const
Definition at line 56 of file DomainBase.cc.
References TREX::transaction::DomainBase::isSingleton(), and TREX::transaction::DomainBase::singleton().
virtual size_t TREX::transaction::BasicEnumerated::getSize () const [pure virtual]
element count
This method gives access to the number of elements in this instance.
Returns:
the number of values associated to this domain
Note:
by convention if the returned value is 0, TREX will consider this domain as full
Implemented in TREX::transaction::EnumeratedDomain< Ty, Comp >, TREX::transaction::EnumeratedDomain< std::string >, and TREX::transaction::EnumeratedDomain< TREX::utils::Symbol >.
Referenced by isFull(), isSingleton(), toXml(), and TREX::europa::details::europa_domain::visit().
std::string DomainBase::getStringSingleton () const [inherited]
singleton value
This methods give acces to the value of a singleton instance represented as a string
Precondition:
the instance is a singleton
Exceptions:
DomainAccess the insatnce was not a singleton
Returns:
The text representation of the singleton value
Note:
except for the control of the instance being a singleton the actual code of this method will be provided by the virtual method stringSingleton()
See also:
std::string stringSingleton() const
getStringSingleton() const
getTypedSingleton() const
Definition at line 62 of file DomainBase.cc.
References TREX::transaction::DomainBase::isSingleton(), and TREX::transaction::DomainBase::stringSingleton().
std::string BasicEnumerated::getStringValue (size_t i) const [virtual]
Get element textual value.
Parameters:
[in] i Index of the element
Get the value of the element i of the domain in its textual form
Precondition:
i is a valid index (between 0 and the size of the set-1)
Returns:
A string with a human readable for the value of the element i
See also:
getSize() const
getElement(size_t) const
getTypedElement(size_t) const
Definition at line 68 of file BasicEnumerated.cc.
Referenced by getTypedElement(), toXml(), and TREX::europa::details::europa_domain::visit().
template<class Ty , bool Safe> Ty TREX::transaction::BasicEnumerated::getTypedElement (size_t n) const [inline]
Typed element access.
Template Parameters:
Ty expected return type
Safe extraction method
Parameters:
i index of the element
This method give access to the element i of the domain converted in the type Ty. The Safe flag indicate whether the conversion to Ty should be done using boost::any_cast -- which will fail if the encapsulated type is not Ty -- or using the safer string_cast that should be more type robust
Precondition:
i is less than the size of the set
if Safe is false, the underlying type of the container has to be exactly Ty
if Safe is true the string value of this element should be parseable into Ty
Returns:
the element at index i converted to the type Ty
Note:
No matter what this method is heavy in term of computation overhead and should be used wisely (mostly for debugging/instrumentation purpose)
See also:
size_t getSize() const
boost::any getElement(size_t i) const
std::string getStringValue(size_t i) const
Definition at line 137 of file BasicEnumerated.hh.
References getElement(), getStringValue(), and TREX::utils::string_cast().
template<class Ty , bool Safe> Ty TREX::transaction::DomainBase::getTypedSingleton () const [inline, inherited]
singleton value
Template Parameters:
Ty output type
Safe robust conversion
This methods give acces to the value of a singleton instance The output will be of type Ty
The Safe parameter indicates which method should be used.
If the real type of the underneath domain type is guaranteed to be Ty the Safe can be false for performance
If the type is not guaranteed to be Ty but its text representation is compatible with Ty the Safe should be true
Precondition:
the instance is a singleton
the type of the value manip[ulated by this domain should be convertible to Ty or exactly Ty is Safe is false
Exceptions:
DomainAccess the insatnce was not a singleton
boost::bad_string_cast Safe is true and the value of the singleton cannot be parse into Ty
boost::bad_string_cast Safe is false and the type of the singleton is not Ty
Returns:
The singleton value of this domain
See also:
getStringSingleton() const
getSingleton() const
Definition at line 368 of file DomainBase.hh.
References TREX::utils::string_cast().
TREX::utils::Symbol const& TREX::transaction::DomainBase::getTypeName () const [inline, inherited]
type of the domain
This method indicates the type of this domain. The type is a symbol that describes what is the type manipulated by this domain.
Returns:
the type associated to this domain
Definition at line 223 of file DomainBase.hh.
Referenced by TREX::transaction::EnumeratedDomain< Ty, Comp >::equals(), TREX::transaction::BooleanDomain::equals(), TREX::transaction::EnumeratedDomain< Ty, Comp >::intersect(), TREX::transaction::BooleanDomain::intersect(), TREX::transaction::EnumeratedDomain< Ty, Comp >::restrictWith(), TREX::transaction::BooleanDomain::restrictWith(), TREX::transaction::BasicInterval::toXml(), toXml(), and TREX::europa::details::europa_domain::visit().
virtual bool TREX::transaction::DomainBase::intersect (DomainBase const & other) const [pure virtual, inherited]
check for common values
Parameters:
other another instance
This methods indicates if current instance share values with other. This generally means that both have the same type and that one can safely restrict the domain of the other.
Return values:
true if current instance shares values with other
false otherwise
See also:
bool equals(DomainBase const &other) const
DomainBase &restrictWith(DomainBase const &other)
Implemented in TREX::europa::EuropaDomain, TREX::europa::EuropaProxy, TREX::europa::EuropaProxy, TREX::transaction::BooleanDomain, TREX::transaction::EnumeratedDomain< Ty, Comp >, TREX::transaction::IntervalDomain< Ty, Comp >, TREX::transaction::EnumeratedDomain< std::string >, TREX::transaction::EnumeratedDomain< TREX::utils::Symbol >, TREX::transaction::IntervalDomain< long >, and TREX::transaction::IntervalDomain< double >.
Referenced by TREX::transaction::Goal::restrictTime().
bool TREX::transaction::BasicEnumerated::isEnumerated () const [inline, virtual]
Check for enumerated domain.
This method check if the domain is based on an enumerated representation. In which case its representation is based on the list of all the possible values.
Return values:
true if the domain is enumeration based
false otherwise
See also:
bool isInterval() const
Implements TREX::transaction::DomainBase.
Definition at line 70 of file BasicEnumerated.hh.
bool TREX::transaction::BasicEnumerated::isFull () const [inline, virtual]
check for full domain
This method identifies if current domain is full. A full domain is adomain that includes al the possibles values for its type.
Return values:
true if current instance is full
false otherwise
Implements TREX::transaction::DomainBase.
Definition at line 74 of file BasicEnumerated.hh.
References getSize().
Referenced by TREX::transaction::EnumeratedDomain< TREX::utils::Symbol >::contains(), and TREX::transaction::EnumeratedDomain< Ty, Comp >::intersect().
bool TREX::transaction::BasicEnumerated::isInterval () const [inline, virtual]
Check for interval domain.
This method is used to identify if this domain is an interval based domain. In which case it is represented by a lower and upper bound.
Return values:
true if the domain is interval based
false otherwise
See also:
bool isEnumerated() const
Implements TREX::transaction::DomainBase.
Definition at line 67 of file BasicEnumerated.hh.
bool TREX::transaction::BasicEnumerated::isSingleton () const [inline, virtual]
check for singleton value
This method identifies if current domain is a singleton. A singleton domain is defined by one and only one value.
Return values:
true if current instance is a singleton
false otherwise
Implements TREX::transaction::DomainBase.
Definition at line 77 of file BasicEnumerated.hh.
References getSize().
DomainBase& TREX::transaction::DomainBase::operator*= (DomainBase const & other) [inline, inherited]
Restrict domain possible values.
Parameters:
other Another domain
This method restrict the domain of current instance to the values that are shared by this domain and other.
Precondition:
this domain intersect other
Returns:
this domain after the operation
Exceptions:
EmptyDomain resulting domain is empty
See also:
bool intersect(DomainBase const &) const
Definition at line 280 of file DomainBase.hh.
virtual DomainBase& TREX::transaction::DomainBase::restrictWith (DomainBase const & other) [pure virtual, inherited]
Restrict domain possible values.
Parameters:
other Another domain
This method restrict the domain of current instance to the values that are shared by this domain and other.
Precondition:
this domain intersect other
Returns:
this domain after the operation
Exceptions:
EmptyDomain resulting domain is empty
See also:
bool intersect(DomainBase const &) const
Implemented in TREX::europa::EuropaDomain, TREX::europa::EuropaProxy, TREX::europa::ProxyDomain, TREX::europa::EuropaProxy, TREX::transaction::BooleanDomain, TREX::transaction::EnumeratedDomain< Ty, Comp >, TREX::transaction::IntervalDomain< Ty, Comp >, TREX::transaction::EnumeratedDomain< std::string >, TREX::transaction::EnumeratedDomain< TREX::utils::Symbol >, TREX::transaction::IntervalDomain< long >, and TREX::transaction::IntervalDomain< double >.
std::ostream & BasicEnumerated::toXml (std::ostream & out, size_t tabs) const [virtual]
XML conversion.
Parameters:
out An output stream
tabs indentation level
This methods writes an XML representation of the domain into the output stream out. The tabs attribute indicates the indentation level expected for the tags.
Note:
To ensure compatibility this method should produce an xml output which is compatible with the XML parsing constructor of this domain.
Returns:
out after the operation
See also:
DomainBase(rapidxml::xml_node<> const &)
xml_factory
Implements TREX::transaction::DomainBase.
Definition at line 86 of file BasicEnumerated.cc.
References getSize(), getStringValue(), and TREX::transaction::DomainBase::getTypeName().
The documentation for this class was generated from the following files:
trex/domain/BasicEnumerated.hh
trex/domain/BasicEnumerated.cc