trex: TREX::utils::SharedVar< Ty > Class Template Reference
TREX::utils::SharedVar< Ty > Class Template Reference
Basic utilities
multi-thread shared variable
#include <trex/utils/SharedVar.hh>
Public Types
typedef boost::unique_lock
< SharedVar< Ty > > scoped_lock
Scoped variable locking type.
Public Member Functions
void lock () const
Locking method.
boost::call_traits< Ty >
::param_type operator= (typename boost::call_traits< Ty >::param_type value)
Assignment operator.
bool ownIt () const
Check for thread ownership.
SharedVar (typename boost::call_traits< Ty >::param_type val=Ty())
Constructor.
void unlock () const
Unlocking method.
~SharedVar ()
Destructor.
Ty & operator* ()
Dereferencing operator.
Ty const & operator* () const
Dereferencing operator.
Ty * operator-> ()
Access operator.
Ty const * operator-> () const
Access operator.
Detailed Description
template<class Ty>
class TREX::utils::SharedVar< Ty >
multi-thread shared variable
This class implements a simple utility to manage a variable which is manipulated by multiple threads. It ensures that this variable is accessed only by the thread which have reserved (locked) it.
Template Parameters:
Ty Type of the variable to be shared
Precondition:
Ty must provides a copy constructor
Ty must be default constructible
Author:
Frederic Py fpy@m.nosp@m.bari.nosp@m..org
Definition at line 101 of file SharedVar.hh.
Member Typedef Documentation
template<class Ty> typedef boost::unique_lock< SharedVar<Ty> > TREX::utils::SharedVar< Ty >::scoped_lock
Scoped variable locking type.
This type can be used to locally lock one SharedVar based in a C++ scope. A new instance of this class will lock the mutex associated to the SharedVar during its whiole lifetime and release the mutex on its destruction.
This provide a simple, exception safe, way to lock a SharedVar during a critical section while avoiding to have it remains locked in the eventuality of an exception.
For example on can implement the function getval(SharedVar const &) that returns the value of a SharedVar like this:
 template<class Ty>
 Ty getval(SharedVar<Ty> const &var) {
   SharedVar<Ty>::scoped_lock slock(var);
   return *var;
 }
At the begining of this function the creation of slock locks the mutex associated to var. This alows to access to var on the next line. Finally, as we leave the function context slock will be destroyed and by doing so will release the mutex it locked during its creation.
Definition at line 133 of file SharedVar.hh.
Constructor & Destructor Documentation
template<class Ty> TREX::utils::SharedVar< Ty >::SharedVar (typename boost::call_traits< Ty >::param_type val = Ty()) [inline]
Constructor.
Parameters:
[in] val An init value
Create a new instance and set its value to val
Postcondition:
the newly created instance is not locked
Definition at line 143 of file SharedVar.hh.
Member Function Documentation
template<class Ty> void TREX::utils::SharedVar< Ty >::lock () const [inline]
Locking method.
This method locks the current variable.
Note:
This call is blocking; If this inatnce is locked by another thread. The caller will be suspended until we can sucedsfully lock the varaible for this thread.
Postcondition:
The variable is locked by the current thread.
Exceptions:
ErrnoExcept System error
See also:
unlock() const
Definition at line 162 of file SharedVar.hh.
Referenced by TREX::utils::SharedVar< bool >::operator=(), and TREX::utils::SharedVar< bool >::ownIt().
template<class Ty> Ty& TREX::utils::SharedVar< Ty >::operator* () [inline]
Dereferencing operator.
Give access to the shared variable
Precondition:
This instance is locked by current thread
Returns:
A reference to the variable
Exceptions:
AccessExcept Variable is not locked by current thread.
ErrnoExcept System error
See also:
lock() const
ownIt() const
operator->()
Definition at line 242 of file SharedVar.hh.
Referenced by TREX::utils::SharedVar< bool >::operator->().
template<class Ty> Ty const& TREX::utils::SharedVar< Ty >::operator* () const [inline]
Dereferencing operator.
Give access to the shared variable
Precondition:
This instance is locked by current thread
Returns:
A reference to the variable
Exceptions:
AccessExcept Variable is not locked by current thread.
ErrnoExcept System error
See also:
lock() const
ownIt() const
operator->()
Definition at line 248 of file SharedVar.hh.
template<class Ty> Ty* TREX::utils::SharedVar< Ty >::operator-> () [inline]
Access operator.
Give access to variable and more specifically to its attributes.
Precondition:
This instance is locked by current thread
Returns:
A pointer to the variable allowing access to its attributes
Exceptions:
AccessExcept Variable is not owned by current thread.
ErrnoExcept System error.
See also:
lock() const
ownIt() const
operator* ()
Definition at line 271 of file SharedVar.hh.
template<class Ty> Ty const* TREX::utils::SharedVar< Ty >::operator-> () const [inline]
Access operator.
Give access to variable and more specifically to its attributes.
Precondition:
This instance is locked by current thread
Returns:
A pointer to the variable allowing access to its attributes
Exceptions:
AccessExcept Variable is not owned by current thread.
ErrnoExcept System error.
See also:
lock() const
ownIt() const
operator* ()
Definition at line 275 of file SharedVar.hh.
template<class Ty> boost::call_traits<Ty>::param_type TREX::utils::SharedVar< Ty >::operator= (typename boost::call_traits< Ty >::param_type value) [inline]
Assignment operator.
Parameters:
[in] value A value
This methods set current instance to value.
Returns:
value
Note:
This call is thread safe and atomic. If current instance is not already locked by the calling thread, it will do so and unlock it on completion.
Exceptions:
ErrnoExcept System error.
Definition at line 202 of file SharedVar.hh.
template<class Ty> bool TREX::utils::SharedVar< Ty >::ownIt () const [inline]
Check for thread ownership.
This methods indicates if current instance is locked by current thread. A thread can manipulate a SharedVariable if and only if this variable is locked by the thread. This method allows user to check such information.
Return values:
true If this instance is locked by the calliung thread.
false otherwise
See also:
lock() const
unlock() const
Definition at line 221 of file SharedVar.hh.
Referenced by TREX::utils::SharedVar< bool >::operator*(), and TREX::utils::SharedVar< bool >::unlock().
template<class Ty> void TREX::utils::SharedVar< Ty >::unlock () const [inline]
Unlocking method.
Unlock the mutex attached to this variable.
Precondition:
The variable is locked by current thread.
Postcondition:
The variable is not locked by this thread anymore.
Exceptions:
AccessExcept Variable not locked by this thread.
ErrnoExcept System error.
See also:
lock() const
ownIt() const
Definition at line 179 of file SharedVar.hh.
The documentation for this class was generated from the following file:
trex/utils/SharedVar.hh