trex: TREX::agent::CycleDetector Class Reference
TREX::agent::CycleDetector Class Reference
[TREX agent]
Cycle detector.
#include <trex/agent/agent_graph.hh>
Public Member Functions
void back_edge (TREX::transaction::graph::relation_type const &rel, TREX::transaction::graph const &g)
back edge callback
CycleDetector (CycleDetector const &other)
Copy constructor.
CycleDetector ()
Default constructor.
virtual ~CycleDetector ()
Destructor.
Protected Member Functions
bool is_valid (TREX::transaction::graph::reactor_id r) const
Check for node validity.
Detailed Description
Cycle detector.
This class is the base class used by a TREX agent to traverse all its reactors.
It ensures that a CyclicDependency extception will be thrown if a cyclic dependency is identified during the reactors traversal
Author:
Frederic Py <fpy@mbari.org>
Definition at line 122 of file agent_graph.hh.
Constructor & Destructor Documentation
TREX::agent::CycleDetector::CycleDetector (CycleDetector const & other) [inline]
Copy constructor.
Parameters:
[in] other Another instance
Definition at line 130 of file agent_graph.hh.
Member Function Documentation
void TREX::agent::CycleDetector::back_edge (TREX::transaction::graph::relation_type const & rel, TREX::transaction::graph const & g) [inline]
back edge callback
This dfs callback is called only when the dfs loops back to a vertex that is still being explored. This clearly idenitfy a loop in the graph wwhich is a proof of cyclic dependncy betwee two reactors
Exceptions:
CycleDetected always thrown as this call indicates a cyclic dependency in the egent graph
Definition at line 144 of file agent_graph.hh.
bool TREX::agent::CycleDetector::is_valid (TREX::transaction::graph::reactor_id r) const [inline, protected]
Check for node validity.
Parameters:
[in] r A reactor reference
Check that r referes to an exisiting reactor. This method is used during graph traversal to vcheck that the an edge is not pointing to nothing
Return values:
true if r refers to a reactor
false otherwise
See also:
TREX::transaction::garph::null_reactor()
Definition at line 163 of file agent_graph.hh.
Referenced by TREX::agent::details::sync_scheduller::discover_vertex(), TREX::agent::details::sync_scheduller::finish_vertex(), and TREX::agent::details::init_visitor::finish_vertex().
The documentation for this class was generated from the following file:
trex/agent/agent_graph.hh