trex: Basic utilities
Basic utilities
TREX core
simple utilities library
Files
file ErrnoExcept.cc
ErrnoExcept implementation.
file ErrnoExcept.hh
ErrnoExcept definition.
file Exception.cc
TREX Exception implementation.
file Exception.hh
TREX exception base.
file Factory.hh
Factory class definition.
file Factory.tcc
Factory class implementation.
file Factory.tcc
Factory class implementation.
file Hashable.hh
TR1 hashing utilities.
file IOstreamable.hh
Standard streams support utilities.
file LogManager.cc
LogManager implementation.
file LogManager.hh
LogManager class definition.
file Pdlfcn.cc
unix dl* wrappers to support different platforms
file Plugin.hh
Plugin header.
file PluginLoader.cc
Implementation of PluginLoader.
file PluginLoader.hh
plug-in loading utility
file RStat.cc
RStat implementation.
file RStat.hh
Definition of RStat.
file SharedVar.hh
utilities for multi-thread shared variable
file SingletonDummy.cc
SingletonDummy internal class implmentation.
file SingletonDummy.hh
Defintion of the SingletonDummy class.
file SingletonServer.cc
SingletonServer internal class implmentation.
file SingletonServer.hh
Defintion of the SingletonServer class.
file SingletonServer_fwd.hh
Forward declaration of SingletonServer class.
file SingletonUse.hh
Define the access class to a phoenix singleton.
file SingletonUse.tcc
SingletonUse implementation.
file SingletonWrapper.hh
Defintion of the SingletonWrapper class.
file SingletonWrapper.tcc
SingletonWrapper implementation.
file StringExtract.hh
Utilities for values extraction from string.
file Symbol.hh
file Symbol.tcc
BasicSymbol implementation.
file Symbol.tcc
BasicSymbol implementation.
file TextLog.cc
TextLog implementation.
file TextLog.hh
Definition of the TextLog class.
file TimeUtils.hh
C++ utilities for timeval.
file XmlFactory.hh
Factory based XML parsing utilities.
file XmlFactory.tcc
XmlFactory implementation.
file XmlFactory.tcc
XmlFactory implementation.
file XmlUtils.cc
XML utilities implmentation.
file XmlUtils.hh
Helpers for xml manipulation.
Namespaces
namespace TREX::utils
TREX basic utilities.
namespace TREX::utils::internals
utils internals
Classes
class TREX::utils::AccessExcept
Bad access exception.
class TREX::utils::bad_string_cast
Bad string cast exception.
class TREX::utils::BasicSymbol< CharT, Traits, Alloc >
generic symbol class
class TREX::utils::ErrnoExcept
errno handling exception
class TREX::utils::Exception
TREX exception.
class TREX::utils::Factory< AbstractProduct, Id, ConsArg, ProductRef, IdComp >
Generic global factory.
class TREX::utils::FactoryException
generic Factory exception
class TREX::utils::Hashable
Abstract class that supports hash.
struct TREX::utils::id_cmp< IdTraits, Cmp >
list_set sorting functor
class TREX::utils::id_mapper< IdTraits, Cmp >
Embedded key comparison helper.
class TREX::utils::istreamable
standard input stream support class
class TREX::utils::list_set< IdTraits, Cmp >
List based generalized set.
class TREX::utils::internals::LogEntry
Text Entry manager for TextLog.
class TREX::utils::LogManager
Centralized logging and files management.
struct TREX::utils::map_id_traits< IdTraits, Ty >
Identifier extraction for pair based element.
class TREX::utils::MultipleFactoryDecl
Multiple producers declaration.
class TREX::utils::ostreamable
standard output stream support class
class TREX::utils::PluginError
Plugin management related error.
class TREX::utils::PluginLoader
plug-in management class
struct TREX::utils::pointer_id_traits< IdTraits, Ptr >
Identifier extraction for pointer based element.
class TREX::utils::RStat
Resource usage stats management class.
class TREX::utils::RStatLap
Stop-watch for RStat.
struct TREX::utils::internal::sdummy_factory
Abstract factor for singleton.
class TREX::utils::SharedVar< Ty >
multi-thread shared variable
class TREX::utils::internal::SingletonDummy
Abstract class for singleton control.
class TREX::utils::internal::SingletonServer
Singleton central manager.
struct TREX::utils::SingletonUse< Ty >
Singleton accessor.
class TREX::utils::SingletonWrapper< Ty >
Phoenix singleton wrapper.
class TREX::utils::TextLog
Thread safe text logging.
class TREX::utils::UnknownFactoryType
Unknown producer ID.
struct TREX::version
Core libraies version information.
class TREX::utils::XmlError
XML parsing related errors.
Defines
#define TV_USEC_F 1000000l
Number of micro seconds in a second.
Typedefs
typedef void(* TREX::utils::internals::plugin_fn)()
Pointer to a plugin function.
typedef BasicSymbol< char > TREX::utils::Symbol
char based BasicSymbol
Functions
std::string TREX::utils::checked_string (char const *str)
size_t hash_value (TREX::utils::Hashable const &x)
Hashing proxy for boost::hash.
bool TREX::utils::is_tag (boost::property_tree::ptree::value_type const &node, std::string const &tag)
bool TREX::utils::operator!= (timeval const &t1, timeval const &t2)
"Not equal to" operator
timeval TREX::utils::operator* (timeval const &t, long n)
Multiply.
RStat operator* (long n, RStat const &s)
Multiplication.
timeval TREX::utils::operator+ (timeval const &t1, timeval const &t2)
Addition.
timeval & TREX::utils::operator+= (timeval &t1, timeval const &t2)
Increment operator.
timeval TREX::utils::operator- (timeval const &t1, timeval const &t2)
Substract.
timeval & TREX::utils::operator-= (timeval &t1, timeval const &t2)
Decrement operator.
timeval TREX::utils::operator/ (timeval const &t, long n)
Divide.
bool TREX::utils::operator< (timeval const &t1, timeval const &t2)
"Less than" operator
std::ostream & TREX::utils::operator<< (std::ostream &os, timeval const &t)
Print operator.
std::ostream & operator<< (std::ostream &out, RStat const &stats)
Output write operator.
bool TREX::utils::operator<= (timeval const &t1, timeval const &t2)
"Less or equal to" operator
bool TREX::utils::operator== (timeval const &t1, timeval const &t2)
"Equal to" operator
bool TREX::utils::operator> (timeval const &t1, timeval const &t2)
"Greater than" operator
bool TREX::utils::operator>= (timeval const &t1, timeval const &t2)
"Greater or equal to" operator
int TREX::utils::internals::p_dlclose (void *handle)
Close a dynamic library.
const char * TREX::utils::internals::p_dlerror (void)
dynamic library error messages
std::string const & TREX::utils::internals::p_dlext ()
Dynamic library extension helper.
void * TREX::utils::internals::p_dlopen (const char *path, int mode)
dynamic library load
void * TREX::utils::internals::p_dlsym (void *handle, const char *symbol)
dynamic library symbol access
template<class Ty >
Ty TREX::utils::parse_attr (Ty const &on_missing, boost::property_tree::ptree const &node, std::string const &attr)
Optional XML attribute extraction.
template<typename Ty >
Ty TREX::utils::string_cast (std::string const &in, std::ios_base &(*format)(std::ios_base &)=std::dec)
Convert string to type.
template<typename Ty >
Ty TREX::utils::string_cast (Ty const &on_error, std::string const &in, std::ios_base &(*format)(std::ios_base &)=std::dec)
Convert string to type.
template<>
std::string TREX::utils::string_cast< std::string > (std::string const &in, std::ios_base &(*format)(std::ios_base &))
string casting specialization
double TREX::utils::to_double (timeval const &t)
Conversion to double.
timeval TREX::utils::to_timeval (double v)
conversion of a double to a timeval
template<class Ty >
Ty TREX::utils::parse_attr (boost::property_tree::ptree const &node, std::string const &attr)
XML attribute extraction.
template<class Ty >
Ty TREX::utils::parse_attr (boost::property_tree::ptree::value_type const &node, std::string const &attr)
XML attribute extraction.
Detailed Description
simple utilities library
This library embeds all the basic utilities manipulated by higher level TREX components. They are all provided by the library named lib/libTREXutils
Author:
Frederic Py fpy@m.nosp@m.bari.nosp@m..org
Typedef Documentation
typedef void(* TREX::utils::internals::plugin_fn)()
Pointer to a plugin function.
This type is used internally to know how to refer to the initPlugin function
See also:
TREX::initPlugin()
Definition at line 64 of file Plugin.hh.
typedef BasicSymbol<char> TREX::utils::Symbol
char based BasicSymbol
This typedef is the default type one would use to manipulate symbols. It is the counterpart of the standard C++ string class.
Definition at line 325 of file Symbol.hh.
Function Documentation
std::string TREX::utils::checked_string (char const * str) [inline]
Checked char * to std::string conversion
Parameters:
str A C string
This convert a C string to a std::string checking if str is not NULL. Indeed std::string does not check it and std::string(NULL) has an undefined behavior.
Returns:
A std::string corresponding to the value of str. If str is NULL, it returns an empty std::string.
Definition at line 99 of file StringExtract.hh.
size_t hash_value (TREX::utils::Hashable const & x) [related]
Hashing proxy for boost::hash.
Parameters:
x Insance to hash
This method is used internally by boost::hash functor to compute the hash value
Returns:
The hash value of x
See also:
std::size_t Hashable::hash() const
Definition at line 104 of file Hashable.hh.
References TREX::utils::Hashable::hash().
bool TREX::utils::is_tag (boost::property_tree::ptree::value_type const & node, std::string const & tag) [inline]
brief Check for XML tag name
Parameters:
node A property tree value
tag A tag name
Return values:
true if the tag name of node is tag
false otherwise
Definition at line 236 of file XmlUtils.hh.
Referenced by TREX::transaction::TeleoReactor::TeleoReactor().
bool TREX::utils::operator!= (timeval const & t1, timeval const & t2) [inline]
"Not equal to" operator
Parameters:
t1 a date
t2 a date
Return values:
true if t1 is different from t2
false else.
Definition at line 100 of file TimeUtils.hh.
References TREX::utils::operator==().
timeval TREX::utils::operator* (timeval const & t, long n) [inline]
Multiply.
Parameters:
t a date
n The factor
Returns:
The mutlplication of t by n
Definition at line 256 of file TimeUtils.hh.
References TV_USEC_F.
RStat operator* (long n, RStat const & s) [related]
Multiplication.
Parameters:
n factor
s A statisitic information
Multiplies s by n. This function assure the commutativity of the multiplication.
Returns:
The result of the multiplication.
See also:
RStat RStat::operator* (long n) const
Definition at line 360 of file RStat.hh.
timeval TREX::utils::operator+ (timeval const & t1, timeval const & t2) [inline]
Addition.
Parameters:
t1 a date
t2 a date
Returns:
The sum of t1 and t2
Definition at line 151 of file TimeUtils.hh.
References TV_USEC_F.
timeval& TREX::utils::operator+= (timeval & t1, timeval const & t2) [inline]
Increment operator.
Parameters:
t1 a date
t2 a date
This operator increments t1 by the value of t2.
Returns:
t1 after the operation
Definition at line 204 of file TimeUtils.hh.
References TV_USEC_F.
timeval TREX::utils::operator- (timeval const & t1, timeval const & t2) [inline]
Substract.
Parameters:
t1 a date
t2 a date
Returns:
the difference between t1 and t2
Definition at line 221 of file TimeUtils.hh.
References TV_USEC_F.
timeval& TREX::utils::operator-= (timeval & t1, timeval const & t2) [inline]
Decrement operator.
Parameters:
t1 a date
t2 a date
This operator decrement the value of t1 by t2.
Returns:
t1 after the operation
Definition at line 276 of file TimeUtils.hh.
References TV_USEC_F.
timeval TREX::utils::operator/ (timeval const & t, long n) [inline]
Divide.
Parameters:
t a date
n The divider
Returns:
The division of t by n
Definition at line 239 of file TimeUtils.hh.
References TV_USEC_F.
bool TREX::utils::operator< (timeval const & t1, timeval const & t2) [inline]
"Less than" operator
Parameters:
t1 a date
t2 a date
Return values:
true if t1 is before t2
false else.
Definition at line 73 of file TimeUtils.hh.
Referenced by TREX::utils::operator>=().
std::ostream& TREX::utils::operator<< (std::ostream & os, timeval const & t) [inline]
Print operator.
Parameters:
os An output stream
t a date
Thsi method writes the value of t in os. The value format is seconds.microseconds
Returns:
os after the operation
Definition at line 296 of file TimeUtils.hh.
References TV_USEC_F.
std::ostream & operator<< (std::ostream & out, RStat const & stats) [related]
Output write operator.
Parameters:
out An output stream
stats A stats snapshot
Write the compact_desc of stats to out
Returns:
out after the operation.
See also:
std::ostream &RStat::compact_desc(std::ostream &)
Definition at line 320 of file RStat.hh.
References TREX::utils::RStat::compact_desc().
bool TREX::utils::operator<= (timeval const & t1, timeval const & t2) [inline]
"Less or equal to" operator
Parameters:
t1 a date
t2 a date
Return values:
true if t1 is before or equal to t2
false else.
Definition at line 126 of file TimeUtils.hh.
References TREX::utils::operator>().
bool TREX::utils::operator== (timeval const & t1, timeval const & t2) [inline]
"Equal to" operator
Parameters:
t1 a date
t2 a date
Return values:
true if t1 has the same value as t2
false else.
Definition at line 87 of file TimeUtils.hh.
Referenced by TREX::utils::operator!=().
bool TREX::utils::operator> (timeval const & t1, timeval const & t2) [inline]
"Greater than" operator
Parameters:
t1 a date
t2 a date
Return values:
true if t1 is after t2
false else.
Definition at line 113 of file TimeUtils.hh.
Referenced by TREX::utils::operator<=().
bool TREX::utils::operator>= (timeval const & t1, timeval const & t2) [inline]
"Greater or equal to" operator
Parameters:
t1 a date
t2 a date
Return values:
true if t1 is after or equal to t2
false else.
Definition at line 139 of file TimeUtils.hh.
References TREX::utils::operator<().
int TREX::utils::internals::p_dlclose (void * handle)
Close a dynamic library.
Parameters:
[in,out] handle a library handle
This method unload the library handle
Return values:
0 success
-1 failure
See also:
void *p_dlopen(const char *, int)
const char *p_dlerror()
Author:
Patrick Daley
Definition at line 212 of file Pdlfcn.cc.
Referenced by TREX::utils::PluginLoader::load(), and TREX::utils::PluginLoader::unload().
const char * TREX::utils::internals::p_dlerror (void)
dynamic library error messages
This methosds give the error message corresponding to the error of the last call to a p_dl* function
Returns:
an error message
See also:
void p_dlopen(const char, int)
void *p_dlsym(void *, const char *)
int p_dlconst(void *)
Author:
Patrick Daley
Definition at line 208 of file Pdlfcn.cc.
std::string const & TREX::utils::internals::p_dlext ()
Dynamic library extension helper.
This function helps to identify the usual extension of dynamic libraries for the current platform. Indeed, depending on the OS this extension differ.
The cases that are supported now are:
.so for linux and most of the UNIXes
.dylib under MacOS X
.dll under Windows
Returns:
The usual dynamic library extension for this platform
See also:
void *p_dlopen(const char *, int)
Author:
Frederic Py fpy@m.nosp@m.bari.nosp@m..org
Definition at line 36 of file Pdlfcn.cc.
Referenced by TREX::utils::PluginLoader::load().
void * TREX::utils::internals::p_dlopen (const char * path, int mode)
dynamic library load
Parameters:
[in] path The library name
[in] mode The mode
Open the dynamic library path with the mode mode
Returns:
A pointer to the dynamic library handle or NULL in case of failure
See also:
int p_dlclose(void *)
const char *p_dlerror()
Author:
Patrick Daley
Definition at line 200 of file Pdlfcn.cc.
Referenced by TREX::utils::PluginLoader::load().
void * TREX::utils::internals::p_dlsym (void * handle, const char * symbol)
dynamic library symbol access
Parameters:
[in] handle the dynamic library handle
[in] symbol symbol to look for
Look for the symbol symbol in the library handle
Precondition:
handle should be a valid handle as returned by p_dlopen
Returns:
A pointer to the entity corresponding to symbol or NULL in case of failure
See also:
void p_dlopen(const char, int)
const char *p_dlerror()
std::string const &p_dlext()
Author:
Patrick Daley
Definition at line 204 of file Pdlfcn.cc.
Referenced by TREX::utils::PluginLoader::load().
template<class Ty > Ty TREX::utils::parse_attr (boost::property_tree::ptree const & node, std::string const & attr)
XML attribute extraction.
Template Parameters:
Ty output type
Parameters:
node An XML node
attr Attribute name
This method extract attribute attr from node and parses it as a Ty variable
Precondition:
node has the attribute attr
the value of attr can be parsed into the type Ty
Exceptions:
XmlError Unable to find attribute attr
bad_string_cast Cannot parse the value of attr as Ty
Returns:
The parsed value from attr
See also:
template<class Ty> Ty const &parse_attr(Ty const &, rapidxml::xml_node<> const &, std::string const &attr)
Definition at line 155 of file XmlUtils.hh.
References TREX::utils::internals::attr_helper< Ty >::get().
template<class Ty > Ty TREX::utils::parse_attr (boost::property_tree::ptree::value_type const & node, std::string const & attr)
XML attribute extraction.
Template Parameters:
Ty output type
Parameters:
node An XML node
attr Attribute name
This method extract attribute attr from node and parses it as a Ty variable
Precondition:
node has the attribute attr
the value of attr can be parsed into the type Ty
Exceptions:
XmlError Unable to find attribute attr
bad_string_cast Cannot parse the value of attr as Ty
Returns:
The parsed value from attr
See also:
template<class Ty> Ty const &parse_attr(Ty const &, rapidxml::xml_node<> const &, std::string const &attr)
Definition at line 165 of file XmlUtils.hh.
template<class Ty > Ty TREX::utils::parse_attr (Ty const & on_missing, boost::property_tree::ptree const & node, std::string const & attr)
Optional XML attribute extraction.
Template Parameters:
Ty output type
Parameters:
on_missing default value if missing
node An XML node
attr Attribyute name
This method extract attribute attr from node and parses it as a Ty variable. If the attribute is missing it returns the default on_missing value
Precondition:
the value of attr can be parsed into the type Ty
Exceptions:
bad_string_cast Cannot parse the value of attr as Ty
Return values:
@a on_missing If attr does not exist in node
Returns:
The parsed value from attr otherwise
See also:
template<class Ty> Ty const &parse_attr(rapidxml::xml_node<> const &, std::string const &attr)
Definition at line 208 of file XmlUtils.hh.
template<typename Ty > Ty TREX::utils::string_cast (std::string const & in, std::ios_base &(*)(std::ios_base &) format = std::dec)
Convert string to type.
Template Parameters:
Ty Destination type
Parameters:
in A string
format A format descriptor
This method extract a value of type Ty from in.
Returns:
The extracted value.
Exceptions:
bad_string_cast Error while trying to parse in
Definition at line 121 of file StringExtract.hh.
Referenced by TREX::utils::internals::attr_helper< Ty >::get(), TREX::transaction::BasicEnumerated::getTypedElement(), TREX::transaction::DomainBase::getTypedSingleton(), main(), and TREX::utils::string_cast().
template<typename Ty > Ty TREX::utils::string_cast (Ty const & on_error, std::string const & in, std::ios_base &(*)(std::ios_base &) format = std::dec)
Convert string to type.
Template Parameters:
Ty Destination type
Parameters:
on_error A value for erro handling
in A string
format A format descriptor
This method extract a value of type Ty from in. If the parsing fails it will return on_error.
Returns:
The extracted value or on_error if parsing of in failed.
See also:
Ty string_cast(std::string const &, std::ios_base &(*)(std::ios_base &))
Definition at line 164 of file StringExtract.hh.
References TREX::utils::string_cast().
template<> std::string TREX::utils::string_cast< std::string > (std::string const & in, std::ios_base &(*)(std::ios_base &) format) [inline]
string casting specialization
Parameters:
in A string
format A format
Returns:
A copy of in
Definition at line 143 of file StringExtract.hh.
double TREX::utils::to_double (timeval const & t) [inline]
Conversion to double.
Parameters:
t a date
Convert t to a double value.
Warning:
There may be a precision loss during conversion.
Returns:
A double value corresponding to t
Definition at line 173 of file TimeUtils.hh.
References TV_USEC_F.
timeval TREX::utils::to_timeval (double v) [inline]
conversion of a double to a timeval
Parameters:
v A double representation of time in seconds
Returns:
the conversion of v to a timeval
Definition at line 187 of file TimeUtils.hh.
Referenced by TREX::agent::RealTimeClock::RealTimeClock().