trex: TREX::transaction::EnumDomain Class Reference
TREX::transaction::EnumDomain Class Reference
[Domains]
Enum domain.
#include <trex/domain/EnumDomain.hh>
Public Types
typedef
container_type::const_iterator iterator
Possible values iterator.
typedef
TREX::utils::XmlFactory
< DomainBase,
boost::shared_ptr< DomainBase > > xml_factory
XML parsing factory for domains.
Public Member Functions
void add (Iter from, Iter to)
Add an element to the domain.
void add (TREX::utils::Symbolconst &val)
Add an element to the domain.
iterator begin () const
First element.
bool contains (TREX::utils::Symbolconst &val) const
test for membership
DomainBase * copy () const
Copy operator.
iterator end () const
End iterator.
EnumDomain (boost::property_tree::ptree::value_type &node)
EnumDomain (TREX::utils::Symbol const &val)
Constructor.
template<class Iter >
EnumDomain (Iter from, Iter to)
Constructor.
EnumDomain ()
Default Constructor.
bool equals (DomainBase const &other) const
Equality test.
boost::any getElement (size_t i) const
generic element access
boost::any getSingleton () const
singleton value
size_t getSize () const
element count
std::string getStringSingleton () const
singleton value
virtual std::string getStringValue (size_t i) const
Get element textual value.
template<class Ty , bool Safe>
Ty getTypedElement (size_t n) const
Typed element access.
template<class Ty , bool Safe>
Ty getTypedSingleton () const
singleton value
TREX::utils::Symbol const & getTypeName () const
type of the domain
bool intersect (DomainBase const &other) const
check for common values
bool isEnumerated () const
Check for enumerated domain.
bool isFull () const
check for full domain
bool isInterval () const
Check for interval domain.
bool isSingleton () const
check for singleton value
DomainBase & operator*= (DomainBase const &other)
Restrict domain possible values.
boost::any operator[] (size_t i) const
DomainBase & restrictWith (DomainBase const &other)
Restrict domain possible values.
std::ostream & toXml (std::ostream &out, size_t tabs) const
XML conversion.
~EnumDomain ()
Destructor.
Static Public Attributes
static TREX::utils::Symbol const type_name
Protected Member Functions
void addTextValue (std::string const &val)
void completeParsing (boost::property_tree::ptree::value_type &node)
std::ostream & print_value (std::ostream &out, size_t i) const
Friends
std::ostream & std::operator<< (std::ostream &out, TREX::utils::ostreamable const &x)
Detailed Description
Enum domain.
This class implements a simple representation of strings domain. The representation is based on an EnumeratedDomain that enumerates all the possible values for this string.
Author:
Frederic Py <fpy@mbari.org>
Definition at line 63 of file EnumDomain.hh.
Member Typedef Documentation
typedef TREX::utils::XmlFactory<DomainBase, boost::shared_ptr<DomainBase> > TREX::transaction::DomainBase::xml_factory [inherited]
XML parsing factory for domains.
This type defines the factory that should be manipulated for parsing domains from xml.
Definition at line 403 of file DomainBase.hh.
Constructor & Destructor Documentation
TREX::transaction::EnumDomain::EnumDomain () [inline]
Default Constructor.
Creates a new full string domain.
Definition at line 71 of file EnumDomain.hh.
Referenced by copy().
template<class Iter > TREX::transaction::EnumDomain::EnumDomain (Iter from, Iter to) [inline]
Constructor.
Template Parameters:
a C++ iterator type
Parameters:
from an iterator
to an iterator
Precondition:
[from, to) should be a valide iterator sequence
Iter should points to TREX::utils::Symbol elements
Creates a new instance restricted to all the elements in [from, to)
Exceptions:
EmptyDomainthe created domain is empty
Definition at line 87 of file EnumDomain.hh.
TREX::transaction::EnumDomain::EnumDomain (TREX::utils::Symbol const & val) [inline]
Constructor.
Parameters:
val a value
Create a new domain with the single value val
Definition at line 94 of file EnumDomain.hh.
Member Function Documentation
void TREX::transaction::EnumeratedDomain< TREX::utils::Symbol , std::less<TREX::utils::Symbol > >::add (Iter from, Iter to) [inline, inherited]
Add an element to the domain.
Template Parameters:
Iter An iterator type
Parameters:
from an iterator
to an iterator
This method allows user to add all the elements referred by [from, to) into the possible values of this domain.
Precondition:
[from, to) should be a valid iterator sequence
the type referred by Iter should be convertible into Ty
Note:
this method is an helper to ease the construction of enumerated domains. It should be used only when the domain is constructed and still not public to other reactors. Overwise it using it represent a domain relaxation which could be problematic for third party components such as planner based reactors.
See also:
void add(Ty const &)
Definition at line 188 of file EnumeratedDomain.hh.
void TREX::transaction::EnumeratedDomain< TREX::utils::Symbol , std::less<TREX::utils::Symbol > >::add (TREX::utils::Symbol const & val) [inline, inherited]
Add an element to the domain.
Parameters:
val A value
This method allows user to add val into the possible values of this domain.
Note:
this method is an helper to ease the construction of enumerated domains. It should be used only when the domain is constructed and still not public to other reactors. Overwise using it represent a domain relaxation which could be problematic for third party components such as planner based reactors.
See also:
template<class Iter> void add(Iter, Iter)
Definition at line 164 of file EnumeratedDomain.hh.
iterator TREX::transaction::EnumeratedDomain< TREX::utils::Symbol , std::less<TREX::utils::Symbol > >::begin () const [inline, inherited]
First element.
This method allows user to iterate through the possible values of the domain using classic C++ iterator paradigm.
Returns:
An iterator to the beginnig of the possible values collection
Definition at line 224 of file EnumeratedDomain.hh.
Referenced by copy().
bool TREX::transaction::EnumeratedDomain< TREX::utils::Symbol , std::less<TREX::utils::Symbol > >::contains (TREX::utils::Symbol const & val) const [inline, inherited]
test for membership
Parameters:
val A value
Return values:
true if val is a possible value for this domain
false otherwise
Definition at line 197 of file EnumeratedDomain.hh.
References TREX::transaction::EnumeratedDomain< Ty, Comp >::end(), and TREX::transaction::BasicEnumerated::isFull().
DomainBase* TREX::transaction::EnumDomain::copy () const [inline, virtual]
Copy operator.
Allocates a new copy of current instance
Implements TREX::transaction::DomainBase.
Definition at line 126 of file EnumDomain.hh.
References TREX::transaction::EnumeratedDomain< TREX::utils::Symbol >::begin(), TREX::transaction::EnumeratedDomain< TREX::utils::Symbol >::end(), and EnumDomain().
iterator TREX::transaction::EnumeratedDomain< TREX::utils::Symbol , std::less<TREX::utils::Symbol > >::end () const [inline, inherited]
End iterator.
This method allows user to iterate through the possible values of the domain using classic C++ iterator paradigm.
Returns:
An iterator to the end of the possible values collection
Definition at line 234 of file EnumeratedDomain.hh.
Referenced by copy().
bool TREX::transaction::EnumeratedDomain< TREX::utils::Symbol , std::less<TREX::utils::Symbol > >::equals (DomainBase const & other) const [virtual, inherited]
Equality test.
Parameters:
other Another instance
Checks if current instance is identical to other. This generally means that both have the same type and exactly the same possible values. In that sense it is more restrictive than the intersect method.
Return values:
true if current instance is identical to other
false otherwise
See also:
bool intersect(DomainBase const &other) const
Implements TREX::transaction::DomainBase.
boost::any TREX::transaction::EnumeratedDomain< TREX::utils::Symbol , std::less<TREX::utils::Symbol > >::getElement (size_t i) const [inline, virtual, inherited]
generic element access
Parameters:
i index of the element
This method give access to the element i of the domain.
Precondition:
i is less than the size of the set
Returns:
the element at index i encapsulated on the boost::any class
See also:
size_t getSize() const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Implements TREX::transaction::BasicEnumerated.
Definition at line 208 of file EnumeratedDomain.hh.
References TREX::transaction::EnumeratedDomain< Ty, Comp >::begin(), and TREX::transaction::EnumeratedDomain< Ty, Comp >::end().
boost::any DomainBase::getSingleton () const [inherited]
singleton value
This methods give acces to the value of a singleton instance.
Precondition:
the instance is a singleton
Exceptions:
DomainAccess the insatnce was not a singleton
Returns:
The value of the domain encapsulated in a boost::any
Note:
except for the control of the instance being a singleton the actual code of this method will be provided by the virtual method singleton()
See also:
boost::any singleton() const
getStringSingleton() const
getTypedSingleton() const
Definition at line 56 of file DomainBase.cc.
References TREX::transaction::DomainBase::isSingleton(), and TREX::transaction::DomainBase::singleton().
size_t TREX::transaction::EnumeratedDomain< TREX::utils::Symbol , std::less<TREX::utils::Symbol > >::getSize () const [inline, virtual, inherited]
element count
This method gives access to the number of elements in this instance.
Returns:
the number of values associated to this domain
Note:
by convention if the returned value is 0, TREX will consider this domain as full
Implements TREX::transaction::BasicEnumerated.
Definition at line 204 of file EnumeratedDomain.hh.
std::string DomainBase::getStringSingleton () const [inherited]
singleton value
This methods give acces to the value of a singleton instance represented as a string
Precondition:
the instance is a singleton
Exceptions:
DomainAccess the insatnce was not a singleton
Returns:
The text representation of the singleton value
Note:
except for the control of the instance being a singleton the actual code of this method will be provided by the virtual method stringSingleton()
See also:
std::string stringSingleton() const
getStringSingleton() const
getTypedSingleton() const
Definition at line 62 of file DomainBase.cc.
References TREX::transaction::DomainBase::isSingleton(), and TREX::transaction::DomainBase::stringSingleton().
std::string BasicEnumerated::getStringValue (size_t i) const [virtual, inherited]
Get element textual value.
Parameters:
[in] i Index of the element
Get the value of the element i of the domain in its textual form
Precondition:
i is a valid index (between 0 and the size of the set-1)
Returns:
A string with a human readable for the value of the element i
See also:
getSize() const
getElement(size_t) const
getTypedElement(size_t) const
Definition at line 68 of file BasicEnumerated.cc.
Referenced by TREX::transaction::BasicEnumerated::getTypedElement(), TREX::transaction::BasicEnumerated::toXml(), and TREX::europa::details::europa_domain::visit().
template<class Ty , bool Safe> Ty TREX::transaction::BasicEnumerated::getTypedElement (size_t n) const [inline, inherited]
Typed element access.
Template Parameters:
Ty expected return type
Safe extraction method
Parameters:
i index of the element
This method give access to the element i of the domain converted in the type Ty. The Safe flag indicate whether the conversion to Ty should be done using boost::any_cast -- which will fail if the encapsulated type is not Ty -- or using the safer string_cast that should be more type robust
Precondition:
i is less than the size of the set
if Safe is false, the underlying type of the container has to be exactly Ty
if Safe is true the string value of this element should be parseable into Ty
Returns:
the element at index i converted to the type Ty
Note:
No matter what this method is heavy in term of computation overhead and should be used wisely (mostly for debugging/instrumentation purpose)
See also:
size_t getSize() const
boost::any getElement(size_t i) const
std::string getStringValue(size_t i) const
Definition at line 137 of file BasicEnumerated.hh.
References TREX::transaction::BasicEnumerated::getElement(), TREX::transaction::BasicEnumerated::getStringValue(), and TREX::utils::string_cast().
template<class Ty , bool Safe> Ty TREX::transaction::DomainBase::getTypedSingleton () const [inline, inherited]
singleton value
Template Parameters:
Ty output type
Safe robust conversion
This methods give acces to the value of a singleton instance The output will be of type Ty
The Safe parameter indicates which method should be used.
If the real type of the underneath domain type is guaranteed to be Ty the Safe can be false for performance
If the type is not guaranteed to be Ty but its text representation is compatible with Ty the Safe should be true
Precondition:
the instance is a singleton
the type of the value manip[ulated by this domain should be convertible to Ty or exactly Ty is Safe is false
Exceptions:
DomainAccess the insatnce was not a singleton
boost::bad_string_cast Safe is true and the value of the singleton cannot be parse into Ty
boost::bad_string_cast Safe is false and the type of the singleton is not Ty
Returns:
The singleton value of this domain
See also:
getStringSingleton() const
getSingleton() const
Definition at line 368 of file DomainBase.hh.
References TREX::utils::string_cast().
Referenced by TREX::europa::details::europa_domain::visit().
TREX::utils::Symbol const& TREX::transaction::DomainBase::getTypeName () const [inline, inherited]
type of the domain
This method indicates the type of this domain. The type is a symbol that describes what is the type manipulated by this domain.
Returns:
the type associated to this domain
Definition at line 223 of file DomainBase.hh.
Referenced by TREX::transaction::EnumeratedDomain< Ty, Comp >::equals(), TREX::transaction::BooleanDomain::equals(), TREX::transaction::EnumeratedDomain< Ty, Comp >::intersect(), TREX::transaction::BooleanDomain::intersect(), TREX::transaction::EnumeratedDomain< Ty, Comp >::restrictWith(), TREX::transaction::BooleanDomain::restrictWith(), TREX::transaction::BasicInterval::toXml(), TREX::transaction::BasicEnumerated::toXml(), and TREX::europa::details::europa_domain::visit().
bool TREX::transaction::EnumeratedDomain< TREX::utils::Symbol , std::less<TREX::utils::Symbol > >::intersect (DomainBase const & other) const [virtual, inherited]
check for common values
Parameters:
other another instance
This methods indicates if current instance share values with other. This generally means that both have the same type and that one can safely restrict the domain of the other.
Return values:
true if current instance shares values with other
false otherwise
See also:
bool equals(DomainBase const &other) const
DomainBase &restrictWith(DomainBase const &other)
Implements TREX::transaction::DomainBase.
bool TREX::transaction::BasicEnumerated::isEnumerated () const [inline, virtual, inherited]
Check for enumerated domain.
This method check if the domain is based on an enumerated representation. In which case its representation is based on the list of all the possible values.
Return values:
true if the domain is enumeration based
false otherwise
See also:
bool isInterval() const
Implements TREX::transaction::DomainBase.
Definition at line 70 of file BasicEnumerated.hh.
bool TREX::transaction::BasicEnumerated::isFull () const [inline, virtual, inherited]
check for full domain
This method identifies if current domain is full. A full domain is adomain that includes al the possibles values for its type.
Return values:
true if current instance is full
false otherwise
Implements TREX::transaction::DomainBase.
Definition at line 74 of file BasicEnumerated.hh.
References TREX::transaction::BasicEnumerated::getSize().
Referenced by TREX::transaction::EnumeratedDomain< TREX::utils::Symbol >::contains(), and TREX::transaction::EnumeratedDomain< Ty, Comp >::intersect().
bool TREX::transaction::BasicEnumerated::isInterval () const [inline, virtual, inherited]
Check for interval domain.
This method is used to identify if this domain is an interval based domain. In which case it is represented by a lower and upper bound.
Return values:
true if the domain is interval based
false otherwise
See also:
bool isEnumerated() const
Implements TREX::transaction::DomainBase.
Definition at line 67 of file BasicEnumerated.hh.
bool TREX::transaction::BasicEnumerated::isSingleton () const [inline, virtual, inherited]
check for singleton value
This method identifies if current domain is a singleton. A singleton domain is defined by one and only one value.
Return values:
true if current instance is a singleton
false otherwise
Implements TREX::transaction::DomainBase.
Definition at line 77 of file BasicEnumerated.hh.
References TREX::transaction::BasicEnumerated::getSize().
DomainBase& TREX::transaction::DomainBase::operator*= (DomainBase const & other) [inline, inherited]
Restrict domain possible values.
Parameters:
other Another domain
This method restrict the domain of current instance to the values that are shared by this domain and other.
Precondition:
this domain intersect other
Returns:
this domain after the operation
Exceptions:
EmptyDomain resulting domain is empty
See also:
bool intersect(DomainBase const &) const
Definition at line 280 of file DomainBase.hh.
DomainBase& TREX::transaction::EnumeratedDomain< TREX::utils::Symbol , std::less<TREX::utils::Symbol > >::restrictWith (DomainBase const & other) [virtual, inherited]
Restrict domain possible values.
Parameters:
other Another domain
This method restrict the domain of current instance to the values that are shared by this domain and other.
Precondition:
this domain intersect other
Returns:
this domain after the operation
Exceptions:
EmptyDomain resulting domain is empty
See also:
bool intersect(DomainBase const &) const
Implements TREX::transaction::DomainBase.
std::ostream & BasicEnumerated::toXml (std::ostream & out, size_t tabs) const [virtual, inherited]
XML conversion.
Parameters:
out An output stream
tabs indentation level
This methods writes an XML representation of the domain into the output stream out. The tabs attribute indicates the indentation level expected for the tags.
Note:
To ensure compatibility this method should produce an xml output which is compatible with the XML parsing constructor of this domain.
Returns:
out after the operation
See also:
DomainBase(rapidxml::xml_node<> const &)
xml_factory
Implements TREX::transaction::DomainBase.
Definition at line 86 of file BasicEnumerated.cc.
References TREX::transaction::BasicEnumerated::getSize(), TREX::transaction::BasicEnumerated::getStringValue(), and TREX::transaction::DomainBase::getTypeName().
The documentation for this class was generated from the following files:
trex/domain/EnumDomain.hh
trex/domain/DomainImpl.cc