trex: TREX::agent::Clock Class Reference
TREX::agent::Clock Class Reference
TREX agent
TREX clock.
#include <trex/agent/Clock.hh>
Public Types
typedef
TREX::utils::XmlFactory< Clock > xml_factory
XML factory for clocks.
Public Member Functions
void doStart ()
Start the clock.
virtual TREX::transaction::TICK getNextTick ()=0
get time in TICK
virtual TREX::transaction::TICK initialTick () const
Initial tick.
virtual void sleep () const
Sleep until next tick.
virtual double tickDuration () const
tick duration
virtual double tickToTime (TREX::transaction::TICK cur) const
virtual TREX::transaction::TICK timeToTick (time_t secs, suseconds_t usecs=0) const
virtual ~Clock ()
Destructor.
Static Public Member Functions
static void sleep (double sleepDuration)
Process sleep.
Protected Member Functions
void advanceTick (TREX::transaction::TICK &tick)
increment tick value
Clock (double sleepSeconds)
Constructor.
virtual double getSleepDelay () const
Time left before next tick.
virtual void start ()
Internal start method.
Detailed Description
TREX clock.
This class defines the abstract interface to the Clock that manage the TICK advance.
Author:
Conor McGann
Definition at line 62 of file Clock.hh.
Constructor & Destructor Documentation
TREX::agent::Clock::Clock (double sleepSeconds) [inline, explicit, protected]
Constructor.
Parameters:
sleepSeconds A default sleep delay Create a new instance with the default sleeping delay set to sleepSeconds
Definition at line 149 of file Clock.hh.
Member Function Documentation
void Clock::advanceTick (TREX::transaction::TICK & tick) [protected]
increment tick value
Parameters:
tick A tick variable
increase the value of tick by 1
Deprecated:
This method was used for computing extra stats. We need to find a better approach. Specifically it would be relevant to have the tick variable located on this class.
Definition at line 76 of file Clock.cc.
Referenced by TREX::agent::StepClock::getNextTick().
void Clock::doStart ()
Start the clock.
This method is the public interface used to start the clock.
See also:
void start()
Definition at line 71 of file Clock.cc.
Referenced by TREX::agent::Agent::initComplete().
virtual TREX::transaction::TICK TREX::agent::Clock::getNextTick () [pure virtual]
get time in TICK
This method is used to compute the current time. This is where one specialization of clock will identify whether the TICK value has advanced or not
Returns:
current tick value
Implemented in TREX::agent::RealTimeClock, and TREX::agent::StepClock.
Referenced by TREX::agent::Agent::doNext().
virtual double TREX::agent::Clock::getSleepDelay () const [inline, protected, virtual]
Time left before next tick.
This method indicates how much time is left before the next tick
Returns:
time left before next tick
Definition at line 141 of file Clock.hh.
virtual TREX::transaction::TICK TREX::agent::Clock::initialTick () const [inline, virtual]
Initial tick.
Returns:
the value of the initial tick
Definition at line 89 of file Clock.hh.
void Clock::sleep () const [virtual]
Sleep until next tick.
This method check the time left before next tick and put the process asleep for this duration.
Exceptions:
ErrnoExcept An error occurred while trying to sleep
See also:
double getSleepDelay() const
void sleep(double)
Definition at line 83 of file Clock.cc.
Referenced by TREX::agent::Agent::doNext().
void Clock::sleep (double sleepDuration) [static]
Process sleep.
Parameters:
sleepDuration number of seconds to sleep
This methods make the calling process to sleep for sleepDuration seconds
Exceptions:
ErrnoExcept An error occurred while trying to sleep
Definition at line 51 of file Clock.cc.
virtual void TREX::agent::Clock::start () [inline, protected, virtual]
Internal start method.
This method is called internally by doStart to allow specialized initialization before starting the clock.
See also:
void doStart()
Definition at line 159 of file Clock.hh.
virtual double TREX::agent::Clock::tickDuration () const [inline, virtual]
tick duration
This methods return the TICK duration. It is expected to be in seconds
Returns:
tick duration
Reimplemented in TREX::agent::RealTimeClock.
Definition at line 98 of file Clock.hh.
Referenced by TREX::agent::Agent::tickDuration().
The documentation for this class was generated from the following files:
trex/agent/Clock.hh
trex/agent/Clock.cc