trex: TREX::agent::Agent Class Reference
TREX::agent::Agent Class Reference
[TREX agent]
TREX agent.
#include <trex/agent/Agent.hh>
Classes
class AgentProxy
Public Types
typedef
details::reactor_set::difference_type difference_type
typedef boost::directed_tag directed_category
typedef details::relation_iter edge_iterator
typedef
boost::allow_parallel_edge_tag edge_parallel_category
typedef boost::edge_name_t edge_property_type
typedef std::multimap< double,
reactor_id, std::greater
< double > > priority_queue
reactors deliberation scheduling queue
typedef details::reactor_id reactor_id
reactor ID type
typedef Relation relation_type
reactor relation type
typedef
details::reactor_set::size_type size_type
typedef boost::vertex_name_t vertex_property_type
typedef
TREX::utils::XmlFactory
< TeleoReactor,
boost::shared_ptr
< TeleoReactor >, graph * > xml_factory
Reactor factory.
Public Member Functions
reactor_id add_reactor (boost::property_tree::ptree::value_type &description)
Create new reactor for this graph.
size_t add_reactors (boost::property_tree::ptree &conf)
Create new reactors for this graph.
template<class Iter >
size_t add_reactors (Iter from, Iter to)
Create new reactors for this graph.
Agent (boost::property_tree::ptree::value_type &config, Clock *clock=NULL)
Constructor.
Agent (std::string const &file_name, Clock *clock=NULL)
Constructor.
Agent (TREX::utils::Symbol const &name, TREX::transaction::TICK final=0, Clock *clock=NULL)
Constructor.
size_t cleanup ()
Kill all isolated reactors.
void clear ()
Clear the graph.
size_type count_reactors () const
Number of reactors.
size_type count_relations () const
bool doNext ()
Execute for one tick.
bool empty () const
Check if empty.
reactor_iterator find_reactor (TREX::utils::Symbol const &name) const
find a reactor
TICK getCurrentTick () const
get current tick
TREX::utils::Symbol const & getName () const
Graph name.
long index (reactor_id r) const
Reactor index.
void initComplete ()
Complete agent initialization.
reactor_id isolate (reactor_id r) const
Isolate a reactor.
bool kill_reactor (reactor_id r)
Kill a reactor.
graph const & me () const
graph & me ()
bool missionCompleted ()
Check if mission is completed.
reactor_iterator reactor_begin () const
Beginning reactor iterator.
reactor_iterator reactor_end () const
End reactor iterator.
edge_iterator relation_begin () const
edge_iterator relation_end () const
void run ()
run the agent
void sendRequest (boost::property_tree::ptree::value_type &g)
Post a goal from xml.
void sendRequest (TREX::transaction::goal_id const &g)
Post a goal.
size_t sendRequests (boost::property_tree::ptree &g)
Post a goals from xml.
bool setClock (Clock *clock)
Set agent clock.
double tickDuration () const
get tick duration
double tickToTime (TREX::transaction::TICK cur) const
convert a TICK into its real-time equivalent
TREX::transaction::TICK timeToTick (time_t secs, suseconds_t usecs=0) const
convert real-time into a TICK
~Agent ()
Destructor.
Static Public Member Functions
static reactor_id null_reactor ()
Protected Types
typedef
details::timeline_set::const_iterator timeline_iterator
Protected Member Functions
reactor_id add_reactor (reactor_id r)
virtual void external_check (reactor_id r, details::timeline const &tl)
bool has_timeline (TREX::utils::Symbol const &tl) const
virtual void internal_check (reactor_id r, details::timeline const &tl)
TREX::utils::LogManager & manager () const
void set_name (TREX::utils::Symbol const &name)
TREX::utils::internals::LogEntry syslog (std::string const &context=std::string()) const
timeline_iterator timeline_begin () const
timeline_iterator timeline_end () const
void updateTick (TICK value)
Related Functions
(Note that these are not member functions.)
std::pair< graph_traits
< TREX::transaction::graph >
::adjacency_iterator,
graph_traits
< TREX::transaction::graph >
::adjacency_iterator > adjacent_vertices (TREX::transaction::graph::reactor_id r, TREX::transaction::graph const &g)
Reactor adjacency vertices of a reactor.
TREX::transaction::details::graph_vertex_id_map get (vertex_index_t, TREX::transaction::graph const &g)
Get reactor ID map.
TREX::utils::Symbol const & get (TREX::transaction::details::graph_vertex_name_map const &m, TREX::transaction::graph::reactor_id r)
Get reactor name.
TREX::transaction::details::graph_vertex_name_map get (vertex_name_t, TREX::transaction::graph const &)
Get reactor name map.
TREX::utils::Symbol const & get (TREX::transaction::details::graph_edge_name_map const &m, TREX::transaction::graph::relation_type const &rel)
Get relation name.
TREX::transaction::details::graph_edge_name_map get (edge_name_t, TREX::transaction::graph const &)
Get relation name map.
TREX::transaction::graph::size_type num_vertices (TREX::transaction::graph const &g)
Number of reactors.
TREX::transaction::TeleoReactor::size_type out_degree (TREX::transaction::graph::reactor_id r, TREX::transaction::graph const &g)
Number of external relations for a reactor.
std::pair
< TREX::transaction::TeleoReactor::external_iterator,
TREX::transaction::TeleoReactor::external_iterator > out_edges (TREX::transaction::graph::reactor_id r, TREX::transaction::graph const &g)
Out edges of a reactor.
TREX::transaction::graph::reactor_id source (TREX::transaction::graph::relation_type const &rel, TREX::transaction::graph const &g)
source of a relation
TREX::transaction::graph::reactor_id target (TREX::transaction::graph::relation_type const &rel, TREX::transaction::graph const &g)
target of a relation
std::pair
< TREX::transaction::graph::reactor_iterator,
TREX::transaction::graph::reactor_iterator > vertices (TREX::transaction::graph const &g)
Graph reactors.
Detailed Description
TREX agent.
This class implements the TREX agent. It extends the graph concept by:
enforcing that there's no cyclic dependency between reactors
calling the different methods of the reactors in order to execute them
The execution of the reactors is made according to a clock which the agent observes in order to idenitfy a new tick that will gives the rythm of execution
As soon as the reactor graph as been fully loaded the agent will call in each reactors the TeleoReactor::initialize method while controlling that there's no cyclic dependencies in the graph and idenitfy if there's some Internal timelines missing.
After this ti will start the clock and ate each tick will execute the following callbacks of the reactors int the following order
TeleoReactor::newTick indicate to each reactor that a new tick have started
TeleoReactor::doSynchronize() require to each reactors to identify their current state based on the observation they did receive and potentially produce new observation on their intiernal timelines
TeleoReactor::workRatio() identify each reactor workload for scedulling their deliberation
TeleoReactor::step() is called only if a reactor have works (idenitifed by the fact that is workRatio() was not NAN). It allow the reactor to do a single step in roder to deliberate.
Do note that ass all theses called have to be executed in the duration of a TICK all of these should be executed in a duration that is well below the tick granularity of the clock used by the agent.
Author:
Frederic Py <fpy@mbari.org>
See also:
class TREX::transaction::TeleoReactor
class Clock
Definition at line 101 of file Agent.hh.
Member Typedef Documentation
typedef std::multimap< double, reactor_id, std::greater<double> > TREX::agent::Agent::priority_queue
reactors deliberation scheduling queue
This structure is used to find a good scheduling order for the reactors deliberation. It sorts the reactors that needs to deliberate from the one with the largest workRatio to the one with smaller workRatio
Definition at line 110 of file Agent.hh.
typedef details::reactor_id TREX::transaction::graph::reactor_id [inherited]
reactor ID type
The type used to represent a reactor in the graph
Definition at line 120 of file reactor_graph.hh.
typedef Relation TREX::transaction::graph::relation_type [inherited]
reactor relation type
The type used to represent the dependencies between reactors in the graph.
Definition at line 155 of file reactor_graph.hh.
typedef TREX::utils::XmlFactory<TeleoReactor, boost::shared_ptr<TeleoReactor>, graph *> TREX::transaction::graph::xml_factory [inherited]
Reactor factory.
A factory used ot produce new reactor in a graph using XML input.
Definition at line 162 of file reactor_graph.hh.
Constructor & Destructor Documentation
TREX::agent::Agent::Agent (TREX::utils::Symbol const & name, TREX::transaction::TICK final = 0, Clock * clock = NULL) [explicit]
Constructor.
Parameters:
[in] name The name of the agent
[in] final The value of the final tick for this mission
[in] clock A pointer to the clock that this agent will use
Create a new Agent named name with and intialize both its end and clock according to the optional arguments final and clock
Postcondition:
the agent has no reactor
Agent::Agent (std::string const & file_name, Clock * clock = NULL) [explicit]
Constructor.
Parameters:
[in] file_name A configuration file name
[in] clock A pointer to the clock that this agent will use.
Create a new Agent by parsing the onctent of the file file_name. If clock is not provided, it will take the first clock defined in file_name. Create a new Agent by parsing the content of the xml structure conf. If the clock has not beeen set yet, it will take the first clock defined in file_name.
An Agent configuration xml definition can be defined as follow:
 <Agent name="<agent name>" finalTick="<final tick>" config="<extra cfg>" >
    <!-- plugin loading information -->
    <!-- clocks defintions -->
    <!-- reactors definitions -->
    <!-- goal definitions -->
 </Agent>
Where the attributes are as follow
name is the name of the agent
finalTick is a value greater than 0 that indicates the agent lifetime
config is an optional attribute that points to another XML file. this file will contains extra tags that will be parse in simlar mananer to the childs of this root tag.
the child tags will be parsed in the following order:
Plugin information allowing TREX to load external plugins. These XML tags have the following syntax :
     <Plugin name="TREXvitre" />
and will result on the attempting to load the dynamic libray TREXvitre as a TREX plugin. These need to be loaded firast as oner plugin can defines new clocks or reactors types used by this agent
Clock definition. These will be parsed only if a clock is not defined and as a result only the first clock definition may be parsed in this configuration The tag of the XML depends on the way the clock class declared itself inside TREX. And you need to look at the documentation of the clock class you want to use in order to know how to declare it in this file.
Reactors definition. these will define all the reactors that are declared initially on this agent. As for clock, the way to specify a reactor depends on the type of reactor and onwe should look at its documentation to know further
The initial goals for this mission. Goals have generic xml format that is described in TREX::transaction::Goal class documentation
This constructor will try first to locate file_name and if does not find it will try to locate file_name.cfg
Precondition:
file_name is a a valid file on current directory or accessible through TREX_PATH
file_name is a valid xml file that defines an agent
the root node of file_name needs to be an Agent tag
Exceptions:
TREX::utils::ErrnoExcept failed to locate the file
rapidxml::parse_error parse error while loading the file
TREX::utils::XmlError invalid XML content for agent configuration
TREX::utils::Exception one exception occured while laoding the agent
See also:
Agent::Agent(rapidxml::xml_node<> &, Clock *)
Agent::loadConf(std::string const &)
Definition at line 257 of file Agent.cc.
References TREX::transaction::graph::add_reactor().
Agent::Agent (boost::property_tree::ptree::value_type & config, Clock * clock = NULL) [explicit]
Constructor.
Parameters:
[in] config A xml structure
[in] clock A pointer to the clock that this agent will use.
Create a new Agent by parsing the content of the XML node config If clock is not provided, it will take the first clock defined in file_name.
This constructor will try first to locate file_name and if does not find it will try to locate file_name.cfg
Precondition:
config root node is Agent
file_name is a valid xml file that defines an agent
Exceptions:
TREX::utils::ErrnoExcept failed to locate the file
rapidxml::parse_error parse error while loading the file
TREX::utils::XmlError invalid XML content for agent configuration
TREX::utils::Exception one exception occured while laoding the agent
See also:
Agent::Agent(std::string const &, Clock *)
Agent::loadConf(rapidxml::xml_node<> &)
Definition at line 280 of file Agent.cc.
References TREX::transaction::graph::add_reactor().
Member Function Documentation
graph::reactor_id graph::add_reactor (boost::property_tree::ptree::value_type & description) [inherited]
Create new reactor for this graph.
Parameters:
[in] definition A xml configuration tree node
Create the reactor defined by description and attch it to this graph
Definition at line 105 of file reactor_graph.cc.
References TREX::utils::list_set< IdTraits, Cmp >::insert().
Referenced by Agent().
size_t TREX::transaction::graph::add_reactors (boost::property_tree::ptree & conf) [inline, inherited]
Create new reactors for this graph.
Parameters:
[in] conf A xml configuration tree
Create all the reactors defined in conf and attach them to this graph
Definition at line 373 of file reactor_graph.hh.
References TREX::transaction::graph::add_reactors().
template<class Iter > size_t TREX::transaction::graph::add_reactors (Iter from, Iter to) [inline, inherited]
Create new reactors for this graph.
Template Parameters:
Iter An iterator type
Parameters:
[in] from Initial iterator
[in] to end iterator
Precondition:
The value_type of Iter is boost::property_tree::ptree::value_type
Add all the reactor that can be parsed from thre properties referred by [from, to) to this graph
Definition at line 40 of file reactor_graph.tcc.
References TREX::utils::list_set< IdTraits, Cmp >::insert().
Referenced by TREX::transaction::graph::add_reactors(), and TREX::transaction::graph::graph().
size_t graph::cleanup () [inherited]
Kill all isolated reactors.
Kill all the reactors which have been explicitedly isolated in this graph
Returns:
the numeof reactor that have been killed
See also:
isolate(reactor_id) const
kill_reactor(reeactor_id)
Definition at line 156 of file reactor_graph.cc.
References TREX::utils::list_set< IdTraits, Cmp >::empty(), and TREX::transaction::graph::kill_reactor().
Referenced by initComplete().
void graph::clear () [inherited]
Clear the graph.
Disconnect all the reactors from this graph
Postcondition:
The graph is empty
Definition at line 87 of file reactor_graph.cc.
References TREX::utils::list_set< IdTraits, Cmp >::clear(), and TREX::utils::list_set< IdTraits, Cmp >::empty().
Referenced by ~Agent(), and TREX::transaction::graph::~graph().
size_type TREX::transaction::graph::count_reactors () const [inline, inherited]
Number of reactors.
Returns:
the number of reactors in this graph
Definition at line 503 of file reactor_graph.hh.
References TREX::utils::list_set< IdTraits, Cmp >::size().
Referenced by missionCompleted(), and TREX::transaction::graph::num_vertices().
bool Agent::doNext ()
Execute for one tick.
This method execute all the reactors of the graphs for the current tick. This execution can be descibed as follow
TeleoReactor::newTick indicate to each reactor that a new tick have started
TeleoReactor::doSynchronize() require to each reactors to identify their current state based on the observation they did receive and potentially produce new observation on their intiernal timelines
TeleoReactor::workRatio() identify each reactor workload for scedulling their deliberation
TeleoReactor::step() is called only if a reactor have works (idenitifed by the fact that is workRatio() was not NAN). It allow the reactor to do a single step in roder to deliberate.
The function will return as soon as we reached the next tick.
Precondition:
initComplete should have been called before
true the mission is not finished
Return values:
false end of agent mission
Postcondition:
the current tick is larger than it was when we called this method
See also:
initComplete()
missionCompleted()
Definition at line 518 of file Agent.cc.
References TREX::transaction::graph::empty(), TREX::transaction::graph::getCurrentTick(), TREX::agent::Clock::getNextTick(), missionCompleted(), and TREX::agent::Clock::sleep().
Referenced by run().
bool TREX::transaction::graph::empty () const [inline, inherited]
Check if empty.
Checks if the graph is empty. Meanining that it has no reactor associated to it.
Return values:
true if the graph is empty
false otherwise
Definition at line 350 of file reactor_graph.hh.
References TREX::utils::list_set< IdTraits, Cmp >::empty().
Referenced by doNext(), and initComplete().
reactor_iterator TREX::transaction::graph::find_reactor (TREX::utils::Symbol const & name) const [inline, inherited]
find a reactor
Parameters:
[in] name A reactor symbolic name
Returns:
An iterator referring to the reactor with the name name or reactor_end() if no such reactor exists
Note:
As the graph does not allow to have multiple reactors with the same name the solution is always unique.
See also:
reactor_end() const
TeleoReactor::getName() const
Definition at line 553 of file reactor_graph.hh.
References TREX::utils::list_set< IdTraits, Cmp >::find().
TICK TREX::transaction::graph::getCurrentTick () const [inline, inherited]
get current tick
This method provides the current tick being executed in the graph.
Returns:
The tick value
Note:
This method is not usefull at the graph level and is more used by the Agent. It may be refactored in roder to keep the graph class as simple as possible.
Definition at line 441 of file reactor_graph.hh.
Referenced by doNext(), TREX::transaction::TeleoReactor::getCurrentTick(), and missionCompleted().
TREX::utils::Symbol const& TREX::transaction::graph::getName () const [inline, inherited]
Graph name.
Returns:
The name of the graph
Definition at line 298 of file reactor_graph.hh.
Referenced by TREX::transaction::TeleoReactor::getGraphName(), and initComplete().
long graph::index (graph::reactor_id id) const [inherited]
Reactor index.
Parameters:
[in] r A reactor
Returns:
An arbitrary index value for r or count_reactors() if this reactor doea not belong to this graph.
Note:
For reactor tat belong to the graph the returned value is between 0 and count_reactors()-1
Warning:
The index of a reactor can change whenver the graph is changed (by either adding new reactors or removing ones)
See also:
count_reactors() const
Definition at line 96 of file reactor_graph.cc.
References TREX::utils::list_set< IdTraits, Cmp >::begin(), and TREX::utils::list_set< IdTraits, Cmp >::end().
Referenced by TREX::transaction::details::graph_vertex_id_map::operator[]().
void Agent::initComplete ()
Complete agent initialization.
Thsi function should be called before starting to execute an agent mission. It specifies to the agent that the initialization has been completed. This method makes final checks that :
the agent name is not empty
the agent have a clock associated
there's no cyclic dependencies between reactors
It will also use a TREX::agent::details::init_visitor to ensure that all the reactors can complete their initialization Finally it starts the clock alllowing the mission to be executed
See also:
TREX::agent::details::init_visitor
setClock(Clock *)
Exceptions:
CycleDetected There's a cyclic dependency between the reactors of this agent
AgentException The eagent is not correctly initialized
Definition at line 423 of file Agent.cc.
References TREX::transaction::graph::cleanup(), TREX::agent::Clock::doStart(), TREX::transaction::graph::empty(), TREX::utils::LogManager::file_name(), and TREX::transaction::graph::getName().
Referenced by run().
graph::reactor_id graph::isolate (graph::reactor_id r) const [inherited]
Isolate a reactor.
Parameters:
[in] r A reactor
Disconnect the ractor r in this graph. Disconnecting a reactor correspond to disable all timeline declarations made by this reactor inside this graph.
Note:
After this operation the graph still belongs to the graph, it is just not connected to any other reactor anymore.
Return values:
@p r or null_reactor() if r did not belong to this graph
Postcondition:
if r did belong to this graph it is added to the set of reactor to be killed during the next cleanup operation
See also:
cleanup()
Definition at line 143 of file reactor_graph.cc.
References TREX::utils::list_set< IdTraits, Cmp >::find(), and TREX::utils::list_set< IdTraits, Cmp >::insert().
Referenced by TREX::agent::details::init_visitor::finish_vertex().
bool graph::kill_reactor (graph::reactor_id r) [inherited]
Kill a reactor.
[in] r A reactor
Disconnect and remove r from this graph
Return values:
true the reactor was successfully removed
false r did not belong to this graph
Postcondition:
r does not belong to this graph
See also:
isolate()
Definition at line 126 of file reactor_graph.cc.
References TREX::utils::list_set< IdTraits, Cmp >::erase(), and TREX::utils::list_set< IdTraits, Cmp >::find().
Referenced by TREX::transaction::graph::cleanup().
bool Agent::missionCompleted ()
Check if mission is completed.
This methods indicates whehter tha mission of this agent has finished or not. Reasons for an agent to finish are one of the following:
the time of the clock is greater or equal to the deadline initially provided for this agent
the agent does not have anymore reactor in its graph
Return values:
true if the mission is finished
false otherwise
Definition at line 311 of file Agent.cc.
References TREX::transaction::graph::count_reactors(), and TREX::transaction::graph::getCurrentTick().
Referenced by doNext().
reactor_iterator TREX::transaction::graph::reactor_begin () const [inline, inherited]
Beginning reactor iterator.
Returns:
a reactor_iterator pointing to the beginning of the reactors set maintained by this graph
See also:
reactor_end() const
Definition at line 528 of file reactor_graph.hh.
References TREX::utils::list_set< IdTraits, Cmp >::begin().
Referenced by TREX::transaction::graph::vertices().
reactor_iterator TREX::transaction::graph::reactor_end () const [inline, inherited]
End reactor iterator.
Returns:
a reactor_iterator pointing to the end of the reactors set maintained by this graph
See also:
reactor_begin() const
Definition at line 537 of file reactor_graph.hh.
References TREX::utils::list_set< IdTraits, Cmp >::end().
Referenced by TREX::transaction::graph::vertices().
void Agent::run ()
run the agent
This method runs the agent until its completes. It is just a simple utility method taht will call initComplete and then loop on a doNext() call untils this one returns false
Precondition:
The agent have a clock set
See also:
intiComplete()
doNext()
Definition at line 456 of file Agent.cc.
References doNext(), and initComplete().
void TREX::agent::Agent::sendRequest (boost::property_tree::ptree::value_type & g) [inline]
Post a goal from xml.
Parameters:
[in] g A goal in xml
This method will insert the goal defined by xml structure g
See also:
TREX::transaction::Goal::Goal(rapidxml::xml_node<> &)
sendRequest(TREX::transaction::goal_id const &)
sendRequests(TREX::utils::ext_iterator &)
Definition at line 337 of file Agent.hh.
References sendRequest().
void Agent::sendRequest (TREX::transaction::goal_id const & g)
Post a goal.
Parameters:
[in] g A goal This method will add the goal g to the agent. This goal will be posted to whichever reactor owns the timeline associated to g
Definition at line 536 of file Agent.cc.
Referenced by sendRequest(), and sendRequests().
size_t Agent::sendRequests (boost::property_tree::ptree & g)
Post a goals from xml.
Parameters:
[in] g A xml iterator
This method will insert all the goals that are acessibles by iterating through g
See also:
TREX::transaction::Goal::Goal(rapidxml::xml_node<> &)
sendRequest(rapidxml::xml_node<> &)
Definition at line 542 of file Agent.cc.
References sendRequest().
bool Agent::setClock (Clock * clock)
Set agent clock.
Parameters:
[in] clock A clock
If the agent did not have a clock yet it is then associated to clock. Otherwise clock will be deleted
Return values:
true clock is now the clock of this agent
false this agent had already a clock and deleted clock
Precondition:
clock has been allocated in memory using the new operator
Postcondition:
the laifetime of clock is now taken coare by this agent. Do note that this post-condition is true no matter what value has been returned by this function.
Definition at line 323 of file Agent.cc.
double TREX::agent::Agent::tickDuration () const [inline, virtual]
get tick duration
This method provides the tick duration in real-time in order to allow to convert tick varelated values into a real-time value
Returns:
The tick duration
Note:
This method is not usefull at the graph level and is more used by the Agent. It may be refactored in roder to keep the graph class as simple as possible.
See also:
tickToTime(TICK) const
timeToTick(time_t, suseconds_t) const
Reimplemented from TREX::transaction::graph.
Definition at line 353 of file Agent.hh.
References TREX::agent::Clock::tickDuration().
double TREX::agent::Agent::tickToTime (TREX::transaction::TICK cur) const [inline, virtual]
convert a TICK into its real-time equivalent
Parameters:
cur A TICK date
This method provides an utility to convert a TICK value into its real-time equivalent
Returns:
a float representing the date (usually in seconds) corresponding to the tTICK cur
Note:
This method is not usefull at the graph level and is more used by the Agent. It may be refactored in roder to keep the graph class as simple as possible.
See also:
tickDuration() const
timeToTick(time_t, suseconds_t) const
Reimplemented from TREX::transaction::graph.
Definition at line 360 of file Agent.hh.
TREX::transaction::TICK TREX::agent::Agent::timeToTick (time_t secs, suseconds_t usecs = 0) const [inline, virtual]
convert real-time into a TICK
Parameters:
secs Number of seconds
usecs Micro seconds
This method provides an utility to convert a real-time date into a TICK value
Returns:
the TICK equalent to the time sepresented by secs seconds and usecs microseconds
Note:
This method is not usefull at the graph level and is more used by the Agent. It may be refactored in roder to keep the graph class as simple as possible.
See also:
tickDuration() const
tickToTime(TICK) const
Reimplemented from TREX::transaction::graph.
Definition at line 357 of file Agent.hh.
The documentation for this class was generated from the following files:
trex/agent/Agent.hh
trex/agent/Agent.cc