trex: TREX::transaction::IntegerDomain Class Reference
TREX::transaction::IntegerDomain Class Reference
Domains
Integer domain.
#include <trex/domain/IntegerDomain.hh>
Public Types
typedef long base_type
subjacent type for interval
typedef
TREX::utils::XmlFactory
< DomainBase,
boost::shared_ptr< DomainBase > > xml_factory
XML parsing factory for domains.
Public Member Functions
longconst & closestTo (longconst &val) const
Closest value.
bool contains (longconst &val) const
Check for inclusion.
DomainBase * copy () const
Duplicate method.
bool equals (DomainBase const &other) const
Equality test.
void getBounds (bound &lo, bound &hi) const
Get interval bounds.
boost::any getLower () const
boost::any getSingleton () const
singleton value
virtual std::string getStringLower () const
std::string getStringSingleton () const
singleton value
virtual std::string getStringUpper () const
template<class Ty , bool Safe>
Ty getTypedLower () const
template<class Ty , bool Safe>
Ty getTypedSingleton () const
singleton value
template<class Ty , bool Safe>
Ty getTypedUpper () const
TREX::utils::Symbol const & getTypeName () const
type of the domain
boost::any getUpper () const
bool hasLower () const
bool hasUpper () const
IntegerDomain ()
Constructor.
IntegerDomain (boost::property_tree::ptree::value_type &node)
Constructor.
IntegerDomain (IntervalDomain< long >::bound const &lb, IntervalDomain< long >::bound const ub)
Constructor.
IntegerDomain (long val)
Constructor.
bool intersect (DomainBase const &other) const
check for common values
bool isEnumerated () const
Check for enumerated domain.
bool isFull () const
check for full domain
bool isInterval () const
Check for interval domain.
bool isSingleton () const
check for singleton value
bound const & lowerBound () const
interval lower bound
DomainBase & operator*= (DomainBase const &other)
Restrict domain possible values.
DomainBase & restrictWith (bound const &lo, bound const &hi)
Restrict domain possible values.
DomainBase & restrictWith (DomainBase const &other)
Restrict domain possible values.
std::ostream & toXml (std::ostream &out, size_t tabs) const
XML conversion.
bound const & upperBound () const
interval upper bound
~IntegerDomain ()
Destructor.
Static Public Attributes
static bound const minus_inf
Minus infinity bound.
static bound const plus_inf
Plus infinity bound.
static TREX::utils::Symbol const type_name
Symbolic type name for this domain.
Protected Member Functions
void completeParsing (boost::property_tree::ptree::value_type &node)
Friends
std::ostream & std::operator<< (std::ostream &out, TREX::utils::ostreamable const &x)
Detailed Description
Integer domain.
This class implements a a domain used to describe integers. The symbolic type name for this class is "int" and it fully support XML serialization.
Author:
Frederic Py fpy@m.nosp@m.bari.nosp@m..org
Definition at line 60 of file IntegerDomain.hh.
Member Typedef Documentation
typedef TREX::utils::XmlFactory<DomainBase, boost::shared_ptr<DomainBase> > TREX::transaction::DomainBase::xml_factory [inherited]
XML parsing factory for domains.
This type defines the factory that should be manipulated for parsing domains from xml.
Definition at line 403 of file DomainBase.hh.
Constructor & Destructor Documentation
TREX::transaction::IntegerDomain::IntegerDomain () [inline]
Constructor.
Create a full integer domain
Definition at line 75 of file IntegerDomain.hh.
Referenced by copy().
TREX::transaction::IntegerDomain::IntegerDomain (boost::property_tree::ptree::value_type & node) [inline]
Constructor.
Parameters:
node A XML node
Create a integer domain by parsing node.
Exceptions:
TREX::utils::bad_string_cast One of the attributes is not correctly formatted
EmptyDomain the resulting interval is empty
Definition at line 87 of file IntegerDomain.hh.
TREX::transaction::IntegerDomain::IntegerDomain (IntervalDomain< long >::bound const & lb, IntervalDomain< long >::bound const ub) [inline]
Constructor.
Parameters:
lb A lower bound
ub An upper bound
Create an integer domain represented by the interval [lb, ub]
Precondition:
[lb, ub] is a valid interval (ie not empty)
Exceptions:
EmptyDomain the resulting domain is empty
Definition at line 97 of file IntegerDomain.hh.
TREX::transaction::IntegerDomain::IntegerDomain (long val) [inline]
Constructor.
Parameters:
val A value
Create a new integer domain with only the value val. in other terms the domain is represented by the interval [val, val]
Definition at line 107 of file IntegerDomain.hh.
Member Function Documentation
long const& TREX::transaction::IntervalDomain< long , std::less<long > >::closestTo (long const & val) const [inline, inherited]
Closest value.
Parameters:
val A value
This method is a simplae utility that gives the value of the domain which is the closest to val.
It is generally iused when one want to get a singleton value even if the domain is not a singleton
Return values:
lowerBound() if val < lowerBound()
upperBound() if val > upperBound()
val otherwise
Definition at line 417 of file IntervalDomain.hh.
bool TREX::transaction::IntervalDomain< long , std::less<long > >::contains (long const & val) const [inline, inherited]
Check for inclusion.
Parameters:
val A value
This method is used to check if val is part of the domain
Return values:
true if is member of te domain
false otherwise
Definition at line 400 of file IntervalDomain.hh.
DomainBase* TREX::transaction::IntegerDomain::copy () const [inline, virtual]
Duplicate method.
Create a new instance which is identical to current instance value. This instance is usually created using the new operator and it is up to the caller to de-allocate it when not needed.
Returns:
The newly created instance
Implements TREX::transaction::DomainBase.
Definition at line 112 of file IntegerDomain.hh.
References IntegerDomain().
bool TREX::transaction::IntervalDomain< long , std::less<long > >::equals (DomainBase const & other) const [virtual, inherited]
Equality test.
Parameters:
other Another instance
Checks if current instance is identical to other. This generally means that both have the same type and exactly the same possible values. In that sense it is more restrictive than the intersect method.
Return values:
true if current instance is identical to other
false otherwise
See also:
bool intersect(DomainBase const &other) const
Implements TREX::transaction::DomainBase.
void TREX::transaction::IntervalDomain< long , std::less<long > >::getBounds (bound & lo, bound & hi) const [inline, inherited]
Get interval bounds.
Parameters:
lo a reference to a bound variable
hi a reference to a bound variable
Store the bounds of this interval in lo and hi.
Precondition:
lo and hi do not refer to the same varaiable
Postcondition:
lo stores the lower bound value of this interval
hi stores the upper bound value of this interval
See also:
bound const &lowerBound() const
bound const &upperBound() const
Definition at line 494 of file IntervalDomain.hh.
boost::any DomainBase::getSingleton () const [inherited]
singleton value
This methods give acces to the value of a singleton instance.
Precondition:
the instance is a singleton
Exceptions:
DomainAccess the insatnce was not a singleton
Returns:
The value of the domain encapsulated in a boost::any
Note:
except for the control of the instance being a singleton the actual code of this method will be provided by the virtual method singleton()
See also:
boost::any singleton() const
getStringSingleton() const
getTypedSingleton() const
Definition at line 56 of file DomainBase.cc.
References TREX::transaction::DomainBase::isSingleton(), and TREX::transaction::DomainBase::singleton().
Referenced by TREX::transaction::DomainBase::getTypedSingleton().
std::string DomainBase::getStringSingleton () const [inherited]
singleton value
This methods give acces to the value of a singleton instance represented as a string
Precondition:
the instance is a singleton
Exceptions:
DomainAccess the insatnce was not a singleton
Returns:
The text representation of the singleton value
Note:
except for the control of the instance being a singleton the actual code of this method will be provided by the virtual method stringSingleton()
See also:
std::string stringSingleton() const
getStringSingleton() const
getTypedSingleton() const
Definition at line 62 of file DomainBase.cc.
References TREX::transaction::DomainBase::isSingleton(), and TREX::transaction::DomainBase::stringSingleton().
Referenced by TREX::transaction::DomainBase::getTypedSingleton().
template<class Ty , bool Safe> Ty TREX::transaction::DomainBase::getTypedSingleton () const [inline, inherited]
singleton value
Template Parameters:
Ty output type
Safe robust conversion
This methods give acces to the value of a singleton instance The output will be of type Ty
The Safe parameter indicates which method should be used.
If the real type of the underneath domain type is guaranteed to be Ty the Safe can be false for performance
If the type is not guaranteed to be Ty but its text representation is compatible with Ty the Safe should be true
Precondition:
the instance is a singleton
the type of the value manip[ulated by this domain should be convertible to Ty or exactly Ty is Safe is false
Exceptions:
DomainAccess the insatnce was not a singleton
boost::bad_string_cast Safe is true and the value of the singleton cannot be parse into Ty
boost::bad_string_cast Safe is false and the type of the singleton is not Ty
Returns:
The singleton value of this domain
See also:
getStringSingleton() const
getSingleton() const
Definition at line 368 of file DomainBase.hh.
References TREX::transaction::DomainBase::getSingleton(), TREX::transaction::DomainBase::getStringSingleton(), and TREX::utils::string_cast().
Referenced by TREX::europa::details::europa_domain::visit().
TREX::utils::Symbol const& TREX::transaction::DomainBase::getTypeName () const [inline, inherited]
type of the domain
This method indicates the type of this domain. The type is a symbol that describes what is the type manipulated by this domain.
Returns:
the type associated to this domain
Definition at line 223 of file DomainBase.hh.
Referenced by TREX::transaction::BooleanDomain::equals(), TREX::transaction::EnumeratedDomain< Ty, Comp >::equals(), TREX::transaction::BooleanDomain::intersect(), TREX::transaction::EnumeratedDomain< Ty, Comp >::intersect(), TREX::transaction::BooleanDomain::restrictWith(), TREX::transaction::EnumeratedDomain< Ty, Comp >::restrictWith(), TREX::transaction::BasicEnumerated::toXml(), TREX::transaction::BasicInterval::toXml(), and TREX::europa::details::europa_domain::visit().
bool TREX::transaction::IntervalDomain< long , std::less<long > >::intersect (DomainBase const & other) const [virtual, inherited]
check for common values
Parameters:
other another instance
This methods indicates if current instance share values with other. This generally means that both have the same type and that one can safely restrict the domain of the other.
Return values:
true if current instance shares values with other
false otherwise
See also:
bool equals(DomainBase const &other) const
DomainBase &restrictWith(DomainBase const &other)
Implements TREX::transaction::DomainBase.
bool TREX::transaction::BasicInterval::isEnumerated () const [inline, virtual, inherited]
Check for enumerated domain.
This method check if the domain is based on an enumerated representation. In which case its representation is based on the list of all the possible values.
Return values:
true if the domain is enumeration based
false otherwise
See also:
bool isInterval() const
Implements TREX::transaction::DomainBase.
Definition at line 70 of file BasicInterval.hh.
bool TREX::transaction::BasicInterval::isFull () const [inline, virtual, inherited]
check for full domain
This method identifies if current domain is full. A full domain is adomain that includes al the possibles values for its type.
Return values:
true if current instance is full
false otherwise
Implements TREX::transaction::DomainBase.
Reimplemented in TREX::transaction::BooleanDomain.
Definition at line 77 of file BasicInterval.hh.
Referenced by TREX::europa::details::europa_domain::visit().
bool TREX::transaction::BasicInterval::isInterval () const [inline, virtual, inherited]
Check for interval domain.
This method is used to identify if this domain is an interval based domain. In which case it is represented by a lower and upper bound.
Return values:
true if the domain is interval based
false otherwise
See also:
bool isEnumerated() const
Implements TREX::transaction::DomainBase.
Definition at line 67 of file BasicInterval.hh.
bool TREX::transaction::IntervalDomain< long , std::less<long > >::isSingleton () const [inline, virtual, inherited]
check for singleton value
This method identifies if current domain is a singleton. A singleton domain is defined by one and only one value.
Return values:
true if current instance is a singleton
false otherwise
Implements TREX::transaction::DomainBase.
Definition at line 463 of file IntervalDomain.hh.
bound const& TREX::transaction::IntervalDomain< long , std::less<long > >::lowerBound () const [inline, inherited]
interval lower bound
Returns:
the lower bound of the interval for this domain
See also:
bound const &upperBound() const
void getBounds(bound &, bound&) vonst
Definition at line 450 of file IntervalDomain.hh.
DomainBase& TREX::transaction::DomainBase::operator*= (DomainBase const & other) [inline, inherited]
Restrict domain possible values.
Parameters:
other Another domain
This method restrict the domain of current instance to the values that are shared by this domain and other.
Precondition:
this domain intersect other
Returns:
this domain after the operation
Exceptions:
EmptyDomain resulting domain is empty
See also:
bool intersect(DomainBase const &) const
Definition at line 280 of file DomainBase.hh.
References TREX::transaction::DomainBase::restrictWith().
DomainBase& TREX::transaction::IntervalDomain< long , std::less<long > >::restrictWith (bound const & lo, bound const & hi) [inherited]
Restrict domain possible values.
Parameters:
lo minimum value
hi maximum value
This method restrict the domain of current instance to tits subset included in [lo, hi]
Precondition:
[lo, hi] is a valid interval
this domain intersect [lo, hi]
Returns:
this domain after the operation
Exceptions:
EmptyDomain resulting domain is empty
DomainBase& TREX::transaction::IntervalDomain< long , std::less<long > >::restrictWith (DomainBase const & other) [virtual, inherited]
Restrict domain possible values.
Parameters:
other Another domain
This method restrict the domain of current instance to the values that are shared by this domain and other.
Precondition:
this domain intersect other
Returns:
this domain after the operation
Exceptions:
EmptyDomain resulting domain is empty
See also:
bool intersect(DomainBase const &) const
Implements TREX::transaction::DomainBase.
std::ostream & BasicInterval::toXml (std::ostream & out, size_t tabs) const [virtual, inherited]
XML conversion.
Parameters:
out An output stream
tabs indentation level
This methods writes an XML representation of the domain into the output stream out. The tabs attribute indicates the indentation level expected for the tags.
Note:
To ensure compatibility this method should produce an xml output which is compatible with the XML parsing constructor of this domain.
Returns:
out after the operation
See also:
DomainBase(rapidxml::xml_node<> const &)
xml_factory
Implements TREX::transaction::DomainBase.
Reimplemented in TREX::transaction::BooleanDomain.
Definition at line 80 of file BasicInterval.cc.
References TREX::transaction::DomainBase::getTypeName().
bound const& TREX::transaction::IntervalDomain< long , std::less<long > >::upperBound () const [inline, inherited]
interval upper bound
Returns:
the upper bound of the interval for this domain
See also:
bound const &lowerBound() const
void getBounds(bound &, bound&) vonst
Definition at line 459 of file IntervalDomain.hh.
Member Data Documentation
bound const TREX::transaction::IntervalDomain< long , std::less<long > >::minus_inf [static, inherited]
Minus infinity bound.
This static attribute gives access to the minus infinity value for a bound.
Definition at line 351 of file IntervalDomain.hh.
bound const TREX::transaction::IntervalDomain< long , std::less<long > >::plus_inf [static, inherited]
Plus infinity bound.
This static attribute gives access to the plus infinity value for a bound.
Definition at line 345 of file IntervalDomain.hh.
Referenced by TREX::transaction::Goal::startsAfter().
Symbol const IntegerDomain::type_name [static]
Symbolic type name for this domain.
This static attibute gives an access to the symbolic name used for IntegerDomain. As stated in the main class description its value is "int" but programmers who want to use this name would better use this variable in case it changes in the future
Definition at line 69 of file IntegerDomain.hh.
The documentation for this class was generated from the following files:
trex/domain/IntegerDomain.hh
trex/domain/DomainImpl.cc