trex: TREX::europa::EuropaProxy Class Reference
TREX::europa::EuropaProxy Class Reference
A proxy between Europa domains and TREX domains.
#include <extra/europa.old/EuropaProxy.hh>
Public Types
typedef
TREX::utils::XmlFactory
< DomainBase,
boost::shared_ptr< DomainBase > > xml_factory
XML parsing factory for domains.
Public Member Functions
virtual void accept (DomainVisitor &visitor) const
Visiting method.
TREX::transaction::DomainBase * copy () const
Duplicate method.
TREX::transaction::DomainBase * copy () const
Duplicate method.
bool equals (TREX::transaction::DomainBase const &other) const
Equality test.
bool equals (TREX::transaction::DomainBase const &other) const
Equality test.
EUROPA::Domain const & europaDomain () const
EUROPA::Domain const & europaDomain () const
EuropaProxy (EuropaProxy const &other)
EuropaProxy (EUROPA::Domain const &dom)
EuropaProxy (EuropaProxy const &other)
EuropaProxy (EUROPA::Domain const &dom)
boost::any getSingleton () const
singleton value
std::string getStringSingleton () const
singleton value
template<class Ty , bool Safe>
Ty getTypedSingleton () const
singleton value
TREX::utils::Symbol const & getTypeName () const
type of the domain
bool intersect (TREX::transaction::DomainBase const &other) const
check for common values
bool intersect (TREX::transaction::DomainBase const &other) const
check for common values
bool isEnumerated () const
Check for enumerated domain.
bool isEnumerated () const
Check for enumerated domain.
bool isFull () const
check for full domain
bool isFull () const
check for full domain
bool isInterval () const
Check for interval domain.
bool isInterval () const
Check for interval domain.
bool isSingleton () const
check for singleton value
bool isSingleton () const
check for singleton value
DomainBase & operator*= (DomainBase const &other)
Restrict domain possible values.
TREX::transaction::DomainBase & restrictWith (TREX::transaction::DomainBase const &other)
Restrict domain possible values.
TREX::transaction::DomainBase & restrictWith (TREX::transaction::DomainBase const &other)
Restrict domain possible values.
std::ostream & toXml (std::ostream &out, size_t tabs) const
XML conversion.
std::ostream & toXml (std::ostream &out, size_t tabs) const
XML conversion.
Static Public Attributes
static TREX::utils::Symbol const type_name
Friends
std::ostream & std::operator<< (std::ostream &out, TREX::utils::ostreamable const &x)
Detailed Description
A proxy between Europa domains and TREX domains.
This class acts as a proxy in order to make europa Domain instances easily accessible for TREX. It behave as a tempraray proxy that llow TREX to access to a domain information without necessary requireing to convert this domain into its TREX counterpart. The copy of an instance of this class will do the conversion of the europa domain into a its TREX domain representation.
Note:
This lcass is really meant to be used as a temporary proxy to ease the whole europa to trex conversion process. It is not really meant for a more classic trex domain usage and we do recommend to copy a EuropaProxy before doing many extra manipulation.
Bug:
Many of the methods here are actually doinfg the domain conversion under the hood and it may be worthwhile to cache such conversion instead of doing it every time one of these call is made.
Author:
Frederic Py <fpy@mbari.org>
This class acts as a proxy in order to make europa Domain instances easily accessible for TREX. It behave as a tempraray proxy that llow TREX to access to a domain information without necessary requireing to convert this domain into its TREX counterpart. The copy of an instance of this class will do the conversion of the europa domain into a its TREX domain representation.
Note:
This lcass is really meant to be used as a temporary proxy to ease the whole europa to trex conversion process. It is not really meant for a more classic trex domain usage and we do recommend to copy a EuropaProxy before doing many extra manipulation.
Bug:
Many of the methods here are actually doinfg the domain conversion under the hood and it may be worthwhile to cache such conversion instead of doing it every time one of these call is made.
Author:
Frederic Py <fpy@mbari.org>
Definition at line 67 of file EuropaProxy.hh.
Member Typedef Documentation
typedef TREX::utils::XmlFactory<DomainBase, boost::shared_ptr<DomainBase> > TREX::transaction::DomainBase::xml_factory [inherited]
XML parsing factory for domains.
This type defines the factory that should be manipulated for parsing domains from xml.
Definition at line 403 of file DomainBase.hh.
Member Function Documentation
void DomainBase::accept (DomainVisitor & visitor) const [virtual, inherited]
Visiting method.
Parameters:
visitor A domain visitor
This method implement the Visitor design pattern for TREX domains. It will call visitor methods depending on the actual type of this instance.
There's 3 possible cases supported :
this class is a BasicInterval instance
this class is a BasicEnumerated instance
this class is none of the above
in each case the corresponding method of visitor will be called
See also:
DomainVisitor
Definition at line 52 of file DomainBase.cc.
References TREX::transaction::DomainVisitor::visit().
Referenced by TREX::europa::EuropaDomain::equals(), equals(), TREX::europa::EuropaDomain::intersect(), intersect(), TREX::europa::EuropaDomain::restrictWith(), and restrictWith().
TREX::transaction::DomainBase* TREX::europa::EuropaProxy::copy () const [virtual]
Duplicate method.
Create a new instance which is identical to current instance value. This instance is usually created using the new operator and it is up to the caller to de-allocate it when not needed.
Returns:
The newly created instance
Implements TREX::transaction::DomainBase.
DomainBase * EuropaProxy::copy () const [virtual]
Duplicate method.
Create a new instance which is identical to current instance value. This instance is usually created using the new operator and it is up to the caller to de-allocate it when not needed.
Returns:
The newly created instance
Implements TREX::transaction::DomainBase.
Definition at line 280 of file EuropaDomains.cc.
Referenced by toXml().
bool TREX::europa::EuropaProxy::equals (TREX::transaction::DomainBase const & other) const [virtual]
Equality test.
Parameters:
other Another instance
Checks if current instance is identical to other. This generally means that both have the same type and exactly the same possible values. In that sense it is more restrictive than the intersect method.
Return values:
true if current instance is identical to other
false otherwise
See also:
bool intersect(DomainBase const &other) const
Implements TREX::transaction::DomainBase.
bool EuropaProxy::equals (TREX::transaction::DomainBase const & other) const [virtual]
Equality test.
Parameters:
other Another instance
Checks if current instance is identical to other. This generally means that both have the same type and exactly the same possible values. In that sense it is more restrictive than the intersect method.
Return values:
true if current instance is identical to other
false otherwise
See also:
bool intersect(DomainBase const &other) const
Implements TREX::transaction::DomainBase.
Definition at line 266 of file EuropaDomains.cc.
References TREX::transaction::DomainBase::accept().
boost::any DomainBase::getSingleton () const [inherited]
singleton value
This methods give acces to the value of a singleton instance.
Precondition:
the instance is a singleton
Exceptions:
DomainAccess the insatnce was not a singleton
Returns:
The value of the domain encapsulated in a boost::any
Note:
except for the control of the instance being a singleton the actual code of this method will be provided by the virtual method singleton()
See also:
boost::any singleton() const
getStringSingleton() const
getTypedSingleton() const
Definition at line 56 of file DomainBase.cc.
References TREX::transaction::DomainBase::isSingleton(), and TREX::transaction::DomainBase::singleton().
std::string DomainBase::getStringSingleton () const [inherited]
singleton value
This methods give acces to the value of a singleton instance represented as a string
Precondition:
the instance is a singleton
Exceptions:
DomainAccess the insatnce was not a singleton
Returns:
The text representation of the singleton value
Note:
except for the control of the instance being a singleton the actual code of this method will be provided by the virtual method stringSingleton()
See also:
std::string stringSingleton() const
getStringSingleton() const
getTypedSingleton() const
Definition at line 62 of file DomainBase.cc.
References TREX::transaction::DomainBase::isSingleton(), and TREX::transaction::DomainBase::stringSingleton().
template<class Ty , bool Safe> Ty TREX::transaction::DomainBase::getTypedSingleton () const [inline, inherited]
singleton value
Template Parameters:
Ty output type
Safe robust conversion
This methods give acces to the value of a singleton instance The output will be of type Ty
The Safe parameter indicates which method should be used.
If the real type of the underneath domain type is guaranteed to be Ty the Safe can be false for performance
If the type is not guaranteed to be Ty but its text representation is compatible with Ty the Safe should be true
Precondition:
the instance is a singleton
the type of the value manip[ulated by this domain should be convertible to Ty or exactly Ty is Safe is false
Exceptions:
DomainAccess the insatnce was not a singleton
boost::bad_string_cast Safe is true and the value of the singleton cannot be parse into Ty
boost::bad_string_cast Safe is false and the type of the singleton is not Ty
Returns:
The singleton value of this domain
See also:
getStringSingleton() const
getSingleton() const
Definition at line 368 of file DomainBase.hh.
References TREX::utils::string_cast().
TREX::utils::Symbol const& TREX::transaction::DomainBase::getTypeName () const [inline, inherited]
type of the domain
This method indicates the type of this domain. The type is a symbol that describes what is the type manipulated by this domain.
Returns:
the type associated to this domain
Definition at line 223 of file DomainBase.hh.
Referenced by TREX::transaction::EnumeratedDomain< Ty, Comp >::equals(), TREX::transaction::BooleanDomain::equals(), TREX::transaction::EnumeratedDomain< Ty, Comp >::intersect(), TREX::transaction::BooleanDomain::intersect(), TREX::transaction::EnumeratedDomain< Ty, Comp >::restrictWith(), TREX::transaction::BooleanDomain::restrictWith(), TREX::transaction::BasicInterval::toXml(), TREX::transaction::BasicEnumerated::toXml(), and TREX::europa::details::europa_domain::visit().
bool TREX::europa::EuropaProxy::intersect (TREX::transaction::DomainBase const & other) const [virtual]
check for common values
Parameters:
other another instance
This methods indicates if current instance share values with other. This generally means that both have the same type and that one can safely restrict the domain of the other.
Return values:
true if current instance shares values with other
false otherwise
See also:
bool equals(DomainBase const &other) const
DomainBase &restrictWith(DomainBase const &other)
Implements TREX::transaction::DomainBase.
bool EuropaProxy::intersect (TREX::transaction::DomainBase const & other) const [virtual]
check for common values
Parameters:
other another instance
This methods indicates if current instance share values with other. This generally means that both have the same type and that one can safely restrict the domain of the other.
Return values:
true if current instance shares values with other
false otherwise
See also:
bool equals(DomainBase const &other) const
DomainBase &restrictWith(DomainBase const &other)
Implements TREX::transaction::DomainBase.
Definition at line 252 of file EuropaDomains.cc.
References TREX::transaction::DomainBase::accept().
bool TREX::europa::EuropaProxy::isEnumerated () const [inline, virtual]
Check for enumerated domain.
This method check if the domain is based on an enumerated representation. In which case its representation is based on the list of all the possible values.
Return values:
true if the domain is enumeration based
false otherwise
See also:
bool isInterval() const
Implements TREX::transaction::DomainBase.
Definition at line 82 of file EuropaProxy.hh.
bool TREX::europa::EuropaProxy::isEnumerated () const [inline, virtual]
Check for enumerated domain.
This method check if the domain is based on an enumerated representation. In which case its representation is based on the list of all the possible values.
Return values:
true if the domain is enumeration based
false otherwise
See also:
bool isInterval() const
Implements TREX::transaction::DomainBase.
Definition at line 82 of file EuropaProxy.hh.
bool TREX::europa::EuropaProxy::isFull () const [virtual]
check for full domain
This method identifies if current domain is full. A full domain is adomain that includes al the possibles values for its type.
Return values:
true if current instance is full
false otherwise
Implements TREX::transaction::DomainBase.
bool EuropaProxy::isFull () const [virtual]
check for full domain
This method identifies if current domain is full. A full domain is adomain that includes al the possibles values for its type.
Return values:
true if current instance is full
false otherwise
Implements TREX::transaction::DomainBase.
Definition at line 236 of file EuropaDomains.cc.
bool TREX::europa::EuropaProxy::isInterval () const [inline, virtual]
Check for interval domain.
This method is used to identify if this domain is an interval based domain. In which case it is represented by a lower and upper bound.
Return values:
true if the domain is interval based
false otherwise
See also:
bool isEnumerated() const
Implements TREX::transaction::DomainBase.
Definition at line 79 of file EuropaProxy.hh.
bool TREX::europa::EuropaProxy::isInterval () const [inline, virtual]
Check for interval domain.
This method is used to identify if this domain is an interval based domain. In which case it is represented by a lower and upper bound.
Return values:
true if the domain is interval based
false otherwise
See also:
bool isEnumerated() const
Implements TREX::transaction::DomainBase.
Definition at line 79 of file EuropaProxy.hh.
bool TREX::europa::EuropaProxy::isSingleton () const [inline, virtual]
check for singleton value
This method identifies if current domain is a singleton. A singleton domain is defined by one and only one value.
Return values:
true if current instance is a singleton
false otherwise
Implements TREX::transaction::DomainBase.
Definition at line 86 of file EuropaProxy.hh.
bool TREX::europa::EuropaProxy::isSingleton () const [inline, virtual]
check for singleton value
This method identifies if current domain is a singleton. A singleton domain is defined by one and only one value.
Return values:
true if current instance is a singleton
false otherwise
Implements TREX::transaction::DomainBase.
Definition at line 86 of file EuropaProxy.hh.
DomainBase& TREX::transaction::DomainBase::operator*= (DomainBase const & other) [inline, inherited]
Restrict domain possible values.
Parameters:
other Another domain
This method restrict the domain of current instance to the values that are shared by this domain and other.
Precondition:
this domain intersect other
Returns:
this domain after the operation
Exceptions:
EmptyDomain resulting domain is empty
See also:
bool intersect(DomainBase const &) const
Definition at line 280 of file DomainBase.hh.
TREX::transaction::DomainBase& TREX::europa::EuropaProxy::restrictWith (TREX::transaction::DomainBase const & other) [virtual]
Restrict domain possible values.
Parameters:
other Another domain
This method restrict the domain of current instance to the values that are shared by this domain and other.
Precondition:
this domain intersect other
Returns:
this domain after the operation
Exceptions:
EmptyDomain resulting domain is empty
See also:
bool intersect(DomainBase const &) const
Implements TREX::transaction::DomainBase.
DomainBase & EuropaProxy::restrictWith (TREX::transaction::DomainBase const & other) [virtual]
Restrict domain possible values.
Parameters:
other Another domain
This method restrict the domain of current instance to the values that are shared by this domain and other.
Precondition:
this domain intersect other
Returns:
this domain after the operation
Exceptions:
EmptyDomain resulting domain is empty
See also:
bool intersect(DomainBase const &) const
Implements TREX::transaction::DomainBase.
Definition at line 301 of file EuropaDomains.cc.
References TREX::transaction::DomainBase::accept().
std::ostream& TREX::europa::EuropaProxy::toXml (std::ostream & out, size_t tabs) const [virtual]
XML conversion.
Parameters:
out An output stream
tabs indentation level
This methods writes an XML representation of the domain into the output stream out. The tabs attribute indicates the indentation level expected for the tags.
Note:
To ensure compatibility this method should produce an xml output which is compatible with the XML parsing constructor of this domain.
Returns:
out after the operation
See also:
DomainBase(rapidxml::xml_node<> const &)
xml_factory
Implements TREX::transaction::DomainBase.
std::ostream & EuropaProxy::toXml (std::ostream & out, size_t tabs) const [virtual]
XML conversion.
Parameters:
out An output stream
tabs indentation level
This methods writes an XML representation of the domain into the output stream out. The tabs attribute indicates the indentation level expected for the tags.
Note:
To ensure compatibility this method should produce an xml output which is compatible with the XML parsing constructor of this domain.
Returns:
out after the operation
See also:
DomainBase(rapidxml::xml_node<> const &)
xml_factory
Implements TREX::transaction::DomainBase.
Definition at line 285 of file EuropaDomains.cc.
References copy().
The documentation for this class was generated from the following files:
extra/europa.old/EuropaProxy.hh
extra/europa2.old/EuropaProxy.hh
extra/europa.old/EuropaDomains.cc
extra/europa2.old/EuropaDomains.cc