trex: TREX::transaction::Observation Class Reference
TREX::transaction::Observation Class Reference
TREX transaction
Reactor observation.
#include <trex/transaction/Observation.hh>
Public Types
typedef attr_set::const_iterator const_iterator
Predicate attributes' const iterator.
typedef attr_set::iterator iterator
Predicate attributes' iterator.
typedef
TREX::utils::XmlFactory
< Predicate, boost::shared_ptr
< Predicate > > xml_factory
XML parsing factory for predicates.
Public Member Functions
iterator begin ()
beginning of the attributes set
const_iterator begin () const
beginning of the attributes set
iterator end ()
end of the attributes set
const_iterator end () const
end of the attributes set
virtual Variable const & getAttribute (TREX::utils::Symbol const &name) const
Attribute access.
template<class Ty >
Ty const & getDomain (TREX::utils::Symbol const &name) const
Attribute domain access.
bool hasAttribute (TREX::utils::Symbol const &name) const
Check for constrained attribute.
virtual void listAttributes (std::list< TREX::utils::Symbol > &attr, bool all=true) const
List predicate's attributes.
TREX::utils::Symbol const & object () const
Predicate object.
Observation (Predicate const &pred)
Copy constructor.
Observation (TREX::utils::Symbol const &obj, TREX::utils::Symbol const &pred)
Constructor.
Observation (boost::property_tree::ptree::value_type &node)
XML parsing constructor.
Variable const & operator[] (TREX::utils::Symbol const &name) const
Attribute access.
TREX::utils::Symbol const & predicate () const
predicate type
void restrictAttribute (TREX::utils::Symbol const &name, DomainBase const &domain)
attribute domain restriction
virtual void restrictAttribute (Variable const &var)
attribute domain restriction
std::ostream & toXml (std::ostream &out, size_t tabs=0) const
XML output.
~Observation ()
Protected Types
typedef std::map
< TREX::utils::Symbol,
Variable > attr_set
Type used to store predicate attributes.
Protected Member Functions
iterator find (TREX::utils::Symbol const &name)
Search for attribute.
virtual std::ostream & print_to (std::ostream &out) const
output method
void remove (iterator const &i)
removce an attribute
Friends
std::ostream & std::operator<< (std::ostream &out, TREX::utils::ostreamable const &x)
Detailed Description
Reactor observation.
This class encapsulate the latest observation on a timeline. Each time a timeline value changes/is updated the reactor owning this timeline is producing tis observation which in turn is dispatched to all the reactors tha observe the corresponding timeline.
See also:
void TeleoReactor::postObservation(Observation const &obs)
void TeleoReactor::notify(Observation const &obs)
Deprecated:
the current implementation of observations is not as flexible and transparent as desired and may change drastically in the future
Author:
Frederic Py fpy@m.nosp@m.bari.nosp@m..org
Definition at line 69 of file Observation.hh.
Member Typedef Documentation
typedef TREX::utils::XmlFactory< Predicate, boost::shared_ptr<Predicate> > TREX::transaction::Predicate::xml_factory [inherited]
XML parsing factory for predicates.
This defines a factory that allows to parse Predicate classes from XML.
Definition at line 307 of file Predicate.hh.
Constructor & Destructor Documentation
TREX::transaction::Observation::Observation (Predicate const & pred) [inline]
Copy constructor.
Parameters:
pred A predicate
Create a copy of pred as an observation
Definition at line 76 of file Observation.hh.
TREX::transaction::Observation::Observation (TREX::utils::Symbol const & obj, TREX::utils::Symbol const & pred) [inline]
Constructor.
Parameters:
obj A timline identifier
pred A predicate name
Create a new instance connected to timeline object with the state pred and all its attributes not constrained.
Definition at line 85 of file Observation.hh.
TREX::transaction::Observation::Observation (boost::property_tree::ptree::value_type & node) [inline]
XML parsing constructor.
Parameters:
node An XML node
Create a new instance by parsing the content of node. The expected format of node is
 <Observation on="<name>" pred="<name>">
   <!-- attribute definition -->
 </Observation>
Exceptions:
PredicateException Error while trying to parse
EmptyDomain A domain became empty during parsing
XmlError Another error while parsing
See also:
Variable::Variable(rapidxml::xml_node<> const &)
Predicate::Predicate(rapidxml::xml_node<> const &)
Definition at line 105 of file Observation.hh.
TREX::transaction::Observation::~Observation () [inline]
brief Destructor
Definition at line 108 of file Observation.hh.
Member Function Documentation
iterator TREX::transaction::Predicate::begin () [inline, inherited]
beginning of the attributes set
This method allows to iterate through the attributes of this predicate
Returns:
An iterator pointing to the beginning of the attributes' set
See also:
iterator end()
Definition at line 142 of file Predicate.hh.
Referenced by TREX::transaction::Predicate::listAttributes().
const_iterator TREX::transaction::Predicate::begin () const [inline, inherited]
beginning of the attributes set
This method allows to iterate through the attributes of this predicate
Returns:
An iterator pointing to the beginning of the attributes' set
See also:
const_iterator end() const
Definition at line 166 of file Predicate.hh.
iterator TREX::transaction::Predicate::end () [inline, inherited]
end of the attributes set
This method allows to iterate through the attributes of this predicate
Returns:
An iterator pointing to the end of the attributes' set
See also:
iterator begin()
Definition at line 154 of file Predicate.hh.
Referenced by TREX::transaction::Predicate::getAttribute(), TREX::transaction::Goal::Goal(), TREX::transaction::Predicate::hasAttribute(), TREX::transaction::Predicate::listAttributes(), and TREX::transaction::Predicate::restrictAttribute().
const_iterator TREX::transaction::Predicate::end () const [inline, inherited]
end of the attributes set
This method allows to iterate through the attributes of this predicate
Returns:
An iterator pointing to the end of the attributes' set
See also:
const_iterator begin() const
Definition at line 178 of file Predicate.hh.
iterator TREX::transaction::Predicate::find (TREX::utils::Symbol const & name) [inline, protected, inherited]
Search for attribute.
Parameters:
name Attribute name
This method search for attribute name
Return values:
An iterator pointing to the attribute name if it exists
end() if the attribute name is not found
Definition at line 356 of file Predicate.hh.
Referenced by TREX::transaction::Goal::Goal().
Variable const & Predicate::getAttribute (TREX::utils::Symbol const & name) const [virtual, inherited]
Attribute access.
Parameters:
name The name of an attribute
Precondition:
an attribute name should exist
Returns:
The varaible corresponding to the attribute name
Exceptions:
PredicateException Attribute name does not exist
See also:
template<class Ty> Ty const &getDomain(TREX::utils::Symbol const &) const
Reimplemented in TREX::transaction::Goal.
Definition at line 88 of file Predicate.cc.
References TREX::transaction::Predicate::end(), and TREX::utils::BasicSymbol< CharT, Traits, Alloc >::str().
Referenced by TREX::transaction::Predicate::getDomain(), TREX::transaction::Predicate::operator[](), TREX::transaction::Predicate::print_to(), and TREX::transaction::Predicate::toXml().
template<class Ty > Ty const& TREX::transaction::Predicate::getDomain (TREX::utils::Symbol const & name) const [inline, inherited]
Attribute domain access.
Template Parameters:
Ty the type of the domain
Parameters:
name The name of an attribute
Precondition:
Ty should inherit from DomainBase
Ty should be a base class of the domain associted to this Variable
an attribute name should exist
Returns:
The domain corresponding to the attribute name casted to domain class Ty
Exceptions:
PredicateException Attribute name does not exist
std::bad_cast Ty is not the correct domain
See also:
Variable &getDomain(TREX::utils::Symbol const &) const
template<class Ty> Ty const &Variable::typedDomain() const
Definition at line 253 of file Predicate.hh.
References TREX::transaction::Predicate::getAttribute(), and TREX::transaction::Variable::typedDomain().
bool TREX::transaction::Predicate::hasAttribute (TREX::utils::Symbol const & name) const [inline, inherited]
Check for constrained attribute.
Parameters:
name an attribute This methodsw checks if current instance explicitely defines the attribute name
Return values:
true if an attribute name is defined
false otherwise
Note:
the fact that a Predicate instance does not have an attribute just means that this attribute has not been constrained yet using the restrictAttribute method. It is mostly used to check for attribute existence when one wants to access to the domain associated to this attribute
See also:
Variable const &getAttribute(TREX::utils::Symbol const &) const
Definition at line 224 of file Predicate.hh.
References TREX::transaction::Predicate::end().
void Predicate::listAttributes (std::list< TREX::utils::Symbol > & attr, bool all = true) const [virtual, inherited]
List predicate's attributes.
attr A varaible to store the attribute names all A flag used to indicate whether it should list all existing attributes or only the ones with restricted domains (ie not full)
This method is adding the list of all the attributes names defined for this predicate at the end of attr. The all flag allows to indicate that we want all the defined attributes even if their domain is full (meaning they are not really constrained)
Postcondition:
attr list contains all the attributes appendded to it end
Reimplemented in TREX::transaction::Goal.
Definition at line 130 of file Predicate.cc.
References TREX::transaction::Predicate::begin(), and TREX::transaction::Predicate::end().
Referenced by TREX::transaction::Predicate::print_to(), and TREX::transaction::Predicate::toXml().
TREX::utils::Symbol const& TREX::transaction::Predicate::object () const [inline, inherited]
Predicate object.
This method indicates which object this predicate is associated to. In TREX this object has to be the name of a timeline shared between reactors.
Returns:
the name of the associated object
Definition at line 119 of file Predicate.hh.
Referenced by TREX::europa::EuropaReactor::notify(), TREX::transaction::TeleoReactor::postObservation(), and TREX::transaction::Predicate::toXml().
Variable const& TREX::transaction::Predicate::operator[] (TREX::utils::Symbol const & name) const [inline, inherited]
Attribute access.
Parameters:
name The name of an attribute
Precondition:
an attribute name should exist
Returns:
The varaible corresponding to the attribute name
Exceptions:
PredicateException Attribute name does not exist
See also:
Variable const &getAttribute(TREX::utils::Symbol const &) const
template<class Ty> Ty const &getDomain(TREX::utils::Symbol const &)
Definition at line 268 of file Predicate.hh.
References TREX::transaction::Predicate::getAttribute().
TREX::utils::Symbol const& TREX::transaction::Predicate::predicate () const [inline, inherited]
predicate type
This method indicates the type of the predicate. This type reflects the state of the associated object
Returns:
the type of the predicate
Definition at line 129 of file Predicate.hh.
Referenced by TREX::europa::EuropaReactor::notify(), and TREX::transaction::Predicate::toXml().
std::ostream & Predicate::print_to (std::ostream & out) const [protected, virtual, inherited]
output method
Parameters:
[in,out] out An output stream
This method is internally called by the standard output stream operator to write the value of current instance into out
See also:
std::ostream &operator<<(std::ostream &, ostreamable const &)
Implements TREX::utils::ostreamable.
Definition at line 95 of file Predicate.cc.
References TREX::transaction::Predicate::getAttribute(), and TREX::transaction::Predicate::listAttributes().
void TREX::transaction::Predicate::remove (iterator const & i) [inline, protected, inherited]
removce an attribute
Parameters:
i An iterator
remove the attribute pointed by i
Definition at line 364 of file Predicate.hh.
void TREX::transaction::Predicate::restrictAttribute (TREX::utils::Symbol const & name, DomainBase const & domain) [inline, inherited]
attribute domain restriction
Parameters:
name A attribute name
domain A domain
This method restrict the domain of the attribute name with the domain domain
Exceptions:
EmptyDomain The resulting domain for name is empty
See also:
void restrictAttribute(Variable const &)
Variable &restrict(Variable const &)
Definition at line 193 of file Predicate.hh.
Referenced by TREX::transaction::Predicate::Predicate().
void Predicate::restrictAttribute (Variable const & var) [virtual, inherited]
attribute domain restriction
Parameters:
var A varaible describing the attribute
This method restrict the domain of the attribute corresponding to var with the domain of var
Exceptions:
EmptyDomain The resulting domain for name is empty
See also:
void restrictAttribute(TREX::utils::Symbol const &, DomainBase const &)
Variable &restrict(Variable const &)
Reimplemented in TREX::transaction::Goal.
Definition at line 74 of file Predicate.cc.
References TREX::transaction::Predicate::end(), TREX::transaction::Variable::isComplete(), and TREX::transaction::Variable::name().
std::ostream & Predicate::toXml (std::ostream & out, size_t tabs = 0) const [inherited]
XML output.
Parameters:
out An output stream
tabs desired tags indentation
This method writes an XML form of current instance to out indented using tab.
The output excludes all the attributes that are not really constrained to reduce the size of this description.
Returns:
out after the operation
Definition at line 108 of file Predicate.cc.
References TREX::transaction::Predicate::getAttribute(), TREX::transaction::Predicate::getPredTag(), TREX::transaction::Predicate::listAttributes(), TREX::transaction::Predicate::object(), and TREX::transaction::Predicate::predicate().
The documentation for this class was generated from the following files:
trex/transaction/Observation.hh
trex/transaction/Observation.cc