trex: TREX::transaction::Goal Class Reference
TREX::transaction::Goal Class Reference
TREX transaction
TREX goal.
#include <trex/transaction/Goal.hh>
Public Types
typedef attr_set::const_iterator const_iterator
Predicate attributes' const iterator.
typedef attr_set::iterator iterator
Predicate attributes' iterator.
typedef
TREX::utils::XmlFactory
< Predicate, boost::shared_ptr
< Predicate > > xml_factory
XML parsing factory for predicates.
Public Member Functions
iterator begin ()
beginning of the attributes set
const_iterator begin () const
beginning of the attributes set
iterator end ()
end of the attributes set
const_iterator end () const
end of the attributes set
bool endsAfter (TICK date) const
Variable const & getAttribute (TREX::utils::Symbol const &name) const
Attribute access.
template<class Ty >
Ty const & getDomain (TREX::utils::Symbol const &name) const
Attribute domain access.
IntegerDomain const & getDuration () const
Get duration interval.
IntegerDomain const & getEnd () const
Get end interval.
IntegerDomain const & getStart () const
Get start interval.
Goal (Goal const &others)
Copy constructor.
Goal (TREX::utils::Symbol const &object, TREX::utils::Symbol const &pred)
Constructor.
Goal (boost::property_tree::ptree::value_type &node)
XML parsing constructor.
bool hasAttribute (TREX::utils::Symbol const &name) const
Check for constrained attribute.
void listAttributes (std::list< TREX::utils::Symbol > &attr, bool all) const
List predicate's attributes.
TREX::utils::Symbol const & object () const
Predicate object.
Variable const & operator[] (TREX::utils::Symbol const &name) const
Attribute access.
TREX::utils::Symbol const & predicate () const
predicate type
void restrictAttribute (TREX::utils::Symbol const &name, DomainBase const &domain)
attribute domain restriction
void restrictAttribute (Variable const &var)
restrict one of the Goal attributes
void restrictDuration (IntegerDomain const &d)
Restrict duration domain.
void restrictEnd (IntegerDomain const &e)
Restrict end domain.
void restrictStart (IntegerDomain const &s)
Restrict start time domain.
void restrictTime (IntegerDomain const &s, IntegerDomain const &d, IntegerDomain const &e)
Restrict time variables.
bool startsAfter (TICK date, TICK delay=0)
Dispatchability test.
bool startsBefore (IntegerDomain::bound const &date) const
Check for possible early start.
std::ostream & toXml (std::ostream &out, size_t tabs=0) const
XML output.
~Goal ()
destructor
Static Public Attributes
static TREX::utils::Symbol const s_durationName
name of duration attribute
static TREX::utils::Symbol const s_endName
name of end attribute
static TREX::utils::Symbol const s_startName
name of start attribute
Protected Types
typedef std::map
< TREX::utils::Symbol,
Variable > attr_set
Type used to store predicate attributes.
Protected Member Functions
iterator find (TREX::utils::Symbol const &name)
Search for attribute.
virtual std::ostream & print_to (std::ostream &out) const
output method
void remove (iterator const &i)
removce an attribute
Friends
std::ostream & std::operator<< (std::ostream &out, TREX::utils::ostreamable const &x)
Detailed Description
TREX goal.
This class represent a goal as exchanged between reactors a goal is a predicate with the 3 temporal varaiables start, duration and end. It is in substance what is called a Token inside the EUROPA planning framework.
This class embeds also suficient code to ensure that the duration is at least 1 TICK and that any modification of one of the temporal attributes is propagated to the others so start+duration=end is maintained
Author:
Frederic Py fpy@m.nosp@m.bari.nosp@m..org
need to be extended to embed representation from 3rd party planners without copy so it improve efficiency.
Definition at line 73 of file Goal.hh.
Member Typedef Documentation
typedef TREX::utils::XmlFactory< Predicate, boost::shared_ptr<Predicate> > TREX::transaction::Predicate::xml_factory [inherited]
XML parsing factory for predicates.
This defines a factory that allows to parse Predicate classes from XML.
Definition at line 307 of file Predicate.hh.
Constructor & Destructor Documentation
Goal::Goal (Goal const & others)
Copy constructor.
Parameters:
[in] other Another instance
Create a copy of other
Definition at line 66 of file Goal.cc.
Goal::Goal (TREX::utils::Symbol const & object, TREX::utils::Symbol const & pred)
Constructor.
Parameters:
[in] object A timeline identifier
[in] pred A predicate name
Create a new instance connected to timeline object with the state pred and all its attributes not constrained
Definition at line 70 of file Goal.cc.
Goal::Goal (boost::property_tree::ptree::value_type & node)
XML parsing constructor.
Parameters:
[in] node An XML node
Create a new instance by parsing the content of node. The expected format of node is
 <Goal on="<name>" pred="<name>">
   <!-- attribute definition -->
 </Goal>
If start, duration or end variables are defined it checks that their domains are properly defined and propageated.
Exceptions:
PredicateException Error while trying to parse
EmptyDomain A domain became empty during parsing
XmlError Another error while parsing
See also:
Variable::Variable(rapidxml::xml_node<> const &)
Predicate::Predicate(rapidxml::xml_node<> const &)
Definition at line 75 of file Goal.cc.
References TREX::transaction::Predicate::end(), TREX::transaction::Predicate::find(), restrictTime(), TREX::transaction::IntervalDomain< Ty, Comp >::restrictWith(), s_durationName, s_endName, and s_startName.
Member Function Documentation
iterator TREX::transaction::Predicate::begin () [inline, inherited]
beginning of the attributes set
This method allows to iterate through the attributes of this predicate
Returns:
An iterator pointing to the beginning of the attributes' set
See also:
iterator end()
Definition at line 142 of file Predicate.hh.
Referenced by TREX::transaction::Predicate::listAttributes().
const_iterator TREX::transaction::Predicate::begin () const [inline, inherited]
beginning of the attributes set
This method allows to iterate through the attributes of this predicate
Returns:
An iterator pointing to the beginning of the attributes' set
See also:
const_iterator end() const
Definition at line 166 of file Predicate.hh.
iterator TREX::transaction::Predicate::end () [inline, inherited]
end of the attributes set
This method allows to iterate through the attributes of this predicate
Returns:
An iterator pointing to the end of the attributes' set
See also:
iterator begin()
Definition at line 154 of file Predicate.hh.
Referenced by TREX::transaction::Predicate::getAttribute(), Goal(), TREX::transaction::Predicate::hasAttribute(), TREX::transaction::Predicate::listAttributes(), and TREX::transaction::Predicate::restrictAttribute().
const_iterator TREX::transaction::Predicate::end () const [inline, inherited]
end of the attributes set
This method allows to iterate through the attributes of this predicate
Returns:
An iterator pointing to the end of the attributes' set
See also:
const_iterator begin() const
Definition at line 178 of file Predicate.hh.
iterator TREX::transaction::Predicate::find (TREX::utils::Symbol const & name) [inline, protected, inherited]
Search for attribute.
Parameters:
name Attribute name
This method search for attribute name
Return values:
An iterator pointing to the attribute name if it exists
end() if the attribute name is not found
Definition at line 356 of file Predicate.hh.
Referenced by Goal().
Variable const & Goal::getAttribute (TREX::utils::Symbol const & name) const [virtual]
Attribute access.
Parameters:
name The name of an attribute
Precondition:
an attribute name should exist
Returns:
The varaible corresponding to the attribute name
Exceptions:
PredicateException Attribute name does not exist
See also:
template<class Ty> Ty const &getDomain(TREX::utils::Symbol const &) const
Reimplemented from TREX::transaction::Predicate.
Definition at line 216 of file Goal.cc.
References s_durationName, s_endName, and s_startName.
template<class Ty > Ty const& TREX::transaction::Predicate::getDomain (TREX::utils::Symbol const & name) const [inline, inherited]
Attribute domain access.
Template Parameters:
Ty the type of the domain
Parameters:
name The name of an attribute
Precondition:
Ty should inherit from DomainBase
Ty should be a base class of the domain associted to this Variable
an attribute name should exist
Returns:
The domain corresponding to the attribute name casted to domain class Ty
Exceptions:
PredicateException Attribute name does not exist
std::bad_cast Ty is not the correct domain
See also:
Variable &getDomain(TREX::utils::Symbol const &) const
template<class Ty> Ty const &Variable::typedDomain() const
Definition at line 253 of file Predicate.hh.
References TREX::transaction::Predicate::getAttribute(), and TREX::transaction::Variable::typedDomain().
IntegerDomain const & Goal::getDuration () const
Get duration interval.
Identifies the domain of possible furations
Note:
This function is strictly equivalent to :
 getAttribute(s_durationName).typedDomain<IntegerDomain>()
As of today the duration of a token in trex is at least of 1 TICK
Returns:
the domain for the start domain of this goal
See also:
getStart() const
getEnd() const
getAttribute() const
Definition at line 231 of file Goal.cc.
References TREX::transaction::Variable::typedDomain().
IntegerDomain const & Goal::getEnd () const
Get end interval.
Identifies the domain of possible end TICK.
Note:
This function is strictly equivalent to :
 getAttribute(s_endName).typedDomain<IntegerDomain>()
Returns:
the domain for the start domain of this goal
See also:
getDuration() const
getEnd() const
getAttribute() const
Definition at line 235 of file Goal.cc.
References TREX::transaction::Variable::typedDomain().
IntegerDomain const & Goal::getStart () const
Get start interval.
Identifies the domain of possible start TICK.
Note:
This function is strictly equivalent to :
 getAttribute(s_startName).typedDomain<IntegerDomain>()
Returns:
the domain for the start domain of this goal
See also:
getDuration() const
getEnd() const
getAttribute() const
Definition at line 227 of file Goal.cc.
References TREX::transaction::Variable::typedDomain().
Referenced by startsBefore().
bool TREX::transaction::Predicate::hasAttribute (TREX::utils::Symbol const & name) const [inline, inherited]
Check for constrained attribute.
Parameters:
name an attribute This methodsw checks if current instance explicitely defines the attribute name
Return values:
true if an attribute name is defined
false otherwise
Note:
the fact that a Predicate instance does not have an attribute just means that this attribute has not been constrained yet using the restrictAttribute method. It is mostly used to check for attribute existence when one wants to access to the domain associated to this attribute
See also:
Variable const &getAttribute(TREX::utils::Symbol const &) const
Definition at line 224 of file Predicate.hh.
References TREX::transaction::Predicate::end().
void Goal::listAttributes (std::list< TREX::utils::Symbol > & attr, bool all) const [virtual]
List predicate's attributes.
attr A varaible to store the attribute names all A flag used to indicate whether it should list all existing attributes or only the ones with restricted domains (ie not full)
This method is adding the list of all the attributes names defined for this predicate at the end of attr. The all flag allows to indicate that we want all the defined attributes even if their domain is full (meaning they are not really constrained)
Postcondition:
attr list contains all the attributes appendded to it end
Reimplemented from TREX::transaction::Predicate.
Definition at line 240 of file Goal.cc.
References TREX::transaction::Variable::domain(), TREX::transaction::DomainBase::equals(), TREX::transaction::DomainBase::isFull(), s_durationName, s_endName, and s_startName.
TREX::utils::Symbol const& TREX::transaction::Predicate::object () const [inline, inherited]
Predicate object.
This method indicates which object this predicate is associated to. In TREX this object has to be the name of a timeline shared between reactors.
Returns:
the name of the associated object
Definition at line 119 of file Predicate.hh.
Referenced by TREX::europa::EuropaReactor::notify(), TREX::transaction::TeleoReactor::postObservation(), and TREX::transaction::Predicate::toXml().
Variable const& TREX::transaction::Predicate::operator[] (TREX::utils::Symbol const & name) const [inline, inherited]
Attribute access.
Parameters:
name The name of an attribute
Precondition:
an attribute name should exist
Returns:
The varaible corresponding to the attribute name
Exceptions:
PredicateException Attribute name does not exist
See also:
Variable const &getAttribute(TREX::utils::Symbol const &) const
template<class Ty> Ty const &getDomain(TREX::utils::Symbol const &)
Definition at line 268 of file Predicate.hh.
References TREX::transaction::Predicate::getAttribute().
TREX::utils::Symbol const& TREX::transaction::Predicate::predicate () const [inline, inherited]
predicate type
This method indicates the type of the predicate. This type reflects the state of the associated object
Returns:
the type of the predicate
Definition at line 129 of file Predicate.hh.
Referenced by TREX::europa::EuropaReactor::notify(), and TREX::transaction::Predicate::toXml().
std::ostream & Predicate::print_to (std::ostream & out) const [protected, virtual, inherited]
output method
Parameters:
[in,out] out An output stream
This method is internally called by the standard output stream operator to write the value of current instance into out
See also:
std::ostream &operator<<(std::ostream &, ostreamable const &)
Implements TREX::utils::ostreamable.
Definition at line 95 of file Predicate.cc.
References TREX::transaction::Predicate::getAttribute(), and TREX::transaction::Predicate::listAttributes().
void TREX::transaction::Predicate::remove (iterator const & i) [inline, protected, inherited]
removce an attribute
Parameters:
i An iterator
remove the attribute pointed by i
Definition at line 364 of file Predicate.hh.
void TREX::transaction::Predicate::restrictAttribute (TREX::utils::Symbol const & name, DomainBase const & domain) [inline, inherited]
attribute domain restriction
Parameters:
name A attribute name
domain A domain
This method restrict the domain of the attribute name with the domain domain
Exceptions:
EmptyDomain The resulting domain for name is empty
See also:
void restrictAttribute(Variable const &)
Variable &restrict(Variable const &)
Definition at line 193 of file Predicate.hh.
Referenced by TREX::transaction::Predicate::Predicate().
void Goal::restrictAttribute (Variable const & var) [virtual]
restrict one of the Goal attributes
Parameters:
[in] var A variable
Add restrict the attribute var.name() to the domain var.domain()
Exceptions:
PredicateException Restricting the Goal attribute using var result on an empty domain
Note:
If an exception is thrown the domain is not changed
if var refers to one temporal varaibale (start, duration or end) the method restrictTime will be called instead
See also:
restrictTime(IntegerDomain const &, IntegerDomain const &, IntegerDomain const &)
Reimplemented from TREX::transaction::Predicate.
Definition at line 115 of file Goal.cc.
References TREX::transaction::Variable::name(), restrictDuration(), restrictEnd(), restrictStart(), s_durationName, s_startName, and TREX::transaction::Variable::typedDomain().
void TREX::transaction::Goal::restrictDuration (IntegerDomain const & d) [inline]
Restrict duration domain.
Parameters:
[in] d A domain
This method overloads restrictTime by requiring only a domain for the duration domain as argument
Exceptions:
PredicateException applying this constraint would result on an empty domain
See also:
restrictTime(IntegerDomain const &, IntegerDomain const &, IntegerDomain const &)
Definition at line 271 of file Goal.hh.
References restrictTime().
Referenced by restrictAttribute().
void TREX::transaction::Goal::restrictEnd (IntegerDomain const & e) [inline]
Restrict end domain.
Parameters:
[in] e A domain
This method overloads restrictTime by requiring only a domain for the end domain as argument
Exceptions:
PredicateException applying this constraint would result on an empty domain
See also:
restrictTime(IntegerDomain const &, IntegerDomain const &, IntegerDomain const &)
Definition at line 287 of file Goal.hh.
References restrictTime().
Referenced by restrictAttribute().
void TREX::transaction::Goal::restrictStart (IntegerDomain const & s) [inline]
Restrict start time domain.
Parameters:
[in] s A domain
This method overloads restrictTime by requiring only a domain for the start domain as argument
Exceptions:
PredicateException applying this constraint would result on an empty domain
See also:
restrictTime(IntegerDomain const &, IntegerDomain const &, IntegerDomain const &)
Definition at line 255 of file Goal.hh.
References restrictTime().
Referenced by restrictAttribute().
void Goal::restrictTime (IntegerDomain const & s, IntegerDomain const & d, IntegerDomain const & e)
Restrict time variables.
Parameters:
[in] s A start domain
[in] d A duration domain
[in] e A end domain
This method restrict the token temporals variables (start restricted by s, duration restricted by d and end restricted by e) and also progate the constraint such as start+duration=end.
Exceptions:
PredicateException One of the temporal variables domain would become empty if the operation is applied.
Note:
If an exception is thrown the domain is not changed
Postcondition:
the temporal variables have been restrictefd accordingly
See also:
restrictAttribute(Variable const &)
Definition at line 128 of file Goal.cc.
References TREX::transaction::Variable::domain(), TREX::transaction::IntervalDomain< Ty, Comp >::getBounds(), TREX::transaction::DomainBase::intersect(), TREX::transaction::Variable::restrict(), and TREX::transaction::Variable::typedDomain().
Referenced by Goal(), restrictDuration(), restrictEnd(), restrictStart(), and startsAfter().
bool Goal::startsAfter (TICK date, TICK delay = 0)
Dispatchability test.
Parameters:
[in] date current date
[in] delay A delay
Thsi method is used by TeleoReactor class to check if a goal on an external timeline needs to be dispatched or should be kept for now. It can also constraint the start time of this goaal to be after date if possible
Return values:
true if the domain of start intersects [date+delay,+inf). In this case the start time is constrained to be necessarily greater or equal to date
false otherwise
Definition at line 204 of file Goal.cc.
References TREX::transaction::IntervalDomain< Ty, Comp >::intersect(), TREX::transaction::IntervalDomain< long >::plus_inf, restrictTime(), and TREX::transaction::Variable::typedDomain().
bool TREX::transaction::Goal::startsBefore (IntegerDomain::bound const & date) const [inline]
Check for possible early start.
Parameters:
[in] date A date
Return values:
true if start can be less of equal to date
false otherwise
Definition at line 134 of file Goal.hh.
References getStart(), and TREX::transaction::IntervalDomain< Ty, Comp >::lowerBound().
std::ostream & Predicate::toXml (std::ostream & out, size_t tabs = 0) const [inherited]
XML output.
Parameters:
out An output stream
tabs desired tags indentation
This method writes an XML form of current instance to out indented using tab.
The output excludes all the attributes that are not really constrained to reduce the size of this description.
Returns:
out after the operation
Definition at line 108 of file Predicate.cc.
References TREX::transaction::Predicate::getAttribute(), TREX::transaction::Predicate::getPredTag(), TREX::transaction::Predicate::listAttributes(), TREX::transaction::Predicate::object(), and TREX::transaction::Predicate::predicate().
The documentation for this class was generated from the following files:
trex/transaction/Goal.hh
trex/transaction/Goal.cc