trex: TREX::utils::list_set< IdTraits, Cmp > Class Template Reference
TREX::utils::list_set< IdTraits, Cmp > Class Template Reference
Basic utilities
List based generalized set.
#include <trex/utils/id_mapper.hh>
Public Types
typedef
container_type::const_iterator const_iterator
elements const iterator
typedef
container_type::difference_type difference_type
typedef container_type::iterator iterator
elements iterator
typedef IdTraits::id_type key_type
Key type.
typedef container_type::size_type size_type
typedef IdTraits::base_type value_type
Elements type.
Public Member Functions
iterator begin ()
Beginning iterator.
const_iterator begin () const
Beginning iterator.
void clear ()
clear container
bool empty () const
Check if empty.
iterator end ()
End iterator.
const_iterator end () const
End iterator.
iterator erase (iterator pos)
Remove an element.
iterator erase (iterator from, iterator to)
Remove elements.
iterator erase (key_type const &k)
Remove an element.
value_type const & front () const
value_type & front ()
std::pair< iterator, bool > insert (value_type const &v)
Element insertion.
list_set ()
Default constructor.
list_set (list_set const &other)
copy constructor
template<class Iter >
list_set (Iter from, Iter to)
Constructor.
void pop_front ()
size_type size () const
Number of element.
~list_set ()
Destructor.
iterator lower_bound (key_type const &k)
Lower bound.
const_iterator lower_bound (key_type const &k) const
Lower bound.
iterator lower_bound (value_type const &v)
Lower bound.
const_iterator lower_bound (value_type const &v) const
Lower bound.
iterator upper_bound (key_type const &k)
Upper bound.
const_iterator upper_bound (key_type const &k) const
Upper bound.
iterator upper_bound (value_type const &v)
Upper bound.
const_iterator upper_bound (value_type const &v) const
Upper bound.
std::pair< iterator, iterator > equal_range (key_type const &k)
Equal range.
std::pair< const_iterator,
const_iterator > equal_range (key_type const &k) const
Equal range.
std::pair< iterator, iterator > equal_range (value_type const &v)
Equal range.
std::pair< const_iterator,
const_iterator > equal_range (value_type const &v) const
Equal range.
iterator find (key_type const &k)
Find element.
const_iterator find (key_type const &k) const
Find element.
iterator find (value_type const &v)
Find element.
const_iterator find (value_type const &v) const
Find element.
Detailed Description
template<class IdTraits, class Cmp = std::less<typename IdTraits::id_type>>
class TREX::utils::list_set< IdTraits, Cmp >
List based generalized set.
Template Parameters:
IdTraits A traits that helps element key extraction
Cmp A comparison functor
This class is a simple generalized implementation of a set/map using a std::list as the internal container.
It relies on the id_mapper class to locate elements
Note:
This implementation is a simple assovciative container. It implies that it ensure that there's one and only one element with a given key
See also:
class id_mapper
Author:
Frederic Py fpy@m.nosp@m.bari.nosp@m..org
Definition at line 371 of file id_mapper.hh.
Member Typedef Documentation
template<class IdTraits, class Cmp = std::less<typename IdTraits::id_type>> typedef IdTraits::id_type TREX::utils::list_set< IdTraits, Cmp >::key_type
Key type.
The type of the key used to dsort the element.
Definition at line 382 of file id_mapper.hh.
template<class IdTraits, class Cmp = std::less<typename IdTraits::id_type>> typedef IdTraits::base_type TREX::utils::list_set< IdTraits, Cmp >::value_type
Elements type.
The type of the element stored.
Definition at line 377 of file id_mapper.hh.
Constructor & Destructor Documentation
template<class IdTraits, class Cmp = std::less<typename IdTraits::id_type>> TREX::utils::list_set< IdTraits, Cmp >::list_set () [inline]
Default constructor.
Create an empty set
Definition at line 410 of file id_mapper.hh.
template<class IdTraits, class Cmp = std::less<typename IdTraits::id_type>> TREX::utils::list_set< IdTraits, Cmp >::list_set (list_set< IdTraits, Cmp > const & other) [inline]
copy constructor
Parameters:
[in] other Another instance
Create a copy of other
Definition at line 417 of file id_mapper.hh.
template<class IdTraits, class Cmp = std::less<typename IdTraits::id_type>> template<class Iter > TREX::utils::list_set< IdTraits, Cmp >::list_set (Iter from, Iter to) [inline]
Constructor.
Template Parameters:
Iter an iterator
Parameters:
from start iterator
to end iterator
Create A setby inserting all the elements in the interval [from, to)
Note:
If multiple elements have the same key only the first found will be insserted
Definition at line 431 of file id_mapper.hh.
Member Function Documentation
template<class IdTraits, class Cmp = std::less<typename IdTraits::id_type>> iterator TREX::utils::list_set< IdTraits, Cmp >::begin () [inline]
Beginning iterator.
Returns:
An iterator pointing to the beginning of the list
See also:
begin() const
end()
Definition at line 463 of file id_mapper.hh.
Referenced by TREX::transaction::TeleoReactor::count_internal_relations(), TREX::transaction::TeleoReactor::doSynchronize(), TREX::utils::list_set< reactor_id_traits< boost::shared_ptr< TeleoReactor > > >::equal_range(), TREX::transaction::graph::index(), TREX::transaction::TeleoReactor::int_begin(), TREX::transaction::graph::is_member(), TREX::utils::list_set< reactor_id_traits< boost::shared_ptr< TeleoReactor > > >::lower_bound(), TREX::transaction::graph::reactor_begin(), and TREX::utils::list_set< reactor_id_traits< boost::shared_ptr< TeleoReactor > > >::upper_bound().
template<class IdTraits, class Cmp = std::less<typename IdTraits::id_type>> const_iterator TREX::utils::list_set< IdTraits, Cmp >::begin () const [inline]
Beginning iterator.
Returns:
An iterator pointing to the beginning of the list
See also:
begin()
end() const
Definition at line 485 of file id_mapper.hh.
template<class IdTraits, class Cmp = std::less<typename IdTraits::id_type>> void TREX::utils::list_set< IdTraits, Cmp >::clear () [inline]
clear container
Remove all the elements stroed in this instance
Definition at line 776 of file id_mapper.hh.
Referenced by TREX::transaction::graph::clear(), and TREX::transaction::TeleoReactor::doSynchronize().
template<class IdTraits, class Cmp = std::less<typename IdTraits::id_type>> bool TREX::utils::list_set< IdTraits, Cmp >::empty () const [inline]
Check if empty.
Return values:
true if current instance has no element
false otherwise
Definition at line 443 of file id_mapper.hh.
Referenced by TREX::transaction::graph::cleanup(), TREX::transaction::graph::clear(), and TREX::transaction::graph::empty().
template<class IdTraits, class Cmp = std::less<typename IdTraits::id_type>> iterator TREX::utils::list_set< IdTraits, Cmp >::end () [inline]
End iterator.
Returns:
An iterator pointing to the end of the list
See also:
begin()
end() const
Definition at line 474 of file id_mapper.hh.
Referenced by TREX::europa::Assembly::add_state_var(), TREX::transaction::TeleoReactor::count_internal_relations(), TREX::transaction::TeleoReactor::doSynchronize(), TREX::utils::list_set< reactor_id_traits< boost::shared_ptr< TeleoReactor > > >::equal_range(), TREX::utils::list_set< reactor_id_traits< boost::shared_ptr< TeleoReactor > > >::find(), TREX::transaction::graph::index(), TREX::transaction::TeleoReactor::int_begin(), TREX::transaction::TeleoReactor::int_end(), TREX::transaction::graph::is_member(), TREX::transaction::TeleoReactor::isInternal(), TREX::utils::list_set< reactor_id_traits< boost::shared_ptr< TeleoReactor > > >::lower_bound(), TREX::transaction::TeleoReactor::postObservation(), TREX::transaction::TeleoReactor::postPlanToken(), TREX::transaction::graph::reactor_end(), and TREX::utils::list_set< reactor_id_traits< boost::shared_ptr< TeleoReactor > > >::upper_bound().
template<class IdTraits, class Cmp = std::less<typename IdTraits::id_type>> const_iterator TREX::utils::list_set< IdTraits, Cmp >::end () const [inline]
End iterator.
Returns:
An iterator pointing to the end of the list
See also:
begin() const
end()
Definition at line 496 of file id_mapper.hh.
template<class IdTraits, class Cmp = std::less<typename IdTraits::id_type>> std::pair<iterator, iterator> TREX::utils::list_set< IdTraits, Cmp >::equal_range (key_type const & k) [inline]
Equal range.
Parameters:
[in] k A key
Finds the iterators that correspond to all the elements of the set whose key is k
Returns:
a pair defining the iterator interval of all the elements whose key is k
Note:
As we have a unique associative container ther should be at most one element in this interval
See also:
lower_bound(key_type const &)
upper_bound(key_type const &)
equal_range(value_type const &v)
Definition at line 612 of file id_mapper.hh.
Referenced by TREX::utils::list_set< reactor_id_traits< boost::shared_ptr< TeleoReactor > > >::equal_range(), TREX::utils::list_set< reactor_id_traits< boost::shared_ptr< TeleoReactor > > >::erase(), TREX::utils::list_set< reactor_id_traits< boost::shared_ptr< TeleoReactor > > >::find(), and TREX::utils::list_set< reactor_id_traits< boost::shared_ptr< TeleoReactor > > >::insert().
template<class IdTraits, class Cmp = std::less<typename IdTraits::id_type>> std::pair<const_iterator, const_iterator> TREX::utils::list_set< IdTraits, Cmp >::equal_range (key_type const & k) const [inline]
Equal range.
Parameters:
[in] k A key
Finds the iterators that correspond to all the elements of the set whose key is k
Returns:
a pair defining the iterator interval of all the elements whose key is k
Note:
As we have a unique associative container ther should be at most one element in this interval
See also:
lower_bound(key_type const &)
upper_bound(key_type const &)
equal_range(value_type const &v)
Definition at line 617 of file id_mapper.hh.
template<class IdTraits, class Cmp = std::less<typename IdTraits::id_type>> std::pair<iterator, iterator> TREX::utils::list_set< IdTraits, Cmp >::equal_range (value_type const & v) [inline]
Equal range.
Parameters:
[in] v An element value
Finds the iterators that correspond to all the elements of the set whose key is the same as the key of v
Returns:
a pair defining the iterator interval of all the elements whose key is v
Note:
As we have a unique associative container ther should be at most one element in this interval
See also:
lower_bound(value_type const &)
upper_bound(value_type const &)
equal_range(key_type const &)
Definition at line 644 of file id_mapper.hh.
template<class IdTraits, class Cmp = std::less<typename IdTraits::id_type>> std::pair<const_iterator, const_iterator> TREX::utils::list_set< IdTraits, Cmp >::equal_range (value_type const & v) const [inline]
Equal range.
Parameters:
[in] v An element value
Finds the iterators that correspond to all the elements of the set whose key is the same as the key of v
Returns:
a pair defining the iterator interval of all the elements whose key is v
Note:
As we have a unique associative container ther should be at most one element in this interval
See also:
lower_bound(value_type const &)
upper_bound(value_type const &)
equal_range(key_type const &)
Definition at line 647 of file id_mapper.hh.
template<class IdTraits, class Cmp = std::less<typename IdTraits::id_type>> iterator TREX::utils::list_set< IdTraits, Cmp >::erase (iterator pos) [inline]
Remove an element.
Parameters:
[in] pos element to remove
Precondition:
pos is a valid iterator for this instance
Returns:
the iterator after pos
Definition at line 741 of file id_mapper.hh.
Referenced by TREX::utils::list_set< reactor_id_traits< boost::shared_ptr< TeleoReactor > > >::erase(), and TREX::transaction::graph::kill_reactor().
template<class IdTraits, class Cmp = std::less<typename IdTraits::id_type>> iterator TREX::utils::list_set< IdTraits, Cmp >::erase (iterator from, iterator to) [inline]
Remove elements.
Parameters:
[in] from first element to remove
to] to first element to not remove after from
Precondition:
[pos, to) is a valid iterator interval for this instance
Returns:
to
Definition at line 753 of file id_mapper.hh.
template<class IdTraits, class Cmp = std::less<typename IdTraits::id_type>> iterator TREX::utils::list_set< IdTraits, Cmp >::erase (key_type const & k) [inline]
Remove an element.
Parameters:
[in] k A key
Remove the element whose key is k if it exist
the iterator after the expected position of element with key k
Definition at line 765 of file id_mapper.hh.
template<class IdTraits, class Cmp = std::less<typename IdTraits::id_type>> iterator TREX::utils::list_set< IdTraits, Cmp >::find (key_type const & k) [inline]
Find element.
Parameters:
[in] k A key
Finds the elemnt whose key is k
Returns:
An iterator pointing to the first element whose key is k or end() if such element does not exist
See also:
equal_range(key_type const &)
find(value_type const &)
Definition at line 693 of file id_mapper.hh.
Referenced by TREX::europa::Assembly::add_state_var(), TREX::utils::list_set< reactor_id_traits< boost::shared_ptr< TeleoReactor > > >::find(), TREX::transaction::graph::find_reactor(), TREX::transaction::TeleoReactor::isInternal(), TREX::transaction::graph::isolate(), TREX::transaction::graph::kill_reactor(), TREX::transaction::TeleoReactor::postObservation(), and TREX::transaction::TeleoReactor::postPlanToken().
template<class IdTraits, class Cmp = std::less<typename IdTraits::id_type>> const_iterator TREX::utils::list_set< IdTraits, Cmp >::find (key_type const & k) const [inline]
Find element.
Parameters:
[in] k A key
Finds the elemnt whose key is k
Returns:
An iterator pointing to the first element whose key is k or end() if such element does not exist
See also:
equal_range(key_type const &)
find(value_type const &)
Definition at line 701 of file id_mapper.hh.
template<class IdTraits, class Cmp = std::less<typename IdTraits::id_type>> iterator TREX::utils::list_set< IdTraits, Cmp >::find (value_type const & v) [inline]
Find element.
Parameters:
[in] v An element value
Finds the element whose key is the same as v
Returns:
An iterator pointing to the first element whose key is the same as v or end() if such element does not exist
See also:
equal_range(value_type const &)
find(key_type const &)
Definition at line 725 of file id_mapper.hh.
template<class IdTraits, class Cmp = std::less<typename IdTraits::id_type>> const_iterator TREX::utils::list_set< IdTraits, Cmp >::find (value_type const & v) const [inline]
Find element.
Parameters:
[in] v An element value
Finds the element whose key is the same as v
Returns:
An iterator pointing to the first element whose key is the same as v or end() if such element does not exist
See also:
equal_range(value_type const &)
find(key_type const &)
Definition at line 728 of file id_mapper.hh.
template<class IdTraits, class Cmp = std::less<typename IdTraits::id_type>> std::pair<iterator, bool> TREX::utils::list_set< IdTraits, Cmp >::insert (value_type const & v) [inline]
Element insertion.
Parameters:
[in] v An element value
This method Find the position of v in the set and insert it if there is no element with the same key as v
Returns:
A pair with the first element being the iterator pointing to v position in thins set and second a bool which is true if v was inserted and false if an element with the same key as already exist
In the case second is false it is up to the coder to decide whether he wants to overwrite the former value with v or not
Definition at line 667 of file id_mapper.hh.
Referenced by TREX::transaction::graph::add_reactor(), TREX::transaction::graph::add_reactors(), TREX::europa::Assembly::add_state_var(), TREX::transaction::graph::isolate(), TREX::utils::list_set< reactor_id_traits< boost::shared_ptr< TeleoReactor > > >::list_set(), and TREX::transaction::TeleoReactor::postObservation().
template<class IdTraits, class Cmp = std::less<typename IdTraits::id_type>> iterator TREX::utils::list_set< IdTraits, Cmp >::lower_bound (key_type const & k) [inline]
Lower bound.
Parameters:
[in] k A key
Finds the first element whose key is not before k
Returns:
An iterator refering to the first element that is not before k or end() if such element does not exist
See also:
lower_bound(value_type const &)
upper_bound(key_type const &)
id_mapper::lower_bound(Iter,Iter,id_mapper::reference) const
Definition at line 515 of file id_mapper.hh.
Referenced by TREX::utils::list_set< reactor_id_traits< boost::shared_ptr< TeleoReactor > > >::lower_bound().
template<class IdTraits, class Cmp = std::less<typename IdTraits::id_type>> const_iterator TREX::utils::list_set< IdTraits, Cmp >::lower_bound (key_type const & k) const [inline]
Lower bound.
Parameters:
[in] k A key
Finds the first element whose key is not before k
Returns:
An iterator refering to the first element that is not before k or end() if such element does not exist
See also:
lower_bound(value_type const &)
upper_bound(key_type const &)
id_mapper::lower_bound(Iter,Iter,id_mapper::reference) const
Definition at line 518 of file id_mapper.hh.
template<class IdTraits, class Cmp = std::less<typename IdTraits::id_type>> iterator TREX::utils::list_set< IdTraits, Cmp >::lower_bound (value_type const & v) [inline]
Lower bound.
Parameters:
[in] v A value
Finds the first element whose key is not before the key of v
Returns:
An iterator refering to the first element that is not before v or end() if such element does not exist
See also:
lower_bound(key_type const &)
upper_bound(value_type const &)
id_mapper::lower_bound(Iter,Iter,id_mapper::reference) const
Definition at line 538 of file id_mapper.hh.
template<class IdTraits, class Cmp = std::less<typename IdTraits::id_type>> const_iterator TREX::utils::list_set< IdTraits, Cmp >::lower_bound (value_type const & v) const [inline]
Lower bound.
Parameters:
[in] v A value
Finds the first element whose key is not before the key of v
Returns:
An iterator refering to the first element that is not before v or end() if such element does not exist
See also:
lower_bound(key_type const &)
upper_bound(value_type const &)
id_mapper::lower_bound(Iter,Iter,id_mapper::reference) const
Definition at line 541 of file id_mapper.hh.
template<class IdTraits, class Cmp = std::less<typename IdTraits::id_type>> size_type TREX::utils::list_set< IdTraits, Cmp >::size () const [inline]
Number of element.
Returns:
The number of element stored
Definition at line 451 of file id_mapper.hh.
Referenced by TREX::transaction::TeleoReactor::count_internals(), and TREX::transaction::graph::count_reactors().
template<class IdTraits, class Cmp = std::less<typename IdTraits::id_type>> iterator TREX::utils::list_set< IdTraits, Cmp >::upper_bound (key_type const & k) [inline]
Upper bound.
Parameters:
[in] k A key
Finds the first element whose key is after k
Returns:
An iterator refering to the first element that is after k or end() if such element does not exist
See also:
upper_bound(value_type const &)
lower_bound(key_type const &)
id_mapper::upper_bound(Iter,Iter,id_mapper::reference) const
Definition at line 561 of file id_mapper.hh.
Referenced by TREX::utils::list_set< reactor_id_traits< boost::shared_ptr< TeleoReactor > > >::upper_bound().
template<class IdTraits, class Cmp = std::less<typename IdTraits::id_type>> const_iterator TREX::utils::list_set< IdTraits, Cmp >::upper_bound (key_type const & k) const [inline]
Upper bound.
Parameters:
[in] k A key
Finds the first element whose key is after k
Returns:
An iterator refering to the first element that is after k or end() if such element does not exist
See also:
upper_bound(value_type const &)
lower_bound(key_type const &)
id_mapper::upper_bound(Iter,Iter,id_mapper::reference) const
Definition at line 564 of file id_mapper.hh.
template<class IdTraits, class Cmp = std::less<typename IdTraits::id_type>> iterator TREX::utils::list_set< IdTraits, Cmp >::upper_bound (value_type const & v) [inline]
Upper bound.
Parameters:
[in] v A value
Finds the first element whose key is after the key of v
Returns:
An iterator refering to the first element that is after v or end() if such element does not exist
See also:
upper_bound(key_type const &)
lower_bound(value_type const &)
id_mapper::upper_bound(Iter,Iter,id_mapper::reference) const
Definition at line 585 of file id_mapper.hh.
template<class IdTraits, class Cmp = std::less<typename IdTraits::id_type>> const_iterator TREX::utils::list_set< IdTraits, Cmp >::upper_bound (value_type const & v) const [inline]
Upper bound.
Parameters:
[in] v A value
Finds the first element whose key is after the key of v
Returns:
An iterator refering to the first element that is after v or end() if such element does not exist
See also:
upper_bound(key_type const &)
lower_bound(value_type const &)
id_mapper::upper_bound(Iter,Iter,id_mapper::reference) const
Definition at line 588 of file id_mapper.hh.
The documentation for this class was generated from the following file:
trex/utils/id_mapper.hh