trex: TREX::agent::details::init_visitor Class Reference
TREX::agent::details::init_visitor Class Reference
TREX agent
Reactors initialization visitor.
Public Member Functions
void back_edge (TREX::transaction::graph::relation_type const &rel, TREX::transaction::graph const &g)
back edge callback
void finish_vertex (graph::reactor_id r, graph const &g)
Finish vertex callback.
init_visitor (TICK final)
Constructor.
init_visitor (init_visitor const &other)
Copy constructor.
virtual ~init_visitor ()
Destructor.
Protected Member Functions
bool is_valid (TREX::transaction::graph::reactor_id r, TREX::transaction::graph const &g) const
Check for node validity.
Protected Attributes
TICK m_final
Final tick value.
Detailed Description
Reactors initialization visitor.
This class is a depth first search visitor that will initialize all the reactors from the least dependent to the most dependent in the graph.
The initialization is done through the initialize call on each reactor that will in turn call handleInit callback insisde this reactor
See also:
TREX::transaction::TeleoReactor::initialize(TREX::transaction::TICK)
TREX::transaction::TeleoReactor::handleInit()
Agent
Author:
Frederic Py fpy@m.nosp@m.bari.nosp@m..org
Definition at line 81 of file Agent.cc.
Constructor & Destructor Documentation
TREX::agent::details::init_visitor::init_visitor (TICK final) [inline, explicit]
Constructor.
Parameters:
[in] final the final tick of the mission
Definition at line 86 of file Agent.cc.
TREX::agent::details::init_visitor::init_visitor (init_visitor const & other) [inline]
Copy constructor.
Parameters:
[in] other the instance to copy
Definition at line 92 of file Agent.cc.
Member Function Documentation
void TREX::agent::CycleDetector::back_edge (TREX::transaction::graph::relation_type const & rel, TREX::transaction::graph const & g) [inline, inherited]
back edge callback
This dfs callback is called only when the dfs loops back to a vertex that is still being explored. This clearly idenitfy a loop in the graph wwhich is a proof of cyclic dependncy betwee two reactors
Exceptions:
CycleDetected always thrown as this call indicates a cyclic dependency in the egent graph
Definition at line 144 of file agent_graph.hh.
References TREX::agent::CycleDetector::is_valid().
void TREX::agent::details::init_visitor::finish_vertex (graph::reactor_id r, graph const & g) [inline]
Finish vertex callback.
Parameters:
[in] r A reactor
[in] g The graph r is attached to
This method will be called during a depth first search when all the reactors r depends on have been already explored.
It will call the initialize method of r with a final tick value as provided by the m_finalTick attribute in order to allow this reactor to complete its initialization.
See also:
Agent::initComplete()
TREX::transaction::TeleoReactor::initialize(TREX::transaction::TICK)
Definition at line 112 of file Agent.cc.
References TREX::transaction::graph::isolate().
bool TREX::agent::CycleDetector::is_valid (TREX::transaction::graph::reactor_id r, TREX::transaction::graph const & g) const [inline, protected, inherited]
Check for node validity.
Parameters:
[in] r A reactor reference
[in] g The graph supporting r
Check that r referes to an exisiting reactor. This method is used during graph traversal to check that the an edge is not pointing to nothing or to a node that has been isolated
Return values:
true if r refers to a reactor
false otherwise
See also:
TREX::transaction::garph::null_reactor()
Definition at line 166 of file agent_graph.hh.
Referenced by TREX::agent::CycleDetector::back_edge().
Member Data Documentation
TICK TREX::agent::details::init_visitor::m_final [protected]
Final tick value.
Stores the final tick of the mission that will be proovided to the reactors during the depth first search execution of this visitor.
Definition at line 125 of file Agent.cc.
The documentation for this class was generated from the following file:
trex/agent/Agent.cc