trex: TREX::transaction::Predicate Class Reference
TREX::transaction::Predicate Class Reference
[TREX transaction]
TREX Predicate.
#include <trex/transaction/Predicate.hh>
Public Types
typedef attr_set::const_iterator const_iterator
Predicate attributes' const iterator.
typedef attr_set::iterator iterator
Predicate attributes' iterator.
typedef
TREX::utils::XmlFactory
< Predicate, boost::shared_ptr
< Predicate > > xml_factory
XML parsing factory for predicates.
Public Member Functions
const_iterator begin () const
beginning of the attributes set
iterator begin ()
beginning of the attributes set
const_iterator end () const
end of the attributes set
iterator end ()
end of the attributes set
virtual Variable const & getAttribute (TREX::utils::Symbol const &name) const
Attribute access.
template<class Ty >
Ty const & getDomain (TREX::utils::Symbol const &name) const
Attribute domain access.
bool hasAttribute (TREX::utils::Symbol const &name) const
Check for constrained attribute.
virtual void listAttributes (std::list< TREX::utils::Symbol > &attr, bool all=true) const
List predicate's attributes.
TREX::utils::Symbol const & object () const
Predicate object.
Variable const & operator[] (TREX::utils::Symbol const &name) const
Attribute access.
TREX::utils::Symbol const & predicate () const
predicate type
virtual void restrictAttribute (Variable const &var)
attribute domain restriction
void restrictAttribute (TREX::utils::Symbol const &name, DomainBase const &domain)
attribute domain restriction
std::ostream & toXml (std::ostream &out, size_t tabs=0) const
XML output.
virtual ~Predicate ()=0
Destructor.
Protected Types
typedef std::map
< TREX::utils::Symbol,
Variable > attr_set
Type used to store predicate attributes.
Protected Member Functions
iterator find (TREX::utils::Symbol const &name)
Search for attribute.
virtual TREX::utils::Symbol const & getPredTag () const =0
XML tag name.
Predicate (Predicate const &other)
Constructor.
Predicate (boost::property_tree::ptree::value_type &node)
Constructor.
Predicate (TREX::utils::Symbol const &obj, TREX::utils::Symbol const &pred)
Constructor.
virtual std::ostream & print_to (std::ostream &out) const
output method
void remove (iterator const &i)
removce an attribute
Friends
std::ostream & std::operator<< (std::ostream &out, TREX::utils::ostreamable const &x)
Detailed Description
TREX Predicate.
This class defines predicate as manipulated by TREX. A predicate is an abstract representaion of Goal and/or Observation exchanged between reactors. It is a named predicate attached to an object with different attributes represented as Variable.
The object is the name of the timeline supporting this observation while the predicate is the value of the state for object
A goal has just the specificity to also define the start, duration and end temporal attributes.
Author:
Frederic Py <fpy@mbari.org>
Definition at line 97 of file Predicate.hh.
Member Typedef Documentation
typedef TREX::utils::XmlFactory< Predicate, boost::shared_ptr<Predicate> > TREX::transaction::Predicate::xml_factory
XML parsing factory for predicates.
This defines a factory that allows to parse Predicate classes from XML.
Definition at line 307 of file Predicate.hh.
Constructor & Destructor Documentation
TREX::transaction::Predicate::Predicate (TREX::utils::Symbol const & obj, TREX::utils::Symbol const & pred) [inline, protected]
Constructor.
Parameters:
obj An object name
pred A predicate type
Create a new instance referring to object obj with the state pred.
Precondition:
both obj and pred should not be empty symbols
Exceptions:
PredicateException One of the argument was empty
Definition at line 320 of file Predicate.hh.
References TREX::utils::BasicSymbol< CharT, Traits, Alloc >::empty().
Predicate::Predicate (boost::property_tree::ptree::value_type & node) [protected]
Constructor.
Parameters:
node A XML node
Create a new insatnce by parsing the XML node node
Exceptions:
PredicateException object and/or predicate type were not correctly defined in node
VariableException An XML attribute definition is ill-formed
XMLError An occurred while parsing domains definition
See also:
xml_factory
Variable::Variable(rapidxml::xml_node<> const &)
Definition at line 50 of file Predicate.cc.
References TREX::utils::BasicSymbol< CharT, Traits, Alloc >::empty(), and restrictAttribute().
Predicate::Predicate (Predicate const & other) [protected]
Constructor.
Parameters:
other another instance
Create a copy of other
Definition at line 66 of file Predicate.cc.
Member Function Documentation
const_iterator TREX::transaction::Predicate::begin () const [inline]
beginning of the attributes set
This method allows to iterate through the attributes of this predicate
Returns:
An iterator pointing to the beginning of the attributes' set
See also:
const_iterator end() const
Definition at line 166 of file Predicate.hh.
iterator TREX::transaction::Predicate::begin () [inline]
beginning of the attributes set
This method allows to iterate through the attributes of this predicate
Returns:
An iterator pointing to the beginning of the attributes' set
See also:
iterator end()
Definition at line 142 of file Predicate.hh.
Referenced by listAttributes().
const_iterator TREX::transaction::Predicate::end () const [inline]
end of the attributes set
This method allows to iterate through the attributes of this predicate
Returns:
An iterator pointing to the end of the attributes' set
See also:
const_iterator begin() const
Definition at line 178 of file Predicate.hh.
iterator TREX::transaction::Predicate::end () [inline]
end of the attributes set
This method allows to iterate through the attributes of this predicate
Returns:
An iterator pointing to the end of the attributes' set
See also:
iterator begin()
Definition at line 154 of file Predicate.hh.
Referenced by getAttribute(), TREX::transaction::Goal::Goal(), listAttributes(), and restrictAttribute().
iterator TREX::transaction::Predicate::find (TREX::utils::Symbol const & name) [inline, protected]
Search for attribute.
Parameters:
name Attribute name
This method search for attribute name
Return values:
An iterator pointing to the attribute name if it exists
end() if the attribute name is not found
Definition at line 356 of file Predicate.hh.
Referenced by TREX::transaction::Goal::Goal().
Variable const & Predicate::getAttribute (TREX::utils::Symbol const & name) const [virtual]
Attribute access.
Parameters:
name The name of an attribute
Precondition:
an attribute name should exist
Returns:
The varaible corresponding to the attribute name
Exceptions:
PredicateException Attribute name does not exist
See also:
template<class Ty> Ty const &getDomain(TREX::utils::Symbol const &) const
Reimplemented in TREX::transaction::Goal.
Definition at line 88 of file Predicate.cc.
References end(), and TREX::utils::BasicSymbol< CharT, Traits, Alloc >::str().
Referenced by print_to(), and toXml().
template<class Ty > Ty const& TREX::transaction::Predicate::getDomain (TREX::utils::Symbol const & name) const [inline]
Attribute domain access.
Template Parameters:
Ty the type of the domain
Parameters:
name The name of an attribute
Precondition:
Ty should inherit from DomainBase
Ty should be a base class of the domain associted to this Variable
an attribute name should exist
Returns:
The domain corresponding to the attribute name casted to domain class Ty
Exceptions:
PredicateException Attribute name does not exist
std::bad_cast Ty is not the correct domain
See also:
Variable &getDomain(TREX::utils::Symbol const &) const
template<class Ty> Ty const &Variable::typedDomain() const
Definition at line 253 of file Predicate.hh.
References TREX::transaction::Variable::typedDomain().
virtual TREX::utils::Symbol const& TREX::transaction::Predicate::getPredTag () const [protected, pure virtual]
XML tag name.
This method is used internally to determine the tag that should be used to describe this attribute in its XML form
Returns:
The tag name to use
See also:
std::ostream &toXml(std::ostream &, size_t) const
Referenced by toXml().
bool TREX::transaction::Predicate::hasAttribute (TREX::utils::Symbol const & name) const [inline]
Check for constrained attribute.
Parameters:
name an attribute This methodsw checks if current instance explicitely defines the attribute name
Return values:
true if an attribute name is defined
false otherwise
Note:
the fact that a Predicate instance does not have an attribute just means that this attribute has not been constrained yet using the restrictAttribute method. It is mostly used to check for attribute existence when one wants to access to the domain associated to this attribute
See also:
Variable const &getAttribute(TREX::utils::Symbol const &) const
Definition at line 224 of file Predicate.hh.
void Predicate::listAttributes (std::list< TREX::utils::Symbol > & attr, bool all = true) const [virtual]
List predicate's attributes.
attr A varaible to store the attribute names all A flag used to indicate whether it should list all existing attributes or only the ones with restricted domains (ie not full) This method is adding the list of all the attributes names defined for this predicate at the end of attr. The all flag allows to indicate that we want all the defined attributes even if their domain is full (meaning thay are not really constrained)
Postcondition:
attr list contains all the attributes appendded to it end
Reimplemented in TREX::transaction::Goal.
Definition at line 130 of file Predicate.cc.
References begin(), and end().
Referenced by print_to(), and toXml().
TREX::utils::Symbol const& TREX::transaction::Predicate::object () const [inline]
Predicate object.
This method indicates which object this predicate is associated to. In TREX this object has to be the name of a timeline shared between reactors.
Returns:
the name of the associated object
Definition at line 119 of file Predicate.hh.
Referenced by TREX::transaction::TeleoReactor::postObservation(), and toXml().
Variable const& TREX::transaction::Predicate::operator[] (TREX::utils::Symbol const & name) const [inline]
Attribute access.
Parameters:
name The name of an attribute
Precondition:
an attribute name should exist
Returns:
The varaible corresponding to the attribute name
Exceptions:
PredicateException Attribute name does not exist
See also:
Variable const &getAttribute(TREX::utils::Symbol const &) const
template<class Ty> Ty const &getDomain(TREX::utils::Symbol const &)
Definition at line 268 of file Predicate.hh.
TREX::utils::Symbol const& TREX::transaction::Predicate::predicate () const [inline]
predicate type
This method indicates the type of the predicate. This type reflects the state of the associated object
Returns:
the type of the predicate
Definition at line 129 of file Predicate.hh.
Referenced by toXml().
std::ostream & Predicate::print_to (std::ostream & out) const [protected, virtual]
output method
Parameters:
[in,out] out An output stream
This method is internally called by the standard output stream operator to write the value of current instance into out
See also:
std::ostream &operator<<(std::ostream &, ostreamable const &)
Implements TREX::utils::ostreamable.
Definition at line 95 of file Predicate.cc.
References getAttribute(), and listAttributes().
void TREX::transaction::Predicate::remove (iterator const & i) [inline, protected]
removce an attribute
Parameters:
i An iterator
remove the attribute pointed by i
Definition at line 364 of file Predicate.hh.
void Predicate::restrictAttribute (Variable const & var) [virtual]
attribute domain restriction
Parameters:
var A varaible describing the attribute
This method restrict the domain of the attribute corresponding to var with the domain of var
Exceptions:
EmptyDomain The resulting domain for name is empty
See also:
void restrictAttribute(TREX::utils::Symbol const &, DomainBase const &)
Variable &restrict(Variable const &)
Reimplemented in TREX::transaction::Goal.
Definition at line 74 of file Predicate.cc.
References end(), TREX::transaction::Variable::isComplete(), and TREX::transaction::Variable::name().
void TREX::transaction::Predicate::restrictAttribute (TREX::utils::Symbol const & name, DomainBase const & domain) [inline]
attribute domain restriction
Parameters:
name A attribute name
domain A domain
This method restrict the domain of the attribute name with the domain domain
Exceptions:
EmptyDomain The resulting domain for name is empty
See also:
void restrictAttribute(Variable const &)
Variable &restrict(Variable const &)
Definition at line 193 of file Predicate.hh.
Referenced by Predicate().
std::ostream & Predicate::toXml (std::ostream & out, size_t tabs = 0) const
XML output.
Parameters:
out An output stream
tabs desired tags indentation
This method writes an XML form of current instance to out indented using tab.
The output excludes all the attributes that are not really constrained to reduce the size of this description.
Returns:
out after the operation
Definition at line 108 of file Predicate.cc.
References getAttribute(), getPredTag(), listAttributes(), object(), and predicate().
The documentation for this class was generated from the following files:
trex/transaction/Predicate.hh
trex/transaction/Predicate.cc