trex: TREX::transaction::Relation Class Reference
TREX::transaction::Relation Class Reference
[TREX transaction]
Timeline relation.
#include <trex/transaction/Relation.hh>
Public Types
typedef Relation base_type
typedef utils::Symbol id_type
typedef Relation const * pointer
typedef Relation const & reference
typedef Relation value_type
Public Member Functions
bool accept_goals () const
Check if accept goal.
bool active () const
Check if relation active.
TeleoReactor & client () const
client for this relation
IntegerDomain dispatch_window (TICK current) const
Dispatch window.
TICK lastObsDate () const
Date of last observation.
Observation const & lastObservation () const
Last observation.
TICK latency () const
Relation latency.
TICK look_ahead () const
Timeline look ahead.
utils::Symbol const & name () const
Timeline name.
bool operator!= (Relation const &other) const
Difference test.
Relation & operator++ ()
advance to next Relation
bool operator== (Relation const &other) const
Equality test.
void recall (goal_id const &g)
Relation (Relation const &other)
Copy constructor.
Relation ()
Default constructor.
void request (goal_id const &g)
TeleoReactor & server () const
Timeline server.
bool valid () const
Check for relation validity.
~Relation ()
Destructor.
reference operator* () const
Access operator.
pointer operator-> () const
Access operator.
Static Public Member Functions
static id_type const & get_id (base_type const &rel)
Get relation identifier.
Friends
class details::timeline
class TeleoReactor
Detailed Description
Timeline relation.
This class represent a single timline dependency link between 2 reactors. Such relation can be described as follow:
name() A timeline name
client() A reactor that declares this timeline as External
server() The reactor that declares this timeline as Internal
When the relation is active() both the client() and server() are defined. Otherwise one of the 2 -- usually the server -- is yet to be assigned.
This class plays a central role in TREX transaction management. It is used as an edge of the graph that gives the full dependencies between reactors and is strongly used by the agent in order to properly propagate observations and goals between reactors.
It also provide a basic management on observation and goals dispatching for each reactor that ensures basic properties required for TREX such as:
There can be only one Observation per timeline aper Tick
A goal can should be send to the server only when its start overlaps the reactor planning window
Finally this class allows to flexibly change the server internally in order to easily change reactors dependencies by the Agent (for example killing a reactor, or creating a new reactor that provides missing timlines in the middle of agent lifetime).
Author:
Frederic Py <fpy@mbari.org>
Definition at line 107 of file Relation.hh.
Constructor & Destructor Documentation
TREX::transaction::Relation::Relation () [inline]
Default constructor.
Create a new empty relation
Postcondition:
this relation is not valid
Definition at line 140 of file Relation.hh.
TREX::transaction::Relation::Relation (Relation const & other) [inline]
Copy constructor.
Parameters:
[in] other A relation
Create a new relation identical to other
Definition at line 148 of file Relation.hh.
Member Function Documentation
bool Relation::accept_goals () const
Check if accept goal.
Indicates whether this relation is accepting goals or not. This method is used by a reactor to identifies if it can dispatch goals or not.
Potential reasons a relation do not accept goal are:
the relation is not active
the look-ahead of the reactor owning the timeline is 0
the client for this relation declared it as an observation relation
Return values:
true if the relation accept goals
false else
See also:
Relation::client() const
Relation::active() const
Relation::server() const
Definition at line 204 of file Relation.cc.
References active(), and TREX::transaction::details::timeline::look_ahead().
Referenced by look_ahead(), and TREX::transaction::graph_names_writer::operator()().
bool Relation::active () const
Check if relation active.
An active relation is a relation that is both valid and is associated to a timeline that have a server. In that case this relation is an edge of the reactor relation graph.
Return values:
true if the relation is active
false otherwise
See also:
Relation::valid() const
details::timeline::active() const
Definition at line 220 of file Relation.cc.
References TREX::transaction::details::timeline::owned(), and valid().
Referenced by accept_goals(), TREX::transaction::graph_names_writer::operator()(), and TREX::transaction::graph::target().
TeleoReactor& TREX::transaction::Relation::client () const [inline]
client for this relation
Indicates which reactor created this relation by declaring the associated timeline as external.
Precondition:
the relation is valid
Returns:
the client for this relation
See also:
Relation::valid() const
Definition at line 294 of file Relation.hh.
Referenced by TREX::transaction::graph::source().
IntegerDomain TREX::transaction::Relation::dispatch_window (TICK current) const [inline]
Dispatch window.
Parameters:
[in] current A tick date
Gives the time interval for which this elation will allow dispatch goals at tick current. Any goal that has its start time potantially starting in this window can be safely posted to this relation.
Precondition:
The relation accepts goals
Exceptions:
EmptyDomain the relation does not accept goals
Returns:
the dispatch interval at current
See also:
accept_goals() const
latency() const
look_ahead() const
Definition at line 222 of file Relation.hh.
References latency(), and look_ahead().
static id_type const& TREX::transaction::Relation::get_id (base_type const & rel) [inline, static]
Get relation identifier.
Parameters:
[in] rel A relation
This methods give the name of the timeline associated to the relation rel
Precondition:
ral is valid
Returns:
the symbolic timeline name of rel
See also:
Relation::name() const
relation::valid() const
Definition at line 130 of file Relation.hh.
References name().
TICK Relation::lastObsDate () const
Date of last observation.
This method indicates at what tick was produced the last observation on the timeline associated to this relation
Precondition:
the relation is valid
at least one observation has been produce on this timeline
Returns:
the tick during which was produced the last observation
See also:
Relation::valid() const
details::timeline::lastObsDate() const
Relation::lastObservation() const
Definition at line 224 of file Relation.cc.
References TREX::transaction::details::timeline::lastObsDate().
Observation const & Relation::lastObservation () const
Last observation.
Gives the last observation produced for this timeline
Precondition:
the relation is valid
at least one observation has been produce on this timeline
Returns:
the observation for this timeline
See also:
Relation::valid() const
Relation::lastObsDate() const
details::timeline::lastObservation() const
Definition at line 230 of file Relation.cc.
References TREX::transaction::details::timeline::lastObservation().
TICK Relation::latency () const
Relation latency.
This methosd identifie s the timelien latency associated to this relation. It is mostly a proxy to details::timeline::latency().
If the timeline is not valid the latency is then set to 0
Returns:
the execution latency of this relation
See also:
details::timeline::latency() const
valid() const
look_ahead() const
Definition at line 208 of file Relation.cc.
References TREX::transaction::details::timeline::latency(), and valid().
Referenced by dispatch_window(), and TREX::transaction::graph_names_writer::operator()().
TICK Relation::look_ahead () const
Timeline look ahead.
Ideintifies the look ahead associated to this relation. If the relation does not accept goals this value will be 0 otherwise it is just a proxy to timeline::look_ahead()
Returns:
the look ahead of this relation
See also:
accept_goals() const
details::timeline::look_ahead() const
Definition at line 212 of file Relation.cc.
References accept_goals(), and TREX::transaction::details::timeline::look_ahead().
Referenced by dispatch_window(), and TREX::transaction::graph_names_writer::operator()().
utils::Symbol const & Relation::name () const
Timeline name.
Gives the name of the timeline associated to this relation.
Precondition:
the relation is valid
Returns:
the name of the timline for this relation
See also:
Relation::valid() const
Definition at line 234 of file Relation.cc.
References TREX::transaction::details::timeline::name().
Referenced by get_id(), TREX::transaction::graph_names_writer::operator()(), and TREX::transaction::details::graph_edge_name_map::operator[]().
bool TREX::transaction::Relation::operator!= (Relation const & other) const [inline]
Difference test.
Parameters:
[in] other another relation
Check if this relation is not identical to other.
Return values:
false if this relation is identical to other
true otherwise
See also:
operator==(Relation const &) const
Definition at line 347 of file Relation.hh.
References operator==().
reference TREX::transaction::Relation::operator* () const [inline]
Access operator.
These operators are implemented so the Relation clas can be used as an iterator
Definition at line 360 of file Relation.hh.
References operator->().
Relation& TREX::transaction::Relation::operator++ () [inline]
advance to next Relation
Change this instance to point to the next relation. Indeed the relation class is just an iterator of all the relations for a given timeline in disguise.
Precondition:
the relation is valid
Note:
this method is used internally by TREX in order to traverse the relation graph between reactors. It should not be used outside of details::timeline class and other core compoenents
Returns:
this instance after the operation
See also:
details::timeline::begin()
details::timeline::end()
Definition at line 381 of file Relation.hh.
pointer TREX::transaction::Relation::operator-> () const [inline]
Access operator.
These operators are implemented so the Relation clas can be used as an iterator
Definition at line 357 of file Relation.hh.
Referenced by operator*().
bool TREX::transaction::Relation::operator== (Relation const & other) const [inline]
Equality test.
Parameters:
[in] other another relation
Check if this relation is identical to other.
Return values:
true if this relation is identical to other
false otherwise
See also:
operator!=(Relation const &) const
Definition at line 333 of file Relation.hh.
Referenced by operator!=().
TeleoReactor & Relation::server () const
Timeline server.
Gives the reactor that declared the timline associated to this relation as internal.
Precondition:
the relation is active
Returns:
a reference to the reactor owning this timeline
See also:
Relation::active() const
details::timeline::owner() const
Definition at line 238 of file Relation.cc.
References TREX::transaction::details::timeline::owner().
Referenced by TREX::transaction::graph::target().
bool Relation::valid () const
Check for relation validity.
Checks if this relation is valid. A valid relation is a relation which is associated to a timeline and have a client.
Return values:
true if the relation is valid
false otherwise
Definition at line 216 of file Relation.cc.
References TREX::utils::list_set< IdTraits, Cmp >::end().
Referenced by active(), and latency().
The documentation for this class was generated from the following files:
trex/transaction/Relation.hh
trex/transaction/Relation.cc