trex: TREX::transaction::BooleanDomain Class Reference
TREX::transaction::BooleanDomain Class Reference
Domains
Boolean domain.
#include <trex/domain/BooleanDomain.hh>
Public Types
typedef
TREX::utils::XmlFactory
< DomainBase,
boost::shared_ptr< DomainBase > > xml_factory
XML parsing factory for domains.
Public Member Functions
BooleanDomain ()
Default constructor.
BooleanDomain (bool val)
Constructor.
BooleanDomain (BooleanDomain const &d)
Copy constructor.
BooleanDomain (boost::property_tree::ptree::value_type &node)
Constructor.
DomainBase * copy () const
Duplicate method.
bool equals (DomainBase const &other) const
Equality test.
boost::any getSingleton () const
singleton value
virtual std::string getStringLower () const
std::string getStringSingleton () const
singleton value
virtual std::string getStringUpper () const
template<class Ty , bool Safe>
Ty getTypedLower () const
template<class Ty , bool Safe>
Ty getTypedSingleton () const
singleton value
template<class Ty , bool Safe>
Ty getTypedUpper () const
TREX::utils::Symbol const & getTypeName () const
type of the domain
bool hasLower () const
bool hasUpper () const
bool intersect (DomainBase const &other) const
check for common values
bool isEnumerated () const
Check for enumerated domain.
bool isFull () const
check for full domain
bool isInterval () const
Check for interval domain.
bool isSingleton () const
check for singleton value
DomainBase & operator*= (DomainBase const &other)
Restrict domain possible values.
DomainBase & restrictWith (DomainBase const &other)
Restrict domain possible values.
std::ostream & toXml (std::ostream &out, size_t tabs) const
XML conversion.
~BooleanDomain ()
Destructor.
Static Public Attributes
static TREX::utils::Symbol const type_name
Symbolic type name for this domain.
Protected Member Functions
void completeParsing (boost::property_tree::ptree::value_type &node)
Friends
std::ostream & std::operator<< (std::ostream &out, TREX::utils::ostreamable const &x)
Detailed Description
Boolean domain.
This class implements a domain used to describ a boolean. The symbolic typename for this class is "bool" and it fully support XML serialization.
Author:
Frederic Py fpy@m.nosp@m.bari.nosp@m..org
Definition at line 27 of file BooleanDomain.hh.
Member Typedef Documentation
typedef TREX::utils::XmlFactory<DomainBase, boost::shared_ptr<DomainBase> > TREX::transaction::DomainBase::xml_factory [inherited]
XML parsing factory for domains.
This type defines the factory that should be manipulated for parsing domains from xml.
Definition at line 403 of file DomainBase.hh.
Constructor & Destructor Documentation
TREX::transaction::BooleanDomain::BooleanDomain () [inline]
Default constructor.
Creates a full boolean domain
Definition at line 43 of file BooleanDomain.hh.
Referenced by copy().
TREX::transaction::BooleanDomain::BooleanDomain (bool val) [inline, explicit]
Constructor.
Parameters:
val A booelan value
Creates a singleton domain with value val
Definition at line 50 of file BooleanDomain.hh.
TREX::transaction::BooleanDomain::BooleanDomain (BooleanDomain const & d) [inline]
Copy constructor.
Parameters:
d Another instance
Create a copy of d
Definition at line 57 of file BooleanDomain.hh.
BooleanDomain::BooleanDomain (boost::property_tree::ptree::value_type & node) [explicit]
Constructor.
Parameters:
node A XML node
Create a new instance by parsing the node. The expected format for this node is :
 <bool value="<val>"/>
Where value attribute is optional and <val> is an integer representation of a boolean
Exceptions:
TREX::utils::bad_string_cast Unable to parse value attribute
Definition at line 89 of file DomainImpl.cc.
Member Function Documentation
DomainBase* TREX::transaction::BooleanDomain::copy () const [inline, virtual]
Duplicate method.
Create a new instance which is identical to current instance value. This instance is usually created using the new operator and it is up to the caller to de-allocate it when not needed.
Returns:
The newly created instance
Implements TREX::transaction::DomainBase.
Definition at line 82 of file BooleanDomain.hh.
References BooleanDomain().
bool BooleanDomain::equals (DomainBase const & other) const [virtual]
Equality test.
Parameters:
other Another instance
Checks if current instance is identical to other. This generally means that both have the same type and exactly the same possible values. In that sense it is more restrictive than the intersect method.
Return values:
true if current instance is identical to other
false otherwise
See also:
bool intersect(DomainBase const &other) const
Implements TREX::transaction::DomainBase.
Definition at line 120 of file DomainImpl.cc.
References TREX::transaction::DomainBase::getTypeName().
boost::any DomainBase::getSingleton () const [inherited]
singleton value
This methods give acces to the value of a singleton instance.
Precondition:
the instance is a singleton
Exceptions:
DomainAccess the insatnce was not a singleton
Returns:
The value of the domain encapsulated in a boost::any
Note:
except for the control of the instance being a singleton the actual code of this method will be provided by the virtual method singleton()
See also:
boost::any singleton() const
getStringSingleton() const
getTypedSingleton() const
Definition at line 56 of file DomainBase.cc.
References TREX::transaction::DomainBase::isSingleton(), and TREX::transaction::DomainBase::singleton().
Referenced by TREX::transaction::DomainBase::getTypedSingleton().
std::string DomainBase::getStringSingleton () const [inherited]
singleton value
This methods give acces to the value of a singleton instance represented as a string
Precondition:
the instance is a singleton
Exceptions:
DomainAccess the insatnce was not a singleton
Returns:
The text representation of the singleton value
Note:
except for the control of the instance being a singleton the actual code of this method will be provided by the virtual method stringSingleton()
See also:
std::string stringSingleton() const
getStringSingleton() const
getTypedSingleton() const
Definition at line 62 of file DomainBase.cc.
References TREX::transaction::DomainBase::isSingleton(), and TREX::transaction::DomainBase::stringSingleton().
Referenced by TREX::transaction::DomainBase::getTypedSingleton().
template<class Ty , bool Safe> Ty TREX::transaction::DomainBase::getTypedSingleton () const [inline, inherited]
singleton value
Template Parameters:
Ty output type
Safe robust conversion
This methods give acces to the value of a singleton instance The output will be of type Ty
The Safe parameter indicates which method should be used.
If the real type of the underneath domain type is guaranteed to be Ty the Safe can be false for performance
If the type is not guaranteed to be Ty but its text representation is compatible with Ty the Safe should be true
Precondition:
the instance is a singleton
the type of the value manip[ulated by this domain should be convertible to Ty or exactly Ty is Safe is false
Exceptions:
DomainAccess the insatnce was not a singleton
boost::bad_string_cast Safe is true and the value of the singleton cannot be parse into Ty
boost::bad_string_cast Safe is false and the type of the singleton is not Ty
Returns:
The singleton value of this domain
See also:
getStringSingleton() const
getSingleton() const
Definition at line 368 of file DomainBase.hh.
References TREX::transaction::DomainBase::getSingleton(), TREX::transaction::DomainBase::getStringSingleton(), and TREX::utils::string_cast().
Referenced by TREX::europa::details::europa_domain::visit().
TREX::utils::Symbol const& TREX::transaction::DomainBase::getTypeName () const [inline, inherited]
type of the domain
This method indicates the type of this domain. The type is a symbol that describes what is the type manipulated by this domain.
Returns:
the type associated to this domain
Definition at line 223 of file DomainBase.hh.
Referenced by equals(), TREX::transaction::EnumeratedDomain< Ty, Comp >::equals(), intersect(), TREX::transaction::EnumeratedDomain< Ty, Comp >::intersect(), restrictWith(), TREX::transaction::EnumeratedDomain< Ty, Comp >::restrictWith(), TREX::transaction::BasicEnumerated::toXml(), TREX::transaction::BasicInterval::toXml(), and TREX::europa::details::europa_domain::visit().
bool BooleanDomain::intersect (DomainBase const & other) const [virtual]
check for common values
Parameters:
other another instance
This methods indicates if current instance share values with other. This generally means that both have the same type and that one can safely restrict the domain of the other.
Return values:
true if current instance shares values with other
false otherwise
See also:
bool equals(DomainBase const &other) const
DomainBase &restrictWith(DomainBase const &other)
Implements TREX::transaction::DomainBase.
Definition at line 110 of file DomainImpl.cc.
References TREX::transaction::DomainBase::getTypeName().
bool TREX::transaction::BasicInterval::isEnumerated () const [inline, virtual, inherited]
Check for enumerated domain.
This method check if the domain is based on an enumerated representation. In which case its representation is based on the list of all the possible values.
Return values:
true if the domain is enumeration based
false otherwise
See also:
bool isInterval() const
Implements TREX::transaction::DomainBase.
Definition at line 70 of file BasicInterval.hh.
bool TREX::transaction::BooleanDomain::isFull () const [inline, virtual]
check for full domain
This method identifies if current domain is full. A full domain is adomain that includes al the possibles values for its type.
Return values:
true if current instance is full
false otherwise
Reimplemented from TREX::transaction::BasicInterval.
Definition at line 91 of file BooleanDomain.hh.
bool TREX::transaction::BasicInterval::isInterval () const [inline, virtual, inherited]
Check for interval domain.
This method is used to identify if this domain is an interval based domain. In which case it is represented by a lower and upper bound.
Return values:
true if the domain is interval based
false otherwise
See also:
bool isEnumerated() const
Implements TREX::transaction::DomainBase.
Definition at line 67 of file BasicInterval.hh.
bool TREX::transaction::BooleanDomain::isSingleton () const [inline, virtual]
check for singleton value
This method identifies if current domain is a singleton. A singleton domain is defined by one and only one value.
Return values:
true if current instance is a singleton
false otherwise
Implements TREX::transaction::DomainBase.
Definition at line 94 of file BooleanDomain.hh.
DomainBase& TREX::transaction::DomainBase::operator*= (DomainBase const & other) [inline, inherited]
Restrict domain possible values.
Parameters:
other Another domain
This method restrict the domain of current instance to the values that are shared by this domain and other.
Precondition:
this domain intersect other
Returns:
this domain after the operation
Exceptions:
EmptyDomain resulting domain is empty
See also:
bool intersect(DomainBase const &) const
Definition at line 280 of file DomainBase.hh.
References TREX::transaction::DomainBase::restrictWith().
DomainBase & BooleanDomain::restrictWith (DomainBase const & other) [virtual]
Restrict domain possible values.
Parameters:
other Another domain
This method restrict the domain of current instance to the values that are shared by this domain and other.
Precondition:
this domain intersect other
Returns:
this domain after the operation
Exceptions:
EmptyDomain resulting domain is empty
See also:
bool intersect(DomainBase const &) const
Implements TREX::transaction::DomainBase.
Definition at line 132 of file DomainImpl.cc.
References TREX::transaction::DomainBase::getTypeName().
std::ostream & BooleanDomain::toXml (std::ostream & out, size_t tabs) const [virtual]
XML conversion.
Parameters:
out An output stream
tabs indentation level
This methods writes an XML representation of the domain into the output stream out. The tabs attribute indicates the indentation level expected for the tags.
Note:
To ensure compatibility this method should produce an xml output which is compatible with the XML parsing constructor of this domain.
Returns:
out after the operation
See also:
DomainBase(rapidxml::xml_node<> const &)
xml_factory
Reimplemented from TREX::transaction::BasicInterval.
Definition at line 99 of file DomainImpl.cc.
Member Data Documentation
Symbol const BooleanDomain::type_name [static]
Symbolic type name for this domain.
This static attibute gives an access to the symbolic name used for BooleanDomain. As stated in the main class description its value is "bool" but programmers who want to use this name would better use this variable in case it changes in the future
Definition at line 36 of file BooleanDomain.hh.
The documentation for this class was generated from the following files:
trex/domain/BooleanDomain.hh
trex/domain/DomainImpl.cc