trex: TREX::transaction::details::external Class Reference
TREX::transaction::details::external Class Reference
[TREX transaction]
An external timeline.
#include <trex/transaction/bits/external.hh>
Public Types
typedef Relation::pointer pointer
Pointer type.
typedef Relation::reference reference
Reference type.
typedef Relation::value_type value_type
Stored type.
Public Member Functions
void dispatch (TICK current, goal_queue &sent)
Goal dispatching management.
external (external const &other)
Copy constructor.
external ()
Default constructor.
bool operator!= (external const &other) const
Difference test.
reference operator* () const
Relation access.
external & operator++ ()
Next external.
pointer operator-> () const
Relation access.
bool operator== (external const &other) const
Equality test.
bool post_goal (goal_id const &g)
Goal posting.
void recall (goal_id const &g)
Recall a goal.
bool valid () const
Check for validity.
~external ()
Destructor.
Friends
class TREX::transaction::TeleoReactor
Detailed Description
An external timeline.
This class is represent a reactor external timeline declaration It refers to the corresponding relation and also offer some management on the goals that have been posted to this timeline and when they should be dispatched to the ownere of this timeline
TeleoReactor
See also:
class Relation
Author:
Frederic Py <fpy@mbari.org>
Definition at line 63 of file external.hh.
Member Typedef Documentation
typedef Relation::pointer TREX::transaction::details::external::pointer
Pointer type.
The type used to point to the element this iterator refers to
Definition at line 81 of file external.hh.
typedef Relation::reference TREX::transaction::details::external::reference
Reference type.
The type used to refer to the element this iterator refers to
Definition at line 76 of file external.hh.
typedef Relation::value_type TREX::transaction::details::external::value_type
Stored type.
The type used to represent a relation
See also:
Relation
Definition at line 71 of file external.hh.
Constructor & Destructor Documentation
details::external::external ()
Default constructor.
Create a new instance
Postcondition:
the instance is not valid
See also:
valid() const
Definition at line 55 of file TeleoReactor.cc.
details::external::external (details::external const & other)
Copy constructor.
Parameters:
[in] other Another instance
Create a copy of other
Definition at line 59 of file TeleoReactor.cc.
Member Function Documentation
void TREX::transaction::details::external::dispatch (TICK current, goal_queue & sent)
Goal dispatching management.
Parameters:
[in] current The current tick
[out] sent List of goals being dispatched
Precondition:
This instance is valid
This method is called when a the tick value has just been updated to current. It will update the pending goals queue of this timeline and duipatch to the owner of this timeline all the goals that can be dispatched at current. Conversely it will remove the goals on the pending queue that necessarily startes before current and indicate such operation in TREX.log
All the goals dispatched during this call will be added to sent and removed from the pending queue
See also:
valid() const
Referenced by TREX::transaction::TeleoReactor::newTick().
bool TREX::transaction::details::external::operator!= (external const & other) const [inline]
Difference test.
Parameters:
[in] other Another instance
Return values:
false if other is identical to this instance
true otherwise
Note:
invalid instances are considered as identical
See also:
operator==(external const &) const
valid() const
Definition at line 127 of file external.hh.
reference TREX::transaction::details::external::operator* () const [inline]
Relation access.
Precondition:
This instance is valid
Gives access to the timeline relation this instance refers to
Return values:
A reference to the Relation referred by this instance
See also:
class Relation
operator* () const
valid() const
Definition at line 227 of file external.hh.
details::external & details::external::operator++ ()
Next external.
Advance this instance to the next Relation
Returns:
This instance after the operation
Definition at line 130 of file TeleoReactor.cc.
References valid().
pointer TREX::transaction::details::external::operator-> () const [inline]
Relation access.
Precondition:
This instance is valid
Gives access to the timeline relation this instance refers to
See also:
class Relation
operator* () const
valid() const
Definition at line 212 of file external.hh.
bool details::external::operator== (details::external const & other) const
Equality test.
Parameters:
[in] other Another instance
Return values:
true if other is identical to this instance
false otherwise
Note:
invalid instances are considered as identical
See also:
operator!=(external const &) const
valid() const
Definition at line 145 of file TeleoReactor.cc.
References valid().
bool details::external::post_goal (goal_id const & g)
Goal posting.
Parameters:
[in] g A goal
Precondition:
This instance is valid
the object of g is the same as the timeline referred by this instance
Add the goal to this instance pending goal queue. This goal will then be processed during subsequent calls of the dispatch method
Return values:
true g has been added to the goal queue
false g was already present in the goal queue
Warning:
the preconditions described above are not checked here (as they should be checked by TeleoReactor class). Caling this method without controlling these will result on an unknown behavior of the system
See also:
valid() const
operator->() const
Relation::name() const
dispatch(TICK, goal_queue &)
recall(goal_id const &)
Definition at line 81 of file TeleoReactor.cc.
void details::external::recall (goal_id const & g)
Recall a goal.
Parameters:
[in] g A goal
Precondition:
This instance is valid
recall the goal g. If this goal is not in the pending queue a recall notification will be sent to the oewner of this timeline
See also:
valid() const
post_goal(goal_id const &)
Definition at line 116 of file TeleoReactor.cc.
bool TREX::transaction::details::external::valid () const [inline]
Check for validity.
Check if this instance referes to an exisiting relation
Return values:
true if this instance point to an exisiting relation
false otherwise
Definition at line 137 of file external.hh.
Referenced by TREX::transaction::TeleoReactor::newTick(), operator++(), and operator==().
The documentation for this class was generated from the following files:
trex/transaction/bits/external.hh
trex/transaction/TeleoReactor.cc